### ISSUE TITLE
Need to provide ability to execute custom .npm scripts

### ISSUE THREAD

**Issue by johnmcbride** [Microsoft/nodejstools#10]
Would like the ability to define custom .npm scripts to execute in the interactive window or some extensiblity point.

Think of the package manager console in the way you can defined a new PS command by simply adding a PS1 file to a package that gets installed.

**Comment by mousetraps** [comment]
Just to clarify... you want to add your own `.<something>` command?

**Comment by mousetraps** [comment]
This is now available with the NPM Scripts Task Runner extension https://visualstudiogallery.msdn.microsoft.com/8f2f2cbc-4da5-43ba-9de2-c9d08ade4941
