### ISSUE TITLE
IErrorProviderFactory Crash when multiple instances open

### ISSUE THREAD

**Issue by crwilcox** [Microsoft/nodejstools#101]
If I open multiple instances of VS and try to launch a second project it crashes.

Using 1.1 Beta

---------------------------
Microsoft Visual Studio
---------------------------
No exports were found that match the constraint: 
	ContractName	Microsoft.VisualStudio.Text.Adornments.IErrorProviderFactory
	RequiredTypeIdentity	Microsoft.VisualStudio.Text.Adornments.IErrorProviderFactory
---------------------------
OK   
---------------------------

222 ERROR SetSite failed for package [Microsoft.VisualStudio.Editor.Implementation.EditorPackage] {E269B994-EF71-4CE0-8BCD-581C217372E8} 80131500 VisualStudio 2015/05/06 20:30:18.168 
223 ERROR End package load [Microsoft.VisualStudio.Editor.Implementation.EditorPackage]

**Comment by mousetraps** [comment]
@crwilcox can you reproduce this issue at all with the latest builds?

**Comment by mousetraps** [comment]
closing, as there's been no repro on this yet.
