### ISSUE TITLE
Should provide some indication to the user that typings are bing downloaded

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1017]
Otherwise the project opens up, IntelliSense doesn't work immediately, and it's unclear what's going on.

**Comment by mjbvz** [comment]
I believe this a duplicate of the feature we were targeting with #797.

However, we only start to acquire typings after NPM install completes and the node_modules folder settles down, so it still may be unclear why there is no intellisense if a user starts interacting with a project right away.
