### ISSUE TITLE
REPL window throws ActivityLog error after switching from ES6->ES5

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1018]
Using latest build from master (VS2015 U2, 6/11/2016)
1. had interactive window open
2. switched from ES6->ES5
3. started typing in interactive window
4. activity log error dialog pops up

Relevant ActivityLog entry:
```
System.ObjectDisposedException: Cannot access a disposed object. at
System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period) at
System.Threading.Timer.Change(Int32 dueTime, Int32 period) at
Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer.BufferParser.BufferChangedLowPriority(Object sender, TextContentChangedEventArgs e) at
Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
```

**Comment by mousetraps** [comment]
Also, the same error occurs when switching from ES5->ES6

**Comment by mjbvz** [comment]
This likely was revealed by #881, which added the dispose pattern to `BufferParser` in order to fix a memory leak around Timer. Switching IntelliSense levels should not be too common, but hopefully the fix here is an easy one.
