### ISSUE TITLE
intellisense not working with newest version of express

### ISSUE THREAD

**Issue by phillipwei** [Microsoft/nodejstools#102]
I've noticed that if I start with a new, blank project and install express manually than the module isn't discovered (i.e. an app.set does not complete) -- but if I create a new "Basic Node.js Express 4 Application" it does.

What is the difference? When is the static analyzer kicking off -- can I re-trigger it somehow?

**Comment by mousetraps** [comment]
That's odd... It should always kick off... A few questions: 
* do any items appear in the completion list?
* can you check if there is an .ntvs_analysis.dat file in your project folder? 
* Can you also check that the build action is set to "Compile" on the file you are hoping to get intellisense on?

**Comment by uselesshasid** [comment]
I see the same issue. 

* i have a .ntvs_analysis.dat file
* the js file i'm working with is set to compile

What do you mean by completion list? i dont see any error in the error window

**Comment by uselesshasid** [comment]
Looks like it has to with the version. When i install the latest express version, intellisense will not work. When i install version 3.4.4 (which is the one included with the express project template) intellisense will work.

**Comment by billti** [comment]
It seems to be working fine for me now with the latest RC2.1 release and the latest Express release. If you are still seeing issues, please comment and I'll reopen and investigate.
