### ISSUE TITLE
Why does 6-11-2016 Dev Build for VS15 require VS2015?

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/nodejstools#1022]
Why need VS2015?
Which was not true for 1.2 alpha2

**Comment by alanpurple** [comment]
and yet, even after I installed VS2015 community with updates, still same message blocked me from installing

**Comment by mjbvz** [comment]
Does the message mention something about upgrading to update 2 of VS 2015? We changed the gating recently but this could have broken VS15: #1009

**Comment by mousetraps** [comment]
This should be fixed in the next dev build.
