### ISSUE TITLE
Update VS "15" template manifest to support new tape templates

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1027]
see https://github.com/Microsoft/nodejstools/pull/989

template manifest:
https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Templates/VS_Nodejs.item.vstman

**Comment by jcansdale** [comment]
Was this update necessary in the end? The 'VS_Nodejs.item.vstman' file doesn't appear to have been touched. I'm confused about where this file is used and why each element seems to appear twice (e.g. there are two entries for 'AddWebSiteAzureExpressApp.zip').

**Comment by mjbvz** [comment]
@jcansdale I don't know too much about visual studio and project templates myself, but think [this article](https://msdn.microsoft.com/en-us/library/mt706509.aspx) may cover how the `vstman` file and how it is being used for VS15. 

I also don't know why there are duplicate entries, but have sent out a PR to remove them: #1064

**Comment by mjbvz** [comment]
We just eliminated these files aggregate manifest files altogether. They were not required for VS15 after all.
