### ISSUE TITLE
Cannot define function in Interactive Window

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1030]
**Expected:**
![image](https://cloud.githubusercontent.com/assets/762848/16026040/41b30d96-3180-11e6-95b4-45d8e35e752a.png)

**Actual:**
![image](https://cloud.githubusercontent.com/assets/762848/16026044/48878bb0-3180-11e6-9330-d41255953e11.png)

**Comment by mjbvz** [comment]
This only repos when ES6 IntelliSense is enabled.

**Comment by mjbvz** [comment]
This only repos when ES6 IntelliSense is enabled.

**Comment by mousetraps** [comment]
Actually, turns out it repros in ES5 as well!

**Comment by mjbvz** [comment]
Just was thinking a little more about this and here's what I think is happening:

1. the interactive window receives some code: `function f(){ }` for example.
2. We then wrap this code in parens, so the new code is `(function f(){ })`
3. We evaluate this text.

`(function f(){ })` is a perfectly valid expression, but `f` is only valid within the function body, it does not create a top level function declaration for `f` as we expect here.

Will send out PR shortly.
