### ISSUE TITLE
_references.js in Starter Node.js Express 3 App has line ending differences

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1036]
![image](https://cloud.githubusercontent.com/assets/762848/16027576/d3c8ed30-318b-11e6-90c6-da96a7dff236.png)

**Comment by mjbvz** [comment]
These got corrupted again when I merged with master:

![image](https://cloud.githubusercontent.com/assets/12821956/16053482/df4de182-321d-11e6-97e8-ba63a064db4b.png)

Reopening
