### ISSUE TITLE
Breakpoints not hit

### ISSUE THREAD

**Issue by syagev** [Microsoft/nodejstools#104]
I had a good run with NTVS and then debugging started to fail for no apparent reason.

Debugging starts fine but only breakpoints which are directly in the startup file are hit properly. Breakpoints in callbacks and breakpoints in other files seem to be hit but the IDE says "Code not running" and the call stack is empty. In the breakpoint window the hit count on the breakpoint is properly updated.

using:
VS 2013 ultimate SP1 on Win7 x64
NTVS 1.1b (same problems with 1.0)

**Comment by mousetraps** [comment]
Are you using typescript by any chance? I'm currently working on a similar issue that occurs when the output directory is set and we fail to properly map files.

**Comment by syagev** [comment]
Nope. Here's my `packages.json`:
```javascript
"dependencies": {
    "aws-sdk": "^2.1.4",
    "s3": "^4.4.0",
    "body-parser": "^1.10.0",
    "errorhandler": "^1.3.0",
    "express": "^4.10.6",
    "method-override": "^2.3.0",
    "mongodb": "^2.0.9",
    "morgan": "^1.5.0",
    "nodetime": "^0.8.15",
    "serve-favicon": "^2.2.0",
    "factual-api": "^1.0.7",
    "async": "^0.9.0",
    "request": "^2.51.0",
    "sendgrid": "^1.4.0",
    "serve-static": "^1.7.1",
    "underscore": "^1.7.0",
    "yo-api": "^1.1.2",
    "foursquarevenues": "^1.0.0",
    "googleplaces": "^0.4.0",
    "emailjs": "0.3.16"
  },
  "engines": {
    "node": "^0.10.x",
    "npm": "^1.2.x"
  }
```

**Comment by mousetraps** [comment]
Do you have a sample project by any chance? Unfortunately packages.json isn't as helpful for debugging issues.

**Comment by syagev** [comment]
Do you need the entire source code? If yes, I would like to share it privately (preferably via dropbox)

**Comment by mousetraps** [comment]
That would be easiest unless there's a smaller project.

You can either email a link to ntvshelp@microsoft.com or my Dropbox is sara.itani@gmail.com. (I'll download immediately and let you know when you can take it down)

**Comment by mousetraps** [comment]
Got it, thanks for your help! Feel free to unshare.

**Comment by mousetraps** [comment]
@syagev - mind trying out the [latest dev build](https://github.com/Microsoft/nodejstools/releases)? I believe this may have been fixed in baef9a999e2446521b7e5208d7ea9a5defa8cc40, as I can no longer repro after upgrading to the latest version.

**Comment by syagev** [comment]
Seems to work fine. Thanks!

**Comment by syagev** [comment]
I'm experiencing this again. Using [v1.1.Dev-6.15.2015](https://github.com/Microsoft/nodejstools/releases/tag/v1.1.Dev-6.15.2015). The difference this time is that not even breakpoints on the main file are being hit. All breakpoints receive the status "This breakpoint will not be hit. No code has been loaded for this location".

The good news is that on my machine and project this is completely reproducible. The bad news is that I can't work (restarting VS, and even re-installing NTVS did not resolve the issue).

Help.

**Comment by syagev** [comment]
OK, I managed to find the reason for this!

I was using a symlink for my project due to the MAX_PATH problem and that was giving the debugger a hard time to understand the source files in my project are the correct ones..

So I just re-added the NTVS project to the solution from the *actual* directory and everything works (although I have MAX_PATH problems again but that's another story...)
