### ISSUE TITLE
Source-mapping issue during debugger stepping in basic TypeScript app

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1048]
Repro step:
1. Create a new, blank console TypeScript application.
2. In app.ts, enter the following text:
```js
function count(remaining) {
    if (remaining <= 0)
        return 0;
    return remaining + count(remaining - 1);
}
var sum = 0;
sum = count(3);
sum = count(5);
```
3. Set a breakpoint in count on the line sum = count(3); 
4. Start debugging the program.

**Expected:**
Program runs to the line `sum = count(3);`

**Actual:**
After start debugging, Program runs to the line `var sum=0;`

![image](https://cloud.githubusercontent.com/assets/762848/16053867/65171a6c-321f-11e6-93be-1f89720a151d.png)

**Comment by mousetraps** [comment]
@mjbvz - can you take a look at this while you're in the debugger code? We need to investigate and understand the impact of this issue for Beta.

**Comment by mjbvz** [comment]
@mousetraps I can't repo this using the provided steps. What versions of the various products are you on? I'm on:

* Node 5.9 and 6.2
* VS 2015 Update 3 RC public release
* Typescript 1.8.32.0
* NTVS from master.

**Comment by mjbvz** [comment]
Tried on a fresh vm with RTM VS 2015 Update 3, along with the exact NTVS build that the testers were on, but I still cannot repo this bug (I tried with a few different node versions too.)

Closing this for now as no repo, but we should follow up with the testers to make sure the repo steps were complete and the tested configurations were the same.
