### ISSUE TITLE
Break when an exception is thrown only for user code!

### ISSUE THREAD

**Issue by edvinv** [Microsoft/nodejstools#105]
When I set Break when an exception is thrown it would be nice to have an additional option where debugger will stop only if exception is thrown from user code, or saying other way not coming from node library, files inside ‘node_modules’ and global packages. Normally you are not interested on handled exceptions coming from system libraries, because they only generate a lot of noise and some time, like starting application, it’s practical impossible with this option turned on.

thx

**Comment by mousetraps** [comment]
Great idea. Unfortunately I don't see this getting fixed in the near future unless we get a community contribution... but for the time being you can filter the exceptions that are thrown if you see that a library you are using has a "favorite" exception type.

**Comment by mousetraps** [comment]
Closing, as #699 should offer a less noisy experience and I'm not sure the user / non-usercode distinction will be necessary in this particular instance.
