### ISSUE TITLE
String var containing time, not displayed correctly.

### ISSUE THREAD

**Issue by edvinv** [Microsoft/nodejstools#106]
Variable time from following sample is in watch window displayed as: "05/07/2015 22:00:00", but of  course logged to console correctly as  "2015-05-07T22:00:00.000Z".

var time= "2015-05-07T22:00:00.000Z";
console.log(time);

**Comment by kant2002** [comment]
Please correct me that this is should be done following way:
1. Add test to the `DebuggerTests.cs` file
2. Add file to the `Nodejs\Tests\TestData\DebuggerProject\` where would be JS snippet below
3. Run and make it green

**Comment by kant2002** [comment]
Looks like I have test for that.
Now have more input how to fix that and what's broken.
The JToken object on the line https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Debugger/Serialization/NodeBacktraceVariable.cs#L33 have value of type `Newtonsoft.Json.Linq.JTokenType.Date` which is converted to local time by the library

**Comment by kant2002** [comment]
Not so simple as it seems from the first sight.
Node respond correct value `..{"ref":8,"type":"string","value":"2015-05-07T22:00:00.000Z"}..`, but Newtonsoft.JSON parse `value` as DateTime and then corresponding value in the debugger looks like 
```
...
{
  "ref": 8,
  "type": "string",
  "value": "2015-05-07T22:00:00Z"
}...
```

and there no way to recover that information.
So far to have workaround for that issues we have eaither 
1. to override some deserialization logic, so no DateTime deserializatin would happens
2. or to create strict types for the debugger commands, and explicitly define schema for Node.JS debug protocol.

**Comment by kant2002** [comment]
@mousetraps could you take a look?

**Comment by billti** [comment]
Seems like that DateParse enumeration should be 'None' for the value field if you don't want it converted. See http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_DateParseHandling.htm

**Comment by kant2002** [comment]
I will try that. Thanks. Exactly what I was looking for. Will comeback when test that.
