### ISSUE TITLE
Should console application template define a "main": "app.js"?

### ISSUE THREAD

**Issue by jcansdale** [Microsoft/nodejstools#1061]
Unless you want to kick off your application using `require("myapp")`, it probably shouldn't. New Node.js users this might assume this is some kind of main entry point rather than the main export of a module.

Maybe a "bin": "app.js" would be more appropriate? My instinct would be to remove it completely.

https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/ProjectTemplates/NodejsConsoleApp/package.json#L5

**Comment by mjbvz** [comment]
The current console app template seems to be used both as a template actual console apps and for node packages. I think we should consider making this proposed change, but only if we take in #951, which adds a template explicitly for npm packages.

**Comment by jcansdale** [comment]
There are many packages that include both console application and library functionality. I believe npm itself can be used both a console app and a library via require("npm"). We could add an 'index.js' to suggest this kind of dual purpose use? For example, 'app.js' might become:

var index = require("index");
index.sayHello("World");

Just a thought. ;)

**Comment by paulvanbrenk** [comment]
I will entertain a PR for this, but closing since this is very low on the priority list.
