### ISSUE TITLE
Integrate with the Visual Studio 2015 Interactive Window

### ISSUE THREAD

**Issue by AndreSayreMSFT** [Microsoft/nodejstools#107]

**Comment by mikehc** [comment]
How is this going to be different from the "Node.js Interactive Window" already available?

**Comment by mousetraps** [comment]
It'll be more consistent with the rest of the VS experience and decrease the proliferation of interactive windows in Visual Studio as well as decrease cost on our end because we'll get new features (mostly) for free.

**Comment by mjbvz** [comment]
Closing in favor of #1090, which I believe will be using the Rosyln interactive window instead
