### ISSUE TITLE
NTVS 1.2 Beta: IntelliSense For Locally Required Files needs VS 2015 Update 3 RTM+

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1076]
In NTVS 1.2 Beta on VS 2015 Update 2, IntelliSense does not work for locally required files:

```js
var my_file = require('./my_local_file');

my_file.
// No IntelliSense for `my_file` :(
```

This issue  was originally identified and tracked by #817. It is a Visual Studio / TypeScript bug, that is fixed by (the currently unreleased) VS 2015 Update 3 RTM.

## Workaround
As a workaround, try adding a `tsconfig.json` to the root of your NTVS project with these options:

 ```json
{
  "compilerOptions": {
    "allowJs": true,
    "moduleResolution": "node",
    "noEmit": true
  },
  "exclude": ["node_modules"]
}
```

And [right click `Save As` this file](https://raw.githubusercontent.com/Microsoft/TypeScript/release-1.8/lib/typescriptServices.js) into `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript` to replace the existing `typescriptServices.js` in that directory.

**Comment by mousetraps** [comment]
This issue has been resolved with Visual Studio 2015 Update 3 RTM https://www.visualstudio.com/news/releasenotes/vs2015-update3-vs
