### ISSUE TITLE
Interactive Window busted in Node.js v0.10.x and below

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1080]
**Expected**
Enter statements into interactive window and they get executed properly

**Actual**
`TypeError: needs a 'context' argument.`

![image](https://cloud.githubusercontent.com/assets/762848/16239619/64e84536-379a-11e6-886b-367391e1b9d8.png)

**Comment by mousetraps** [comment]
@avitalb is looking into this

**Comment by mousetraps** [comment]
Looks like it's only broken in v0.10.x and below, probably as a result of using new APIs in #876

**Comment by mjbvz** [comment]
See this old Node documentation for `vm`: https://nodejs.org/docs/v0.10.40/api/vm.html

I suspect we need to change the context creation line to `context = vm.createInContext(context)`
