### ISSUE TITLE
.targets file not copied to proper location in EnvironmentSetup.ps1

### ISSUE THREAD

**Issue by avitalb** [Microsoft/nodejstools#1083]
##### Expected Behavior 
copied to "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Node.js Tools\Microsoft.NodejsTools.targets"

##### Actual Behavior 
copied to "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\14.0\Node.js Tools\Microsoft.NodejsTools.targets"

**Comment by mjbvz** [comment]
Fixed by #1088
