### ISSUE TITLE
Multiple pages of NTVS News opens up on load

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/nodejstools#1086]
Hi,

**Version**: NTVS 1.2 Beta / VS 2015 Update 2

**Actual behaviour**

When I open up the solution 9 tabs showing NTVS News (URL: http://ntvs.azurewebsites.net/news/1010/) open up.

**Expected behaviour**

I would like to see a grand total of 0 tabs of NTVS News opening on launch.

**Comment by mjbvz** [comment]
Thanks for the report. Opening 9 tabs certainly sounds annoying.

A quick question to help with the investigation, did your solution have multiple projects by chance, or was it a pretty standard solution?

These notifications help us let users know when new releases come out and collect feedback, but you can always disable these completely by going to `Tools -> Options` and then `Node.js Tools -> General` and setting `Check for survey/news` to `Never`

**Comment by NoelAbrahams** [comment]
> A quick question to help with the investigation, did your solution have multiple projects by chance, or was it a pretty standard solution?

We have over ten NTVS projects.

> you can always disable these completely by going to Tools -> Options

Yes, I already had them turned off.

![image](https://cloud.githubusercontent.com/assets/1106823/16296044/25bc2010-3922-11e6-818b-dc2c74884066.png)

The news pages all loaded the last two days, but today for some strange reason they didn't. It's possible if you just close the tab then they keep coming back, but if you click the "Dismiss" button then they go away for good.

In any case there are two bugs here:

* The option to turning news off is not being honoured.
* Multiple copies of the news tab is being opened.

**Comment by mjbvz** [comment]
@NoelAbrahams Thanks. I'll take a look into both of these.

Since we did not update the news item for a long time, it's possible this was broken at some point without anyone really noticing.
