### ISSUE TITLE
Typescript Mocha tests is not discovered when using Javascript output dir

### ISSUE THREAD

**Issue by lostfields** [Microsoft/nodejstools#1087]
##### Expected Behavior

Tests is discovered and runnable with JavaScript output directory
##### Actual Behavior

 Tests is not discovered and runnable.
##### Versions
- NTVS Version: 1.2.40329.01
- Visual Studio Version: 14.0.25123.00 Update 2
- Node.js Version: 5.11.0
- Typescript Version:  1.8.29.0
##### Steps to Reproduce
1. Remove all .js files
2. "TypeScript Build" properties for project in Visual Studio 2015 has to have "Redirect JavaScript output to directory" to eg. "build\"
3. Build solution
4. Tests is not discoverable

**Comment by mjbvz** [comment]
I just tried running through these steps with [NTVS 1.2 beta](https://github.com/Microsoft/nodejstools/releases) on VS 2015 Update 3 RC, and was not able to repo the problem. This was with a blank typescript console app project and a new unit test file created using our templates.

Can you please try updating NTVS (and possibly VS) to see if the problem still occurs for you? Thanks.

**Comment by lostfields** [comment]
Since you got it working I tried to create a completely new typescript project in VS2015 and that actually worked. I compared the two project files and noticed one difference for my typescript configurations. 

The project that worked had: 
`<PropertyGroup Condition="'$(Configuration)' == 'Debug">`

My other project where tests wasn't discoverable had: 
`<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
`

After removing platform it suddenly worked for my project!

**Comment by mjbvz** [comment]
Ok, glad you found the problem. 

Do you know if the bad PropertyGroup with `Debug|AnyCPU`  was created by NTVS or not? I'd really like to understand if this is something NTVS caused or could mitigate.

**Comment by lostfields** [comment]
Don't know when it happened, but I had update 2 and created the project using the node template for express. I fiddled alot around the settings trying different stuff but I never used anything but VS2015.

**Comment by Spksh** [comment]
I'm seeing this issue too. It appears to occur when I set compilerOptions outDir in tsconfig.json. Test discovery doesn't seem to expect a different directory. 

Visual Studio 2015 14.0.25422.01 Update 3
NTVS 1.2.40713.01
Node 6.2.2
TypeScript 1.8.35.0

I can repro this with a new Blank Node.js Console Application:

1. Create new solution
2. Add tsconfig.json, set outDir to `"./app"`
3. Add new folder to solution, e.g. "Tests"
4. Add new TypeScript Mocha UnitTest file to /Tests subfolder
5. npm install mocha --save-dev
6. typings install dt~mocha --global --save
7. Add reference to mocha typings in unit test .ts file
8. Build

On first build, I get:

`------ Discover test started ------
Processing: D:\users\xxxxx\Documents\Projects\NodejsMochaTestApp2\NodejsMochaTestApp2\Tests\UnitTest.js
 Test discovery error: { Error: Cannot find module 'D:\users\xxxxx\Documents\Projects\NodejsMochaTestApp2\NodejsMochaTestApp2\Tests\UnitTest.js'
Processing finished for framework of Mocha
Discovered 0 testcases.
========== Discover test finished: 0 found (0:00:00.2162571) ==========`

Note that the "Cannot find module" references the path to the compiled .js file that doesn't respect the outDir configured in tsconfig.json.

After the first build, there are no errors and no messages from Test discovery (and no tests show up in Test Explorer). I can generate the "Test discovery error" again for one build if I change any .ts file or tsconfig.json.

Minimum tsconfig.json to repro:

`{
    "compilerOptions": {
        "outDir": "./app"
    }
}`

Minimum unit test:

```javascript
/// <reference path="../typings/globals/mocha/index.d.ts" />

import assert = require('assert');

describe("Test Suite 1", () => {
    it("Test A", () => {
        assert.ok(true, "This shouldn't fail");
    });

    it("Test B", () => {
        assert.ok(1 === 1, "This shouldn't fail");
        assert.ok(false, "This should fail");
    });
});
```

**Comment by lostfields** [comment]
Hi @Spksh
May you edit your njsproj (project file) and look up the conditions in every PropertGroup tag?

**Comment by lostfields** [comment]
.... and that reference to mocha.d.ts in your test will cause problems as your typings is not copied to you outdir.

**Comment by Spksh** [comment]
No `$(Platform)`. The only conditional PropertyGroups are:

```
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
```

RE: reference. That's fine though, isn't it? Mocha is running as an "ambient" module when it's kicked off as a test host by NTVS. Adding the .d.ts to the project (so that it is auto-discovered) and removing the direct reference does the same thing.

**Comment by lostfields** [comment]
I think it's the javascript version that is running and ntvs is mapping the code line to typescript debugging. Try to copy the typings folder to outdir and see if that makes any difference?

**Comment by Spksh** [comment]
No, copying typings to outdir doesn't make a difference.

After I did that, I got a bunch of duplicate definition errors from the compiler (as expected), so I added an exclude for the new typings folder:

```
{
    "compilerOptions": {
        "outDir": "./app"
    },
    "exclude": [
        "app/typings"
    ]
}
```
...which allows the solution to compile. 

But I still get the same error from Test discovery:

```
Test discovery error: { Error: Cannot find module 'D:\Users\xxxxx\Documents\Projects\NodejsMochaTestApp2\NodejsMochaTestApp2\Tests\UnitTest.js'
```

**Comment by larsendaniel** [comment]
I'm hitting this issue as well.  Any update on a fix for it?

**Comment by lostfields** [comment]
@larsendaniel I think this issue is related to #1243 and #1241 so you may apply the same settings of tsconfig.json to your VS project as well and see if that works out for you.

**Comment by paulvanbrenk** [comment]
This looks like it's much more work than I expected. Closing in favor for #1949 which captures more use cases.
