### ISSUE TITLE
Mocha Typescript Unit Test Template Errors

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1089]
##### Expected Behavior 
No errors in new file created from our file templates.

##### Actual Behavior
Errors in TypeScript Mocha unit test file about globals `describe` and `it`. Here's the code:

```ts
import assert = require('assert');

describe("Test Suite 1", () => {
    it("Test A", () => {
        assert.ok(true, "This shouldn't fail");
    });

    it("Test B", () => {
        assert.ok(1 === 1, "This shouldn't fail");
        assert.ok(false, "This should fail");
    });
});
```
And the errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2304	Cannot find name 'it'.	NodejsConsoleApp2	c:\users\matb.redmond\documents\visual studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\UnitTest1.ts	8	Active
Error		Build:Cannot find name 'describe'.	NodejsConsoleApp2	c:\users\matb.redmond\documents\visual studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\UnitTest1.ts	3	
Error		Build:Cannot find name 'it'.	NodejsConsoleApp2	c:\users\matb.redmond\documents\visual studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\UnitTest1.ts	4	
Error		Build:Cannot find name 'it'.	NodejsConsoleApp2	c:\users\matb.redmond\documents\visual studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\UnitTest1.ts	8	
Error	TS2304	Cannot find name 'describe'.	NodejsConsoleApp2	c:\users\matb.redmond\documents\visual studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\UnitTest1.ts	3	Active
Error	TS2304	Cannot find name 'it'.	NodejsConsoleApp2	c:\users\matb.redmond\documents\visual studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\UnitTest1.ts	4	Active
``` 

The workaround is to add reference paths to `mocha.d.ts`.

**Comment by mjbvz** [comment]
Here's the complete workaround:

1. Install [typings](https://github.com/typings/typings)
2. In project directory, from the command prompt run `$ typings install dt~mocha --global` to get the mocha typings that tell Typescript about `describe` and `it`
3. In the unit test file, add `/// <reference path="typings/globals/mocha/index.d.ts" />` to the top of the file

**Comment by mjbvz** [comment]
Dup of #418, will copy updated instructions to that issue.

**Comment by aventurella** [comment]
Just to add to this solution:

`import * as mocha from 'mocha';`

Also seems to fix it. In this way the imports at the top of the test file remain consistent no outlier with 

`/// <reference path="../node_modules/@types/mocha/index.d.ts" />`

Which also does work as well.

**Comment by tony19** [comment]
@aventurella With the `import` usage, how are you getting around the unused ref error?

![screen shot 2017-01-31 at 12 07 26 am](https://cloud.githubusercontent.com/assets/26580/22454216/e4cba2a2-e749-11e6-8263-9f6d99ca262a.png)
