### ISSUE TITLE
IntelliSense doesn't work properly on global variable declarations

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#109]
``` js
foobar = 3;
global.foo // 'foobar' does not appear in completions list
```

Expected: 'foobar' appears in completions list.

**Comment by mjbvz** [comment]
In ES6 Preview in NTVS 1.2 Alpha, we at least get the name auto completion after a point:

![image](https://cloud.githubusercontent.com/assets/12821956/14266450/262e036c-fa7d-11e5-8786-b748c68a377b.png)

But `foobar` is not actually listed in the `global` completion list. Also, there's no type info.

![image](https://cloud.githubusercontent.com/assets/12821956/14266463/3f4ae2f2-fa7d-11e5-8689-c3318da59075.png)

**Comment by mjbvz** [comment]
Marking this as external since in NTVS 1.2 Beta, ES6 IntelliSense is backed by Typescript / Salsa. Fixing this would likely require work on their side.

**Comment by paulvanbrenk** [comment]
This works as expected in 1.3
