### ISSUE TITLE
Enable ES6 IntelliSense in Node.js Interactive Window

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1090]
Currently the Interactive Window falls back to using ES5 Node.js language service sans squigglies, rather than the new ES6 "Salsa" language service. Instead, we want to start using Salsa so that we can:
- get ES6 syntax highlighting and completions
- provide a more consistent experience across the product
- consolidate JS language service engineering efforts
- improve performance by fully divorcing ourselves from NodeLS

In order to achieve this, we need to investigate the following: 
- [ ] How does the Interactive Window currently work? How does it interact with the language service?
- [ ] Does our current analysis engine have any REPL-specific behavior that we might also want from Salsa?
- [ ] What are the current limitations of Salsa? What would we need to change in Salsa in order to provide a solid REPL experience in NTVS?

(@avitalb is currently working on this issue)

**Comment by paulvanbrenk** [comment]
Considering the limited use of the interactive window and the amount of work to get this to work. Closing.
