### ISSUE TITLE
NTVS Repl Window .npm commands do not work With VS15 Folder based Project

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1092]
##### Expected Behavior

Ability to run `.npm` commands in the Node.js interactive window when using VS15 with a node project opened as a folder.
##### Actual Behavior

```
> .npm install underscore
Please specify a valid Node.js project or project directory. If your solution contains multiple projects, specify a target project using .npm [ProjectName or ProjectDir] <npm arguments> For example: .npm [MyApp] list
> .npm [ExpressApp1] install underscore
Please specify a valid Node.js project or project directory. If your solution contains multiple projects, specify a target project using .npm [ProjectName or ProjectDir] <npm arguments> For example: .npm [MyApp] list
>
```
##### Steps to Reproduce
1. In VS15, open directory as project
2. Try running commands in interactive window

You can pass in the full path like so: `.npm [C:\Users\matb\Documents\Visual Studio 15\Projects\ExpressApp1\ExpressApp1\] install underscore` but cannot use `[.]` because that resolves to `C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE`

**Comment by mjbvz** [comment]
Quick investigation: an EnvDte project item seems to exist in the folder flow, but it does not have the path to the root anywhere easily accessible:

![image](https://cloud.githubusercontent.com/assets/12821956/16321242/b13ad02c-3950-11e6-8848-1505536df058.png)

**Comment by RokitSalad** [comment]
seeing the same behaviour in vs2017. nodejs interactive window isn't really usable with folders.

**Comment by paulvanbrenk** [comment]
We added a bunch of context menu options on the package.json in the Open Folder case. There doesn't seem to be an obvious way to make that work with the interactive window.
