### ISSUE TITLE
NTVS 1.2 RC feedback

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1094]
Love it? Hate it? Let us know what you think!

**Comment by mjbvz** [comment]
Closing since [NTVS 1.2 is now out](https://github.com/Microsoft/nodejstools/releases). Please try upgrading and sending us any feedback here: #1147

**Comment by 4176244** [comment]
now,i create the child_process with nodejs,and vs2015,but i cannot find the way to debug the child_process,and set the breakpoints;

who can tell me how to do?

yes,i know it's can resolved by node-inspector,but i want to be bale to debug inside VS2015.

can you help me?
