### ISSUE TITLE
Typings Tool Install should not print Npm install result

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1098]
##### Expected Behavior

When typings is not installed, it is automatically installed. A message saying the tool has been installed is printed, or a simple failure message is printed.
##### Actual Behavior

After the install, the entire result of the `npm install typings` command is printed to the output window:

![image](https://cloud.githubusercontent.com/assets/12821956/16322800/8fee2efa-395a-11e6-8870-0061c7b19b82.png)

**Comment by paulvanbrenk** [comment]
typingstool is replaced with @types
