### ISSUE TITLE
Is there a way to view console output?

### ISSUE THREAD

**Issue by tejacques** [Microsoft/nodejstools#11]
When running the startup project/file, is there a way to view console (stdout/stderr) output? Ideally it would display in "Output:Debug", or "Output:Tests" in the case of tests. Tests do seem ti have an output view that is visible when clicking on "Output" for the highlighted test, but there is no way to view this as you are debugging, making it usefulness limited.

Is there currently a way to view this?

**Comment by mousetraps** [comment]
Unfortunately no... We should look into either visibly running the console or piping the output of the node process to the output window (I prefer the latter).
https://nodejstools.codeplex.com/workitem/1712

This following code is a good place to start (TestAdapter > TestExecutor.cs > RunTestCase). We can either create include a redirector or use RunVisible
``` csharp
                _nodeProcess = ProcessOutput.Run(
                                        settings.NodeExePath,
                                        args,
                                        workingDir,
                                        null,
                                        false,
                                        null,
                                        false);
```

**Comment by mjbvz** [comment]
Closing as duplicate (or sub problem) of #149 . Please reopen if you do not feel this is not correct.

We had a mob programming session to prototype the basic work here, but there's still a lot of edge cases to figure out (such as reading stdin). We probably would want to have this be an opt in setting at first as well.
