### ISSUE TITLE
Whitespace still added to blank lines

### ISSUE THREAD

**Issue by dougscher** [Microsoft/nodejstools#1110]
##### Expected Behavior 
(function (cb) {
  //no whitespace
  test();
});

##### Actual Behavior 
(function (cb) {
.. //whitespace
  test();
});

- NTVS Version:1.2.40620.00
- Visual Studio Version: visual studio 2016 pro 14.0.25123.00 Update 2
- Node.js Version: 

##### Steps to Reproduce
1. 
type:
(function (cb) {
  test();
});

2. 
type 2 blank lines
(function (cb) {

  test();
});

You end up with blank lines with whitespace above the function test

**Comment by mjbvz** [comment]
Thanks for reporting this.

Just a few questions to help with the investigation:

* What IntelliSense level are you on? This is found in `Tools -> Options`, `Text Editor -> Node.js -> IntelliSense`. It should be ECMAScript 6 for NTVS 1.2.
* Do you have any custom formatting settings? These are also in `Tools -> Options`, `Text Editor -> `Node.js -> Formatting`.

---

And just  to confirm the repo, starting with this code:

```js
(function (cb) {
test();
});
```

Let `$` be the cursor. I position the cursor like so:

```js
(function (cb) {
$test();
});
```

And then hit `return/enter` twice, with the expected result being:

```js
(function (cb) {
// blank line
test();
});
```

and the actual result being:

```js
(function (cb) {
  // blank line with two spaces
test();
});
```

Is that correct?

**Comment by dougscher** [comment]
(function (cb) {
  $test();
});

$test needs to be indented to begin with.
And you may need to do two line feeds to see the white space show up

  a.. What IntelliSense level are you on? This is found in Tools -> Options, Text Editor -> Node.js -> IntelliSense. It should be ECMAScript 6 for NTVS 1.2. 
  yes

  b.. Do you have any custom formatting settings? These are also in Tools -> Options, Text Editor ->Node.js -> Formatting`. 
  Attached

Thanks,
Doug

**Comment by mjbvz** [comment]
Thanks for the clarification. The formatting settings attachment seem to have gotten lost though, could you please try uploading them directly through GitHub.

I'm still having trouble reproducing this issue, but I am on [VS 2015 Update 3](https://www.visualstudio.com/news/releasenotes/vs2015-update3-vs) which may make a difference. It includes a new version of Typescript, which powers our editing and formatting for ES6 IntelliSense. You may want to download it and give it a try, along with [NTVS 1.2 RC](https://github.com/Microsoft/nodejstools/releases)

**Comment by dougscher** [comment]
Looks like this may be fixed.

Having another problem where  NTVS 1.2 RC does not seem to perform automatic brace completion.
options|text editor|node.js|general|automatice brace completion is set.

**Comment by mjbvz** [comment]
Good to hear. Closing this issue then.

The brace completion issue is known and being tracked by: #1142  Take a look at that issue for more context on the problem and some potential workarounds.

Thanks.
