### ISSUE TITLE
Investigate File > Open Folder experiences

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1112]
As we investigate the File > Open Folder experiences, we should keep in mind the following open Qs

**Extensibility**
- [ ] How do we register as an File > Open provider?

**Performance**
- [ ] Why does it take so long to open a folder?
- [ ] is there any way to mitigate this issue?

**Project System**
- [ ] how to determine File > Open Folder project context? 
- [ ] What areas does our current featureset depend on the existing project system? For each of these areas, how do we extend File > Open Folder to make it happen?
- [ ] How to determine Node.js project context?

**Editing / IntelliSense**
- [ ] how to supply Node.js-specific tsconfig.json w/o explictly adding it to the project?

**Telemetry**
- [ ] How to determine # Node.js projects?
- [ ] Any current telemetry?

**Debugging / Build**
- [ ] how do we set options / debug flags?
  - [ ] current options? 
  - [ ] any future options we should consider?
- [ ] msbuild as a "case study" - what would it take? 

**Roaming between VS / VSCode**
- [ ] what does that look like? 
- [ ] are there any existing efforts to bring them closer together?

**Comment by paulvanbrenk** [comment]
implemented
