### ISSUE TITLE
Debug selected tests does not stop at breakpoint

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/nodejstools#112]
Hi,

Version: NTVS for VS 2015 29-Apr.

The issue outline here https://nodejstools.codeplex.com/workitem/801 has resurfaced in the latest build.

I tried rolling back, but the 03-Mar version is also failing with the same problem on VS 2015 RC.

**Comment by mousetraps** [comment]
Same as #79?

**Comment by NoelAbrahams** [comment]
Yes, it is, thanks.
