### ISSUE TITLE
Add NTVS Build for Dev15 on AppVeyor CI

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1121]
We currently only build NTVS for VS 2015 in AppVeyor. As we start adding more VS15 specific code, we need to start building NTVS for VS15 as well as part of CI.

There does not appear to be a prebuilt environment with VS15 installed, but this AppVeyor issue is tracking that: https://github.com/appveyor/ci/issues/753

**Comment by paulvanbrenk** [comment]
No longer using appveyor
