### ISSUE TITLE
Breakpoint misbehavior inside symbol-keyed function property

### ISSUE THREAD

**Issue by kkeri** [Microsoft/nodejstools#1122]
##### Steps to Reproduce
1. Create new "Blank node.js Console Application".
2. Paste the following code into app.js.
3. Set breakpoint at line 5.
4. Choose *Debug > Start debugging*.

~~~js
var S = Symbol();
var o = {
	[S]() {
		console.log("before");
		console.log("at breakpoint");
		console.log("after");
	}
}
o[S]();
~~~

##### Expected Behavior 

"before" is printed to the console then the debugger stops at line 5.

##### Actual Behavior 

"before" is printed to the console then the program hangs up. VS remains responsive.
If I choose *Debug > Break all* then *Debug > Continue*,
the program runs and terminates without ever stopping at the breakpoint.

- NTVS Version: 1.2.40627.01
- Visual Studio Version: VS 2015 Community U3
- Node.js Version: v4.4.7-x64, v6.2.2-x64

**Comment by kkeri** [comment]
I was able to reproduce the same effect using the built-in command line debugger of node.js, so this seems to be unrelated from Node.js tools.
I have [reported the bug](https://github.com/nodejs/node/issues/7536) to the node.js developers.

A possible workaround is to extract the function reference into a variable and call the function via that variable.

~~~js
var S = Symbol();
var o = {
	[S]() {
		console.log("before");
		console.log("at breakpoint");
		console.log("after");
	}
}
var f = o[S];
f();
~~~

**Comment by mjbvz** [comment]
Thank you for reporting this to node and finding a work around.

I'm closing this as external because it's not actionable for NTVS, but will keep on eye on the reported issue to see when the fix lands in Node.

**Comment by kkeri** [comment]
My thoughts exactly. :+1:
