### ISSUE TITLE
.clear Command in Interactive Window is Broken

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1130]
Discovered during our mob programming session writing tests for the interactive window (#1063)
##### Expected Behavior

In the interactive window:

```
> .clear
> 2
```

Should print `2`
##### Actual Behavior

Output is `TypeError: sandbox argument must have been converted to a context`

**Comment by mjbvz** [comment]
One workaround is resetting the interactive window if you get into this state.

**Comment by paulvanbrenk** [comment]
This works as expected with the move to the VS Interactive Window
