### ISSUE TITLE
Interactive Window Globals Leaking into repl Process Globals

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1131]
Discovered during our mob programming session writing tests for the interactive window (#1063)
##### Expected Behavior

In the interactive window:

```
> global.Array = null
> 2
```

Should print `2`
##### Actual Behavior

Many 😢

This crashes the actual repl process in `util.js` on the line:

```
util.js:73
    const objects = new Array(arguments.length);
```

This is because the global `Array` inside the interactive window has leaked into the `repl` script that is running these commands.

Another case to consider is:

```
> global.Array.prototype.indexOf = null;
```

and similar patterns.

**Comment by paulvanbrenk** [comment]
Considering the limited use in the Interactive Window. Closing
