### ISSUE TITLE
Unity - Visual Studio Enterprise - Crashing after exiting Debugger mode while attached to unity.. 

### ISSUE THREAD

**Issue by Quazaka** [Microsoft/nodejstools#1132]
##### Expected Behavior 
Let me continue my work, and let me edit the code after i finish debugging.

##### Actual Behavior 
After i stop debugging, using the red "stop" square, the program crashes as soon as i try to add a character to any line of code.

##### Version Info
Microsoft Visual Studio Enterprise 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise
Architecture and Modeling Tools   00322-80000-00000-AA93

Visual Basic 2015   00322-80000-00000-AA933

Visual C# 2015   00322-80000-00000-AA933

Visual C++ 2015   00322-80000-00000-AA933

Application Insights Tools for Visual Studio Package   4.3.60226.3

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0

Common Azure Tools   1.5

Microsoft Azure Mobile Services Tools   1.4

NuGet Package Manager   3.3.0

PreEmptive Analytics Visualizer   1.2

SQL Server Data Tools   14.0.50616.0

TypeScript   1.8.31.0

Visual Studio Tools for Unity   2.2.0.0

##### DxDiag
DxDiag; http://pastebin.com/DH0imCzr

##### Event Viewer detials about crash
.NET Runtime: http://pastebin.com/X26aeiTX
Application Error: http://pastebin.com/nMRNqpum

##### Steps to Reproduce
1. Open project in unity
2. Open script in unity (automaticly uses VS)
4. Click Debug in toolbar in VS
5. Choose "attach unity debugger"
6. Start project in unity
7. Follow code via breakpoints in VS
8. Stop debugging using red square "Stop Debugging" in VS
9. Try to add any code anywhere in VS
10. Crash

**Comment by mjbvz** [comment]
It doesn't look like you are running Node Tools for Visual Studio. Please try reaching out to the Visual Studio Unity Tools team instead and see if they can help out. Thanks.
