### ISSUE TITLE
No tests on VS15 Preview 3 (Open Folder)

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#1137]
##### Expected Behavior

What have my mocha tests in the Text Exprorer panel
##### Actual Behavior

Popup with text 
`There were build errors. Would you like to continue and run tests from the last successful build?`
appears.

VS Information:

- NTVS Version: 6-24-2016 Dev Build
- Visual Studio Version: VS 15 Update 3
- Node.js Version: 
##### Steps to Reproduce
1. Open Folder with NTVS project

**Comment by mjbvz** [comment]
Thanks.

We don't currently support VS15 open folder scenarios (#1112) so it's likely that NTVS is not being activated at all in this path. We're looking into this as part of that work.

Does the same scenario work with a normal NTVS project?

**Comment by kant2002** [comment]
@mjbvz Ok. Thanks for exaplanation.

I would like to notice that even if testing not working from VS15, overall experience working with NodeJS project much more pleasant comparable to VS2015. I have MUCH less time when VS freezes. 

So for now I could leave without tests inside VS.

**Comment by paulvanbrenk** [comment]
Fixed with #1959
