### ISSUE TITLE
for .. in IntelliSense type is incorrect

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#114]
![image](https://cloud.githubusercontent.com/assets/762848/7558950/6406d8f8-f763-11e4-8506-1e8d3d71783e.png)

**Comment by mjbvz** [comment]
Fixed in ES6 preview Intellisense in NTVS Alpha 1.2

![image](https://cloud.githubusercontent.com/assets/12821956/14266386/b20df0f0-fa7c-11e5-9945-0fe84ef22ab0.png)
