### ISSUE TITLE
Execute typings separately for each package

### ISSUE THREAD

**Issue by hempels** [Microsoft/nodejstools#1140]
##### Expected Behavior 

Typings should be installed for all packages, not failing when some are missing.

##### Actual Behavior 

If Typings is provided multiple packages as command-line arguments, it fails and stops as soon as any of those is missing. Since many npm's do not have typings in the registry, it is quite common for it to fail and then it doesn't attempt to install the remaining listed packages.

- NTVS Version: 1.2.40627.01
- Visual Studio Version: 14.0.25422.01 Update 3
- Node.js Version: 6.3.0
- Typings Version: 1.0.5

##### Steps to Reproduce
1. Add an npm that has no typings info in the registry
2. Add an npm that does have typings info in the registry
3. Note that typings info for the former will not be installed, because it fails on the latter.

**Comment by mjbvz** [comment]
Thanks for reporting this bug. Looks like you already opened an issue on typings as well (https://github.com/typings/typings/issues/628).

The suggested fix of running typings for each package individually would work, but in my testing there is a lot of overhead to booting up typings for each package compared to providing the entire package list in a single command. We may want to check if typings would take an `--ignore-errors` type flag, but with NTVS 1.2 RTM so close, we may hold off on this

**Comment by neico** [comment]
This is really annoying, especially since VS throws a error popup breaking workflow each time.
I'd really like to have the popup silenced for the release at least, if the underlying issue can't be resolved in time.

**Comment by mjbvz** [comment]
I've submitted a PR #1143 that should fix this.

@neico Do you mean the output window or are you seeing a different popup:

![image](https://cloud.githubusercontent.com/assets/12821956/16890192/20787f96-4aa1-11e6-813a-3dbd9a75f85c.png)

**Comment by neico** [comment]
Hm looks like the popup went away when I manually executed the command (without the packages that had no typings), might have been a corrupted index file or so... (it's a standard popup VS always shouts out whenever a extension encounters a error, or even a fatal one)
