### ISSUE TITLE
NTVS 1.2 Feedback

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1147]
Love it? Hate it? Let us know what you think!

**Comment by mirumatsu** [comment]
Had this weird problem. I'm on VS 2015 Community with NTVS 1.1 installed. Everything just works fine. 

Then saw that 1.2 has been released, so went to upgrade. 

But when i tried saving .ts files it says on the status bar "The project contained errors. Output generation skipped". But it works whenever I Build the project.

So i decided to go back to 1.1 for the mean time.

**Comment by benquarmby** [comment]
The editing experience in 1.2 is much faster and closer to what I've come to expect from browser based JavaScript in Visual Studio.

Unfortunately with issues like #1185 and #1188 it's still not sable enough to recommend and roll out across all our teams.

**Comment by mjbvz** [comment]
@mirumatsu Can you share the full error message you are seeing and any other details, along with some steps to reproduce the issue so we can look into fixing this? Does it happen for new typescript projects as well?

Thanks.

**Comment by mirumatsu** [comment]
There were no error messages, not even a line where there is suspected error. No error when building.

I created a new TS project, and just copied the files from the other project to check if the error would still be there. And, yes, the error still occurred.

This was my setup on my home PC
1. Installed VS Community 2015
    Installed NTVS 1.1 after 2015

2. Updated VS [Update 1]

3. Updated VS [VS with Update 2]
    Updated NTVS 1.2 RC

4. Updated VS [Update 3]
    Updated NTVS 1.2

Then the problem started with last setup.
Then I decided to go back to previous setup, but the error indication was still there.
Made a full uninstall, then reinstalled with setup 3, but still there.

My last attempt was:
5. Full reset of my PC
    Installed VS Community 2015 with Update 3
    Installed NTVS 1.1

Pulled the project from office PC.
Saved a file, Built the project and Error indication gone!

But I noticed something regarding node tools analyzing my codes (never showed before),
so I opened my project folder and noticed that ".ntvs_analysis.dat" was there (never there before).

Suspicion: .ntvs_analysis.dat's absence is the culprit.

**Comment by mjbvz** [comment]
@mirumatsu Just confirming that you are on NTVS 1.2.

The `.ntvs_analysis.dat` file is only used by our old static analysis engine that powers intellisense. You can see which intellisense engine you are using by going to `Tools -> Options` and then `Text Editor -> Node.js -> Intellisense`. You should be in ES6 IntelliSense. If you are already on ES6 IntelliSense, the `.ntvs_analysis.dat` file will not be used at all. It was probably created if you opened the project with NTVS 1.1.

**Comment by mirumatsu** [comment]
Currently I'm on NTVS 1.1 ancd my default IntelliSense is `Full IntelliSense`. I see the `ES6 IntelliSense Preview` as the last option. I'm planning to give 1.2 another try. Is the ES6 IntelliSense in 1.2 still a Preview or is it like a final build?

**Comment by mjbvz** [comment]
@mirumatsu With NTVS 1.2, ES6 IntelliSense is the default option that we want all users to be on, except if they absolutely cannot live without a certain ES5 IntelliSense feature that is no longer supported. The new IntelliSense is a better overall experience and much more stable as well.

**Comment by paulvanbrenk** [comment]
Released several versions since 1.2
