### ISSUE TITLE
Non folder items appear as folders in Solution Explorer

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#1160]
##### Expected Behavior

Non folder items does not appear as folders in Solution explorer
##### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/4257079/17091287/dd21008a-525a-11e6-94b7-6efac38c4f45.png)

- NTVS Version: 7-20-2016 Dev Build
- Visual Studio Version VS2015:
##### Steps to Reproduce
1. Create flder distribution, and place activity.html, activity.scss (any file to be true)
2. Add line in the project <Folder Include="distribution\**\" />

**Comment by mjbvz** [comment]
Interesting. Haven't seen that one before. Do the files still open fine and are they still editable?

I'm having trouble reproducing this bug. Could you please provide some more complete, step by step instructions?

Thanks.

**Comment by kant2002** [comment]
Strange, I have that issue on my main project, where I was trying to simplify switching between VS and VS Code. I could not repro on small project, will start to make smallest repro from project where I discover issue.

BTW: filed editable, and opened just fine.

**Comment by kant2002** [comment]
@mjbvz I think I create repro. By the way find other small issue #1166 which maybe related.

1. Clone https://github.com/kant2002/NTVS-NotAddedFolder/tree/master/NodejsConsoleApp1
2. Create folder `public/app/modules/test`
3. Create any file in the folder `public/app/modules/test`

Let me know if it work for you.

**Comment by kant2002** [comment]
That's still the case even with VS2017 which claim has support for things like `<Compile Include="**\*.cs" />`

I suspect that this is required to update in the project system, I'm in general willing to help fix that. @paulvanbrenk maybe you have some ideas why this could happens?

**Comment by paulvanbrenk** [comment]
Closing as this would require a rewrite of the project system to fix reliably. And we will get this for free when we do that work.

**Comment by kant2002** [comment]
Please keep this open, or at least reference this issue in the *public* issue where you track progress of such rewrite. That way somebody could help with such rewrite.
