### ISSUE TITLE
Assert popups when running test from VS

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#1161]
##### Expected Behavior 
Tests are run without popups

##### Actual Behavior 
a lot of screens like that (about 12 failing tests)
![image](https://cloud.githubusercontent.com/assets/4257079/17091576/6a76b446-525d-11e6-98fb-8c08a3c62936.png)

- NTVS Version:
- Visual Studio Version: 
- Node.js Version: 

##### Steps to Reproduce
1. Checkout NTVS
2. Run tests from VS

**Comment by mjbvz** [comment]
Thanks for the report. Could you provide the list of tests you are seeing these assertions for?

It looks like`WrapperSelfSet` is running just fine in AppVeyor and I'm also able to run it locally. It's not a unit test (evidenced by its dependency on the file system) but it does seem to work.

How are you running the tests? Did you do a complete build before executing the tests?

The example test also seems pretty simple, so you should be able to debug it and see what is going wrong or investigate properly fixing the test. Let me know if you would like any help with that.

Thanks.

**Comment by mjbvz** [comment]
Closing as no repo / more info needed.

If this is still a problem, please provide the requested information and we can reopen this and continue the investigation. Thanks.
