### ISSUE TITLE
type definitions to be automatically added when npm packages are installed using NTVS

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/nodejstools#1164]
I am using Visual Studio 2015 Community Update 3. I have installed Node.js Tools 1.1. Node version is v0.12.2. Everything that I have installed are latest stable version. Whenever we are installing npm packages using NTVS, the type definitions should be automatically added to the solution. There should be no need of [tsd](https://github.com/DefinitelyTyped/tsd) or [typings](https://github.com/typings/typings).

**Comment by mjbvz** [comment]
https://github.com/Microsoft/nodejstools/wiki/Automatic-Typings-Acquisition  :)

This is only supported on NTVS 1.2, so download the RC to give it a try. Please let us know if you run into any issues. Thanks.
