### ISSUE TITLE
_references.js file breaks Intellisense for core Node.js API

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/nodejstools#117]
I have a Visual Studio Node.js project which also contains HTML and client-side Javascript. When I added a `_references.js` file, it broke Intellisense for Node's core API _(e.g. `require('path');`)_. As soon as I remove or rename the file, the problem goes away.

~~I also observed that an `.ntvs_analysis.dat` file does not get generated at all when a `_references.js` file exists.~~ (Actually, an `.ntvs_analysis.dat` file does get generated.)

Is there any way to combine Node.js Intellisense with client-side Intellisense in the same project?

UPDATE: It seems like the Intellisense is mixed as well as it can be in this project. I get proper client-side Javascript Intellisense in HTML files, but in Javascript files I get Node.js Intellisense, which does not include anything from `_references.js`. So, I don't know if there's anything to do. I will probably create a separate project for the client-side code, even though the target environment (atom/electron) is not really server/client.

I'll leave the issue open for comment for now, but I don't think there's anything to do so feel free to just close it.

--
##### `_references.js` file:

```js
/// <autosync enabled="false" />
/// <reference path="ui/jquery/jquery.js" />
/// <reference path="ui/knockout/knockout.js" />
```

**Comment by mousetraps** [comment]
Your other option is marking the "build action" of client-side js code as content. See docs: https://github.com/Microsoft/nodejstools/wiki/Working-with-Browser-(Clientside)-JavaScript-in-NTVS#customizing-browser-and-nodejs-intellisense-modes

**Comment by mousetraps** [comment]
Right now we don't support references in Node.js IntelliSense altogether, but just filed a feature request for it - #119

**Comment by waynebloss** [comment]
Wow, that's a great solution. I will try it out. Thanks.
