### ISSUE TITLE
IntelliSense not working for module.exports w/ U3

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1170]
Note that this may just be an issue with my dev box, so please close if it's confirmed to be a non-issue

##### Steps to Reproduce
1. New starter express 3 app w/ es6 intellisense
2. F12 on `routes.index` in `app.js` should navigate to `exports.index` assignment in `routes/index.js`
3. navigation fails

(also it would be good to add this scenario to our test matrix)

**Comment by mjbvz** [comment]
This seems to work on my machine with the latest dev build. Let me know if there are any other steps in the repo. 

Also added this  to the manual test matrix: https://github.com/Microsoft/nodejstools/wiki/NTVS-1.2-Manual-Test-Matrix#basic-intellisense
