### ISSUE TITLE
Visual Studio hangs at the end of a debug session

### ISSUE THREAD

**Issue by kkeri** [Microsoft/nodejstools#1173]
##### Steps to Reproduce
1. Create new "Blank Node.js Console Application". You get `app.js` containing a single line of code.
2. Delete the right parenthesis, so the line contains `console.log('Hello world';`
3. Select Debug -> Start Debugging.
4. In the console window press any key. The window is closing.

##### Expected Behavior 

You can continue editing your code.

##### Actual Behavior 

Visual Studio hangs and should be restarted.

- NTVS Version: 1.1.31117.00
- Visual Studio Version: VS Community 2015 U3
- Node.js Version: v4.4.7

**Comment by mjbvz** [comment]
Please try upgrading to [NTVS 1.2](https://github.com/Microsoft/nodejstools/releases). We've fixed a number of hangs and performance problems with this release, and it may resolve this issue.

Let me know if it works properly on 1.2 or not. Thanks.

**Comment by kkeri** [comment]
I somehow overlooked this update. Yes, it works properly with 1.2. Thank you.

**Comment by mjbvz** [comment]
Glad to hear that. Please share any other feedback about NTVS 1.2 and report any issues you run into. 

Thanks.
