### ISSUE TITLE
get started wikipage contains nodejs 0.12.7 download links

### ISSUE THREAD

**Issue by japj** [Microsoft/nodejstools#1174]
##### Expected Behavior 
Installation instructions should point to an actual recent version of nodejs. Either by not mentioning explicit versions/download links or by keeping the download links up to date. I did not expect an old 0.12.x download link.

##### Actual Behavior 
After installing Node.js Tools 1.2 for Visual Studio a link is provided "Click here to install Node.js and get started with NTVS" (this points to https://github.com/Microsoft/nodejstools/wiki/Install-Node.js-and-get-started-with-NTVS).

This page page contains links to nodejs installers for 0.12.7! This was released on 2015-07-09 and is not the most recent 0.12.x version (which is 0.12.15 from 2016-06-23)
The most recent LTS version is 4.4.7 as of this writing.

##### Steps to Reproduce
1.  goto https://github.com/Microsoft/nodejstools/wiki/Install-Node.js-and-get-started-with-NTVS
2.  look at download links

**Comment by mjbvz** [comment]
Thanks for reporting this. Certainly not a good introduction for users new to Node.

'Tis the curse of such documentation to be forever out of date, so I've just replaced the whole mess with a link to https://nodejs.org/en/download/
