### ISSUE TITLE
debugger doesn't highlight the current statement

### ISSUE THREAD

**Issue by nippur72** [Microsoft/nodejstools#1183]
In a TypeScript application, when the debugger hits a breakpoint, it doesn't highlight the statement/expression under the caret where the application has halted. There is only the flashing caret. Stepping thru the app with F10 etc.. moves the caret but still no statement highlighting. 
##### Expected Behavior

highlight of the current statement/expression where the debugger has halted
##### Actual Behavior

no highlight
- NTVS Version: 1.2.4076.00
- Visual Studio Version: 14.0.25422.01 update 3
- Node.js Version: v6.2.2

**Comment by mjbvz** [comment]
Is this a regression you've noticed in NTVS, or a feature you see supported in VisualStudio for other languages?

I confirmed the statement is not highlighted for ES6 IntelliSense or for our old IntelliSense engine on NTVS 1.2

Anyone is free to take a look at fixing this. [This question make provide some good starting points](https://social.msdn.microsoft.com/Forums/vstudio/en-US/a80c9ac1-dd92-4d21-9ad7-387377fc4e3c/getting-visual-studio-to-highlight-the-current-line-of-code-youre-on-with-custom-debug-engine?forum=vsx) and I'd be happy to help out with any question or problems.

**Comment by paulvanbrenk** [comment]
This is fixed for the Node 8+ debugger.

![image](https://user-images.githubusercontent.com/5273975/35755149-ffbac4ba-081a-11e8-9533-2703f407d996.png)
