### ISSUE TITLE
Scss file support 

### ISSUE THREAD

**Issue by wangkanai** [Microsoft/nodejstools#1184]
Please add support for add new scss files in the add file for the project. Currently, it only support manually typing the file extension.
- Visual studio 2015 update 3
- Nodejs tools 1.2

**Comment by mjbvz** [comment]
Thanks for the suggestion. 

I'm generally not in favor of adding non-Node.js features to NTVS, but I know that we already allow creating blank `*.styl` files, and it [would be trivial to do the same for scss files](https://github.com/Microsoft/nodejstools/tree/master/Nodejs/Product/Nodejs/FileTemplates/NewItem). To be clear though, creating a blank scss file is the extent of sass support we would offer. There would be no intillisense, syntax highlighting, autocompletion, or any other niceties .

I'm marking this as up for grabs for anyone wants to submit a PR. Don't worry about creating a scss icon when initially looking into the work, just use the empty icon.

**Comment by paulvanbrenk** [comment]
We'll consider this when implementing a new project system, but we'll need to sync with the ASP.NET team, since we proably want to do something better than just a template.
