### ISSUE TITLE
Typings should have optional source control / project integration

### ISSUE THREAD

**Issue by benquarmby** [Microsoft/nodejstools#1186]
Like many teams, we exclude the NPM `node_modules` directory (and Bower `bower_components` and NuGet `packages`) from source control. Currently the contents of the NTVS `typings` directory are added to the `.njsproj` project file and source control by default (excluding `typings.json` files for some reason).

It would be great if the NTVS `typings` directory integration with source control and projects could be made optional. For us it would be ideal if it were treated as an invisible, transient folder that can be rebuilt just-in-time, and only for those folks who use NTVS.

P.S. Adding `typings/` to a dot-ignore file will omit the files from source control, but keep the empty project nodes which is in many ways worse.

**Comment by Laro88** [comment]
In the same context I miss a way to disable typescript completely - why is this mandatory anyway?

**Comment by mjbvz** [comment]
Thanks for the suggestion.

Automatic typings acquisition is a short-term workaround to enable better intellisense in VS2015. We plan on getting out of the typings management business altogether with VS15 (or rather, all the typings logic will be handled transparently, behind the scenes by the Typescript team, much like the ideal solution you suggest).

Excluding the typings directories from source control would be great for most cases, but this is not something we want to handle in code. There are simply too many edge cases to consider, and a very real risk that any cleverness around source control could end up annoying users even more than adding the extra typings files in the first place.

My current suggestion: add the `typings` directory to the `.gitignore` for regular JavaScript projects, don't worry about the proj file changes, and ensure all VS users on your team are on NTVS 1.2+. This way, developers who are not using visual studio don't end up with the extra typings files and you don't have to worry about managing the typings files with source control. Developers using VS would initially see the typings files missing from their solution, but with NTVS 1.2+, these will be recreated shortly after the project loads

Not great, but this allows us to bring a modern intellisense experience to users on VS2015. We are working on making this better with VS15, and you can try this out with one of our [VS15 NTVS dev builds](https://github.com/Microsoft/nodejstools/releases/tag/v1.2.Dev-7.24.2016).

**Comment by mjbvz** [comment]
@Laro88 You can disable automatic typings acquisition all together by going to `Tools -> Options` and then `Text Editor -> Node.js -> IntelliSense`. Turn off the `Automatically add intelliSense typings folders to Node.js projects` option.

Keep in mind that will result in a significantly worse intellisense experience.
