### ISSUE TITLE
Mocha tests are not discovered properly when using import statements

### ISSUE THREAD

**Issue by MikeCook9994** [Microsoft/nodejstools#1187]
##### Expected Behavior 

Mocha test files are detected, parsed, and executed correctly

##### Actual Behavior 

The following output is displayed:

    ------ Discover test started ------
    Processing:                                         
    C:\Users\Mike\Documents\projects\TwitchPlaysTinder\Tests_es6\TinderSwipeCounterTests.js
    Test discovery error: 
    C:\Users\Mike\Documents\projects\TwitchPlaysTinder\Tests_es6\TinderSwipeCounterTests.js:1
    Processing finished for framework of Mocha
    Discovered 0 testcases.
    ========== Discover test finished: 0 found (0:00:00.7673068) ==========

For a test file that begins as:

    import { assert } from "chai";
    import sinon from "sinon";
    import TinderSwipeCounter from "../Matchmaker/TinderSwipeCounter";

    describe("Class: TinderSwipeCounter:", function()
    ...

Replacing the import statements with the syntactically equivalent require statements provides the expected behavior. This code also provides the expected behavior if ran with mocha via the command line.

##### Versions

- NTVS Version: 1.2.40726.00
- Visual Studio Version: 14.0.25424.00 Update 3
- Node.js Version: 6.2.2

##### Steps to Reproduce
1.  Take an existing mocha test file that works and uses require statements and swap those with equivalent import statements.
2.  Build the project.
3.  The above output should be displayed in the output panel.

**Comment by mjbvz** [comment]
Thanks for the detailed report (interesting sounding project BTW)))

I believe this is the expected behavior since [es2015 modules are not supported in node 6](http://stackoverflow.com/questions/38664231/use-import-keyword-without-babel-in-node-6). Does the `import` version of the code work with normal mocha? Are you running a transpiled copy or the original code?

We could improve the error messaging for syntax errors in our test running. What error messages, if any, do you currently see?

**Comment by MikeCook9994** [comment]
I do compile to es5 javascript with babel before running tests and I don't think I've ever tried running them without compiling first.

I thought modules were already supported in node 6 already, but if that's not the case than the actual behavior is the expected behavior for now like you said. I'm content running my tests outside of visual studio for now until they are supported though.

There are no errors outside of what I provided.

Thanks
