### ISSUE TITLE
Profiling error - Performance report no longer exists

### ISSUE THREAD

**Issue by Crazometer** [Microsoft/nodejstools#1189]
##### Expected Behavior

Profiler works normally.
##### Actual Behavior

When attempting to view report generated after running profiler get the follow error `Performance report no longer exists: Performance_20160804.vspx`

While the report is being created a v8.log is created in the directory. Once the the recording is finished the log is deleted. A copy of the logs state midway is [here](https://drive.google.com/file/d/0ByZVs5ZsCqVERW5DU1BMem1ieWs/view?usp=sharing)

As suggested by the [wiki](https://github.com/Microsoft/nodejstools/wiki/Profiling) I tried using `Microsoft.NodejsTools.NodeLogConverter.exe` directly however that was throwing a large number of warnings and eventually crashed on execution. From the outside it looks as though this component probably hasn't been updated to work with logs created by the latest version of node. 

- NTVS Version: v1.2.40726.00
- Visual Studio Version: v14.0.25425.01 Update 3 (latest)
- Node.js Version: v6.3.1 (x64)
##### Steps to Reproduce
1. Launch nodejs profiling
2. Standalone script > pick script/working directory, no command line arguments
3. Start profiling
4. Stop after any length of time
5. Attempt to view report by double clicking

**Comment by mjbvz** [comment]
Thank you for reporting this. 

I was unable to repo the problem by following these steps, but did see similar behavior when trying to open a report while the profiler was still running. A few questions to help with the investigation:

* Does this happen for all projects or just this one? Does it happen for a new express project?
* What type of project are you profiling (server, command line app, ...)?
* What warning and errors are printed when running the log converted manually?

We should support Node 6.3 just fine, but there is a known issue with x64 profiling (#434) around displaying function names.

**Comment by Crazometer** [comment]
> Does this happen for all projects or just this one? Does it happen for a new express project?

I created a new express project and that profiled ok. When I profiled the original app from inside the express solution that also worked ok. It exhibited (#434) as you mentioned but was otherwise fine.

However, the problem still exists when I start visual studio and profile immediately without opening a solution. This would probably rule out the log parser as being the source of the error.

> What type of project are you profiling (server, command line app, ...)?

It's a web crawler.

**Comment by TYoung86** [comment]
Reproduced the problem by attempting to profile a Node.js project created from existing code before saving the sln and njsproj files. Tried to delete the report, said access denied to path "C:\Program Files\Micro...blahblah...", not where my project is, definitely shouldn't have rights to... Saved project and re-opened, was able to run profiler.

Separately, the profiler is giving me "No Call Tree Data Is Available"...

**Comment by paulvanbrenk** [comment]
The current profiler is no longer supported, while we investigate options for a replacement. Current guidance is to use the building profiler.

More info here:

https://nodejs.org/en/docs/guides/simple-profiling/
