### ISSUE TITLE
Run site on IIS

### ISSUE THREAD

**Issue by DvirH** [Microsoft/nodejstools#1190]
Is it possible to run the site as an IIS website, the same as I configure a regular website to run on IIS by the project properties - web server - create virtual directory option?

**Comment by mjbvz** [comment]
I'm not terribly familiar with IIS but this does not sound like something that would be handled by VS directly. You should be able to set up IIS to forward to whatever port you are running node on (port 1337 by default).

What specifically are you trying to achieve? What would an ideal workflow look like for that?

**Comment by mjbvz** [comment]
Closing since there hasn't been any follow up on the question.
