### ISSUE TITLE
ESLint integration

### ISSUE THREAD

**Issue by mathiask88** [Microsoft/nodejstools#12]
I like VS scrollbar markers and I like the highly configurable/pluggable ESLint, so I would love to see it integrated.

**Comment by mousetraps** [comment]
I don't think we'll be able to get to this anytime soon, but perhaps this feature would be an even better addition to WebEssentials since it's applicable to many types of web projects.
http://webessentials.uservoice.com/forums/140520-general/suggestions/6006489-provide-support-for-eslint

**Comment by peterblazejewicz** [comment]
@mousetraps 
Does this:
https://visualstudiogallery.msdn.microsoft.com/6edc26d4-47d8-4987-82ee-7c820d79be1d
solve OP request?

**Comment by mousetraps** [comment]
sure does! thanks for pointing that out!
