### ISSUE TITLE
Intellisense is too noisy and there's no way to turn it off

### ISSUE THREAD

**Issue by LegalizeAdulthood** [Microsoft/nodejstools#1213]
See the screencast here: http://screencast.com/t/Jvf0E0Q6l

Notice how many times I have to dismiss the constant popping up of unwanted "help" from intellisense just so I can see the code surrounding the area where I am typing.

Intellisense is great when you need it.  When you don't need it, it's like a constantly nagging backseat driver who's constantly pestering you about every sign on the street as you drive.  It's annoying and distracting and a productivity killer instead of a productivity enhancer.

There should be a way to put NodeJS intellisense into a "don't call us, we'll call you" mode where it only appears if I press a keystroke asking for it like Alt+Space.

**Comment by mjbvz** [comment]
Thanks for the suggestion. I believe the mode you suggest is actually already supported, but it's not terribly discoverable.

To try it, go to `Tools -> Options` then `Text Editor -> Typescript -> General` and uncheck the "auto list members":

![image](https://cloud.githubusercontent.com/assets/12821956/17910553/33555c2c-693e-11e6-8161-22e670332ad2.png)


This disable to automatic IntelliSense but you can still trigger it using `ctrl + space` when you want. Try checking that out and let me know if you were thinking of something else.

Thanks.
