### ISSUE TITLE
Definition files not found with Visual Studio 2015 and Typescript 2.0

### ISSUE THREAD

**Issue by djflex68** [Microsoft/nodejstools#1216]
TypeScript Version: 2.0

Visual Studio 2015 is complaining about definitions not found (because they are in a root folder).
But in my tsconfig.json file, I'm referencing explicitly the parent typings folder (possible using wildcards since Typescript 2.0). 
The compilation works on command line, which means definitions files are resolved correctly, but Visual Studio Intellisense stills complain about them.
Will this problem be solved soon ?

Thanks

**Comment by mjbvz** [comment]
Thanks for the report.

A few points to help us investigate this:

* Which version of NTVS  and VS are you on? It may be helpful if you could just go to `Help -> About Microsoft Visual Studio` and use `Copy Info` to provide a list of all installed extensions and their versions.
* What is the specific error? Can you please provide the text of the message.
* Can you please provide a sample `tsconfig.json` file, plus an example, simple directory layout to show where the typings are. This will help us setup a repo.

Thanks.

**Comment by djflex68** [comment]
Hello,
Versions are  : 

> Microsoft Visual Studio Professional 2015
> Version 14.0.25425.01 Update 3
> Installed Version: Professional
> Node.js Tools   1.2.40627.01
> Adds support for developing and debugging Node.js apps in Visual Studio
> Node.js Tools - Profiling   1.2.40627.01
> Profiling support for Node.js projects.
> TypeScript   2.0.0.0
> TypeScript tools for Visual Studio

The errors are the same everywhere in Visual Studio only (compilation oustide Visual Studio works !)

> cannot find module 'xxx'

where 'xxx' is a module that has a declaration file which is **NOT** located in subfolder of the one containing the tsconfig.json file.
But in tsconfig, these declarations are specifically referenced in "includes" directive.

```
"include": [
        "**/*.ts",
        "../../typings/**/*.ts",
```
I'm preparing a sample demo for you. 

Thanks

**Comment by djflex68** [comment]
Here is a sample demo, which produce the error on my Visual Studio version.

[demo](http://www.filedropper.com/demo_9)

**Comment by mjbvz** [comment]
@djflex68 The example does not work in VS or outside of it. I had to make these basic edits:

* `"target": "ES5"` -> `"target": "ES6"`
* `import { _ } from "lodash";` -> `import _ from "lodash";`
* Include `server` and some additional files that were not in the solution but on the file system.

But then everything compiled fine in VS, including the resolution of the typings modules. I was unable to repo the problem with this setup. Can you please attach an updated demo. Also, what commands are you using outside of VS to compile?

Thanks.

**Comment by djflex68** [comment]
Hello,

I'm sorry, I think I gave you a wrong url. I made the same edits than yours but this is still not working in Visual Studio. 
Here you can find the updated [demo](http://www.filedropper.com/demo_12)
The command I'm using outside VS is simply "tsc" in www or server folder. 
In the zip file, I've attached a screen capture with the error I'm getting.

Thanks

**Comment by paulvanbrenk** [comment]
@djflex68 Can you share your demo on dropbox, or onedrive...

**Comment by paulvanbrenk** [comment]
This should work with `@types`. http://www.typescriptlang.org/docs/handbook/declaration-files/consumption.html
