### ISSUE TITLE
[lightweight-install] UGH C#/VB get out of my NODE workload! Is that why you're so big??

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1218]
##### Expected Behavior

No C#/VB templates exist in Node.js workload
##### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/762848/17909839/28724962-693b-11e6-8631-79b402c136cf.png)

We should look into where these templates are coming from, and ensure that assets we depend on are componentized properly

**Comment by paulvanbrenk** [comment]
The remaining templates are pulled in from the ASP.NET workload; ideally they would split their templates in project-, and item-templates. 

However I don't think we need to track that here.
