### ISSUE TITLE
[lightweight-install] F12 on routes.index

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1219]
In the starter experess app template, F12ing on index doesn't jump to code. Adding a tsconfig to project root resolves the issue and doesn’t look like recent U3 compilation settings changes made it into TS dev15 codebase. We didn't address this in Preview 4, but let's verify that this change makes its way into the next Dev15 release

**Comment by mjbvz** [comment]
Fixed by the Typescript team in latest internal builds.
