### ISSUE TITLE
[lightweight-install] Profiling component is *huge* (>3GB)

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1220]
The profiling component in Dev15 Preview 4 currently pulls in the entire world (i.e. tons of unnecessary c++ dependencies). We should see if we can depend on a smaller package set since the we should only really need the UI component

**Comment by mjbvz** [comment]
We currently depend on `Microsoft.VisualStudio.Component.VC.DiagnosticTools` which is likely too broad. I'll look through that component to see if we can extract some of its dependencies. We may have to create a new component to bundle some of these together, if a smaller component does not already exist.

**Comment by mjbvz** [comment]
Fixed by switching to `Microsoft.VisualStudio.Component.DiagnosticTools`. Change will be in VS15 RC
