### ISSUE TITLE
[lightweight-install] Node.js v6 x86 should be recommended in default install

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1221]
Our goal is to ensure that things work out of the box with the default install. In order to provide this experience, we should update setup authoring to introduce a check to see whether Node.js was previously installed (this means that things won't necessarily work out of the box for ppl with an existing node install and ppl might be stuck on an older version of node). Also make install label clear by adding "(if not installed)". Maybe eventually add in-product warnings to work around.

**Comment by mjbvz** [comment]
Kai and I talked this afternoon and we are removing the node install from the workload entirely. It just adds something that we have to keep up to date, with too much risk of messing up a developer's environment unexpectedly. Handling all the possible edge cases is not something we want to take on.

We already have logic to warn users when node is not installed. This experience matches what VSCode does.
