### ISSUE TITLE
[lightweight-install] Azure deployment doesn't work

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1222]
##### Expected Behavior 
It's not entirely clear what component we require to make this happen, or whether we're already requiring the right component, but there are other issues at play.

##### Actual Behavior
right click, publish, azure app service not available, clicking on custom and entering a profile generates popup

**Comment by mjbvz** [comment]
Resolved by webtools changing what they pull in with the latest build. Bumped node workload back up in size though :(

**Comment by mjbvz** [comment]
Reopening since we still don't have the easy Azure publish options in dev15 yet. We need to add a few more dependencies on web tools in order to pick these up.

**Comment by mjbvz** [comment]
This is fixed in the latest internal builds and should be available for testing in VS15 in Preview 5

![image](https://cloud.githubusercontent.com/assets/12821956/18453127/a8b9898e-78f2-11e6-9034-8e1a576e2d63.png)
