### ISSUE TITLE
[lightweight-install] Default workload install size is 1.2 GB

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1223]
I think we can do better than that :wink:. Some of the bulk may be related to #1218, but we won't know until we investigate

**Comment by mjbvz** [comment]
According to the VS installer (which I'm not sure how much I really trust at this point) we're down to ~800mb now. Will keep an eye on this.

**Comment by mjbvz** [comment]
Oh for the days of 1.2GB 😢 

 Now the default VS15 install size without Node is around 700MB and the node Node kicks it up to 2GB. This has all come from other teams adjusting the packages we depend on, we have not added any new direct dependencies recently. I'll keep investigating and following up with various teams to see if we can cut this down again.

**Comment by paulvanbrenk** [comment]
Keeping an eye on the size, but nothing we can do here, since most increases seem to come from packages node tools depends on.
