### ISSUE TITLE
Where does the package.json template get its values?

### ISSUE THREAD

**Issue by robbie-mac** [Microsoft/nodejstools#1233]
I know the title of this sounds like a diatribe on bad parenting, but that is almost appropriate.

My questions are these:
1. Where do those values come from?
2. Can we get some options to change them?

Call me lazy, but I get tired of editing the name field as the template appears to use my windows username (system variable %username%).  If this is the case, I would suggest reconsidering this as, a lot of users don't get to choose their account/username. Examples: University students on campus systems, Corporate users on company systems, my mother ( Not that she is a dev but it still holds true. )... the list goes on.
If users could populate that info in the options panel, then it could also fix another issue( #1000 The template used to add the email address field. ). More complete info available to the template. If the fields are populated in the options, then the field is added.

If I am incorrect in my conclusion as to the origin of the author name field, how can I change it?

**Comment by mjbvz** [comment]
These values are provided by Visual Studio as [template parameters](https://msdn.microsoft.com/en-us/library/eehb4faa.aspx). See this file for example: https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/ProjectTemplates/NodejsConsoleApp/package.json

In the case of username, I believe VS gets the value from the current Windows username. 

I do not think adding additional UI to project creation is the correct solution here. That's just going to be a poor wrapper around all the functionality that the `package.json`  provides and editing the `package.json` is really what we want to encourage anyways.  Two alternatives I see:

* Pick up [defaults](http://iamsim.me/set-your-npm-init-defaults/) from `npm init` instead.
* Change the author field to just be `author: ""`. This is what `npm init` does if you do not set defaults. You would still have to edit the `package.json` but then at least we wouldn't provide a potentially wrong value.

The idea of the templates is to provide a quick start, while also not getting in the way too much. They also need to work well enough for the maximum number of use cases. If this is annoying you, feel free to submit a PR that improves things or let me know if you have any other ideas.

Thanks.

**Comment by robbie-mac** [comment]
Of the two options you provided I would pick the former. Taking the defaults from NPM Config is more consistent with general practice, and more in line with what I was suggesting.
To be clear I wasn't suggesting adding more to the project creation UI, but adding to the Tools|Options UI. Where you have the option to clear the NPM Cache, maybe add another area to set NPM defaults.
Also, its not annoying me, its just that I don't always remember to do it, and a lot of it is developer specific boilerplate, and the parts that change (dependencies) have their own UI component already.
