### ISSUE TITLE
Include error details in mocha unit test results

### ISSUE THREAD

**Issue by danderson00** [Microsoft/nodejstools#124]
When an error occurs in a mocha unit test, the details of the error are not displayed in the output page. This is fairly critical information and makes running tests through the IDE unviable.

For example, for the following test:

    describe('Test Suite 1', function() {
        it('Test', function () {
            throw new Error('this should show in test explorer');
        })
    })

the output page looks something like:

![screenshot](https://cloud.githubusercontent.com/assets/1265935/7660990/b7905c80-fb03-11e4-81a0-e0a274020074.png)

**Comment by mousetraps** [comment]
Thx for reporting. Fixed in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)
