### ISSUE TITLE
Typescript Mocha tests is not discovered when using typescript root dir or tsconfig.json

### ISSUE THREAD

**Issue by lostfields** [Microsoft/nodejstools#1241]
##### Expected Behavior

Tests is discovered and runnable with JavaScript output directory and root directory.
##### Actual Behavior

 Tests is not discovered and runnable.
##### Versions
- NTVS Version: 1.2.40627.01
- Visual Studio Version: 14.0.25421.00 Update 3
- Node.js Version: 6.2.2
- Typescript Version:  2.0.2.0
##### Steps to Reproduce
1. Remove all .js/.ts files
2. "TypeScript Build" properties for project in Visual Studio 2015 has to have "Redirect JavaScript output to directory" to eg. "build\" and "Specify root directory of TypeScript files" to "src\"
3. Add a unit test UnitTest1.ts in "src\test\" 
4. Build solution after you have added the needed typings declarations.
5. Output has generated "build\UnitTest1.js" <-- **ignoring folder structure**. 
6. Tests is not discoverable
7. Add a empty file named "empty.ts" in "src\" and it will produce the wanted folder structure; "build\test\UnitTest1.js" and "build\empty.js"
8. Now the funny part. Add a shouldignore.ts at root of project folder. 
9. Build solution
10. The structure of "build\" is now changed, and it contains "build\shouldignore.js" and "build\src\empty.js", "build\src\test\UnitTest1.js". <-- **not wanted as we have set root dir to "src\"**
11. Tests is now discoverable.

Looks like it's ignoring rootDir property in project settings in VS2015

**Comment by lostfields** [comment]
And you have to have the "Typescript Build" settings correct (ourDir etc) as NTVS is not using the properties in tsconfig.json for Test Discovery.

**Comment by jshwei** [comment]
It looks like the the test discover only looks at the project directory [TestDiscoverer.cs#L135](https://github.com/Microsoft/nodejstools/blob/2b7fb0faad64335492648e0834274b8eb5ba9104/Nodejs/Product/TestAdapter/TestDiscoverer.cs#L135) to find tests?

**Comment by ncoder** [comment]
Please fix.

**Comment by lostfields** [comment]
This bug still relates to the inbuilt typescript in Visual Studio 2017, is there a github project for VS2017 as well?

**Comment by MarkOGDev** [comment]
@lostfields I just got VS2017 to honor the settings in tsconfig.json

Make sure that your tsconfig.json has its **Build Action** set to **Content**

**How to Set  'Build Action'**
In the Solution Explorer, Right Click the file and select **Properties**.

In the properties window find the setting for **Build Action**.

Select **Content** in the drop down list.

Now Visual Studio will compile ts/js using the tsconfig.json

How this helps.

**Comment by lostfields** [comment]
@MarkOGDev that's good, I dont' have to duplicate the settings in the project file (.njsproj) anymore, but ourDir and rootDir isn't honor when using Test Explorer yet :-/

Tested in VS 2017 15.5.0 Preview 5.0

**Comment by paulvanbrenk** [comment]
This looks like it's much more work than I expected. Closing in favor for #1949 which captures more use cases.
