### ISSUE TITLE
Autos should display returned results of last function

### ISSUE THREAD

**Issue by pps83** [Microsoft/nodejstools#1245]
Currently autos window seems to be totally empty on NTVS. In many languages usually it displays return values of last called functions and some autos/locals when you step over.

See this [C++ sample screenshot](http://i.imgur.com/xuQbrxL.png)

**Comment by paulvanbrenk** [comment]
@digeff Does this work for the inspector protocol?

**Comment by paulvanbrenk** [comment]
We should consider implementing this in the TypeScript LS. i.e. implement `IVsLanguageDebugInfo.GetProximityExpressions`
