### ISSUE TITLE
Q) Build with VS2015 Update 3 problem

### ISSUE THREAD

**Issue by seanshpark** [Microsoft/nodejstools#1246]
##### Expected Behavior 
Build with no error

##### Actual Behavior 
```
CreatePkgDef : error : FileLoadException: Could not load file or assembly  
'Microsoft.NodejsTools.InteractiveWindow, Version=1.0.2015.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. 
(Exception from HRESULT: 0x8013141A)	InteractiveWindow			
```
and 15 more Errors

- NTVS Version: v1.1.x branch, also with master branch
- Visual Studio Version: 2015 Professional Update 3
- Node.js Version: N/A

##### Steps to Reproduce
1. Open Nodejs/NodejsTools.sln in VS2015
2. Menu Build > Build Solution

**Comment by seanshpark** [comment]
Is it just me or any other have this problem?

**Comment by mjbvz** [comment]
Looks like you need to disable strong name verification for the NTVS assemblies. Here are the instructions for that: https://github.com/Microsoft/nodejstools/wiki/Build-Instructions#manual-environment-setup-steps

Also, did you run the [`EnvironmentSetup.ps1` script](https://github.com/Microsoft/nodejstools/wiki/Build-Instructions#2-run-environmentsetupps1)?

Let me know if that works.

**Comment by seanshpark** [comment]
Wow, 
1) ran  EnvironmentSetup.ps1
2) Registered Nodejs\Prerequisites\EnableSkipVerification.reg file
Got "Build: 27 succeeded". Thanks a lot!
