### ISSUE TITLE
Incorrect icon

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#1248]
##### Expected Behavior 
Icon for the Diagnostic info Window is from NTVSTools

##### Actual Behavior 
Icon for the Diagnostic info Window is from PyTools
![image](https://cloud.githubusercontent.com/assets/4257079/18224229/8a8f92ea-71f0-11e6-82f2-47d0b4ae17aa.png)

- NTVS Version: NTVS shipped with VS15 Preview 4
- Visual Studio Version: VS15 Preview 4
- Node.js Version:  Not applicable

##### Steps to Reproduce
1. Clean install of the VS15 Preview 4
2. Open Tools -> NodeJS Tools -> Diagnostic Window

**Comment by mjbvz** [comment]
Thanks for the report. 

This does not appear to be vs15 specific as I'm also seeing it in dev14 in my testing. Not the highest priority but I'm curious where this icon is even coming from.
