### ISSUE TITLE
Can't redirect input/output from VS IDE.

### ISSUE THREAD

**Issue by HarelAshwal** [Microsoft/nodejstools#1249]
Hi

When working with command line ,I can redirect input/output like this:
node test.js > COM1
or
node test.js < COM1

How can I have this functionality within VS IDE?

Harel

**Comment by mjbvz** [comment]
This is not something that we support currently.

I'm not sure this is well supported for other visual studio languages or project types (http://stackoverflow.com/questions/16262394/how-to-redirect-stdout-of-a-c-sharp-project-to-file-using-the-visual-studio-com) but it is something that could be improved.

Marking as up for grabs. [Here's the place where we setup the debug launch args](https://github.com/Microsoft/nodejstools/blob/86327f9bf3ce5789bc2ed4f1923dee21e06623d0/Nodejs/Product/Nodejs/Project/NodejsProjectLauncher.cs#L228) based on the `ScriptArguments` stored in the `njsproj` file.  [And here's where this is called from](https://github.com/Microsoft/nodejstools/blob/86327f9bf3ce5789bc2ed4f1923dee21e06623d0/Nodejs/Product/Nodejs/Project/NodejsProjectLauncher.cs#L67). Even when launching without the debugger, we use `ProcessStartInfo` with `UseShellExecute` set to false which I think prevents redirection from working.
