### ISSUE TITLE
Remote debugging: Error retrieving websocket debug proxy information from web.config

### ISSUE THREAD

**Issue by miparnisari** [Microsoft/nodejstools#125]
Using VS 2013 Ultimate Update 4, I'm getting the error

**Error retrieving websocket debug proxy information from web.config**

When trying to do **Attach debugger (node.js)** in the server explorer.

**Comment by mousetraps** [comment]
Did you try uncommenting and commenting out the relevant parts in the web.config file? Unless you're using web deploy, the web.config file does not undergo the debug transformation.

**Comment by miparnisari** [comment]
Not sure what you mean. This is my Web.config:

```
<configuration>
  <system.webServer>
    <webSocket enabled="false"/>
    <handlers>
      <add name="iisnode" path="app.js" verb="*" modules="iisnode"/>
    </handlers>
    <rewrite>
      <rules>
        <rule name="DynamicContent">
          <match url="/*"/>
          <action type="Rewrite" url="app.js"/>
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
  <!--
    For a description of web.config changes see http://go.microsoft.com/fwlink/?LinkId=235367.

    The following attributes can be set on the <httpRuntime> tag.
      <system.Web>
        <httpRuntime targetFramework="4.5" />
      </system.Web>
  -->
  <system.web>
    <compilation targetFramework="4.5"/>
    <pages controlRenderingCompatibilityVersion="3.5" clientIDMode="AutoID"/>
  </system.web>
</configuration>
```

**Comment by mousetraps** [comment]
We should add a better way of doing this, but you can either try creating one of the azure node templates, or look at the web config and web. debug.config in the following folder 
https://github.com/Microsoft/nodejstools/tree/master/Nodejs/Product/Nodejs/ProjectTemplates/AzureExpressApp

Either try including the web.debug.config from there in your project  and right click and select preview transform or something similar, and copy the result to your web.config file. Or start with the web.config in the template and uncomment/comment accordingly.

After you do that, you'll also need to enable web sockets from the azure website portal if you haven't already.

**Comment by mousetraps** [comment]
If you are using web deploy (which we don't recommend because you are more likely to run into #69) the debug transformation will happen automatically in the debug configuration so you wouldn't have to manually transform the file yourself.

**Comment by mousetraps** [comment]
Did this help at all?

**Comment by billti** [comment]
I hit this issue also yesterday with the latest NTVS bits and a fresh Azure deployment. Looks like something is still amiss here. 

I could attach using the 'Attach to Process' dialog rather than Server Explorer (as outlined at https://github.com/Microsoft/nodejstools/wiki/Advanced-Debugging#attaching-without-server-explorer ), so it would seem debugging was configured fine on the Azure end, it's likely the VS end which has the issue.

**Comment by paulvanbrenk** [comment]
Looks like remote debugging is no longer working, and we need to make a bunch of changes to handle the changes in Azure (and Node 8+). 

Closing as this should be part of the larger Azure plans.
