### ISSUE TITLE
Task Runner Explorer and Gulp error

### ISSUE THREAD

**Issue by chrisculver701** [Microsoft/nodejstools#1256]
##### Expected Behavior 
Can use the task runner explorer.
"gulp --tasks-simple" runs without error

##### Actual Behavior 

- NTVS Version: 1.2.40726.00
- Visual Studio Version: 14.0.25425.01 Update 3
- Node.js Version: 4.5.0

I am able to build and run the helloworld-webpart example.

I'm still learning this setup and not sure where to go with this. I did some searching on these issues but nothing stood out.  Any advice or help would be appreciated.

![image](https://cloud.githubusercontent.com/assets/1316190/18355541/0394d800-75af-11e6-9beb-943f7e8a5d60.png)
![image](https://cloud.githubusercontent.com/assets/1316190/18355567/1e685314-75af-11e6-9fcc-27cf524df88a.png)
![image](https://cloud.githubusercontent.com/assets/1316190/18355600/3a087c98-75af-11e6-8c4c-769c64edcae6.png)

**Comment by mjbvz** [comment]
The task runner is not owned by NTVS. With VS 2015, I believe it's packaged in with Web Tools. 

Looking at the error, it's not clear what the problem, but take a look at this: https://blogs.msdn.microsoft.com/webdev/2015/03/19/customize-external-web-tools-in-visual-studio-2015/ Picking up an old node version is one common cause of problems with the task runner.
