### ISSUE TITLE
Breakpoints are not hit when debugging

### ISSUE THREAD

**Issue by BalassaMarton** [Microsoft/nodejstools#1265]
Similar to an old issue (#112 and #268), but with the latest tools. Breakpoints are not hit, neither in .ts, nor in generated or manually written .js files.
- NTVS Version: 1.2.4072600
- Visual Studio Version: 14.0.25425.01 Update 3
- Node.js Version: 6.5.0
##### Expected behavior

Debugger should stop at breakpoints.
##### Actual behavior

Debugger doesn't stop at breakpoints.
##### Steps to Reproduce
1. Create new Blank Node.js Console Application
2. Place a breakpoint at the `console.log()` row in `app.ts`
3. Build and start debugging
##### Additional notes
- It doesn't matter if I set the breakpoint in the .ts or .js file, the debugger never stops. 
- If I start debugging with F10 (Step over), the debugger stops at the first line as expected, and I can even step into it.
- Placing a `debug;` line in `app.js` and running `node debug app.js` also works as expected.

**Comment by mjbvz** [comment]
Thanks for the report. 

I'm unable to repo this in my testing. Can you please also let me know the following to help with the investigation:

1. In the first case, how are you launching the debugger? `F5`? `Build -> Start Debugging` in the menus?
1. The version of TypeScript you are using in VS. This is under `Help -> About Visual Studio`.
2. Do you have a tsconfig.json or configure the TypeScript build system?

Thanks.

**Comment by BalassaMarton** [comment]
1. F5 or click the green play button. Building the solution before starting makes no difference.
2. TypeScript 1.8.36.0
3. No `tsconfig.json`, I just use Project / Properties for setting up the TS configuration.

Workarounds I have tried without success:
- Disable firewall (both Windows Firewall and ESET Smart Security)
- Target ES6 or ES5
- Run Visual Studio as administrator

I've also tried placing a `debugger;` line into my code. When run, Visual Studio instantly crashed without a meaningful error. However, when I execute `node debug app.js` in a command line, node's console debugger stops at the `debugger;` line as expected. Is there any way to test if Visual Studio has actually connected and receiving messages from the node debugger?

**Comment by mjbvz** [comment]
Here's a few more things to help with the investigation:

Go to `Tools -> Node.js Tools -> Diagnostic Info...` and check `Enable Node.js Tools Live Diagnostics output pane`. This will print information about NTVS's communication with the node debugger to the `Output` window in VS. Then please repo the debugger problem and paste the output from the window here.

For the VS crash, try looking in `%appdata%\Roaming\Microsoft\VisualStudio\14.0\App\ActivityLog.xml` This file may have information about the crash. If you could upload that as well, I can take a quick look through to see if anything stands out. 

Thanks.

**Comment by BalassaMarton** [comment]
Live Diagnostics output:
[NTVSDebug.txt](https://github.com/Microsoft/nodejstools/files/472086/NTVSDebug.txt)

**Comment by paulvanbrenk** [comment]
Moved to shared debugger for Node 8.
