### ISSUE TITLE
Problem elsewhere: Visual Studio Online (VSTS) hosted build NTVS is 1.0

### ISSUE THREAD

**Issue by Laro88** [Microsoft/nodejstools#1269]
Please delete if unfit :-)
This is more of a potential problem elsewhere in MS but here goes since I can't find a way to provide any feedback on the hosted build config site.
The hosted build environment in VSTS depends on NTVS 1.0. I noticed this while trying to find out why Node.JS typescript unit tests can't find a single unit test inside my project, although they run fine locally with NTVS 1.2 installed.
The spec is here:
https://www.visualstudio.com/en-us/docs/build/admin/agents/hosted-pool#software

Any way to let MS know that they should keep up the pace in the hosted build config?

**Comment by mjbvz** [comment]
Thanks for reporting this. I'm also not sure if there's a good public feedback channel for VSTS at this time, so I'll try to find out who to reach out to internally for this. 

Until then, if the main problem running unit tests, try the workaround documented here: https://github.com/Microsoft/nodejstools/wiki/Test-Explorer#running-tests-on-visual-studio-team-services

It's far from ideal, but it should allow you to use the latest NTVS code when running the tests. Please let me know if you run into any problems or have any questions.

**Comment by Laro88** [comment]
@mjbvz that guide is for 1.1, I have tried for 1.2 without any luck.
With only dll's inside bin\ntvs then tsc fails with errorcode 2 in local builds. "Microsoft.TypeScript.targets suddenly has invalid elements."
vsToolsPath and CompileTypeScriptDependsOn has invalid child elements, perhaps the xmlns is being validated against. start of XML at the end.

Any suggestions on making continuous integration on VSTS Build and Release is more than wellcome. After a couple of days with trial and error (lots of error) I feel like i have been banging my head on a door that unfortunately is not there yet - just a paint on a concrete wall :-)


```
<?xml version="1.0" encoding="utf-8"?>
<!--
***********************************************************************************************
Microsoft.TypeScript.targets

WARNING:  DO NOT MODIFY this file unless you are knowledgeable about MSBuild and have
          created a backup copy.  Incorrect changes to this file will make it
          impossible to load or build your web deploy projects from the command-line or the IDE.

This file defines the steps in the standard build process for TypeScript files.

Copyright (C) Microsoft Corporation. All rights reserved.
***********************************************************************************************
-->
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <VsToolsPath Condition="'$(VsToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VsToolsPath>
  </PropertyGroup>

  <UsingTask TaskName="TypeScript.Tasks.VsTsc" AssemblyFile="TypeScript.tasks.dll" />
  <UsingTask TaskName="TypeScript.Tasks.FindConfigFiles" AssemblyFile="TypeScript.tasks.dll" />

  <PropertyGroup>
    <CompileTypeScriptDependsOn>
```

**Comment by Laro88** [comment]
I could not get the typescript compilation and test execution to functionso I reverted back to javascript :-(
