### ISSUE TITLE
IntelliSense should detect return type when using eval statements

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#127]
```javascript
function multiply(a, b) {
	return eval('a*b');
}
multiply(3, 3);
```

In this case, we detect ```a``` and ```b``` to be of type ```number```, but the return type of multiply is ```undefined``` when we expect it to be ```number```.

That said, it's also possible that this limitation is by-design for performance reasons.

**Comment by mjbvz** [comment]
Marking this as external since in NTVS 1.2 Beta, ES6 IntelliSense is backed by Typescript / Salsa. Fixing this would likely require work on their side.

**Comment by mjbvz** [comment]
Closing as external. As noted, this is something the Typescript team would have to implement. I really don't see them getting around it anytime soon however, as there is basically zero use case for this. Besides just not being used all that often in modern js, `eval` is most often called with dynamic strings, which we could never provide proper intellisense for.
