### ISSUE TITLE
feature request: typescript class library project

### ISSUE THREAD

**Issue by wizzard0** [Microsoft/nodejstools#1287]
Project which creates a npm module or just a standalone reference-able .js / .d.ts file which could be added to another NTVS project as a reference together with npm projects, rebuild accordingly and so on. Like the C# does.

Both typescript and plain JS would be awesome, typescript being first.

**Comment by mjbvz** [comment]
Could you perhaps provide an example project or explain what this template would look like in a bit more detail? It may also help to understand how it would be different from the existing Console project templates.

Also, there was a PR out at one point for something like this I believe: #951 . Take a look at that PR and see if it would solve this problem. The PR needs a few updates before we would be able to merge it, but it may be a good starting point.

Thanks.

**Comment by paulvanbrenk** [comment]
This is tracked here: https://github.com/Microsoft/TypeScript/issues/11
