### ISSUE TITLE
Restart server when some code change occurs

### ISSUE THREAD

**Issue by bbodenmiller** [Microsoft/nodejstools#1291]
##### Expected Behavior

When I change some Node code I expect the server to restart and serve the new code (similar to nodemon)
##### Actual Behavior

Currently I must manually stop the node process and restart to get the new changes. How about integrating `nodemon`?

- NTVS Version: 1.2.40726.00
- Visual Studio Version: 14.0.25431.01 Update 3
- Node.js Version: v6.4.0
##### Steps to Reproduce
1. Launch example application
2. Load server
3. Make change and save
4. Refresh, see no change

**Comment by paulvanbrenk** [comment]
We'll consider this when moving to a new project system, the changes requird currently warrant this. An alternative is to use the "Open Folder" functionality and use npm scripts.
