### ISSUE TITLE
Can not install on Visual studio 15 Preview 4

### ISSUE THREAD

**Issue by MaklaCof** [Microsoft/nodejstools#1293]
I can not install Node.js Tools Dev 2016-07-27 on Visual studio 15 Preview 4.

![nodejstools](https://cloud.githubusercontent.com/assets/1589573/18739867/c8281bf8-80a6-11e6-8ca8-18163b53a13d.PNG)

**Comment by mjbvz** [comment]
Thanks. See #1238. This is currently expected.

To try out recent NTVS features on VS15 Preview 4, select the Node.js workload in the VS installer. Please let us know if you run into any problems.
