### ISSUE TITLE
Publish fails when project contains linked Content (dup of #359)

### ISSUE THREAD

**Issue by kbattocchi** [Microsoft/nodejstools#1296]
I'm still hitting exactly the issue described in #359: if there's linked content then publishing through Visual Studio fails.  Actually, even previewing through the Publish wizard fails, with the error

> Error: InvalidParameter
> Parameter name: index

Was there a commit that was supposed to have fixed that issue (there's no discussion there, so it's hard to tell whether it was directly addressed), or could it have regressed?

**Comment by paulvanbrenk** [comment]
Closing. We're re-evaluating publishing from VS, for now if you run into issues please use Azure CLI
