### ISSUE TITLE
Can't profile C# code, Node.js profiling tool overrides default profiler

### ISSUE THREAD

**Issue by hecsalazar** [Microsoft/nodejstools#1298]
##### Expected Behavior

The analyze menu used to have an option for profiling .net code
##### Actual Behavior

The Analyze menu doesn't show anymore the default profiling tool for C#, it only shows nodejs tools profiling

- NTVS Version: 2015
- Visual Studio Version: update 3
- Node.js Version: 1.1
##### Steps to Reproduce

not clear, I noticed sometime ago after installing node.js tools

**Comment by mjbvz** [comment]
Can you please detail what your project and solution look like and describe the expected behavior here. Do you have a mix of C# and NTVS projects in the solution? Does this happen for all projects or just some of them?

Thanks.

**Comment by hecsalazar** [comment]
Hi,

This solution have ASP.Net webapi projects and class libraries, no node js.

I tried uninstalling nodejs tools  but the default VS profiler it's still gone.

**Comment by paulvanbrenk** [comment]
I don't reproduce this. And the node.js profiler is deprecated for VS 2017.
