### ISSUE TITLE
The 'MRU Package' package did not load correctly.

### ISSUE THREAD

**Issue by dotnetdude** [Microsoft/nodejstools#13]
Hi,

   I try to install nodejs tools in visual studio 2013 update 3 and I am getting the following error. Any idea why?

The 'MRU Package' package did not load correctly.

I uninstalled Nodejs tools solved the problem.

Thanks for the help.

**Comment by mousetraps** [comment]
Never seen that error before... 
Are you using Xamarin? http://forums.xamarin.com/discussion/19138/installing-xamarin-destroys-your-visual-studio-2013-modules-configuration

Try running ```devenv /setup```. We run it during the the installer, but there may be something wonky going on here...

**Comment by mousetraps** [comment]
Any update on this issue, or are you still blocked?

**Comment by mousetraps** [comment]
Closing this issue since we haven't heard back. Happy to re-open if you're still having issues.
