### ISSUE TITLE
Exception when scrolling text editor with node.js code

### ISSUE THREAD

**Issue by syagev** [Microsoft/nodejstools#130]
Got a random exception while scrolling the text editor with node.js code. I really can't think of any special circumstances that caused this nor can I reproduce. Perhaps the only non-standard condition is that I'm working in a dual monitor setup where my text editor tabs are in a separate window than the IDE main frame.

Here is my [AcitivityLog.xml](https://www.dropbox.com/s/d75dl04u5dhi8cv/ActivityLog.xml?dl=0)

Running latest build version v1.1.Dev-5.13.2015 (44bd6d6962ab7acb49d1bbe538af1f350edc928f)
VS 2013 Ultimate, win7 x64

**Comment by mousetraps** [comment]
The error is coming from the Node.js classifier, which is running in the background... Does it reproduce consistently?

**Comment by syagev** [comment]
Nope. I thought the log might be enough to find the source and fix. This
happened just once and I use NTVS consistently.

**Comment by mousetraps** [comment]
No worries. It should hopefully be enough to find a fix, but it's always good to understand the reason we ended up in that state to begin with.

**Comment by mousetraps** [comment]
Thx @syagev for reporting, and thx @jaredpar for fixing it :smiley:. Available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)
