### ISSUE TITLE
feature request: for loop iterator clash warning

### ISSUE THREAD

**Issue by dandybreath** [Microsoft/nodejstools#1310]
i stumbled upon this logic error several times, and i need a feature to warn me that iterator var names was already used so i don't need to scroll up just to check if i was inside a loop or not.
```
for(var i = 0; i < len; i++){

  // codes here

    for(var i = 0; i < len; i++){ <- i need a warning here
    }
}
```
please let me know if there's a better solution to this problem, thanks.

**Comment by mjbvz** [comment]
Thanks for the suggestion.

We use TypeScript to power our JavaScript editor, so this would be something that would have to implement on the TS side. It looks like they already considered generating warnings for this case, but ultimately decided not to enable it: https://github.com/Microsoft/TypeScript/issues/656

Please follow up on the Typescript project if you would like to see this supported. Thanks.

**Comment by dandybreath** [comment]
thanks for your reply, it seems like they won't change it since typescript have 'let' syntax.
so i'm thinking that it's better to wrap it under function.
```
function iteration(s, e, fc) {
    for (var i = s; i < e; i++) {
        fc(i);
    }
}

iteration(0, 3, function (i) {
    iteration(0, 3, function (i) {
        console.log(i);
    });
    console.log('=');
    console.log(i);
    console.log('=');
});
```

**Comment by mjbvz** [comment]
@dandybreath You are probably already aware, but you can also use `let` in JavaScript with [Node 4.x+](http://node.green/#let). If you just switch `var` to `let` in the code above, I believe it will do the correct thing

**Comment by dandybreath** [comment]
@mjbvz it won't be a problem if i code only on server side, but i code for both client and server. i think it's better to avoid inconsistency since it was the same language on both client and server
