### ISSUE TITLE
Failing unit tests marked as ok

### ISSUE THREAD

**Issue by Laro88** [Microsoft/nodejstools#1316]
I have some mocha unit tests that are failing, however if I have a matching set of paranthesis in the name then they are marked ok (green)
 fails, but marked as ok (see screen capture further down)
```
it('Test 2(hamster)', function(d) {
        assert.ok(1 === 1, "This shouldn't fail");
        //assert.ok(false, "This should fail");
        dancinghamstercrash
        d();
    })
```
The output from the test looks like this:
```
Test Name:	Mocha Test 2(hamster)
Test Outcome:	Passed
Result StandardOutput:	
mocha.json options file not found. Using default values: { ui: 'tdd', reporter: 'tap', timeout: 2000 }
process.env.NODE_ENV:unittest NODE_ENV set in testconfig - should ONLY be set here for unit testing purposes.
[36m[2016-10-06 08:59:53.326] [DEBUG] testconfig - [39mcloudinfo in config:{ name: 'alarmprocessor', statusinterval: 15 }
1..0
# tests 0
# pass 0
# fail 0
```

I suspect the test engine to disregard the content of the test when there are paranthesis inside the test - or some sort of broken "paint orange" routine.

##### Expected Behavior 
Failing test
##### Actual Behavior 
Test marked as good

- NTVS Version: 1.2
- Visual Studio Version: 2105 update 3
- Node.js Version: 6.7.0
mocha etc is updated

![image](https://cloud.githubusercontent.com/assets/12495700/19143356/a4634654-8ba3-11e6-8fa1-e2acb3fbd2a5.png)

removing a single paranthesis makes the test fail
![image](https://cloud.githubusercontent.com/assets/12495700/19143378/c0b6cef2-8ba3-11e6-9ddf-3b80c5a84bd4.png)

##### Steps to Reproduce
1. create a test with a paranthesis set that fails and see it pass when running the tests - my thoughts are "holy shit, thank god for non VS2015 based CI that caught the issue"

**Comment by mjbvz** [comment]
Thanks for the report. That certainly doesn't sound good.

I'm unable to repo the problem though. here's the test file I used:

```js
var assert = require('assert');

describe('Mocha', function() {
    it('Test 1', function() {
        assert.ok(true, "This shouldn't fail");
    })

    it('Test 2(hamster)', function (d) {
        assert.ok(1 === 1, "This shouldn't fail");
        //assert.ok(false, "This should fail");
        dancinghamstercrash
        d();
    })
})
```

And the results:

![image](https://cloud.githubusercontent.com/assets/12821956/19167837/410bba72-8bc2-11e6-806c-8ce2c71839b3.png)

```
Test Name:	Mocha Test 2(hamster)
Test Outcome:	Failed
Result StandardOutput:	
Using default Mocha settings
1..1
not ok 1 Mocha Test 2(hamster)
  ReferenceError: dancinghamstercrash is not defined
      at Context.<anonymous> (C:\Users\matb.REDMOND\documents\visual studio 2015\Projects\NodejsConsoleApp7\NodejsConsoleApp7\UnitTest2.js:11:9)
# tests 1
# pass 0
# fail 1
```


Can you please let me know if that example looks correct and if there are any other repo steps that are required. Also:

* What specific version of NTVS 1.2 do you have installed? Go to `Help -> About Visual Studio` and Look for Node.js tools.
* Does this still repo for you if you create a new JavaScript console app project with just that failing test case, or does it only repo with you have a larger project with other test cases too?

Thanks.

**Comment by Laro88** [comment]
@mjbvz I am using node tools 1.2.40726.00   (why double zero btw)

I created a new console node.js project, added a test folder and put in my test - it does not fail in VS2015. 
![mocha test](https://cloud.githubusercontent.com/assets/12495700/19188380/a4d8c764-8c91-11e6-9171-8a3bcaf0b25b.jpg)
running mocha from commandline catches the error:
![mocha](https://cloud.githubusercontent.com/assets/12495700/19188471/2c967282-8c92-11e6-86e0-0b58455ab196.jpg)
The Tests output shows that the Mocha Test 2(hamster) is not ignored.
```
------ Run test started ------
Processing: C:\temp\test bug\test bug\test\t1.js
  Creating TestCase:C:\temp\test bug\test bug\test\t1.js::Mocha Test 1::Mocha
  Creating TestCase:C:\temp\test bug\test bug\test\t1.js::Mocha Test 2(hamster)::Mocha
Processing finished for framework of Mocha
========== Run test finished: 2 run (0:00:01,119) ==========
```
I just double checked, breaking the paranthesis matching causes the test to pass, this naming is also making the test pass:
```'Test 2(hamster)()(])(())'```

**Comment by kant2002** [comment]
I confirm the issue with following steps:
1. Create empty project.
2. Add new folder test
3. Add new 'Javascript Mocha Unit Test' with name UnitTest1.js
4. Add mocha to package.json with version "^3.1.0"
5. Install mocha using 'Install missing NPM package' commnad on npm node
6. Run tests. All green.

**Comment by kant2002** [comment]
Another observation that is in VS 15 Preview 5 this is working as expected.

**Comment by Andreyul** [comment]
This bug was fixed in PR https://github.com/Microsoft/nodejstools/pull/1197. Try the latest Dev Build. https://github.com/Microsoft/nodejstools/releases/tag/v1.3.Dev-10.14.2016

**Comment by mjbvz** [comment]
Thanks @Andreyul, I just confirmed that this does seem to be the problem. Please try the latest dev builds or make sure your test names do not contain  any regexp characters if you are using Mocha 3.x and NTVS 1.2.

Closing as resolved.
