### ISSUE TITLE
Installing npm packages doesn't work in Visual Studio 2013 Community Edition

### ISSUE THREAD

**Issue by nramsey** [Microsoft/nodejstools#132]
If I select "Install New npm Packages" search for a package and click "Install" it acts as if everything is working properly.
```
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
cheerio@0.19.0 node_modules\cheerio
├── entities@1.1.1
├── dom-serializer@0.1.0 (domelementtype@1.1.3)
├── css-select@1.0.0 (boolbase@1.0.0, css-what@1.0.0, nth-check@1.0.1, domutils@1.4.3)
├── htmlparser2@3.8.2 (domelementtype@1.3.0, domutils@1.5.1, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13)
└── lodash@3.9.1

====npm command completed with exit code 0====
```
But nothing is added to my packages either in VisualStudio or in my file directory, and nothing is added to package.json.

If I add the package to package.json myself, the package shows up as (missing) I then select "Install Missing npm Packages"

I get the following errors:
```
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! path C:\Windows\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! package.json ENOENT, open 'C:\Windows\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\npm-debug.log

====npm command completed with exit code -4058====
```
If I select the individual missing package and select "Install Missing npm Package" I get the same behavior as installing above, where it seems to work but the package remains (missing) and no data is actually added to the filesystem.

**Comment by mousetraps** [comment]
What's the full path to your project and project files? It looks like the project folder location itself is exceeding max_path (#69), so the install command was instead started in the windows directory. 

Also what happens if you run ```.npm install <somepackage>``` from the Interactive window?

**Comment by mousetraps** [comment]
haven't received any more info on this, so closing it as no-repro for now. Feel free to re-open if you're still running into the issue.

**Comment by ashishmorgan** [comment]
I am using some shared drive. Path is like '\\somedrive\myProject'. I am getting the same error. Is this because of the shared drive?
