### ISSUE TITLE
Cannot Redefine Function Declarations in Interactive Window

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1320]
NTVS 1.2+
##### Repo
1. Open NTVS interactive window.
2. Enter `function a() { return 10 }`
3. Return;
4. Enter `function a() { return 20 }`
5. return;
6. Enter `a()`
##### Expected

`20` is printed
##### Actual

`10` is printed. It seems function declarations cannot be redefined.

![image](https://cloud.githubusercontent.com/assets/12821956/19174559/70009b28-8be4-11e6-93dd-7edee36e6ed7.png)

Forms such as `function a() { return 10 }; function a() { return 20 }` work as expected, as do variable declarations

**Comment by paulvanbrenk** [comment]
This is fixed in VS 2017 Update 7
