### ISSUE TITLE
Building broken in Preview

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#1321]
##### Expected Behavior 
The build success, and tests showing in the Test Explorer

##### Actual Behavior 
An exception occurred while test discoverer 'TestDiscoverer' was loading tests. Exception: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\Node.js Tools\Microsoft.NodejsTools.targets

- NTVS Version: Shipped with VS 15 Preview 5
- Visual Studio Version: VS 15 Preview 5
- Node.js Version: 

##### Steps to Reproduce
1. Create new project
2. Add 'Javascript Mocha Unit Test'
3. Press 'Run All' in Test Explorer

**Comment by mjbvz** [comment]
As discussed in PR #1322, I believe #1304 already provided a solution for this. We'll continue tracking getting the test explorer working with #1180 . I believe it should now properly work in VS15 RC
