### ISSUE TITLE
Installed Scoped Modules not In Package.json Not Displayed in NPM Node

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1339]
##### Steps
1. Create new blank NTVS console JS app.
2. In interactive window, run `.npm install @types/nodes`
##### Expected

`@types/node` is listed in the npm solution explorer tree. It should be listed as not included in the `package.json`.
##### Actual

Package is installed but not listed

![image](https://cloud.githubusercontent.com/assets/12821956/19370919/e89c3022-9163-11e6-957b-28dbfa7e2e53.png)

**Comment by paulvanbrenk** [comment]
This is fixed in Visual Studio 2017 Update 4
