### ISSUE TITLE
Not Installed Scoped Module in Package.json Incorrectly Displayed

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1340]
##### Steps
1. Create a new, blank console Node JavaScript app.
2. Edit the `package.json` to include:
   
   ``` json
   "dependencies": {
     "@types/node": "6.0.x"
   }
   ```
3. Save the `package.json`.
##### Expected

`@types/node` should be listed in the npm solution explorer node, with a `"Not Installed"` message next to it.
##### Actual

`@types/node` incorrectly listed as just `node` and marked as `not listed in package.json`

![image](https://cloud.githubusercontent.com/assets/12821956/19371019/a669c574-9164-11e6-8c1f-d3305fa21357.png)

**Comment by paulvanbrenk** [comment]
This is fixed in Visual Studio 2017 Update 4
