### ISSUE TITLE
Cannot Installed Scoped Modules using NPM UI

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1341]
##### Expected Behavior

Uses should be able to install scoped modules, such as `@types/node`, using the NTVS npm UI.
##### Actual Behavior

It seems that scoped modules are not displayed in the UI:

![image](https://cloud.githubusercontent.com/assets/12821956/19371126/7ab335f4-9165-11e6-854b-4b611e2575e1.png)

I tried searching for `@types/node`, `types/node`, and just `node` but no searches seemed to return the target module.

You can install scoped modules just fine using the interactive window or the command line.

**Comment by Sc0tTyXL** [comment]
Yup, same for company packages :(

**Comment by paulvanbrenk** [comment]
This is fixed in Visual Studio 2017 Update 4
