### ISSUE TITLE
ProjectView should not be part of the project file

### ISSUE THREAD

**Issue by sharwell** [Microsoft/nodejstools#1344]
##### Expected Behavior 

The `ProjectView` element is part of a user-specific file, e.g. **\*.njsproj.user**, which can be excluded from source control.

##### Actual Behavior 

The `ProjectView` element appears in the **\*.njsproj** file, so any time someone changes the view on their local machine it becomes part of a Git commit.

- NTVS Version: 1.2.40726.00
- Visual Studio Version: 14.0.25425.01 Update 3
- Node.js Version: 3.10.3

##### Steps to Reproduce

1. Open a **\*.njsproj** project in Visual Studio
2. Select the project node in Solution Explorer
3. Click **Show All Files** on the Solution Explorer toolbar
4. Save the project

**Comment by mjbvz** [comment]
Thanks. This looks like the same problem as #250 . Let me take a quick look to see if we just need to update the project templates as the comment in #250 describes, or if the fix is more involved.

**Comment by sharwell** [comment]
@mjbvz It is the same issue, and simply deleting the line from our project resolved the issue!
