### ISSUE TITLE
Npm UI Search Box Overlap in Right to Left Input Mode

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1346]
1. Open the NPM UI.
2. Go to search box
3. Hit `Right CTRL + Shift` to switch to right to left input mode

Notice that the search icon overlaps with the entered text:

![image](https://cloud.githubusercontent.com/assets/12821956/19403702/ce3c94e6-921d-11e6-9789-4dcfac53daa2.png)

**Comment by mjbvz** [comment]
This also happens with left to right text if the string is long enough: 

![image](https://cloud.githubusercontent.com/assets/12821956/19536828/842ca3f8-9602-11e6-8e16-6ce81c7138ac.png)

**Comment by paulvanbrenk** [comment]
Fixed in VS 2017 Update3
