### ISSUE TITLE
Improve unit test loading / parsing error reporting (VS2013)

### ISSUE THREAD

**Issue by danderson00** [Microsoft/nodejstools#135]
A few scenarios where it is difficult to tell why unit tests are not being found and appearing in Test Explorer, with no reported reason why:

- no local mocha package - to repro, create a new console project, add the default mocha unit test template and select "Run All". No tests are loaded as mocha is not installed as a local module, no indication of this in the output window.

- error during parsing / executing test files (e.g. syntax error, non-existent module, etc). For example:

        var assert = require('assert');

        describe('Test Suite 1', function () {
            require('non-existent-module');

            it('Test 1', function() {
                assert.ok(true, "This shouldn't fail");
            })
        })

The test in this file is not loaded, and no errors are reported to the output window.

**Comment by mousetraps** [comment]
Hey, regarding the first issue, did the following error not appear in the output window? If so, I can't reproduce it. 
![image](https://cloud.githubusercontent.com/assets/762848/8067770/ad386912-0ea4-11e5-85f9-8f2bdbda6ce0.png)

**Comment by danderson00** [comment]
Repro:
- new NTVS blank console project
- add default mocha unit test
- run all tests

Tests output window is empty. 

Node tools version is 1.0.30324.01. Possibly only occurs with specific environment conditions, e.g. I use nvm-windows to switch between node versions, though it doesn't matter which node version I am using.

**Comment by mousetraps** [comment]
May have narrowed this down a little. I can't reproduce this on the first time I run all, but the second time (after the error is shown), the Tests output window is empty.

**Comment by mjbvz** [comment]
This seems to have been improved with VS2015 or by NTVS at some point.

If I introduce a syntax error in a unit test file, that is now clearly reported in the `Tests` output window:

![image](https://cloud.githubusercontent.com/assets/12821956/18072268/9ab30f72-6e11-11e6-94a2-58dbcb9dda74.png)

The same if I introduce a runtime error:

![image](https://cloud.githubusercontent.com/assets/12821956/18072278/b7f2799c-6e11-11e6-8238-2827c72c252f.png)


In both cases, the text explorer window will not show these tests but the test output window will show what is wrong.
