### ISSUE TITLE
Exception In Interactive Window when Holding Alt and Pressing Up Arrow Key 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1360]
##### Steps to Reproduce
1. Open NTVS interactive window
2. Enter a line of text and press enter to evaluate it.
3. On the next input, hold alt and press the up arrow key.
##### Expected Behavior

Noop
##### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/12821956/19532914/86f1121e-95f2-11e6-9b7d-9d747311aa01.png)

This exception does not seem to come from our code, but from VS. I also do not see any details in the activitylog file.

Alt plus arrow normally moves text in a VS text editor. We may need to disable this behavior in the interactive window.

**Comment by paulvanbrenk** [comment]
Fixed moving to shared VS Interactive Window
