### ISSUE TITLE
Debug with VS2013 Pro

### ISSUE THREAD

**Issue by DrYSG** [Microsoft/nodejstools#137]
I recently upgraded from V1 to V1.1 Alpha of nodejstools. Running on windows 7, I notice the following issue at times. I am debugging an express project

when I start a debug session about 20% of the time, nothing happens when I start debug. But if I F5 a second time the window comes up and all works fine. There is no problem ever when I start the node program from a a DOS command prompt.

Has anyone else seen this?

**Comment by mousetraps** [comment]
Mind trying the latest dev build? 
https://github.com/Microsoft/nodejstools/releases/
We fixed a race condition there with debugging that cleared up many similar issues people were having.

**Comment by DrYSG** [comment]
I would love to. I love what you have done, and would like to help.

**Comment by mousetraps** [comment]
Awesome, let me know when you get the chance to try it out. 5-13-2015 should have the fix. https://github.com/Microsoft/nodejstools/releases/tag/v1.1.Dev-5.13.2015

**Comment by DrYSG** [comment]
The May 13 build seems to have cleared up both the startup issue, and also an additional issue I was having with breakpoints not being triggered.
