### ISSUE TITLE
Header Icon/Image Does Not Show Up in Import Existing Project Wizard UI

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1377]
##### Steps
1. Open VS.
2. Create new project.
3. Select node.js, from existing code.
##### Expected

In the from existing code Project Wizard UI, there is apparently supposed to be an icon/image in the header
##### Actual

Only text, no icon:

![image](https://cloud.githubusercontent.com/assets/12821956/19582539/3e6be912-96ea-11e6-956d-f3bb1ea5090f.png)

I don't know how long this has been broken but I always assumed the above was how things were supposed to look. Only when I looked at the source for this UI did I realize an image is supposed to be loaded here too.

Checked with NTVS 1.3 in VS2015 on a dev machine and in a vs2017 build

**Comment by paulvanbrenk** [comment]
Fixed for 15.4
