### ISSUE TITLE
ES6 support for 'completed' features.

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#141]
**We eventually want all-up ES6 support, but we will be prioritizing features in the 'completed' state.**

ES6 adds lots new features both on the browser side and on the server side.  Google’s V8 engine that Node.js and io.js run on has since made lots progress in supporting the ES6 features.  Node.js v0.12.x (which is what NTVS 1.x has been tested on) ships with V8 version 3.28.73, while the latest io.js v2.0.1 ships with V8 version 4.2.77.20.  Between the two V8 versions, there have been many ES6 features added. 

An ES6 feature is either in the Completed state, or the Staged state or In-Progress state. 

Io.js has shipped the following ES6 features by default in the Completed state (no runtime flag required):
* Block scoping
  * [ ] Let
  * [ ] Const
  * [ ] Function-in-blocks
* Collections
  * [ ] Map
  * [ ] WeakMap
  * [ ] Set
* WeakSet
  * [ ] Generators
  * [ ] Binary and Octal literals
  * [ ] Promises
  * [ ] New string methods
  * [ ] Symbols
  * [ ] Template strings

Features that are in staging (the –es_staging runtime flag):
  * Classes
  * Object literal extensions
  * Symbol.toStringTag

Features that are in-progress are (not recommend for use yet):
  * Modules
  * Arrays
  * Array_includes
  * Regexps
  * Arrow_functions
  * Proxies
  * Sloppy
  * Unicode
  * Unicode_regexps
  * Computed_property_names
  * Rest_parameters

**Comment by gilly3** [comment]
My arrow functions are giving me red squigglies and break the editor.  This is painful.  How long until this is addressed?

**Comment by mousetraps** [comment]
@gilly3 we have an ES6 preview mode now if you want to give it a spin: https://github.com/Microsoft/nodejstools/wiki/ES6-IntelliSense-Preview-in-NTVS-1.1

**Comment by gilly3** [comment]
This didn't work for me.  I have TypeScript v1.6.3.0 installed in Visual Studio Community 2015.  But, when I go to select the IntelliSense level for node, there is no ES6 option.  The only options I see are Full IntelliSense, Quick IntelliSense, and No IntelliSense.

I've rebooted a few times since installing TypeScript 1.6.

**Comment by mousetraps** [comment]
Have you installed the latest NTVS release? http://github.com/Microsoft/nodejstools/releases

**Comment by gilly3** [comment]
I only had the latest release build.  I installed the latest pre-release dev build and now I have the option available.  Thanks.

**Comment by mjbvz** [comment]
Many of these (but not all) are resolved by the new the ES6 Intellisense preview in NTVS Alpha 1.2 .

I think we should close this issue because it is too broad and does not have a clear resolution. If you run into any ES6 issues using the Alpha, please open individual bugs to track those problems.
