### ISSUE TITLE
Automatic Typings Acquisition not working

### ISSUE THREAD

**Issue by pkunze** [Microsoft/nodejstools#1415]
##### Expected Behavior 

When I add a package to a JS-Project, I expect NTVS to create a `Typings` folder and to download the Definition files.

##### Actual Behavior 

I just can't seem to get this to work. No matter if it is within an existing Project, or a brand new one. 

- NTVS Version: 1.2.40726.00
- Visual Studio Version: Microsoft Visual Studio Enterprise 2015 Version 14.0.25431.01 Update 3
- Node.js Version: 6.7.0
- I have set everything as described in the corresponding Wiki page.

##### Steps to Reproduce
1. Create a new JS Project (not TS)
2. `npm install express`
3. No Typings installed

Are there any additional Steps required? Could it be a matter of a corporate Proxy-Server within the Company I work at?

**Comment by mjbvz** [comment]
As long as you have `ES6 IntelliSense` enabled (found under `Tools -> Options` then `Text Editor -> Node.js -> IntelliSense`) and have not disabled automatic typings acquisition, the typings for express should be automatically downloaded. 

Can you try reproducing this again and check the `npm` section of the Output Window in visual studio? It should log if automatic typings acquisition was attempted and if it failed for some reason. The proxy could very well be causing issues here.

**Comment by pkunze** [comment]
Sure, see the output below:

I just did the following:

1. Made sure ES6 IntelliSense is enabled 
2. Made sure automatic typings acquisition is enabled
3. Created new JS Project
4. Installed `express`

> ====Executing command 'npm install express --save '====
> 
> typings-aquisition-test@0.0.0 C:\Users\pkunze\Documents\Visual Studio 2015\Projects\CRM Solution\TypingsAquisitionTest
> npm WARN typings-aquisition-test@0.0.0 No repository field.
> `-- express@4.14.0 
> npm WARN typings-aquisition-test@0.0.0 No license field.
>   +-- accepts@1.3.3 
>   | +-- mime-types@2.1.12 
>   | | `-- mime-db@1.24.0 
>   | `-- negotiator@0.6.1 
>   +-- array-flatten@1.1.1 
>   +-- content-disposition@0.5.1 
>   +-- content-type@1.0.2 
>   +-- cookie@0.3.1 
>   +-- cookie-signature@1.0.6 
>   +-- debug@2.2.0 
>   | `-- ms@0.7.1 
>   +-- depd@1.1.0 
>   +-- encodeurl@1.0.1 
>   +-- escape-html@1.0.3 
>   +-- etag@1.7.0 
>   +-- finalhandler@0.5.0 
>   | +-- statuses@1.3.0 
>   | `-- unpipe@1.0.0 
>   +-- fresh@0.3.0 
>   +-- merge-descriptors@1.0.1 
>   +-- methods@1.1.2 
>   +-- on-finished@2.3.0 
>   | `-- ee-first@1.1.1 
>   +-- parseurl@1.3.1 
>   +-- path-to-regexp@0.1.7 
>   +-- proxy-addr@1.1.2 
>   | +-- forwarded@0.1.0 
>   | `-- ipaddr.js@1.1.1 
>   +-- qs@6.2.0 
>   +-- range-parser@1.2.0 
>   +-- send@0.14.1 
>   | +-- destroy@1.0.4 
>   | +-- http-errors@1.5.0 
>   | | +-- inherits@2.0.1 
>   | | `-- setprototypeof@1.0.1 
>   | `-- mime@1.3.4 
>   +-- serve-static@1.11.1 
>   +-- type-is@1.6.13 
>   | `-- media-typer@0.3.0 
>   +-- utils-merge@1.0.0 
>   `-- vary@1.1.0 
> 
> ====npm command completed with exit code 0====
> 
> Could not acquire typings for 'node'
> Successfully installed typing files for Intellisense.
> (node:12528) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): PopsicleError: Unable to connect to "https://api.typings.org/entries/dt/node/versions/latest"
> Caused by: Error: connect ECONNREFUSED 104.24.113.177:443
> (node:12528) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): PopsicleError: Unable to connect to "https://api.typings.org/entries/dt/express/versions/latest"
> Caused by: Error: connect ECONNREFUSED 104.24.113.177:443
> (node:12528) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): PopsicleError: Unable to connect to "https://api.typings.org/entries/dt/node/versions/latest"
> Caused by: Error: connect ECONNREFUSED 104.24.113.177:443
> (node:12528) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): PopsicleError: Unable to connect to "https://api.typings.org/entries/dt/express/versions/latest"
> Caused by: Error: connect ECONNREFUSED 104.24.113.177:443
> (node:12528) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): PopsicleError: Unable to connect to "https://api.typings.org/entries/dt/express/versions/latest"
> Caused by: Error: connect ECONNREFUSED 104.24.113.177:443
> (node:12528) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): PopsicleError: Unable to connect to "https://api.typings.org/entries/dt/node/versions/latest"
> Caused by: Error: connect ECONNREFUSED 104.24.113.177:443

**Comment by pkunze** [comment]
I am suspecting the Proxy-Server of my company btw. However, placing an `.typingsrc`-file in the project 

```
{
    "proxy": "http://proxy.mycompany.com:8080",
    "rejectUnauthorized": false
}
```

leads to another output:

> ====npm command completed with exit code 0====
> 
> undefined:1
> ﻿{
> ^
> SyntaxError: Unexpected token ﻿ in JSON at position 0
>     at Object.parse (native)
>     at exports.parse (C:\Users\pkunze\AppData\Local\Microsoft\Node.js Tools\ExternalTools\node_modules\rc\lib\utils.js:15:17)
>     at addConfigFile (C:\Users\pkunze\AppData\Local\Microsoft\Node.js Tools\ExternalTools\node_modules\rc\index.js:31:20)
>     at module.exports (C:\Users\pkunze\AppData\Local\Microsoft\Node.js Tools\ExternalTools\node_modules\rc\index.js:45:3)
>     at Object.<anonymous> (C:\Users\pkunze\AppData\Local\Microsoft\Node.js Tools\ExternalTools\node_modules\typings-core\dist\utils\rc.js:11:44)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
> An error occurred installing typings used for IntelliSense.

**Comment by mjbvz** [comment]
Yes, it looks like the proxy is causing issues. Try changing the `.typingsrc` file to:

```js
proxy="http://proxy.mycompany.com:8080"
rejectUnauthorized=false
```

as per: https://github.com/typings/typings/issues/120#issuecomment-184172627

**Comment by pkunze** [comment]
Perfect, works like a charm!
