### ISSUE TITLE
Debugger: No code has been loaded for this code location

### ISSUE THREAD

**Issue by spara** [Microsoft/nodejstools#1421]
##### Expected Behavior 
Attached to Node.js remote debugging
Set breakpoint.
Debugger finds breakpoint.

##### Actual Behavior 
Setting breakpoint has this message:
The breakpoint will not currently be hit. No code has been loaded for this code location.

- NTVS Version: 1.2.40726.00
- Visual Studio Version: 14.0.25431.01
- Node.js Version: 6.9.1

##### Steps to Reproduce
1. Run node app from here: https://github.com/docker/labs/tree/master/developer-tools/nodejs-debugging (add RemoteDebug.js)
2. Modify docker-compose.yml, to `command: nodemon -L RemoteDebug.hs app.js`
3. Attach to Node.js remote debugging
4. set breakpoint in app.js

**Comment by billti** [comment]
Is this issue specific to Docker? Or are you seeing this in other NTVS scenarios involving debugging?

**Comment by spara** [comment]
After additional testing, it appears to be an issue with Docker. Closing this issue.

**Comment by wgutierrezr** [comment]
I'm working on an ASP.Net Core 1.1 MVC project and VS2017 v15.2 doesn't debug any javascript code.
