### ISSUE TITLE
NodeJs templates not available after install

### ISSUE THREAD

**Issue by claudiuconstantin** [Microsoft/nodejstools#1426]
##### Expected Behavior 
As a user I should be able to create a new Node project based on a VS template.

##### Actual Behavior 
After pressing Ok I am getting an error: "The template specified cannot be found. Please check that the full path is correct"

- NTVS Version: 1.2
- Visual Studio Version: Microsoft Visual Studio Enterprise 2015 - Version 14.0.25431.01 Update 3
- Node.js Version: 7.2.0

##### Steps to Reproduce
1. New Project
2. Browse NodeJS project templates and pick one
3. Hit Ok

**Comment by TronicLabs** [comment]
same here

**Comment by TronicLabs** [comment]
after an install repair it fix the problem

**Comment by claudiuconstantin** [comment]
In my case that didn't fixed it :( Had to work in Experimental instance

**Comment by paulvanbrenk** [comment]
Did you install VS in the default location?

**Comment by paulvanbrenk** [comment]
unable to reproduce
