### ISSUE TITLE
Increase visibility of client-side/server-side modes

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#143]
We get a lot of questions on this, and people are *generally* okay with the solution, but it would be great to get rid of that initial frustration. 
https://github.com/Microsoft/nodejstools/wiki/Working-with-Browser-(Clientside)-JavaScript-in-NTVS

**Comment by mousetraps** [comment]
Still needs some work, but you can see where it's going. 

Adding the info to the horizontal editor margin at the bottom.
![image](https://cloud.githubusercontent.com/assets/762848/8269623/014c96fc-1767-11e5-953e-87714aa44a1f.png)

I found this to be the least intrusive of approaches. Other ideas included labeling the files in solution explorer, active editor tab, status bar text, in the intellisense dropdown, etc.

It's just a wpf control, so we'll be able to make it clickable to toggle between the modes too. Additionally, we'll have a context menu command on folders that would make it easy to mark many files as content/client-side. 

@SteveALee, @beautifulcoder, @billti - what do you think?

**Comment by beautifulcoder** [comment]
My vote is the solution explorer and status bar. I like maximizing coding real estate, and drop the horizontal scroll bar / stuff at the bottom of the editor.

**Comment by mousetraps** [comment]
Thanks. Yeah, that was my concern too. I made the text extra small (10pt) to account for it, but ultimately I was hoping I could  bring it inside the pre-existing horizontal scrollbar margin, but there doesn't appear to be any way to do so :-/  

Status bar doesn't work because we would be overloading it - we can only really include text there, and other messages fly by there too (anyone in VS can write to it whenever they want), so it wouldn't stay up for very long, and would also interfere with more important messages like the analysis status. 

Solution explorer... I went back and forth on. I may just make a prototype of that one too. In that case, we would only be able to include the labels on folders, not the files themselves (to avoid clutter), so it might be a little confusing when you have mixed child files/folders. And the labels need to be terse too - e.g. server/client/mixed so that you can actually read them.

**Comment by mousetraps** [comment]
Hmm... the other nice benefit of making it a sln explorer property is that we'll be able to guess better at new files.

**Comment by mousetraps** [comment]
So the solution explorer approach will look something like this...
![image](https://cloud.githubusercontent.com/assets/762848/8270309/b72a8c14-178e-11e5-8001-bf175d71224f.png)

**Comment by SteveALee** [comment]
So I think you have pretty much decided and I'm basically happy with the explorer solution

* Is this as determined by the intelisense setting per file?
* It appears you are showing an aggregated result for the folder? By examining all the files? WHat about each file?
* alternative labels would be node and browser. Perhaps a little more specific about the differences (javascript global context). I someone will have an architecture with a nodejs client :)
* You mention UI to set multiple files but a convention would be to be consistent with-in folders  (as you show). So be good to set only on a top level folder for client, server and possibly mixed. Or is that your proposal and I missed some background?
* what about isomorphic (universal) javascript where files run on both client and server :) I think in NT4VS you could simply treat as node files so can debug on server, while using F12 tools for client. That or allow easy switch as you suggested in other UI example.

**Comment by mousetraps** [comment]
Answers below

* Is this as determined by the intelisense setting per file?
    * Yes, it traverses all the files under that directory to determine the current setting based on whether the js files are set to "Content" or "Compile"
* Rather than showing an aggregated result for the folder how about showing an icon for each file (less screen real estate)? Generally icons are a little less accessible though
  * Less screen real-estate, yes, but it brings with it a whole slew of issues beyond accessibility too
    * didn't think it would be immediately apparent what that means (consider how much information you have to convey in so few pixels! We would need to convey it's both a directory and node.js/mixed/browser, and we'd end up in a similar state we are with npm packages, where people keep wondering what's up with the "circle", and we need to tell them it's actually a hexagon if you look really closely, but we didn't have enough pixels :smiley:) We can talk to UX to see if they can come up with something, but I'm not touching this one :P
    *  In general, people prefer a folder/file-based project system, and changing the icons would make it feel too foreign right off the bat. The labels blend in a little more. 
    * Too inconsistent with the rest of the VS experience.
    * Icons on each file makes it difficult to scan an entire folder - ultimately most of the projects I've seen place their code in it's own directory, so it makes sense to optimize this experience.
    * doesn't have the advantage of allowing us to guess what type of file you want to add next.
* alternative labels would be "node" and "browser". Perhaps a little more specific about the differences (javascript global context). I just bet someone will have an architecture with a nodejs client :)
  * I like it! Also more consistent with how we explain it in the docs.
* You mention UI to set multiple files but a convention would be to be consistent with-in folders  (as you show). So be good to set only on a top level folder for client, server and possibly mixed. Or is that your proposal and I missed some background?
  * To elaborate... essentially what we would do is check all the javascript children in that folder to see if if they are set to Content or Compile (which is effectively the analysis setting). This allows the label to reflect what's actually going on, and helps us avoid discrepencies/confusion if one of the children is not set to that. Additionally, you'll have the ability to right click on any folder (not just top level), and set as "Content", or "Compile", and that will recursively change all the children to that setting (no properties are actually changed on the folder itself, really, as it's simply calculated based off the children.) 
* what about isomorphic (universal) javascript where files run on both client and server :) I think in NT4VS you could simply treat as node files so can debug on server, while using F12 tools for client. That or allow easy switch as you suggested in other UI example.
  * Yep - by default, everything will be set to "Compile" if you add it to a mixed folder (no different than the rest of the VS experience). With these changes, you *still* need to restart the editor, so still not seamless :disappointed: Right now we're chatting with some teams internally re: how we might be able to join forces, so *fingers crossed* hopefully we can come up with a better story for this in the future.

**Comment by SteveALee** [comment]
Thanks for the answers - i've no more comments.

**Comment by mousetraps** [comment]
Available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)
