### ISSUE TITLE
Deleting a folder from the project doesn't remove the TypeScriptCompile items that were in the folder

### ISSUE THREAD

**Issue by billti** [Microsoft/nodejstools#1433]
1. Create a new TypeScript Express project
2. Delete a folder containing a bunch of files in the solution explorer
3. Observe that the project still contains items for each file that was deleted.

The items should be removed from the project if the folder containing them was deleted in solution explorer.

**Comment by paulvanbrenk** [comment]
I don't reproduce this on any project type, with or without nested folders containing just TS files, or a mix of files.
