### ISSUE TITLE
Cannot Inspect Large Object in NTVS

### ISSUE THREAD

**Issue by claytoncarney** [Microsoft/nodejstools#1437]
##### Expected Behavior 
Inspect/Watch all variables
##### Actual Behavior 
Attempt to inspect large object (and then all objects) fails

- NTVS Version: 1.2.40726.00
- Visual Studio Version: Visual Studio Community 2015 Version 14.0.25431.01 Update 3
- Node.js Version: v6.9.1

##### Steps to Reproduce
1. Set breakpoint at line 6 and debug
2. Attempt to Inspect/Watch variables

I posted this on [stackoverflow](http://stackoverflow.com/questions/41083181/cannot-inspect-large-object-in-ntvs), but got no response. 

The json file in the sample was generated in Python with PTVS. There is no inspect/watch issue debugging  that project.

I also discovered that there is no inspect/watch issue debugging the sample in VS Code (provided I use the Node.js v6.3+ Experimental environment).

[KJV2.zip](https://github.com/Microsoft/nodejstools/files/647741/KJV2.zip)

**Comment by paulvanbrenk** [comment]
This should work for Node 8 debugging (since it uses the same debugger as VS Code)
