### ISSUE TITLE
Can't Have Custom Hook for F5 Debugging

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/nodejstools#1441]
Writing an electron app and created the project built using "Import existing Node.Js" Project Type on the electron-sample. This project is started using `npm start` from the commandline, which then calls `electron .`. (This is configured in the package.json).

It doesn't seem like there is any way to start the applet using F5 except by passing various command-line arguments to node, so I can't launch the project form within VS.

##### Actual Behavior 

- NTVS Version:
- Visual Studio Version: 
- Node.js Version: 

##### Steps to Reproduce
# Clone the Quick Start repository
$ git clone https://github.com/electron/electron-quick-start

# Go into the repository
$ cd electron-quick-start

# Install the dependencies and run
$ npm install
$ npm start

Open VS.
Start project using `From Existing Node.js code.`
Observe that the app crashes when started from the shell because that's not how it's supposed to be started.

**Comment by paulvanbrenk** [comment]
This will require a large rewrite of the project system which is currently out of scope for us
