### ISSUE TITLE
Squigglies Not Showing for build errors

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/nodejstools#1445]
![image](https://cloud.githubusercontent.com/assets/3226984/21203630/2b58885a-c208-11e6-9a43-1909c2cc9101.png)

##### Steps to Reproduce
1. Clone and create a partially "typescript-ified" electron app using powershell:
```
mkdir c:\repo
cd c:\repo

# Clone the Quick Start repository
git clone https://github.com/electron/electron-quick-start

# Go into the repository
cd electron-quick-start

mv main.js main.ts

# add tsconfig.json
$tsconfig = @"
{
  "compileOnSave": true,
  "typeAcquisition": { "enable": true },
  "compilerOptions": {
    "module": "commonjs",
    "outFile": "main.js"
  }

}
"@
$tsconfig | add-content -path ./tsconfig.json

# Install the dependencies
npm install
```
2. Overwrite an existing NodeJs project with these files (eg: creat a blank node app, remove all items, and then copy the electron files over and add the existing items).

3. Rebuild solution. Get errors.
4. Observe no squigglies.

**Comment by paulvanbrenk** [comment]
Don't repro
