### ISSUE TITLE
JSON Outline tab opens but doesn't do anything

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/nodejstools#1446]
![image](https://cloud.githubusercontent.com/assets/3226984/21204146/b9f29194-c20a-11e6-89de-c4a69825e92e.png)

##### Steps to Reproduce
1.  Follow steps in #1445
2.  Open tsconfig.json
3. Observe JSON outline tab opens even though it does nothing.

**Comment by paulvanbrenk** [comment]
JSON outline tab is not part of NodeTools, ( I think it's part of the ASP.NET tools).
