### ISSUE TITLE
Allow debugger to work when using server restart plugins like nodemon

### ISSUE THREAD

**Issue by Kesudan** [Microsoft/nodejstools#1449]
I can configure NTVS to start my node server with nodemon. The server starts and debugging in Visual Studio works well.

However when nodemon restarts the node server, Visual Studio stops debugging.

The advised work around from online boards is to start without debugging (Shift + F5) however this loses the ability to use breakpoints which makes it unworkable.

- NTVS Version: 1.2
- Visual Studio Version: 2015 update 3
- Node.js Version: 4.4.7

##### Steps to Reproduce
1: Install nodemon globally from NPM.
2: Open your Project Properties ("PROJECT" > "YourApp Properties...")
point the "Node.exe path" to nodemon.cmd (click on the button right of the input field, enter "%AppData%\npm\" in the adress bar, show all files, select "nodemon.cmd", save the properties form)
3: Start debugger, then whilst the server is running make changes to code and save

**Comment by paulvanbrenk** [comment]
Since the node process is actually killed, the debugger is detached... you can reattach when the node process starts again. We don't currently have a great way to automate this, since we can't know the process id of the newly spawned node process.
