### ISSUE TITLE
output info in output window vs. console dialog

### ISSUE THREAD

**Issue by oldmtn** [Microsoft/nodejstools#1451]
##### Expected Behavior 
NTVS's debug info of javascript can't output to output window.
As we all know, when using visual studio to single step c++ program, all of it's debug info can be output to output window. But NTVS's debug info is a console dialog which is not very convenient for us to read or analyse. 
So I think If NTVS can output debug info into output window of VS, that would be great!

Below is a thumbnail of visual studio output window.
![image](https://cloud.githubusercontent.com/assets/4652810/21538931/d5df89ec-cddc-11e6-951a-c320c065d7bc.png)

**Comment by paulvanbrenk** [comment]
since `util.debug`  is deprecated, and the suggested replacement is `console.error` outputting to the console seems a logical choice.
