### ISSUE TITLE
Visual Studio 2015 Hangs on Node.js Project Creation.

### ISSUE THREAD

**Issue by TylerJaacks** [Microsoft/nodejstools#1467]
##### Visual Studio hangs.

- NTVS Version: 1.2.40726.00
- Visual Studio Version: 2015 Update 3 
- Node.js Version: 5.1.0

##### Steps to Reproduce
1. Create a project.

**Comment by billti** [comment]
Looks similar to #1457 . Not sure what would have suddenly started causing issues here recently. Thanks for the report.

**Comment by billti** [comment]
I just spend some time running through some scenarios without issue. The 1.2 build of NTVS is pretty old now. Are you able to try with one of the newer pre-releases (https://github.com/Microsoft/nodejstools/releases)?

**Comment by paulvanbrenk** [comment]
Closing as no repro
