### ISSUE TITLE
'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'name'

### ISSUE THREAD

**Issue by Michael-0** [Microsoft/nodejstools#1473]
I get this error everytime I install a package or open the solution : 

```
System.AggregateException: One or more errors occurred. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'name'
   at CallSite.Target(Closure , CallSite , Object )
   at Microsoft.NodejsTools.Npm.SPI.PackageJson.get_Name()
   at Microsoft.NodejsTools.Npm.SPI.RootPackage.get_Name()
   at Microsoft.NodejsTools.Npm.SPI.AbstractNodeModules.AddModule(IPackage package)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NpmController.<RefreshAsync>d__1.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'name'
   at CallSite.Target(Closure , CallSite , Object )
   at Microsoft.NodejsTools.Npm.SPI.PackageJson.get_Name()
   at Microsoft.NodejsTools.Npm.SPI.RootPackage.get_Name()
   at Microsoft.NodejsTools.Npm.SPI.AbstractNodeModules.AddModule(IPackage package)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NpmController.<RefreshAsync>d__1.MoveNext()<---
```

I'm working with the latest versions of VS 2015, NTVS, and NodeJS. I tryed reinstalling all of them without success.

- NTVS Version: NTVS 1.2 VS 2015.msi
- Visual Studio Version: VS Pro 2015 (14.0.25431.01 Update 3)
- Node.js Version: v6.9.5

I have read these related issues, but they didn't help :
https://github.com/Microsoft/nodejstools/issues/533
https://github.com/Microsoft/nodejstools/issues/208
http://stackoverflow.com/questions/34355698/npm-stop-working-in-visual-studio-2015-after-node-js-upgrade

Edit: my `package.json` file does have a `name` property :
```
{
   "version": "1.0.0",
   "name": "test",
   "private": true,
  "devDependencies": {
    "gulp": "3.9.1",
    "gulp-sass": "3.1.0",
    "run-sequence": "1.2.2",
    "del": "2.2.2",
    "gulp-uglify": "2.0.1",
    "gulp-imagemin": "3.1.1",
    "gulp-util": "3.0.8",
    "node-sass": "4.5.0",
    "imagemin": "5.2.2",
    "uglify-js": "2.7.5",
    "gulp-sourcemaps": "2.4.0"
  }
}
```

**Comment by paulvanbrenk** [comment]
* Does this reproduce with a new application, or only with an existing application?
* Can you share the application this happens on?

**Comment by Michael-0** [comment]
Yes I can reproduce this issue :
1. Create new ASP.NET MVC Project
1. Add, New Item, "NPM Configuration File", this will create a package.json file
2. Edit the file with the cotent above, this triggers : "Executing command 'npm install'"
3. The error appears in the output window multiple times.

**Comment by Michael-0** [comment]
I installed the latest build, "NTVS.Dev.2016-11-02.VS.2015.msi", the issue still persist.

**Comment by paulvanbrenk** [comment]
Can you try it with a Nodejs template? I believe ASP.NET ships their own copy of the NPM tools (for some historical reasons), so installing the Node tools may not affect the behavior.

**Comment by Michael-0** [comment]
I did install NodeJS v6.9.5 from the official website, and specidfied the path in Options > Projects and Solutions > External Web Tools
![image](https://cloud.githubusercontent.com/assets/3956685/22605985/684179ee-ea52-11e6-833f-0c7db143ec8a.png)

When I execute this task within VS

```
gulp.task('default', function (callback) {
    console.log('Node version: ' + process.version);
});
```

It does correctly output  v6.9.5.

**Comment by paulvanbrenk** [comment]
I meant the "NPM integration with VS", not NPM itself.

**Comment by Michael-0** [comment]
When I create a new project "Blank Node.js Web Application"

![image](https://cloud.githubusercontent.com/assets/3956685/22606564/999e6f22-ea54-11e6-854a-c9ea35b065bd.png)

The creation fails : 
![image](https://cloud.githubusercontent.com/assets/3956685/22606575/a30a887a-ea54-11e6-8821-95795086d386.png)

I assumed the latest  dev build may be unstable, so I went back to NTVS 1.2, but I still get this error when trying any NodeJS template (Blank Node.js Console Application, Starter Express 3, ...)

**Comment by Michael-0** [comment]
Also uninstalling NTVS does not remove this issue. 

I still see :
```
System.AggregateException: One or more errors occurred. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'name'
   at CallSite.Target(Closure , CallSite , Object )
   at Microsoft.NodejsTools.Npm.SPI.PackageJson.get_Name()
...
```

Does the namespace "**Microsoft.NodejsTools**" come from NTVS or is it integrated in VS ?

**Comment by paulvanbrenk** [comment]
> Also uninstalling NTVS does not remove this issue.

Yeah, that's what I expected, you can try filing a bug on the [dev community site](https://developercommunity.visualstudio.com/spaces/8/index.html), but explicitly mention this happens in an ASP.NET app. It may also be worth trying VS 2017, if that's an option for you.

The new issue your seeing, can you see if there is something relevant in this file: 

`%appdata%\Microsoft\VisualStudio\14.0\ActivityLog.xml`
