### ISSUE TITLE
Reporter options are not working in mocha.json

### ISSUE THREAD

**Issue by Noderino** [Microsoft/nodejstools#1476]
I am using Mochawesome as reporter and i need to set some options. But i could not pass --reporter-options to mocha using mocha.json. I did a quick research and Mocha does not have a separate function to set reporter options. Instead reporter takes 2 parameters but applyMochaOptions only sets first parameter.
https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L77
```javascript
Mocha.prototype.reporter = function (reporter, reporterOptions) {
```

Mocha allows you to pass options to the constructor. Is it possible to do something like this?
https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/TestFrameworks/mocha/mocha.js#L109
```javascript

function initializeMocha(Mocha, projectFolder) { 
    // This is current code
    // var mocha = new Mocha();
    // applyMochaOptions(mocha, getMochaOptions(projectFolder));
    // return mocha;
    return new Mocha(getMochaOptions(projectFolder)); 
}
```
This allows us to set mocha options like this
```json
{
  "reporter": "mochawesome",
  "reporterOptions": {
    "reportDir": "customReportDir",
    "reportFilename": "customReportFilename",
    "enableCharts": false
  }
}
```
If above is not possible can you add support for reporter options?
Thanks.

- NTVS Version: 1.2.40726
- Visual Studio Version: 2015 Update 3
- Node.js Version: v6.9.5

**Comment by paulvanbrenk** [comment]
We don't support using a different reporter since that breaks the integration with the Visual Studio Test Explorer. i.e. we wouldn't be able to show you passed/failed tests etc.
