### ISSUE TITLE
Facing issue to install the MSI in VS 2017 RC. Please let me know is there any workaround to install this application for VS2017 RC

### ISSUE THREAD

**Issue by zameerzam** [Microsoft/nodejstools#1479]
##### Actual Behavior 

- NTVS Version:
- Visual Studio Version: 
- Node.js Version: 

##### Steps to Reproduce
1. 
2.

**Comment by billti** [comment]
The Node.js Tools for VS are already included in VS 2017. Just be sure to select the "Node.js development" feature on the first installer screen.
