### ISSUE TITLE
Several issues with Intellisense

### ISSUE THREAD

**Issue by AleksandrRogov** [Microsoft/nodejstools#1486]
##### Expected Behavior 
1. Visual Studio Intellisense should list properties of a JavaScript object created with a constructor. In addition, it should not depend on the parameter passed to its constructor if the parameter is optional.
2. Visual Studio Intellisense should correctly show JSDoc commentaries to function parameters at least as it is described [here](https://msdn.microsoft.com/en-us/library/mt162307.aspx) and [here](https://github.com/Microsoft/nodejstools/wiki/IntelliSense-and-Editing).

##### Actual Behavior 
I would like to show you an actual behavior based on the following example:

```js
/**
 * Test comment
 *
 * @param {object} [param] - test parameter comment
 */
function Test(param) {

    /**
     * Property comment
     */
    this.property = 0;

    /**
     * test function
     *
     * @param {string} param1 - param1 comment
     * @param {string} param2 - param2 comment
     * @returns {boolean}
     */
    this.testFunction = function (param1, param2) {
        return false;
    }
}

/**
 * prototype function
 *
 * @param {string} param - param comment
 * @returns {boolean}
 */
Test.prototype.prototypeFunction = function (param) {
    return false;
};
```
1.
`param` in the constructor is an optional parameter and when I create an object without it `var test = new Test();` and then access `test`, Intellisense does not list the properties:
![pic1](https://cloud.githubusercontent.com/assets/1893650/23343554/6fb574be-fc3b-11e6-9698-dfde89bc2870.jpg)

unless, I pass anything to the constructor, for example `null`:
![pic2](https://cloud.githubusercontent.com/assets/1893650/23343574/c117a430-fc3b-11e6-8828-13171d8e230a.jpg)

2.
Signature help is not shown when I type in "(" for any function (including a constructor):
![pic3](https://cloud.githubusercontent.com/assets/1893650/23344667/5d045a02-fc4e-11e6-9ca9-cae162175b85.jpg)

![pic4](https://cloud.githubusercontent.com/assets/1893650/23344683/8b06fbda-fc4e-11e6-9ffa-779decda9143.jpg)

![pic5](https://cloud.githubusercontent.com/assets/1893650/23344693/b366fa3a-fc4e-11e6-98f7-c8e43b45cddd.jpg)

Surprisingly, function signature works if I change the code snippet above this way:
```js
/**
 * Test comment
 *
 * @param {object} [param] - test parameter comment
 */
function Test(param) {

    /**
     * Property comment
     */
    this.property = 0;

    /**
     * test function
     * @returns { boolean }
     */
    this.testFunction =
        /**
         * @param { string } param1 - param1 comment
         * @param { string } param2 - param2 comment
         */
        function (param1, param2) {
            return false;
        }
}

/**
 * prototype function
 * @returns {boolean}
 */
Test.prototype.prototypeFunction =
    /**
     * @param {string} param - param comment
     */
    function (param) {
        return false;
    };
```
![pic6](https://cloud.githubusercontent.com/assets/1893650/23344832/3e7c1586-fc51-11e6-899f-fc949ae880d2.jpg)

_I suppose, this should not be treated as an expected behavior, right?_

I tried to make it work for `Test` constructor but  did not find any way to show its signature, unfortunately.

- NTVS Version: 1.2.40726.00
- Visual Studio Version: (Professional) 14.0.25431.01 Update 3
- Node.js Version: 4.3.0

##### Steps to Reproduce
1. Copy the first example to VS text editor (NTVS project),
2. Try to do same things what I did when described an actual behavior.

Thank you for your time

**Comment by paulvanbrenk** [comment]
@AleksandrRogov we made improvements in the NTVS 1.3 release, can you see if the behavior there works better for you?
