### ISSUE TITLE
Use v8_inspector protocol for debugger

### ISSUE THREAD

**Issue by gilly3** [Microsoft/nodejstools#1487]
Are there any plans to switch to using the v8_inspector protocol for the debugger [now that it is available in node](https://github.com/nodejs/node/pull/6792)?

I love the ability to view an async stack trace, but would love it even more if I could have that using Visual Studio's debugger.

**Comment by billti** [comment]
Yes - see the latest check-ins into 'master'. This will depend on the Chrome Debugger already in VS 2017. I'd also note the decision to remove the old protocol from the next major Node.js release has not been made yet, so for now, the existing debugger still works fine.
