### ISSUE TITLE
node --debug is deprecated

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/nodejstools#1488]
node --debug is deprecated which is called by ntvs

should use node --inspect instead as node instance says

**Comment by billti** [comment]
Note that the most recent check-ins on 'master' are work to enable this (though it will depend on the Chrome debugger already in VS 2017 and will not work down-level).

I'd also note the old debug protocol is still present and the call to remove it from the next major version of Node.js has not been decided yet.
