### ISSUE TITLE
Redirect node.exe output to the Output Window instead of a separate console window

### ISSUE THREAD

**Issue by syagev** [Microsoft/nodejstools#149]
Launching a Node.js app is not like launching a Console Windows Application - the console does not receive any input and there is no real meaning in having a full blown console.. So like a Windows Application it makes more sense to redirect the output to the Output Window in the IDE (when debugging, not when launching without debug).

Debugging a Node.js app with the code, watch, and output in the same window is a dream. Constantly swapping between the console and the code/watch is more of a nightmare ;) After all, it isn't called an **Integrated** Development Environment for nothing...

A bonus is to make sure the 'Redirect all Output Window text to the Immediate Window" debugging option will also work.

**Comment by mousetraps** [comment]
Actually, we have seen cases where the console *does* receive input, so we wouldn't want to get rid of it completely. Eg 
https://nodejstools.codeplex.com/workitem/1817

that said, there is ALOT of demand for this feature, so it would be great to have this option. 
https://nodejstools.codeplex.com/workitem/527

**Comment by syagev** [comment]
Cool. I might be misunderstanding, but [Work item #1817](https://nodejstools.codeplex.com/workitem/1817) would not need a console window. He spawns a **child process** that receives input via `stdin`, i.e. the `node.exe` is not the one receiving input. 

In anycase, to my understanding, spawning either the `node.exe` process or any child process without a hosting console wouldn't disable either one to receive input programmatically via `stdin`. I think it just means that it cannot be done with the keyboard.

In fact, my own project does exactly that - it spawns a child process, feeds it data via `stdin` and operates on the output from `stdout`. All without a single console GUI being opened.

Is this item already in working? If not I'll make an attempt on it (coarse estimate is around two weeks).

**Comment by mousetraps** [comment]
Yeah, it wouldn't be necessary, but not permitting keyboard entry seems like a subpar experience.  

It is not currently in the works, and would be an awesome feature to have.

**Comment by paulvanbrenk** [comment]
With the move to the VS Code debug adapter for Node 8 I don't think this is as easy anymore. 

Closing, as this has low priority and is potentially very complex.
