### ISSUE TITLE
npm Error

### ISSUE THREAD

**Issue by DeepakNandan** [Microsoft/nodejstools#1490]
##### Expected Behavior 
It should install pakages
##### Actual Behavior 
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\CONCCFJ>cd c:\node\nodejsconsoleapp1\nodejsconsoleapp1

c:\node\NodejsConsoleApp1\NodejsConsoleApp1>node app.js
Hello world

c:\node\NodejsConsoleApp1\NodejsConsoleApp1>npm install -express save
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\node\\nodejs\\node.exe" "C:\\node\\nodejs\\node_modules\\npm\
\bin\\npm-cli.js" "install" "-express" "save"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\node\NodejsConsoleApp1\NodejsConsoleApp1\npm-debug.log

c:\node\NodejsConsoleApp1\NodejsConsoleApp1>

c:\node\NodejsConsoleApp1\NodejsConsoleApp1>

##### Steps to Reproduce
1. 
2.

**Comment by DeepakNandan** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\node\\nodejs\\node.exe',
1 verbose cli   'C:\\node\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-express',
1 verbose cli   'save' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData save
8 silly fetchNamedPackageData save
9 silly mapToRegistry name save
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'save',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'save',
12 silly mapToRegistry   name: 'save',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/save
14 verbose request uri https://registry.npmjs.org/save
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:54:06 AM
17 verbose request id 6e4752a40bf759f9
18 http request GET https://registry.npmjs.org/save
19 info retry will retry, error on last attempt: Error: unable to verify the first certificate
20 info attempt registry request try #2 at 10:54:16 AM
21 http request GET https://registry.npmjs.org/save
22 info retry will retry, error on last attempt: Error: unable to verify the first certificate
23 info attempt registry request try #3 at 10:55:16 AM
24 http request GET https://registry.npmjs.org/save
25 silly fetchPackageMetaData Error: unable to verify the first certificate
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
25 silly fetchPackageMetaData  error for save { Error: unable to verify the first certificate
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: unable to verify the first certificate
30 verbose stack     at Error (native)
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
30 verbose stack     at emitNone (events.js:86:13)
30 verbose stack     at TLSSocket.emit (events.js:185:7)
30 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:603:8)
30 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
31 verbose cwd c:\node\NodejsConsoleApp1\NodejsConsoleApp1
32 error Windows_NT 6.1.7601
33 error argv "C:\\node\\nodejs\\node.exe" "C:\\node\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-express" "save"
34 error node v6.10.0
35 error npm  v3.10.10
36 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
37 error unable to verify the first certificate
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by billti** [comment]
Looks like you are just getting a straight Node.js/NPM error, not related to the Node.js Tools for Visual Studio in any way. I'd check out general issues (such as http://stackoverflow.com/questions/20747817/error-unable-to-verify-leaf-signature-phonegap-installation ) and follow up with those projects if you still can't resolve it.
