### ISSUE TITLE
Wrong path to Microsoft.NodejsTools.target with Visual Studio 2017

### ISSUE THREAD

**Issue by mbp** [Microsoft/nodejstools#1492]
When creating a Console Node.js project in Visual Studio 2017, and running tests using vstest.console.exe, the path to `Microsoft.NodejsTools.target` is wrong.:

    vstest.console.exe "Project\Project.njsproj" /TestAdapterPath:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\NodeJsTools\NodeJsTools"

> Microsoft (R) Test Execution Command Line Tool Version 15.0.26228.0
Copyright (c) Microsoft Corporation.  All rights reserved.

> Starting test execution, please wait...
Error: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\Node.js Tools\Microsoft.NodejsTools.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\src\scs-performance-timings\PerformanceTimingsApi\PerformanceTimingsApi.njsproj

The file is actually located here: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\Node.js Tools`

**Comment by billti** [comment]
Thanks for the report. I've seen this intermittently, but every time I try to debug it, it won't repro. Are you running the tests from VS, or explicitly from the command-line? Are you using a "VS 2017 developer command prompt" if/when you run from the command-line?

**Comment by mbp** [comment]
I was running it from VS 2017 Developer Command Prompt.

I initially experienced the problem using a Visual Studio Team Services build, but reproduced it locally as described.

**Comment by mbp** [comment]
FWIW I currently use a workaround where I have added the following lines to the csproj file:

    <VSToolsPath Condition="Exists('C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild')">C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0</VSToolsPath>
    <VSToolsPath Condition="Exists('C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild')">C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0</VSToolsPath>

**Comment by danielgreen** [comment]
In a Node JS project migrated from VS 2015 to 2017, the nsjproj contains the following:

``
<Import Project="$(VSToolsPath)\Node.js Tools\Microsoft.NodejsTools.targets" />
``

Running dotnet restore results in this error:

The imported project "C:\Program Files\dotnet\sdk\1.0.3\Microsoft\VisualStudio\v11.0\Node.js Tools\Microsoft.NodejsTools.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Whereas the targets file it's looking for is actually here:
D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\Node.js Tools

I thought it was interesting that the restore command is looking in the .NET Core SDK location rather than the VS install location.

**Comment by steveculshaw** [comment]
My tests are working locally if I use the `/TestAdapterPath:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\NodeJsTools\NodeJsTools"` parameter

But what's the corresponding location in a VSTS Test build task using a "Hosted VS 2017" agent?

**Comment by spratmannc** [comment]
One solution that has worked for me is to remove the `<VisualStudioVersion />` declaration at the top of the *.njsproj file.  This seems to allow the running version of Visual Studio to locate the appropriate VSToolsPath.  This modification allows the projects to be opened in either VS2015 or 2017, with compilation and Test Explorer working as desired.

**Comment by paulvanbrenk** [comment]
@danielgreen `dotnet restore` is only supported on .NET Core project, which the Node.js projects are not. 

@steveculshaw "Hosted VS 2017" is currently not supported for Node.js projects, this is something we're looking into. However, that would require an install of the Node.exe, and then we need to figure out which version to install.

**Comment by paulvanbrenk** [comment]
I'll update the docs to once I've figured out how to run the tests reliably from the command line.

**Comment by starquake** [comment]
I suddenly have this issue in BitBucket. It chokes on the nsproj file. A previously successful test now suddenly fails:

+ dotnet restore
/opt/atlassian/pipelines/agent/build/src/Company.Project.Client/Company.Project.Client.njsproj(81,3): error MSB4019: The imported project "/usr/share/dotnet/sdk/2.1.101/Microsoft/VisualStudio/v15.0/Node.js Tools/Microsoft.NodejsTools.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

But the same happens locally.

**Comment by starquake** [comment]
@paulvanbrenk Yeah forget about bitbucket. It's irrelevant. It also happens locally.
Sure it doesn't support .nsproject. That's okay. But instead of crashing shouldn't it just ignore .nsproj files then? I'm justing running dotnet restore in the root of my folder. And it will not finish because there are .nsproj files there.

**Comment by paulvanbrenk** [comment]
@starquake I agree, I created an issue in their repo. https://github.com/dotnet/cli/issues/8793

**Comment by starquake** [comment]
Thanks @paulvanbrenk 
Groeten uit Nederland

**Comment by araza142** [comment]
I was facing same issue in TeamCity. I end up specifying wildcard for csproj files:
dotnet restore **/*.csproj

This worked!

**Comment by paulvanbrenk** [comment]
I haven't been able to reproduce this anymore.

**Comment by xdvarpunen** [comment]
Happened to me too, points to wrong folder.
