### ISSUE TITLE
Tools / Node.js Tools / Diagnostic Info... - Fails with Dialog

### ISSUE THREAD

**Issue by NetTecture** [Microsoft/nodejstools#1493]
Open Window from a fresh windows / visual studio 2017 install and I get:

"Gould not find any resources appropriate for the speified culture or the netural culture. Make sure "Microsoft.NoejsTools.COmmands.DiagosticsForm.en.resources" was correctly embedded or linked into the asembly "Microsoft.NodejsTools" at compile time of that all satellite assemblies required are loadable and fully signed.

##### Expected Behavior 

Open of window.

##### Actual Behavior 

Error.

- NTVS Version: 
- Visual Studio Version: 15.0.0-RTW+26228.4
- Node.js Version: 1.3.50201,.08

##### Steps to Reproduce

* Install WIN 10 En Enterprise. patch up
* Install VS 2017 Pro
* Install NodeJs
* Go to Tools / Node.js Tools / Diagnostic Info...
* Watch error.

**Comment by billti** [comment]
Thanks. I just verified this also. We'll look into it.

**Comment by billti** [comment]
(note: this is there only for internal diagnostics to help investigate other issues... are you hitting other issues you need the output from this window for?)

**Comment by NetTecture** [comment]
@billti  No. I just wanted to see whether my node install worked, so I went there and... voila. Everything seems to work fine.

**Comment by fulls1z3** [comment]
Hi guys, I have the same issue with the diagnostic window right here on my fresh Win 10 & VS2017 Professional.

OS and VS versions are same as above (and of course after NodeJs 6 installation)

**Comment by paulvanbrenk** [comment]
Thanks, there is a fix which will be part of VS 2017 Update 1.
