### ISSUE TITLE
Javascript Outlining Stops after a certain depth

### ISSUE THREAD

**Issue by eddieloeffen** [Microsoft/nodejstools#1496]
##### Expected Behavior 
.JS files that belong to a NodeJS Tools project should have their outlining behave the same way as in other project types.

##### Actual Behavior 
.JS files are outlined, but only to a certain "depth" or "level". After that, outlining stops until the depth is reduced again.

- NTVS Version: 1.3.41102.01 (11-02-2016 Dev Build)
- Visual Studio Version: 2015 Community
- Node.js Version: v4.4.5

##### Steps to Reproduce
1. Create 2 identical javascript files with the following contents, one under a NodeJSTools Project and one under a .csproj (you can copy paste the file from one project to another)

```
(function () {
    var a = {
        
    };

    (function () {
        var a = {

        };

        (function () {
            var a = {

            };

            (function () {
                var a = {

                };

                (function () {
                    //Outlining Stops here

                    var a = {

                    };

                    (function () {
                        var a = {

                        };

                        (function () {

                        });
                    });
                });
            });
        });
    });
})
```

2. In the file that lives under NodeJS Tools, the outlining will "give up" after reaching a certain depth:

![image](https://cloud.githubusercontent.com/assets/2539705/23836372/ed4774f8-07db-11e7-83bb-ef0ce02eac77.png)

Whereas in the file that lives under the .csproj, the outlining will continue:

![image](https://cloud.githubusercontent.com/assets/2539705/23836397/3a1f8428-07dc-11e7-8261-5407cebf859d.png)

**Comment by paulvanbrenk** [comment]
Thanks for reporting. This is an issue with the TypeScript language service, which is used as the language service for JavaScript in the nodetools projects.

https://github.com/Microsoft/TypeScript/issues/15112
