### ISSUE TITLE
Opening up nodejstools in visual studio generates A numeric comparison was attempted on "$(VSUpdateVersion)" error

### ISSUE THREAD

**Issue by johnmcbride** [Microsoft/nodejstools#15]
When trying to open the nodesjtool project in Visual Studio 2013, I receiver A numeric comparison was attempted on "$(VSUpdateVersion)" error on every project. I have some some searching and it looks like this issue is related to resharped, but i dont have resharped installed. How can I get the projects loaded as I would like to work on some customizations.

![nodejstool_error_projectload](https://cloud.githubusercontent.com/assets/125551/6953951/ec9a5ace-d89a-11e4-9e67-11bac9f13382.png)

**Comment by johnmcbride** [comment]
Looks like the common.build.settings file has a hard coded registry value that assumes you are running on a 64 bit system
<_VSUpdateVersion Condition="$(VSUpdateVersion)=='' and $(VisualStudioVersion)!='10.0'">$([MSBuild]::GetRegistryValueFromView('HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\DevDiv\vs\Servicing\$(VSTarget)\devenv', 'UpdateVersion', null, RegistryView.Registry32))</_VSUpdateVersion>

Since I am running on a 32bit OS I removed the Wow6432Node from the path and now I can load the project. I'll try and submit a fix that detects the OS but I'm not a msbuild expert :)

**Comment by mousetraps** [comment]
Awesome, glad you figured it out. I actually think that'll be enough because RegistryView.Registry32 will resolve to the 32-bit view (Wow6432Node on a 64-bit OS)

**Comment by mousetraps** [comment]
btw your fix looks good to me. you should totally submit a PR :smiley:
