### ISSUE TITLE
How can I run node.js application specific command in Visual Studio using Node tools for visual studio(NTVS)?

### ISSUE THREAD

**Issue by MagSag** [Microsoft/nodejstools#1508]
I have a node.js application which I am developping inside Visual Studio using Node Tools for Visual Studio(NTVS). It said that to run my application, I should run this is the command:

    page_token=<MY PAGE TOKEN> verify_token=<MY_VERIFY_TOKEN> node bot.js

It is a project that I cloned from botkit.

The first problem is I've never seen such command for running the node application so I don't undertand what it does exactly. I need to understand it.

My question is : How can I set the Node tools for visual studio to know that whenever I run(debug) the project it should run that command?

If I run without debugging this is what I get  as message: 
![ntvs](https://cloud.githubusercontent.com/assets/13017395/24212907/dba78400-0f41-11e7-948b-72054f165d7a.PNG)

- NTVS Version:1.2
- Visual Studio Version: 2015
- Node.js Version: 6.6.9

**Comment by billti** [comment]
In the Project Properties for a Node.js project (right click on the project, select "Properties") you can specify the arguments when launching.
