### ISSUE TITLE
Intellisense does not support DOM API

### ISSUE THREAD

**Issue by beautifulcoder** [Microsoft/nodejstools#151]
I created a new index.js inside the 'javascripts' folder, and typed:

    document.

From what I gather, there is no intellisense support here. It would be nice to have this since it seems to work in ASP.NET.

**Comment by mousetraps** [comment]
Check out [our docs](https://github.com/Microsoft/nodejstools/wiki/Working-with-Browser-(Clientside)-JavaScript-in-NTVS) to see how to enable this feature.

Ideally this wouldn't be necessary, but unfortunately the IntelliSense engines ended up diverging for technical reasons, so we are currently exploring to make this easier and more discoverable (#142 and #143), as well as chatting with some teams internally to see how we can eventually combine our efforts so this switch won't be necessary.

**Comment by beautifulcoder** [comment]
Wow, amazing response time. Will do.

I'm super excited to see what you all are doing with Node.js. I'll definitely be sharing what NTVS is capable of with the community.

**Comment by mousetraps** [comment]
Np - happened to be online, and glad you like the tools! :smiley:
