### ISSUE TITLE
Error when trying to open the npm dialog window

### ISSUE THREAD

**Issue by SDP190** [Microsoft/nodejstools#1510]
##### Expected Behavior 
When i right-click on the npm node witch appears at the project explorer on my  node.js project, and then select the option to install new packages, it should open the npm ui dialog window.

##### Actual Behavior 
but instead, i am getting an error message:
 **Cannot locate resource 'npmui/npmpackageinstallwindow.xaml'**

- NTVS Version: VS 2015 v1.3 Dev Build - 2017-03-06
- Visual Studio Version: 14.0.25431.01 Update 3
- Node.js Version: v6.9.2

Before installing this NTVS 1.3-DevBuild i had no problem with version NTVS 1.2, but then after i uninstalled NTVS 1.2 and installed the 1.3-DevBuild version i got this bug, please help me.

**Comment by billti** [comment]
Thanks for the report @SDP190 . Sorry for the delay. The guy that did our loc work for VS 2017 is out currently, and I expect its some of the changes he made here that are causing issues. I'll see if I can figure it out. Are you using a non-English OS or VS by any chance?

**Comment by SDP190** [comment]
Every thing is english!

**Comment by SDP190** [comment]
However, i forgot to tell "Thank You" for response.

**Comment by billti** [comment]
Thanks. I can see the issue on my test box too. Hopefully an easy fix. Looks like we messed up an `#ifdef` when doing the localization work for VS 2017.

**Comment by billti** [comment]
(p.s. If you're blocked, you can open the `package.json` directly and edit the `dependencies` property in there. You'll get completions on package names and versions. Then when done, right click on the 'NPM' icon and select "Install new NPM packages").

**Comment by SDP190** [comment]
Thanks, however i will wait for a new fixed version.

**Comment by billti** [comment]
Thanks. I've checked in a fix. There's a couple more bugs to get in before we upload the next Dev build.

**Comment by SDP190** [comment]
Thanks a lot.
