### ISSUE TITLE
Cannot remote debug on Raspberry pi

### ISSUE THREAD

**Issue by starofsky** [Microsoft/nodejstools#1511]
Hi,
I using VS2015 to remote debug on Raspberry pi Node server but i cannot work:

![untitled](https://cloud.githubusercontent.com/assets/5322431/24349812/5673ed2e-130a-11e7-967d-ed14b0545ab7.png)

**Comment by paulvanbrenk** [comment]
Looking at the log it looks like the server killed the connection? Can you debug using the debugging tools in Chrome?
