### ISSUE TITLE
VS2017 Installation Guide?

### ISSUE THREAD

**Issue by leetroot** [Microsoft/nodejstools#1513]
I was wanting to know how to install NodeJS Tools on VS2017. Using the March 2017 build that was uploaded to GitHub it says that I need VS 2015. I later went back to find that you guys uploaded the Source Code files for the tools to work in VS2017 but how do I compile the source as I'm a bit confused here. 

Thanks!

**Comment by leetroot** [comment]
Update #1: Seems like I found the NodeJS Tools! I didn't even know it came with VS 2017 Enterprise. I looked through the menus and noticed it already came when I installed VS 2017.

**Comment by billti** [comment]
Yeah, it's the "Node.js workload" in VS 2017, one of the main feature boxes in the installer UI.

**Comment by leetroot** [comment]
Thanks @billti
