### ISSUE TITLE
can't export and import to itemtemplate?

### ISSUE THREAD

**Issue by qwerty2501** [Microsoft/nodejstools#152]
hi.
I use this plugin in VS2015.
But, I couldn't export and import to itemtemplate in nodejs project. 
Are these behavior normal?

**Comment by mousetraps** [comment]
Indeed, you are correct... my best guess is that we identify and see templates for Node.js, not JavaScript, so we'd have to investigate adding this feature.

@SteveALee - mea culpa, I may have misled you the other day when I linked you to some docs on creating project templates.

**Comment by qwerty2501** [comment]
Yeah, I want to add this feature too.

**Comment by paulvanbrenk** [comment]
Closing this for now. It involves much more work than expected, for relative little gain. More info on creating your own templates can be found here: [How to: Create Item Templates](https://msdn.microsoft.com/en-us/library/tsyyf0yh.aspx)
