### ISSUE TITLE
How can I profile a node.js application?

### ISSUE THREAD

**Issue by isvaljek** [Microsoft/nodejstools#1530]
##### Expected Behavior 
Click Analyze/Performance profiler, have an app profiled.

##### Actual Behavior 

http://korak.info/tempo/vs2017-exception-profiler.png

- NTVS Version:
- Visual Studio Version: 
- Node.js Version: 

##### Steps to Reproduce
1. Click Analyze/Performance profiler, have an app profiled.
2. Click start

**Comment by billti** [comment]
There is no Profiler in NTVS for VS 2017. It has too many issues (it rarely works in VS 2015 either). So unfortunately you'll need to use something other than VS to profile your Node.js app.
