### ISSUE TITLE
typescript requirement error message form VS 15.2

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/nodejstools#1532]
![image](https://cloud.githubusercontent.com/assets/4515120/25110626/888c1ed6-2420-11e7-8777-389822bfc6f5.png)

![image](https://cloud.githubusercontent.com/assets/4515120/25110662/c74a4422-2420-11e7-8d43-a0be2982540f.png)

Microsoft Visual Studio Community 2017 Preview (2)
Version 15.2 (26412.1-Preview) Preview
VisualStudio.15.Preview/15.2.0-Preview+26412.1
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA231
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA231
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA231
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.6.00404.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30404.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

Node.js Tools   1.3.50316.00
Adds support for developing and debugging Node.js apps in Visual Studio

TypeScript   2.2.2.0
TypeScript tools for Visual Studio

**Comment by billti** [comment]
Just click OK. The error is benign, and will be gone in the next update (due in a couple days).
