### ISSUE TITLE
How to debug nodejs internal javascript code?

### ISSUE THREAD

**Issue by jiakai1000** [Microsoft/nodejstools#1534]
When I debug a nodejs application, I can step into internal source code of nodejs such as http.js or fs.js, but when I restart debugging, the opened http.js disappeared, and so are the breakpoints, and the breakpoints which I set in http.js doesn't work. How can I solve the problem? Thanks.

**Comment by paulvanbrenk** [comment]
I don't think we have a good answer here for now.. since the files are internal to node we don't track them between debug sessions. As much as I hate to suggest this, I would use Chrome, which may work better in this case.
