### ISSUE TITLE
Pausing Debugger while breakpoint condition is evaluating throws exception

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/nodejstools#1541]
##### Expected Behavior 
Debugger pauses
##### Actual Behavior 
![image](https://cloud.githubusercontent.com/assets/3226984/25450144/d58fcfb8-2a72-11e7-9e62-8a5bbb717c08.png)

Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.2 (26424.2-Preview) d15rel Internal Preview - Dogfood
VisualStudio.15.IntPreview/15.2.0-Preview+26424.2.d15rel
Microsoft .NET Framework
Version 4.6.01586

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Node.js Tools   1.3.50417.1
Adds support for developing and debugging Node.js apps in Visual Studio

TypeScript   2.2.0.0
TypeScript tools for Visual Studio

##### Steps to Reproduce
1. 
```
cd c:\
mkdir temp
cd temp
npm install express-generator -g
express --view=pug myapp
cd myapp
npm install
```
2. Start VS
3. `Ctrl+Shift+N` (Create new project)
4. Templates -> JavaScript -> From Existing Node.js code
5. Click `OK`
6. Pick folder containing Node.js code: `c:\temp\myapp`
7. `Alt-F` (Finish)
8. Set a breakpoint on line 19 of app.js with the following condition:
``` js
(function(){while(true){}})()
```
(Right click on red dot and edit text of condition)
9. Start debugging
10. press pause.
11. get exception.

**Comment by paulvanbrenk** [comment]
This no longer repros on Visual Studio 2017 Update 6, and Node 8+
