### ISSUE TITLE
Irrelevant Exception Settings When Debugging JS

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/nodejstools#1542]
##### Expected Behavior 
Only show exception settings for JS exceptions
##### Actual Behavior 
![image](https://cloud.githubusercontent.com/assets/3226984/25450638/5c66ccb6-2a74-11e7-8ad1-3ea2490fa69e.png)

Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.2 (26424.2-Preview) d15rel Internal Preview - Dogfood
VisualStudio.15.IntPreview/15.2.0-Preview+26424.2.d15rel
Microsoft .NET Framework
Version 4.6.01586

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Node.js Tools   1.3.50417.1
Adds support for developing and debugging Node.js apps in Visual Studio

TypeScript   2.2.0.0
TypeScript tools for Visual Studio

##### Steps to Reproduce
1. 
```
cd c:\
mkdir temp
cd temp
npm install express-generator -g
express --view=pug myapp
cd myapp
npm install
```
2. Start VS
3. `Ctrl+Shift+N` (Create new project)
4. Templates -> JavaScript -> From Existing Node.js code
5. Click `OK`
6. Pick folder containing Node.js code: `c:\temp\myapp`
7. `Alt-F` (Finish)
8. Set a breakpoint on line 19 of app.js 
9. Start debugging
10. press pause.
11. Click on Exception Settings tab.

**Comment by paulvanbrenk** [comment]
When debugging a C# app, all the options are available as well. Not something we want to invest in.
