### ISSUE TITLE
No Perf Tips when debugging and Diagnostics Tools not available

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/nodejstools#1543]
##### Expected Behavior 
Get perf tips on breakpoints when debugging.

Pressing `Ctrl+Shift+F2` should open a  window with diagnostics tools, or not be available at all.

##### Actual Behavior 
No perf tip to the right of text on breakpoint'd line:
![image](https://cloud.githubusercontent.com/assets/3226984/25453704/df585a36-2a7e-11e7-86d5-704f773e6c8e.png)

No usable diagnostics tools: 
![image](https://cloud.githubusercontent.com/assets/3226984/25453931/9d4c8e5e-2a7f-11e7-8a12-c0c858634efb.png)

Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.2 (26424.2-Preview) d15rel Internal Preview - Dogfood
VisualStudio.15.IntPreview/15.2.0-Preview+26424.2.d15rel
Microsoft .NET Framework
Version 4.6.01586

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Node.js Tools   1.3.50417.1
Adds support for developing and debugging Node.js apps in Visual Studio

TypeScript   2.2.0.0
TypeScript tools for Visual Studio

##### Steps to Reproduce
1. 
```
cd c:\
mkdir temp
cd temp
npm install express-generator -g
express --view=pug myapp
cd myapp
npm install
```
2. Start VS
3. `Ctrl+Shift+N` (Create new project)
4. Templates -> JavaScript -> From Existing Node.js code
5. Click `OK`
6. Pick folder containing Node.js code: `c:\temp\myapp`
7. `Alt-F` (Finish)
8. Set a breakpoint on line 1 of app.js
8. Set a breakpoint on line 11 of app.js 
9. Start debugging
10. After hitting first breakpoint, press continue.
11. Observe that there is no Perf Tip info at the breakpoint on line 19 after breaking.

**Comment by paulvanbrenk** [comment]
Closing as this tracked by the JavaScript diagnostics team
