### ISSUE TITLE
Mocha UnitTests not found with "From Existing Node.js Code"

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/nodejstools#1544]
##### Expected Behavior 
Runs mocha unit tests
##### Actual Behavior 
![image](https://cloud.githubusercontent.com/assets/3226984/25454721/491c98ee-2a82-11e7-8a1a-0a66f5743f96.png)

Appears to occur because imported code is not located under the same root as the added mocha unit tests file. So node_modules and the test file live under the imported code, but VS looks for mocha in a node_modules folder under the *.sln file's location.

Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.2 (26424.2-Preview) d15rel Internal Preview - Dogfood
VisualStudio.15.IntPreview/15.2.0-Preview+26424.2.d15rel
Microsoft .NET Framework
Version 4.6.01586

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Node.js Tools   1.3.50417.1
Adds support for developing and debugging Node.js apps in Visual Studio

TypeScript   2.2.0.0
TypeScript tools for Visual Studio

##### Steps to Reproduce
1. 
```
cd c:\
mkdir temp
cd temp
npm install express-generator -g
express --view=pug myapp
cd myapp
npm install
```
2. Start VS
3. `Ctrl+Shift+N` (Create new project)
4. Templates -> JavaScript -> From Existing Node.js code
5. Click `OK`
6. Pick folder containing Node.js code: `c:\temp\myapp`
7. `Alt-F` (Finish)
8. Add mocha npm package (using npm installer(CTRL + K, G) or other means)
9. Add a mocha unit test file (right click > add > new item… > JavaScript Mocha UnitTest file)
10. run tests: Test -> Run -> All Tests (`Ctrl+R, A`)

**Comment by paulvanbrenk** [comment]
Looks like this is the same issue as #376
