### ISSUE TITLE
New MSBuild format for njsproj files

### ISSUE THREAD

**Issue by Meir017** [Microsoft/nodejstools#1548]
The njsproj files created from the templates use the old format.

Any plans on migrating them to use the new format? (no GUIDs, globbing and more...)

**Comment by billti** [comment]
We are investigating moving the entire project system to a newer model based on CPS (https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/intro.md). But that is a looooooooot of work, and unlikely to land in 2017.

**Comment by paulvanbrenk** [comment]
Closing as this is definitely the route we will take if/when we invest in a new project system, but don't need a bug to track this.

**Comment by thesobercoder** [comment]
@paulvanbrenk Any update on this?
