### ISSUE TITLE
npm package list download fails with npm 4.2 in VS2017

### ISSUE THREAD

**Issue by sam-public** [Microsoft/nodejstools#1549]
##### Expected Behavior 
npm can add packages
##### Actual Behavior 
npm "install new packages" dialog fails

- NTVS Version: 1.3.50316.00
- Visual Studio Version: 15.1
- Node.js Version: 7.9.0

##### Steps to Reproduce
1. Download "current" (not LTS) version of node/npm (7.9.0/4.2.0)
2. Install VS2017 Community Edition
3. Create a new Blank NodeJS javascript web application
4. Select "Install new npm packages"
5. Observe error in dialog, and outut window shows the following:

```
Registry url: https://registry.npmjs.org/
Your package catalog database needs to be upgraded. Please wait while we execute a full refresh.
Deleting C:\Users\user\AppData\Local\Microsoft\Node.js Tools\NpmCache
Path to npm: C:\Program Files\nodejs\npm.cmd
Downloading package cache to C:\Users\user\AppData\Local\Microsoft\Node.js Tools\NpmCache\all_packages.json
Downloading list of packages from https://registry.npmjs.org/-/all
Download complete - updating database
Reading 0 bytes from C:\Users\user\AppData\Local\Microsoft\Node.js Tools\NpmCache\all_packages.json (4/30/2017 6:43:49 PM)
Newtonsoft.Json.JsonException: Unexpected JSON token at start of NPM catalog data
```

Note that command line npm is functional, and adding packages there does result in them showing in the project tree UI under npm

**Comment by billti** [comment]
This has nothing to do with the 'npm' version, as NTVS goes directly to the npm web endpoint. Unfortunately this has been sporadic of late (you can find other recent issues in this repo for similar bugs that refer to the NPM issue). The bottom line is that NPM is deprecating that API, and aren't investing in it. We already have code changes in the pipeline to replace this code and use newer NPM endpoints (see https://github.com/Microsoft/nodejstools/pull/1501 ).

**Comment by sam-public** [comment]
Thanks Bill, hopefully that PR can goes in soon, the current experience is not good...
