### ISSUE TITLE
File appears randomly ~/bin/Microsoft.NodejsTools.WebRole.dll

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/nodejstools#155]
This file seems to be created when I rebuild an nsproj. It does not seem to happen when I simply build the solution or the nsproj. However, the file appears randomly even though I never hit rebuild. (I do occasionally hit F6/build solution out of frustration if Javascript Intellisense isn't working.)

The file is `~/bin/Microsoft.NodejsTools.WebRole.dll` (where ~ indicates the project root).

What is this file for and is there a way to control whether it gets created? I'm assuming it's got something to do with IIS, but I can't find much information about it.

**Comment by mousetraps** [comment]
This is for remote debugging with iisnode, and appears to be a bug in our targets file - at the very least, we should restrict it to projects with a web.config file
https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Microsoft.NodejsTools.targets#L71-L77

If you want, you can go ahead and comment out the offending lines of code it as a workaround - it'll be in the following path:
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Node.js Tools

**Comment by pke** [comment]
@mousetraps How can I prevent that file from being created in my published folder? I am not using IIS.

**Comment by mousetraps** [comment]
Can't reproduce this issue anymore with latest NTVS & VS2015 Update 1, but will reopen if others are still seeing it.

**Comment by drcmda** [comment]
I run the latest NTVS & VS2015, though it doesn't seem to include it any longer there is something else going on now. The publish build takes ages and it seems to recycle multiple times:

''''
------ Publish started: Project: azure, Configuration: Release Any CPU ------
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(1057,5): warning : CloudServices67 : The entrypoint for role farm is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(1057,5): warning : CloudServices67 : The entrypoint for role public is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(1057,5): warning : CloudServices67 : The entrypoint for role farm is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(1057,5): warning : CloudServices67 : The entrypoint for role public is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(3006,5): warning : CloudServices67 : The entrypoint for role farm is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(3006,5): warning : CloudServices67 : The entrypoint for role public is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(3006,5): warning : CloudServices67 : The entrypoint for role farm is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(3006,5): warning : CloudServices67 : The entrypoint for role public is already defined in the service definition file. Ignoring entrypoint Microsoft.NodejsTools.WebRole.dll.
========== Build: 1 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
''''
