### ISSUE TITLE
Make npm IDE features available in non-Node.js web projects

### ISSUE THREAD

**Issue by lilred** [Microsoft/nodejstools#156]
npm is often used as a client-side package manager, even in projects where the back-end platform is not Node.js. It would be helpful to be able to use the npm features in any kind of web project.

**Comment by mousetraps** [comment]
Which projects are ya thinking it might be useful in?

Right now NTVS uses a different project system than other projects in VS, so it would not be easy to do. ASP.NET actually worked in our npm component in to their project system, so perhaps they'd be a good team to contact about bringing it into other projects in the future.

That said, the Interactive Window ```.npm``` command should be more doable. I believe we have some code in there that specifically checks for the Node.js project flavor.

**Comment by brettpostin** [comment]
+1 for this. It would be nice to be able to use the npm GUI in other project types.

e.g. I've just created a sample project using the ASP.NET 5 Preview Templates and would like to use it here.

**Comment by mousetraps** [comment]
@brettpostin gotcha, so the npm integration in solution explorer is already there (it's not the exact same, but hey're using our npm component).. and it'd take a bit of work, but we could turn the GUI into a global command...
