### ISSUE TITLE
Mocha Test id depends on the file path

### ISSUE THREAD

**Issue by fforjan** [Microsoft/nodejstools#1561]
When running javascript unit test via Mocha on a TFS build, TFS is not able to detect that the test was failing in a previous build and tag as failing in the current build

##### Expected Behavior 
same test failing in consecutive build should be detected as failing in the first build.

##### Actual Behavior 
same test failing in consecutive build is not detected as failed in the first build

##### Steps to Reproduce
My assumption about this issue is about the test having some file path in its ID. the file path depends on the workspace location and is different between build agents:
Build A : 
![image](https://cloud.githubusercontent.com/assets/601810/25775121/7da1fe10-3252-11e7-8c5f-906af866697b.png)

Build A + 1
![image](https://cloud.githubusercontent.com/assets/601810/25775133/017c3f16-3253-11e7-9e01-c2b3b863d30b.png)

Which seems to be related to the fully qualified name : https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/TestAdapter/TestFrameworks/NodejsTestInfo.cs#L42

On regular C# unit tests, you can see the ID seems to not only include the file name but the class name which should be the unique ID
![image](https://cloud.githubusercontent.com/assets/601810/25775160/dc9cf0ae-3253-11e7-84ae-d1e16b3bbd14.png)

**Comment by fforjan** [comment]
Update to confirm when the test can be find in previous build :
![image](https://cloud.githubusercontent.com/assets/601810/25782762/79967bc6-3305-11e7-8b37-7907750b8c5e.png)
![image](https://cloud.githubusercontent.com/assets/601810/25782776/a726ea3a-3305-11e7-8627-ecf6382379dd.png)

**Comment by paulvanbrenk** [comment]
Which version of VS and the Node Tools for VS are you using?

**Comment by fforjan** [comment]
TFS 2015 build agent with VS 2015, NTVS tools is based on 1.3 plus private changes done by @ozyx  and pushed to you already.

**Comment by paulvanbrenk** [comment]
@fforjan  Any progress on this work? i.e. should I push out a new 1.3 drop, or wait for this?

**Comment by fforjan** [comment]
@ozyx was away and should be back tomorrow, I will discuss with him and give you a status

**Comment by ozyx** [comment]
@paulvanbrenk Currently working on this now, will have a PR for you either today or tomorrow.

**Comment by paulvanbrenk** [comment]
Awesome, going to take a look tomorrow. @billti feel free to swipe this from me

**Comment by paulvanbrenk** [comment]
This is now also fixed in VS 2017
