### ISSUE TITLE
Eventually deprecate the press any key app features

### ISSUE THREAD

**Issue by digeff** [Microsoft/nodejstools#1568]
The latest versions of node have a built-in feature to keep the process open until the debugger detaches. This makes obsolete the press any key features in newer versions. After we deprecate the old versions that don't have this feature built-in, we should eventually remove this feature.

**Comment by paulvanbrenk** [comment]
This is not used by the new Node 8 debugger. Still needed by the Node 6 debugger, which we can't get rid off.
