### ISSUE TITLE
in windows 10 node.js tools doesnt update

### ISSUE THREAD

**Issue by nattlip** [Microsoft/nodejstools#1578]
##### i still see the node.js tools 1.3 installed on 3-12-2016 in extensions and update,  and no update available. on my windos 7 machine node.js tools 1.3.0.7 is present updated 12-05-2017

Microsoft Visual Studio Community 2017 
Version 15.2 (26430.6) Release
VisualStudio.15.Release/15.2.0+26430.6
Microsoft .NET Framework
Version 4.7.02500

Installed Version: Community

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Node.js Tools   1.3.41102.00
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.2.0

TypeScript   2.2.2.0
TypeScript tools for Visual Studio

**Comment by paulvanbrenk** [comment]
Is one of the VS 2017 releases targeting the preview releases?

Can you post the top 3 lines: 
`
Microsoft Visual Studio Community 2017
Version 15.2 (26430.6) Release
VisualStudio.15.Release/15.2.0+26430.6
`

for both installs?

**Comment by nattlip** [comment]
on windows 7 

Microsoft Visual Studio Community 2017 
Version 15.2 (26430.6) Release
VisualStudio.15.Release/15.2.0+26430.6
Microsoft .NET Framework
Version 4.6.01055

**Comment by nattlip** [comment]
on windows 10 insider preview

Microsoft Visual Studio Community 2017 
Version 15.2 (26430.6) Release
VisualStudio.15.Release/15.2.0+26430.6
Microsoft .NET Framework
Version 4.7.02505

**Comment by paulvanbrenk** [comment]
Curious, I assume in both cases the node workload was installed and neither show an update available in the Visual Studio Installer.

**Comment by nattlip** [comment]
indeed

**Comment by paulvanbrenk** [comment]
Can you try remove the node workload from the older install, and re-installing? And reboot the machine in between...

**Comment by nattlip** [comment]
how do i remove the node workload or what is the node workload ?

**Comment by paulvanbrenk** [comment]
Now I'm curious how you installed VS...  I was talking about this option in the VS installer.

![image](https://cloud.githubusercontent.com/assets/5273975/26325150/9f419702-3eea-11e7-8ddc-8f543a88f132.png)

**Comment by nattlip** [comment]
i reinstalled  vs completely , it only shows visal studio rc now on the taskbar but node is up to date.

**Comment by paulvanbrenk** [comment]
actually figured this out... should be fixed in VS 2017 update 3
