### ISSUE TITLE
Unhandled error in Visual Studio when opening an empty .tsx file

### ISSUE THREAD

**Issue by DmytroLapshyn** [Microsoft/nodejstools#1579]
##### Expected Behavior 
When I double-click an empty .tsx file in Solution Explorer, no error messages are shown.

##### Actual Behavior 
Visual Studio shows a message box that an unhandled error has occurred and refers to ActivityLog.xml. Here are the relevant entries from that file:

```
793 ERROR System.InvalidOperationException: Operation is not valid due to the current state of the object. at Microsoft.VisualStudioTools.Project.Automation.OAProjectItem.get_Collection() at Microsoft.VisualStudio.Web.Editor.Package.Lint.WebLinter.LinterUtilities.IsFileSupported(String fileName) at Microsoft.VisualStudio.Web.Editor.Package.Lint.ErrorTagger.LintErrorTaggerProvider.CreateTagger[T](ITextBuffer textBuffer) at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)   Editor or Editor Extension 2017/05/15 13:07:54.693 

794 ERROR System.InvalidOperationException: Operation is not valid due to the current state of the object. at Microsoft.VisualStudioTools.Project.Automation.OAProjectItem.get_Collection() at Microsoft.VisualStudio.Web.Editor.Package.Lint.WebLinter.LinterUtilities.IsFileSupported(String fileName) at Microsoft.VisualStudio.Web.Editor.Package.Lint.ErrorTagger.LintErrorTaggerProvider.CreateTagger[T](ITextBuffer textBuffer) at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)   Editor or Editor Extension 2017/05/15 13:07:54.695 

```

- NTVS Version: 1.2.40726.00
- Visual Studio Version: Microsoft Visual Studio Professional 2015 Version 14.0.25431.01 Update 3
- Node.js Version:  6.10.3

##### Steps to Reproduce
1. Add an empty .tsx file to the project
2. Open it from Solution Explorer

**Comment by paulvanbrenk** [comment]
I don't reproduce this on NTVS 1.3 which we just released.

I created a new TypeScript Node Tools Console App, and added a `.tsx` file, deleted the comment that's in there, closed the file and re-opened from the solution explorer.

Did you install the eslint support from somewhere, or do you have a specific configuration in your project?

**Comment by DmytroLapshyn** [comment]
NTVS 1.3 seems to work just fine, thanks a million! 

Answering your question, no, I don't think I have any other eslint suport, if only the NPM Task Runner extension adds it. However what I do have is the latest TypeScript version (2.3.2 if I am not mistaken) which, turns out, is known to be incompatible with older releases of NTVS.

**Comment by paulvanbrenk** [comment]
Good to hear 1.3 resolved it.

> the latest TypeScript version (2.3.2 if I am not mistaken) which, turns out, is known to be incompatible with older releases of NTVS

I was not aware of that, and we're the same team. ;) Can you point to a link to that.

**Comment by DmytroLapshyn** [comment]
> I was not aware of that, and we're the same team. ;) Can you point to a link to that.

Hi Paul! Sorry for delayed response, was on sick leave. Sure - here's the link: [NTVS 1.3 for VS 2015 Update 3](https://github.com/Microsoft/nodejstools/releases/tag/v1.3)

Right there, it says

> Important: If you are using a version of TypeScript later than the default version with Visual Studio Update 3 (TypeScript 1.8), then please update to the latest release from https://www.microsoft.com/en-us/download/details.aspx?id=48593 . There was a bug impacting NTVS in TypeScript releases > 2.0 prior to March 8, 2017

**Comment by paulvanbrenk** [comment]
I actually posted that....  :|
