### ISSUE TITLE
Unable to set the node_modules path for npm package installation

### ISSUE THREAD

**Issue by lu8890** [Microsoft/nodejstools#1585]
##### Expected Behavior 
Be able to point each node.js package path to a desired location
##### Actual Behavior 
Each node.js project creates its own node_modules, even within the same solution.  That means same packages has to be installed multiple times in different projects.

- NTVS Version: Have no idea what NTVS is?
- Visual Studio Version: 15.2(26430.6) Release
- Node.js Version: v7.10.0

##### Steps to Reproduce
1. Create a new node.js project with a solution
2. Create a second node.js project within the same solution
3. try to find a way to install a new npm package to a target location 
4. no such settings

**Comment by paulvanbrenk** [comment]
This is a limitation of NPM. It installs the modules based on where the `package.json` is located, or in a global location. So there is no good way to tell NPM to use a different location (like NuGet allows you to do).
