### ISSUE TITLE
Unable to evaluate expression. The expression evaluation took too long.

### ISSUE THREAD

**Issue by pps83** [Microsoft/nodejstools#1587]
use this code:
```
var data = [];
for (var i = 0; i < 10000000; ++i)
    data.push(i);
data.push(0);
```
put a breakpoint on last line: `data.push(0);`
When you run it you'll be able to type in watch window 'data.length' to see current size (should be `10000000`). Now, simply try to hover mouse over `data`, that's it, game over from that point, VS is having heart attack, if you try to reevaluate `data.length` you'll get "Unable to evaluate expression. The expression evaluation took too long" error:

![image](https://cloud.githubusercontent.com/assets/1614246/26281591/6f17fa98-3db0-11e7-917c-1e47b2810d4a.png)

**Comment by paulvanbrenk** [comment]
Thanks for reporting, we're aware of performance issues in the debugger. We've re-architecting the debugger to target the new debug protocol in Node 8, and expect the performance to be a lot better there. This should be in preview for Visual Studio 2017 Update 3.

**Comment by paulvanbrenk** [comment]
This should be fixed for Node 8 debugging
