### ISSUE TITLE
Can't Attach Remote Debugger

### ISSUE THREAD

**Issue by markolbert** [Microsoft/nodejstools#1591]
I am trying to debug a nodejs app running on a Raspberry Pi. Both the Pi and my development machine are on the same LAN. I'm using Visual Studio 2017 and the NodeJs Tools for Visual Studio 2017. 

I start the debugger on the Pi like this:

```
$ nodejs --debug-brk RemoteDebug.js app.js  
debugger listening on port 5858

```
I'm using the --debug-brk switch because the bug I'm trying to find throws an exception during the app's startup, so I need nodejs to wait until a debugger is attached.

When I try to attach to the remote process from within Visual Studio I get the following error:

> Could not attach to Node.js process at tcp://majordomo:5858/:  
> No connection could be made because the target machine actively refused it 10.0.0.78:5858

I've confirmed that Visual Studio 2017 is allowed to access private networks through the Windows firewall. 

How do I open the port on the Pi side? I thought that the message the debugger is listening on 5858 meant the port was "open", but that's clearly not the case.

**Additional Info**

I discovered that the RemoteDebug.js script supplied by Microsoft accepts a command line argument to wait for the remote debugger to attach. Apparently, telling >>node<< to wait means that the RemoteDebug script doesn't get to start up.

So I changed the command on the Pi to:

```
    $ node RemoteDebug.js -waitforattach app.js 
    node: /usr/local/bin/node  
    scriptToDebug: app.js  
    passThroughArgs:  
    localClientPort: localhost:5859  
    remoteServerPort: undefined:5858  
    startDebuggeeOnRemoteConnect: true  
    startDebuggeeBrokenAtEntryPoint: false  
    remoteServerSocket listening for connection
```
This allowed Visual Studio to find the remote process to attach to...but as soon as it made the attempt, it threw the following error:

>Unable to attach to the process. Operation not supported. Unknown error 0x80004005.

Over on the Pi the following error message appeared, and the remote debug process terminated:

>     Debuggee started: /usr/local/bin/node --debug=5859 app.js
>     events.js:141
>           throw er; // Unhandled 'error' event
>           ^
>     
>     Error: connect ECONNREFUSED 127.0.0.1:5859
>         at Object.exports._errnoException (util.js:856:11)
>         at exports._exceptionWithHostPort (util.js:879:20)
>         at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

So I think I've just traded on problem for another :)

**Comment by paulvanbrenk** [comment]
Can you attach in either case using Chrome?

**Comment by markolbert** [comment]
Thanx for getting back to me, Paul. Since I posted this, I've jettisoned my Pi-based solution in favor of a commercially-available one. I'll close the issue.
