### ISSUE TITLE
TypeScript: Add menu item should have more options

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/nodejstools#16]
This is an NTVS project menu

![image](https://cloud.githubusercontent.com/assets/1106823/6962426/47f84818-d92c-11e4-820e-e9a9f6ffdc6e.png)

Ordinary TypeScript projects also have these further options in another item group just below:
* TypeScript File
* HTML Page
* JavaScript File
* Style Sheet

**Comment by mousetraps** [comment]
If we do this, we should also do something similar for JavaScript files.

**Comment by NoelAbrahams** [comment]
The new set of options seem to be cropping up in duplicate in TypeScript (i.e. not NTVS) projects:

![image](https://cloud.githubusercontent.com/assets/1106823/18683294/93313550-7f67-11e6-96b9-7819caf9b932.png)
