### ISSUE TITLE
Node.js Tools requires TypeScript for Visual Studio 1.8 or higher.

### ISSUE THREAD

**Issue by AskYous** [Microsoft/nodejstools#1603]
##### Expected Behavior 
Expect this popup to not come up.

##### Actual Behavior 
Popup comes up. I think it's saying I don't have typescript installed.

- NTVS Version: 1.3.41102.00
- Visual Studio Version: 2017 Version 15.2 (26430.6) Release
- Node.js Version: v6.10.3
- TypeScript: 2.2.2.0 (found in Help > About Microsoft Visual Studio)

##### Steps to Reproduce
1. Install typescript globally
2. Open a Visual Studio typescript project

![image](https://user-images.githubusercontent.com/791996/27048690-a32b9656-4f61-11e7-966b-438ab66b67ae.png)

I receive the above pop up everytime I open or create a TypeScript NodeJS project. I tested on PowerShell and command prompt running `tsc -v` and it returns `Version 2.3.2`.

Here's some more information about my versions:

![image](https://user-images.githubusercontent.com/791996/27048933-835e7e96-4f62-11e7-9dd2-546045c94b01.png)

**Comment by paulvanbrenk** [comment]
This is fixed in 15.3

**Comment by AskYous** [comment]
Cool. Thanks for the update.
