### ISSUE TITLE
node_modules folder causes several minutes of lag when exploring files in VS2017

### ISSUE THREAD

**Issue by briman0094** [Microsoft/nodejstools#1606]
I'm not entirely sure if this is the right place for this question as it pertains more to VS2017 than Node.js tools, but as it is triggered by large `node_modules` folders, I figured I would ask here.

I am working on a project with a large amount of Node dependencies in the main `package.json`, and of course each dependency installs several of its own to the root of the `node_modules` folder (tree is flattened in the latest versions of NPM). I am also working on part of the project in VS Code as it has far better support for Pug and SCSS files than VS2017 does, and sometimes handles TypeScript better than ReSharper.

Because I am working in both IDEs, if I create a file in VS Code, I must add it manually to the project in VS2017 by clicking Show All Files and then "Include In Project" for each of the files I need to add. The problem with this is that when I click "Show All Files", it tries to enumerate the directory structure of the entire `node_modules` folder which freezes the whole IDE for about 5 minutes. It also freezes whenever I install or remove any packages, even if the `node_modules` folder is hidden from the Solution Explorer.

Is there any way to have the IDE completely ignore the `node_modules` folder even in "Show All Files" mode? If not, would this be possible as a feature in NTVS? I can't work effectively if the IDE freezes this often.

**Comment by paulvanbrenk** [comment]
This has been called out before, and this is something the project system would have to support... as a work around, you can use the "add existing item" menu option, so you don't have to use "show all files". I do realize this is annoying when adding folders.

**Comment by briman0094** [comment]
I actually figured something out since writing this...I decided to try setting the `node_modules` directory and all children as "Hidden", and it seems to have made Visual Studio ignore the folder even with "Show All Files" enabled. Of course, this isn't a perfect solution because any time I need to reinstall packages, or if I clone the project on a new machine, I have to remember to go mark `node_modules` as Hidden or I'll end up freezing my IDE for 5 minutes.

**Comment by paulvanbrenk** [comment]
Can you share your `package.json` so we can try to reproduce.

**Comment by uniqueiniquity** [comment]
https://developercommunity.visualstudio.com/content/problem/148195/nodejs-projects-lead-to-high-load-of-visual-studio.html seems to a related issue.

**Comment by paulvanbrenk** [comment]
This should be greatly improved by  #1835
