### ISSUE TITLE
Support debugging SSR from SpaServices

### ISSUE THREAD

**Issue by rosieks** [Microsoft/nodejstools#1607]
ASP.NET team has introduced [SpaServices](https://github.com/aspnet/JavaScriptServices/) that runs JS/TS to support server-side rendering. Please cooperate with them and introduce ability to debug that code directly in Visual Studio. Currently I have to use Chrome to do that: https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-javascripttypescript-code-when-it-runs-on-the-server

**Comment by paulvanbrenk** [comment]
You can actually do this in Visual Studio currently.

1. Choose "Debug" - "Attach to process...."
2. Select "Connection Type" : "Webkit"
3. Enter the Url in the "Connection Target"
4. Click "Refresh"

And you should be able to attach.

![image](https://user-images.githubusercontent.com/5273975/28043619-8bb56f42-6587-11e7-99b1-3f6a373bbb5e.png)
