### ISSUE TITLE
Export Control Classification Number

### ISSUE THREAD

**Issue by mohduzair1605** [Microsoft/nodejstools#1608]
Hello Team,

I am a Software Analyst, working on behalf of ExxonMobil Corporation. My group, IT Asset Management, is responsible for software licensing in our organization.

Please help me ECCN of Node.js Tools for Visual Studio 1.1.

**ECCN – Export Control Classification Number :** 

If you do not have your software classified with an ECCN, please kindly answer the following questions so that we may self-assess:

1, Does the Software perform any encryption or utilize any encryption processes?  Y/N
2. If the answer is YES to question 1, please indicate if the encryption is coded into the application or separately called (such as using SSL)
3. If the answer is YES to question 1, please indicate what function(s) the cryptography/encryption serves 
 
A, Copyright protection purposes (Includes using a license key/code)
B, User authentication purposes
C, A core part of the functionality such as to encrypt databases
D, To encrypt communications between the software and a host system.

Background information : 
An Export Control Classification Number (ECCN) is a specific alpha-numeric code that identifies the level of export control for items e.g. software that are exported from member states of the Wassenaar Arrangement, including the United States. After obtaining the ECCN, the exporter must determine whether an export license is required to export items to certain countries.

Thanks and Regards,
Mohd Uzair
New Products and Complex Team
EMIT Customer Infrastructure

HCL Technologies Limited
(CIN: L74140DL1991PLC046369)
10th Floor, ODC-IV, Software Tower 6, Sector 126
Noida SEZ, Uttar Pradesh – 201301, India
Work :- +1 408 809 3746  (Extension - 414-4550)
Email mohd.uzair@em-msph.com

for

ExxonMobil Global Services Company
22777 Springwoods Village Parkway
Spring, TX 77389
United States of America

**Comment by paulvanbrenk** [comment]
@bowdenk7 can you help this user.

**Comment by bowdenk7** [comment]
Hi @mohduzair1605, I am checking with our legal team and will get back to you shortly.

**Comment by bowdenk7** [comment]
@mohduzair1605, still waiting for a response from our legal team. If this is particularly urgent, let us know. Thanks!

**Comment by mohduzair1605** [comment]
It would be good if we can have this information as soon as possible.
Thanks !

**Comment by mohduzair1605** [comment]
Do we have any update please?

**Comment by paulvanbrenk** [comment]
Tuesday was a holiday in the US, so response may be slow this week.

**Comment by mohduzair1605** [comment]
Thanks for writing to me, I will be waiting for the information.

Thanks !

**Comment by bowdenk7** [comment]
Hi @mohduzair1605, sorry for the long delay. We don't have an ECCN, but the code in **this repository** doesn't utilize any kind of encryption. 

Please let me know if we can be of any further assistance.
