### ISSUE TITLE
high cpu usage for sometime, after npm update

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/nodejstools#1610]
##### Expected Behavior 
usual cpu usage after npm job is done
##### Actual Behavior 
about 40% cpu usage more than 5~7 minutes

- NTVS Version:
1.3.50417.1
- Visual Studio Version: 
15.2 ( 26430.14 )
- Node.js Version: 
8.1.2 x64
##### Steps to Reproduce
1.  npm update anay pachage(s)

**Comment by paulvanbrenk** [comment]
I think this is the same issue as #1606
