### ISSUE TITLE
Addition of TestAdapter to Hosted VS2017 agent in VSTS

### ISSUE THREAD

**Issue by steveculshaw** [Microsoft/nodejstools#1611]
The existing "Hosted VS2017" doesn't have the NTVS test adapter installed.

Can it be added to the official VSTS environment?

**Comment by paulvanbrenk** [comment]
The current implementation is not ideal for that... but we can make that work. Can you open a suggestion on the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), so the right team can handle this.

**Comment by steveculshaw** [comment]
At ... [issue](https://developercommunity.visualstudio.com/content/problem/78473/add-the-ntvs-test-adapter-to-the-official-hosted-v.html)
