### ISSUE TITLE
debugger fails to start after some time

### ISSUE THREAD

**Issue by dvirtz** [Microsoft/nodejstools#1612]
I'm using Node.js tools on VS 2017. 
After some successful debugging sessions, when I hit "Start Debugging" the console is opened with the message "Debugger listening on [::]:5858" and then nothing and the debugger does not start.
If I hit "Start Without Debugging" the application runs but I get a message window saying "failed to start process" and I'm unable to attach to the process.
After I restart my PC the problem is gone for some time and then returns.

I wanted to enable diagnostics log but that seems to be missing from this version of Node.js tools.

- NTVS Version:1.0.0.0
- Visual Studio Version: VS 2017 15.3.0 Preview 2.1
- Node.js Version: 6.11.0

**Comment by paulvanbrenk** [comment]
Is there an existing Node process still running n the background when this happens. 

( We removed the diagnostic window, since it never gave any useful information. And would have been very expensive to make accessible. )

**Comment by paulvanbrenk** [comment]
Closing as I need more info to debug this, further we're not investing in Node 6 debugging, but if this repros in Node 8+ please ping me.
