### ISSUE TITLE
NPM registry refresh is not working

### ISSUE THREAD

**Issue by robbie-mac** [Microsoft/nodejstools#1621]
##### Expected Behavior 
The local cache of the NPM registry to update when I 
##### Actual Behavior 

- NTVS Version: 1.3.50417.1
- Visual Studio Version: 15.2 (26430.15)
- Node.js Version: 8.1.3

##### Steps to Reproduce
1. new blank nodejs console app
2. install new npm package
3. update NPM registry
ERROR

After checking the link: registry.npmjs.org/-/all
it returns: {"message":"deprecated"}

Ive tried the solution in #1592 however the result is the same message.

**Comment by paulvanbrenk** [comment]
That wasn't supposed to happen till 9/1

http://blog.npmjs.org/post/157615772423/deprecating-the-all-registry-endpoint
