### ISSUE TITLE
VS 2017 message: "You can improve Startup performance.... Microsoft.NodejsTools.Repl.ReplWindow"

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/nodejstools#1627]
NTVS Version: 1.0.0.0
VS Version: 2017 Preview 3

![image](https://user-images.githubusercontent.com/1106823/28408167-82cfa628-6d2e-11e7-8478-83762aacc4eb.png)

I assume this message is referring to the NodeJS command window. I use this tool frequently, so don't want to shut it down.

Please look into improving the startup performance of this tool.

Thanks!

**Comment by NoelAbrahams** [comment]
Adds **6 seconds** to startup time:

![image](https://user-images.githubusercontent.com/1106823/28460366-a1e05efa-6e09-11e7-9255-1c6c472cc513.png)

**Comment by paulvanbrenk** [comment]
Haven't seen this in a while, and investigation shows this is not caused specifically by the Repl window. (i.e. the creation of the WindowFrame is the main cause, you could observer the same behavior in the error list).

**Comment by NoelAbrahams** [comment]
Love the bug fix strategy.

**Comment by kant2002** [comment]
@NoelAbrahams is you carefully watch this repository, this is a new one actually. Before that was one of the following
- TypeScript team should fix that
- It is issues in the new VS Project System (CPS)
- NodeJS broke debugger
- Ask for more information once a week, or less often

Likely this is New Year greeting for you

**Comment by NoelAbrahams** [comment]
We could call this the "kick into the long grass" method.
