### ISSUE TITLE
Debugger attaching when Config is on Release

### ISSUE THREAD

**Issue by Salmakis** [Microsoft/nodejstools#1638]
The debugger should not attach (and stop the execution and bring itself in foreground) when the configuration is on Release.

This is really annoying.

##### Expected Behavior 
Dont attach debugger when starting with release settings

##### Actual Behavior 
Debugger is being attached, stops the execution and brings VS into the foreground.

- NTVS Version:1.3.50417.1
- Visual Studio Version: 2017 (15.2(6430.16)
- Node.js Version: 8.1.2

##### Steps to Reproduce
1. use a fresh install of vs 2017 with nodejs tools
2. create any project with a few lines of code
3. set config to release
4. start the application
5. be annoyed when visual studio bring itself into the foreground and stops the execution at the start (no breakpoint)

**Comment by paulvanbrenk** [comment]
Thanks for reporting this. It sounds like the most annoying is the break on the first line, without the breakpoint. (I believe this is actually fixed in 15.3)

And there is a  workaround. Right-click on the project and select start with debugging.

**Comment by paulvanbrenk** [comment]
VS no longer stops on the first line unless explicitly specified by starting debugging with 'Step Into' [F11].

Support for separate Debug/Release configurations is considered for a future major release of VS.
