### ISSUE TITLE
[loc][Query][Node.js] Localizability of "AzureRemoteDebugWaitMessage" 

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/nodejstools#1641]
Hi, we have a question from a translator. Could you help please?

Source:
Attaching to Azure Website at {0}

File Name:
localize\ENU\Microsoft.NodejsTools.dll

Resource ID:
0; "AzureRemoteDebugWaitMessage"

------------------------------------------------
BPI 7892 Query:
Could you please provide information what the placeholder stands for? In our translation, we assumed that a webisite will be inserted and have translated the text around the placeholder accordingly. Or will a time/date be inserted? Could you please clarify?
Also refers to next string "Could not attach to node.exe process on Azure Website at {0}.

**Comment by paulvanbrenk** [comment]
in both cases the placeholder is the URL of the website.

**Comment by PDostalek** [comment]
Thx for reply
