### ISSUE TITLE
[loc][Query][Node.js] Localizability of "CannotAddFolderAsDescendantOfSelf"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/nodejstools#1642]
Hi, we have a question from a translator. Could you help please?

Source:
Cannot add folder '{0}' as a child or decedent of self.

File Name:
localize\ENU\Microsoft.NodejsTools.dll

Resource ID:
0; "CannotAddFolderAsDescendantOfSelf"

----------------------------------------------------------------
BPI 7920 Query:
Is "decedent" in the source supposed to be "descendant"?

**Comment by paulvanbrenk** [comment]
Yes, fixed

**Comment by PDostalek** [comment]
Thank you
