### ISSUE TITLE
[loc][Query][Node.js] Localizability of "UnhandledException" 

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/nodejstools#1643]
Hi, we have a question from a translator. Could you help please?

Source:
Unhandled exception in {3} ({1}:{2})\r\n{0}

File Name:
localize\ENU\Microsoft.NodejsTools.dll

Resource ID:
0; "UnhandledException"

------------------------------------------
BPI 7921 Query:
ould you kindly clarify the placeholders? We translated it assuming the whole "{3} ({1}:{2})" is a location where the unhandled exception occurred.

**Comment by paulvanbrenk** [comment]
{3} methodname
{1} filename
{2} line number
{0} exception name

**Comment by PDostalek** [comment]
Perfect, thx
