### ISSUE TITLE
[loc][Query][Node.js] Localizability of "0; "3059"" 

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/nodejstools#1644]
Hi, we have a question from a translator. Could you help please?

Source:
Basic Azure Node.js Express 4 Application

File Name:
localize\ENU\Microsoft.NodejsTools.dll

Resource ID:
 "0; "3059"" 

--------------------------------------------------
BPI 7934 Query:
Does this "blank" mean "empty" here? Same for the following Ress IDs: 
0; "3063" 
0; "3071" 0; "3073" 
0; "3077" 0; "3079" 
0; "3081" 0; "3083" 
0; "3085" 0; "3091"

**Comment by paulvanbrenk** [comment]
3059: basic means simple

All others "Blank" means "Empty"

**Comment by PDostalek** [comment]
Thank you
