### ISSUE TITLE
[loc][Query][Node.js] Localizability of "0; "RequestedVersionRangeNone", 0; "PackageCatalogRefresh0Days"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/nodejstools#1645]
Hi, we have a question from a translator. Could you help please?

Source:
None
Today at {0:t}

File Name:
localize\ENU\Microsoft.NodejsTools.dll

Resource ID:
0; "RequestedVersionRangeNone"
0; "PackageCatalogRefresh0Days"
---------------------------------------------------------
Query:
1) What is genre of "none"
2) What is meaning of the placeholder

**Comment by paulvanbrenk** [comment]
1. Not sure what the question is.. but it is used to indicate the user has not selected a version range for a specific NPM package

2. Indicates the last time the NPM database was refreshed e.g "Today at 2.00PM"

**Comment by PDostalek** [comment]
1. genre as : noun, adjective etc.. which should be there ?

**Comment by paulvanbrenk** [comment]
1. noun

**Comment by PDostalek** [comment]
perfect, thanks

**Comment by PDostalek** [comment]
We need more specify genre for this string.  Genre refers to "masculine/feminine". Please clarify.

**Comment by paulvanbrenk** [comment]
"None" here means "No Version Range" , as in:

Which version range is selected?  - None
