### ISSUE TITLE
[loc][Query][Node.js] Localizability of 0; "3048"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/nodejstools#1646]
Hi, we have a question from a translator. Could you help please?

Source:
Advanced

File Name:
localize\ENU\Microsoft.NodejsTools.dll

Resource ID:
0; "3048"

Query:
Is this " Advanced Options or Advanced Settings "

**Comment by paulvanbrenk** [comment]
That would be "Advanced Options"

**Comment by PDostalek** [comment]
Perfect, thx.
