### ISSUE TITLE
[Node.js tools]Truncation of button "Clear cache"

### ISSUE THREAD

**Issue by lukaschal** [Microsoft/nodejstools#1647]
##### Expected Behavior 
Whole button is visible.

##### Actual Behavior 
Button is truncated.

- Visual Studio Version: 15.2

Repro steps: Tools -> Options -> Node.js Tools -> Npm

See attached screenshot. Non-resizable from localization side.

![clear cache](https://user-images.githubusercontent.com/18324331/28771310-9a58bd54-75e2-11e7-9f0d-aa382c455429.png)

**Comment by paulvanbrenk** [comment]
Thanks for reporting, this button is removed in 15.3.
