### ISSUE TITLE
Debugging issues

### ISSUE THREAD

**Issue by ujaroe** [Microsoft/nodejstools#1650]
I'm reporting these issues since I've not found any statements regarding these, although I can't believe I'm the only one being affected.

First, starting a NodeJS project application always breaks on the first line. I suppose this is due to starting the project with "--inspect-brk" which looks like "kind of" intentional. I find it rather annoying though, especially since in a Typescript project the corresponding .js file isn't part of the project at all. VS reports this file most of the time as being changed (compiled from ts) which needs to be confirmed to be reloaded. Can this ("inspect-brk") be changed somehow ("inspect") or will it be made configurable?

Second, when I stop debugging (by menu or red squared stop button), the NodeJS script isn't stopped at all. Instead it reports "Debugger listening on..." again. So we need to close the NodeJS application explicitely which is too easy to be forgotten.

- NTVS Version: 1.3.50417.1
- Visual Studio Version: 15.2 (26430.16)
- Node.js Version: 8.2.1

**Comment by ujaroe** [comment]
![image](https://user-images.githubusercontent.com/9551280/28823631-d40e9d8e-76be-11e7-8c4d-288b458a1a62.png)

**Comment by paulvanbrenk** [comment]
Thanks for reporting this is fixed in Visual Studio 2017 Update 3

**Comment by jeffrson** [comment]
So VS 2017 15.3 gives
"[DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead."

Shouldn't "--inspect" be sufficient?
