### ISSUE TITLE
VS tooling references out of date

### ISSUE THREAD

**Issue by Mikejo5000** [Microsoft/nodejstools#1653]
This topic:
https://github.com/Microsoft/nodejstools/wiki/Azure-Cloud-Service-Projects

Has references to VS2013 tooling. Presumably, it needs to be updated to VS2017...

**Comment by paulvanbrenk** [comment]
Pinging @bowdenk7

**Comment by IronSean** [comment]
Is this also the issue to watch regarding the updated npm documentation? 
https://github.com/Microsoft/nodejstools/wiki/Npm-Integration

**Comment by paulvanbrenk** [comment]
Yes, slowly working through the docs to update them.

**Comment by paulvanbrenk** [comment]
Current plan is to have a good first set, and then rolling updates/additions. 

We were hoping before 2018, but Q1 is probably more realistic.

**Comment by paulvanbrenk** [comment]
Updated documentation can be found here:

https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs
