### ISSUE TITLE
[loc][Query][Node.js] Localizability of 0; "3066" 

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/nodejstools#1654]
Hi, we have a question from a translator. Could you help please?

Source:
Azure Cloud Service

File Name:
localize\ENU\Microsoft.NodejsTools.dll

Resource ID:
0; "3066"

Query:
When in plural, Azure Cloud Services is the name of "The Platform-as-a-Service (PaaS) offer in Microsoft Azure" and it is not translatable. What about singular? Is it a generic name, and therefore translatable?

**Comment by paulvanbrenk** [comment]
Nope, don't translate
