### ISSUE TITLE
[loc][Query][Node.js] Localizability of"0; "F5FileSelectTitle""

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/nodejstools#1655]
Hi, we have a question from a translator. Could you help please?

Source:
Choose which file to run when F5 is pressed.

File Name:
localize\ENU\Microsoft.NodejsTools.dll

Resource ID:
0; "F5FileSelectTitle"

Query:
According to the Resid, this string is a title, so the full stop at the end is unnecessary. Please confirm

**Comment by paulvanbrenk** [comment]
The resid is wrong.. it's simply a label
