### ISSUE TITLE
Remote debugging doesn't work

### ISSUE THREAD

**Issue by HarelAshwal** [Microsoft/nodejstools#1656]
I'm trying to connect using Remote Debug, it doesn't work.
debian@arm:~/pubTest/SAMPLER$ sudo node RemoteDebug.js -waitforattach app.js
node: /usr/local/bin/node
scriptToDebug: app.js
passThroughArgs:
localClientPort: localhost:5859
remoteServerPort: undefined:5858
startDebuggeeOnRemoteConnect: true
startDebuggeeBrokenAtEntryPoint: false
remoteServerSocket listening for connection
remoteServerSocket connected
Debuggee started: /usr/local/bin/node --debug=5859 app.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:5859
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

I tried with build in nodejs inspection feature (Chrome DevTools) and it works perfectly.
I also tried changing the ports (local & remote) , same issue.

sudo node --debug-brk --inspect app.js
Debugger listening on port 9229.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/f2050a8e-0ba9-4d25-8ee8-e16366083d00
Debugger attached.

Version info:

debian@arm:~/pubTest/SAMPLER$ node -v
v6.11.2

Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.16) Release
VisualStudio.15.Release/15.2.0+26430.16
Microsoft .NET Framework
Version 4.6.01055

Node.js Tools   1.3.50417.1

**Comment by paulvanbrenk** [comment]
I'm going to need more details here. What are you trying to do?

**Comment by HarelAshwal** [comment]
I'm trying to start a nodejs application at my BeagleBone Black card. 
And remote debug it with my VS 2017 runs on my PC.

**Comment by paulvanbrenk** [comment]
I still can't figure out what it is, you're doing. How do you attach to the remote instance of Node from VS?

**Comment by miparnisari** [comment]
Related: https://stackoverflow.com/questions/46500302/attach-visual-studio-debugger-to-electron-app

I am running `electron --remote-debugging-port=5858 .` on a terminal, then from VS 2017 I'm trying to remotely debug it, and when i select the target to "localhost:5858" it just hangs.

**Comment by paulvanbrenk** [comment]
@miparnisari Which connection type are you using?

**Comment by paulvanbrenk** [comment]
@miparnisari can you try the webkit debugger... though the name is confusing, that may actually work.

**Comment by miparnisari** [comment]
Wow, that worked! Thanks 👍

**Comment by paulvanbrenk** [comment]
Closing, as I need more info for the initial question, but the webkit debugger seems to do the trick.
