### ISSUE TITLE
VS 2017 Enterprise upgrade from 15.2 to 15.3

### ISSUE THREAD

**Issue by wholroyd** [Microsoft/nodejstools#1657]
[dd_setup_20170815141230_001_Microsoft.VisualStudio.NodejsTools.NodejsTools.txt](https://github.com/Microsoft/nodejstools/files/1225996/dd_setup_20170815141230_001_Microsoft.VisualStudio.NodejsTools.NodejsTools.txt)
[dd_setup_20170815141230_002_Microsoft.VisualStudio.NodejsTools.InteractiveWindow.txt](https://github.com/Microsoft/nodejstools/files/1225997/dd_setup_20170815141230_002_Microsoft.VisualStudio.NodejsTools.InteractiveWindow.txt)
[dd_setup_20170815141230_errors.txt](https://github.com/Microsoft/nodejstools/files/1225995/dd_setup_20170815141230_errors.txt)

Trying to upgrade my Visual Studio 2017 Enterprise upgrade from 15.2 to 15.3 and ran into an issue with the Visual Studio installer around the following two packages...

```
Microsoft.VisualStudio.NodejsTools.InteractiveWindow,version=1.3.41102.0
Microsoft.VisualStudio.NodejsTools.NodejsTools,version=1.3.41102.0
```

##### Expected Behavior 

Upgrade to 15.3 occurs smoothly

##### Actual Behavior 

Installer appears to upgrade everything successfully, except for NodeJS Tools. It shows the version as being 15.3.0 in the installer and in the Help > About within Visual Studio.

There is a note that "Setup completed with warnings". Digging into the logs for each component, the failure looks the same (component name being different)...

```
8/15/2017 2:18:14 PM - Initializing Uninstall...
8/15/2017 2:18:14 PM - Extension Details...
8/15/2017 2:18:14 PM - 	Identifier         : 29102E6C-34F2-4FF1-BA2F-C02ADE3846E8
8/15/2017 2:18:14 PM - 	Name               : Node.js Tools - Interactive Window
8/15/2017 2:18:14 PM - 	Author             : Microsoft
8/15/2017 2:18:14 PM - 	Version            : 1.4.10602.1
8/15/2017 2:18:14 PM - 	Description        : Node.js Tools - Interactive Window.
8/15/2017 2:18:14 PM - 	Locale             : en-US
8/15/2017 2:18:14 PM - 	MoreInfoURL        : http://go.microsoft.com/fwlink/?LinkId=785971
8/15/2017 2:18:14 PM - 	InstalledByMSI     : False
8/15/2017 2:18:14 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
8/15/2017 2:18:14 PM - 
8/15/2017 2:18:14 PM - 	Supported Products : 
8/15/2017 2:18:14 PM - 		Microsoft.VisualStudio.Community
8/15/2017 2:18:14 PM - 			Version : [15.0.0,16.0)
8/15/2017 2:18:14 PM - 		Microsoft.VisualStudio.Pro
8/15/2017 2:18:14 PM - 			Version : [15.0.0,16.0)
8/15/2017 2:18:14 PM - 		Microsoft.VisualStudio.Enterprise
8/15/2017 2:18:14 PM - 			Version : [15.0.0,16.0)
8/15/2017 2:18:14 PM - 
8/15/2017 2:18:14 PM - 	References         : 
8/15/2017 2:18:14 PM - 	Prerequisites      : 
8/15/2017 2:18:14 PM - 		-------------------------------------------------------
8/15/2017 2:18:14 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
8/15/2017 2:18:14 PM - 		Name         : Visual Studio core editor
8/15/2017 2:18:14 PM - 		Version      : [15.0,16.0)
8/15/2017 2:18:14 PM - 
8/15/2017 2:18:14 PM - 
8/15/2017 2:18:14 PM - Found installed product - displayName
8/15/2017 2:18:14 PM - Uninstalling 'Node.js Tools - Interactive Window', version 1.4.10602.1.
8/15/2017 2:18:20 PM - System.InvalidOperationException: Uninstall of Node.js Tools - Interactive Window failed. To uninstall this extension please uninstall all of the following components: Node.js support, Node.js development
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.App.UninstallExtensionFromSKU(String vsixID, SupportedVSSKU sku)
   at VSIXInstaller.App.UninstallSilently(String vsixId, IEnumerable`1 validSKUs)
   at VSIXInstaller.App.OnStartup(StartupEventArgs e)
```

Full logs are attached. One thing that looked odd is that the versions for the components are different between the error overview log and the component installer logs.

`Uninstalling 'Node.js Tools - Interactive Window', version 1.4.10602.1.`
vs.
`Package 'Microsoft.VisualStudio.NodejsTools.InteractiveWindow,version=1.3.41102.0' failed to uninstall.`

This machine also has VS 2017 15.3.0 Preview 7.1 installed side-by-side to the RTM version.

- NTVS Version: (not showing in the Installed Products list)
- Visual Studio Version: VS 2017 15.3.0
- Node.js Version: (not showing in the Installed Products list, 6.3.1 installed in `c:\Program Files (x86)\nodejs`)

##### Steps to Reproduce
No clue.

**Comment by pfeigl** [comment]
Same problem on my side, but completely different parametrs:
- german OS (so also the named dependencies which should be removed first are called out in german)
- no preview of 15.3 was installed
- nodejs was installed in latest version 8

**Comment by paulvanbrenk** [comment]
Thanks for reporting, this seems to be an issue with the Visual Studio setup engine. And unfortunately the nodetools package seems to suffer the most.

The workaround is to remove the 2 packages from: 

> Manually removing the packages below from the "C:\ProgramData\Microsoft\VisualStudio\Packages" folder, fixed the upgrade issue that I had. 
> - Microsoft.VisualStudio.NodejsTools.NodejsTools
> - Microsoft.VisualStudio.NodejsTools.InteractiveWindow

Please, follow[ the issue on the Visual Studio Developer Community](https://developercommunity.visualstudio.com/content/problem/93253/packageidmicrosoftvisualstudionodejstoolsnodejstoo.html) for more info.
