### ISSUE TITLE
nodejs 8 debugging with VS 2017 Community 15.3.0

### ISSUE THREAD

**Issue by Frahmer** [Microsoft/nodejstools#1658]
##### Expected Behavior 
output :
Hello world

##### Actual Behavior 
output :
(node:11172) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.
Hello world

- NTVS Version: 1.4.10602.1
- Visual Studio Version: VS Community 2017 15.3.0
- Node.js Version: 8.3.0

##### Steps to Reproduce
1. create new empty nodejs project
2. app.js contains: `'use strict'; console.log('Hello world');`
4. start debugging

If I add `console.info(process.execArgv);` the output  `[ '--inspect=<random number>', '--debug-brk' ]` is displayed.

I tried to change the RemoteDebug.js, but it does not change the behavior.

Why --debug and why --debug-brk ?

**Comment by paulvanbrenk** [comment]
When we implemented the support for the new debug protocol in Node 8, `--debug-brk` was still supported. Unfortunately we were not able to change our implementation between the change in Node 8, and the release of Update 3. 

This will be fixed in Update 4 for Visual Studio 2017 (15.4)

**Comment by paulvanbrenk** [comment]
This is tracked here. (And may not actually be fixed in 15.4 👎 )

**Comment by designerx2** [comment]
I'm experiencing this problem with a freshly installed Visual Studio 15.4.5 and Node JS 8.9.1 LTS. Are there any updates?

**Comment by paulvanbrenk** [comment]
Nothing to report yet, I'll update this issue when it's fixed

**Comment by wtyp** [comment]
Any updates?

**Comment by anupammaurya** [comment]
I am dealing with same, I have 
Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15:55:03.538Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

ERROR: (node:30884) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.

**Comment by delatitude** [comment]
I am using the default Node js Express Template with TypeScript in visual studio 2017.  I get this below warning when i try to run the application.  Although the application runs fine. 

`DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.`

**Comment by paulvanbrenk** [comment]
This should be in Visual Studio 2017 Update 6, not sure when that's released though.

**Comment by SlurpTheo** [comment]
@paulvanbrenk Which issue made you think it was going to be in Update 6 (still happening for me in Update 7)?

**Comment by jeffrson** [comment]
I assume that Update **15.6** had been meant - not **15.5.7** (which is the latest at the moment).

**Comment by paulvanbrenk** [comment]
@jeffrson is correct, Visual Studio 2017 Update 6, which would indeed be 15.6 and not 15.5.7.

**Comment by suthakarkps** [comment]
still the issue persist in Visual Studio 2017 Update 6

**Comment by paulvanbrenk** [comment]
@suthakarkps what's your question, debugging Node applications works fine, this is a superfluous message and shouldn't affect your ability to debug your code. And we know what's wrong, and the team responsible has fixed this in update 7, which is currently in [preview](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-Preview-relnotes).

**Comment by paulvanbrenk** [comment]
Closing, since Update 7 is released.
