### ISSUE TITLE
"An unexpected error occurred" popup shown after starting Node JS project in VS2015

### ISSUE THREAD

**Issue by simonbor** [Microsoft/nodejstools#1661]
I don't know exactly when I started to get following Error dialog each time I open my Node JS solution - 
![image](https://user-images.githubusercontent.com/8211293/29378300-37833d2a-82c7-11e7-9638-12308570ca05.png)
##### Expected Behavior 
Open Node JS proj without errors
##### Actual Behavior 
Error dialog while starting Node JS proj

- NTVS Version: 1.3
- Visual Studio Version: 2015 update 3
- Node.js Version: 6.11.2

##### Steps to Reproduce
1. Open the project from command line - devenv /log
2. open the ActivityLog.xml and see following error - 

`
<entry>
    <record>518</record>
    <time>2017/08/16 18:15:36.465</time>
    <type>Error</type>
    <source>Node.js Tools for Visual Studio</source>
    <description>Unhandled exception in ReloadHierarchySafe (F:\A\_work\2\s\Nodejs\Product\Nodejs\Project\NodeModulesNode.cs:315)&#x000D;&#x000A;Microsoft.NodejsTools.Npm.SemverVersionFormatException: Invalid semantic version: &apos;https://registry.npmjs.org/accepts/-/accepts-1.1.4.tgz&apos;. The version number must consist of three non-negative numeric parts of the form MAJOR.MINOR.PATCH, with optional pre-release and/or build metadata. The optional parts may only contain characters in the set [0-9A-Za-z-].&#x000D;&#x000A;   at Microsoft.NodejsTools.Npm.SemverVersion.Parse(String versionString)&#x000D;&#x000A;   at Microsoft.NodejsTools.Npm.SPI.PackageJson.get_Version()&#x000D;&#x000A;   at Microsoft.NodejsTools.Npm.SPI.RootPackage.get_Version()&#x000D;&#x000A;   at Microsoft.NodejsTools.Project.DependencyNode.GetInitialPackageDisplayString(IPackage package)&#x000D;&#x000A;   at Microsoft.NodejsTools.Project.AbstractNpmNode.BuildModuleHierarchy(HierarchyNode parent, IEnumerable`1 modules, IReadOnlyDictionary`2 recycle)&#x000D;&#x000A;   at Microsoft.NodejsTools.Project.AbstractNpmNode.ReloadHierarchy(HierarchyNode parent, IEnumerable`1 modules)&#x000D;&#x000A;   at Microsoft.NodejsTools.Project.NodeModulesNode.ReloadPackageHierarchies(INpmController controller)&#x000D;&#x000A;   at Microsoft.NodejsTools.Project.NodeModulesNode.ReloadHierarchy()&#x000D;&#x000A;   at Microsoft.VisualStudioTools.UIThread.InvokeAsyncHelper(Action action, TaskCompletionSource`1 tcs)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudioTools.VsTaskExtensions.&lt;HandleAllExceptions&gt;d__4.MoveNext()</description>
  </entry>
`

**Comment by paulvanbrenk** [comment]
Can you share your `package.json`?

**Comment by simonbor** [comment]
{
  "name": "web-app",
  "version": "0.0.0",
  "description": "WebApp",
  "main": "server.js",
  "author": {
    "name": "Simon"
  },
  "scripts": {
    "start": "node server.js",
    "build:live": "nodemon --exec ./node_modules/.bin/ts-node -- ./server.ts"
  },
  "dependencies": {
    "body-parser": "^1.15.2",
    "express": "^4.14.0",
    "mongoose": "^4.6.6",
    "nodemailer": "^2.6.4",
    "q": "^1.5.0",
    "validator": "^6.2.0"
  },
  "devDependencies": {
    "[at]types/mongodb": "^2.1.43",
    "[at]types/mongoose": "^4.7.9",
    "[at]types/node": "^7.0.12",
    "[at]types/nodemailer": "^1.3.32",
    "assert": "^1.4.1",
    "nodemon": "^1.11.0",
    "ts-node": "^3.2.0",
    "typescript": "^2.4.0"
  }
}

**Comment by paulvanbrenk** [comment]
I'm unable to reproduce this, and the `package.json` you shared doesn't seem to include the problematic package... `https://registry.npmjs.org/accepts/-/accepts-1.1.4.tgz` 

Can you try to create a small sample project, or try VS 2017 Update 3?

**Comment by simonbor** [comment]
I just decided to continue working on the project in vscode.
Thanks for your support.
