### ISSUE TITLE
Permit loading custom modules in the Interactive Window

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/nodejstools#17]
The interactive window is a very nice feature. It's great that I'm able to test out NodeJS code on the fly. 

This request is to associate the interactive window with a particular project in Visual Studio. This would permit loading custom modules defined in that project.

At present this works:

```typescript
var x = require('fs');
```

but this doesn't

```typescript
var x = require('htmlParser2')
// Error: Cannot find module 'htmlParser2'
```

NB: I have installed htmlParser2 in one of the NTVS projects, but not all of them.

**Comment by MystK** [comment]
Custom modules are in fact supported, but after some testing, you would need to either add a "./" before or ".js" after the custom module.

**Comment by MystK** [comment]
Could you clarify more on what the problem is? From my testing, it looks like the NIW does load custom modules. I did a copy of a module, renamed it, and it worked fine when I required it in NIW. Did you check which project your NIW was in by entering "process.cwd()?"

**Comment by NoelAbrahams** [comment]
@MystK, `process.cwd()` is a nice tip. How do I ***set*** the active project?

**Comment by MystK** [comment]
Setting the active project is automated from what I understand depending on the solution you have open. 

If you switch solutions but already have NIW open, you'll have to reset NIW by pressing the blue loop-back arrow button in the same window as NIW.

**Comment by NoelAbrahams** [comment]
Ah, okay. That works, thanks! The procedure:

To test a package installed in a particular project

* Open up a file from the project.
* In the NIW hit the blue reset button.
* Check that you are in the correct project by running `process.cwd()`.
* Now you can `require` the packages installed in that particular project.
