### ISSUE TITLE
Clarify Environment Variable syntax

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/nodejstools#1703]
I'm only seeing a large textbox labeled "Environment variables". This is annoying and frustrating. I have no idea how it expects the variables to be formatted.

**Comment by oliversalzburg** [comment]
Additionally, it seems like the environment variables aren't even persisted into the project files. No matter what I enter, it is not saved.

However, when I add an `Environment` node into my `.njsproj` file, the values in it appear in the UI.

**Comment by paulvanbrenk** [comment]
I agree on the Environment Variables formatting. I'll update that for the next update.

The saving issue is fixed in VS 2017 Update 4

**Comment by paulvanbrenk** [comment]
I'm going to add this to the docs, I spend too much time trying to add this to the property pages with very little success..
