### ISSUE TITLE
Typo in Build Instructions

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/nodejstools#171]
There is a minor type in the [Build Instructions](https://github.com/Microsoft/nodejstools/wiki/Build-Instructions) page.  The location of `VSTestHost.msi` reads

> Common\Prerequisites\VSTestHost.msi

Should be 

> Common\Tests\Prerequisites\VSTestHost.msi

**Comment by mousetraps** [comment]
Thanks, and fixed
