### ISSUE TITLE
Why do we need to use the dot prefix?

### ISSUE THREAD

**Issue by Matthew-Bonner** [Microsoft/nodejstools#1714]
When copying commands from tutorials, people quite often provide npm commands.

Having to prefix the command with a dot gets annoying, especially when you are doing a lot of command line work where a dot prefix is not required.

The dot prefix is a source of confusion when you first work with the Node.js interactive window and even the Microsoft Docs website does not mention anything about this from what I can see.

Is it possible to remove the requirement for the dot prefix as this is really annoying and I can't really see what the use of it is.

**Comment by paulvanbrenk** [comment]
We can certainly consider it.

**Comment by paulvanbrenk** [comment]
Looked into this, and there isn't an otherwise good way to distinguish between command and code in the interactive window. (Except for a 'command' mode, which I dislike even more, or a separate window for handling npm command).
