### ISSUE TITLE
Need a way to restore npm packages in open-folder solutions

### ISSUE THREAD

**Issue by amcasey** [Microsoft/nodejstools#1728]
When you Open Folder, there's no `npm` node in Solution Explorer, so there's no way to restore npm packages (without resorting to the command line).  It would be helpful to have some way to trigger this through the Solution Explorer.

**Comment by jgwinner** [comment]
Just open and save package.json. That'll trigger it, depending on your project settings - EVEN IF you do not have a project open!

I've found that in my case it runs npm automatically, and with apparently slightly different versions. Mucked up my node files all over the place.

There IS a setting in the project-settings to tell it not to run npm, but I thought if I was just opening package.json as a text file (Run VS2017-> File Open), it wouldn't 'execute' project options. I was wrong!

== John ==

**Comment by amcasey** [comment]
@jgwinner, I opened this on your behalf because I understood you were asking for a menu item to explicitly trigger npm install.  Please let me know if that's not the case.

**Comment by jgwinner** [comment]
Doh! Sorry had too many bugs open. That is correct. I was trying to help you out, LOL.

It's actually sort of the opposite symptom - when you open package.json, no matter what, it messes with your npm packages. 

As you mention, a good fix would be an optional way to trigger the package rebuild. Thank you! I would normally assume this would be part of a "build" stage as with everything else. Then, the build settings can stay with the current defaults.

== John ==

**Comment by paulvanbrenk** [comment]
We def. need to make this easier for users to control... Install on Save is not the most discoverable.

**Comment by jgwinner** [comment]
Exactly!

Thanks, you guys are very responsive, much appreciated.

== John ==

**Comment by ihuchukwu** [comment]
> Just open and save package.json. That'll trigger it, depending on your project settings - EVEN IF you do not have a project open!
> 
> I've found that in my case it runs npm automatically, and with apparently slightly different versions. Mucked up my node files all over the place.
> 
> There IS a setting in the project-settings to tell it not to run npm, but I thought if I was just opening package.json as a text file (Run VS2017-> File Open), it wouldn't 'execute' project options. I was wrong!
> 
> == John ==

Thanks John. that was perfect!
