### ISSUE TITLE
Cannot set breakpoint to files in symbolic linked directory

### ISSUE THREAD

**Issue by Magentaize** [Microsoft/nodejstools#1733]
##### Expected Behavior 
Hit breakpoints in files.
##### Actual Behavior 

- NTVS Version: 1.4.10918.1
- Visual Studio Version: 15.4.0
- Node.js Version: 6.11.0

##### Steps to Reproduce
1. Created a folder 'A'
2. Create a js file 'index.js' in 'A'
3. Create a directory 'LinkA' symbolic linked to 'A'
4. Set a breakpoint in 'index.js' located in 'LinkA' and start debugging
5. 
![image](https://user-images.githubusercontent.com/11793304/31573078-6038ff92-b0ef-11e7-8859-808658a55ba8.png)

**Comment by paulvanbrenk** [comment]
Did you happen to try this with Node 8, does that work?

**Comment by Magentaize** [comment]
I have tried nodejs 8.7.0, the same.

**Comment by paulvanbrenk** [comment]
Thanks for trying.

What exactly do you mean by "linked to 'A'"?

**Comment by Magentaize** [comment]
Execute in cmd 'mklink LinkA /D A'

**Comment by paulvanbrenk** [comment]
We're no longer making changes to the node 6 debugger, if this reproduces in Node 8 please create a feedback item in VS, so the righ team can take a look.
