### ISSUE TITLE
Test adapter always fails if codepage is UTF-8 using vstest.console.exe

### ISSUE THREAD

**Issue by mbp** [Microsoft/nodejstools#1735]
Background:
We are using VSTS to run unit tests. We use the "Visual Studio Test" Build Task for `*.njsproj` projects. This invokes `vstest.console.exe`

A few days ago, the build stopped working without us making any changes. The reason: A new version of of the VSTS Build Task was released with this commit: https://github.com/Microsoft/vsts-tasks/commit/88417fb0ee15e0af69d2f439dff4e69b82fc0166

For some reason `vstest.console.exe` is now running in UTF-8 codepage. And this causes vstest.console.exe combined with Node.Js tools to fail.

##### Expected Behavior 

Tests can be run using vstest.console.exe and pass, even when code page is UTF-8

##### Actual Behavior 

All tests fail for no apparent reason. Output:

> Microsoft (R) Test Execution Command Line Tool Version 15.0.26720.2
> Copyright (c) Microsoft Corporation.  All rights reserved.
>
> Starting test execution, please wait...
> Information: Processing: C:\Users\mbp\Desktop\TestProject\app.tests.js
>
> Information:   Creating TestCase:C:\Users\mbp\Desktop\TestProject\app.tests.js::unit test example::Mocha
>
> Information: Processing finished for framework of Mocha
>
> Failed   unit test example
> Results File: C:\Users\mbp\TestResults\mbp_EC2AMAZ-DAD7KPJ 2017-10-20 08_59_18.trx
>
> Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
> Test Run Failed.
> Test execution time: 0.6170 Seconds

- NTVS Version: 1.4.10918.1
- Visual Studio Version: 2017 15.4.1
- Node.js Version: 6.10

##### Steps to Reproduce
1. Start command prompt
2. Call `c:\Windows\system32\chcp.com 65001`
3. Call `vstest.console.exe Projectfile.njsproj /TestAdapterPath:C:\PathToNodeJsTestAdapter`

Below you can see the concrete files I used:

package.json
```
{
  "name": "test-project",
  "version": "0.0.0",
  "description": "test-project",
  "main": "app.js",
  "author": {
    "name": "test-project"
  },
  "devDependencies": {
    "mocha": "^3.2.0"
  }
}
```

app.tests.js
```
describe('unit test', function () {
    it('example', function () {
    });
});
```

TestProject.njsproj
```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">14.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
    <VSToolsPath Condition="Exists('C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild')">C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0</VSToolsPath>
    <VSToolsPath Condition="Exists('C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild')">C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0</VSToolsPath>
    <Name>TestProject</Name>
    <RootNamespace>TestProject</RootNamespace>
  </PropertyGroup>
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>b7c42dbc-92ee-41d5-b1bb-65b25dfa0efc</ProjectGuid>
    <ProjectHome>.</ProjectHome>
    <StartupFile>app.js</StartupFile>
    <StartWebBrowser>False</StartWebBrowser>
    <SearchPath>
    </SearchPath>
    <WorkingDirectory>.</WorkingDirectory>
    <OutputPath>.</OutputPath>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <ProjectTypeGuids>{3AF33F2E-1136-4D97-BBB7-1795711AC8B8};{9092AA53-FB77-4645-B42D-1CCCA6BD08BD}</ProjectTypeGuids>
    <ProjectView>ShowAllFiles</ProjectView>
    <StartWebBrowser>false</StartWebBrowser>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="app.tests.js">
      <SubType>Code</SubType>
      <TestFramework>Mocha</TestFramework>
    </Compile>
    <Content Include="package.json" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="test\" />
  </ItemGroup>
  <!-- Do not delete the following Import Project.  While this appears to do nothing it is a marker for setting TypeScript properties before our import that depends on them. -->
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="False" />
  <Import Project="$(VSToolsPath)\Node.js Tools\Microsoft.NodejsTools.targets" />
</Project>
```

**Comment by paulvanbrenk** [comment]
Thanks for the clear repro steps... I'll see if I can get an easy fix in.

**Comment by paulvanbrenk** [comment]
I have a fix, which works on my machine.... 

In the `run_test.js` file, change the following lines:
```javascript
 rl.on('line', (line) => {
     rl.close();
     var testCases = JSON.parse(line);
```

to 
```js
rl.on('line', (line) => {
    rl.close();

    // strip the BOM in case of UTF-8
    if (line.charCodeAt(0) === 0xFEFF) {
        line = line.slice(1);
    }

    var testCases = JSON.parse(line);
```

You should be able to find that file here:

`<Path to VS>\Common7\IDE\Extensions\Microsoft\NodeJsTools\TestAdapter\TestFrameworks`

**Comment by mbp** [comment]
I can confirm the fix works. Thanks!

**Comment by paulvanbrenk** [comment]
Looks like this should be in Update 5 for Visual Studio 2017.
