### ISSUE TITLE
Missing Nodejs template 

### ISSUE THREAD

**Issue by ramadhyanir** [Microsoft/nodejstools#1750]
Expected Behavior 

New Project -> Installed Templates -> Javascrpit -> Nodejs

##### Actual Behavior 

Javascript templates are missing. When I try to open an existing *.nsproj, it fails. 
I first installed Node.js (v 6.11.5), then I installed VS Community 2017 and include the Node.js Development workload.   

- NTVS Version: No separate NTVS used. Downloaded VS Community 2017 edition. 
- Visual Studio Version: 15.4.1
- Node.js Version: 6.11.5

##### Steps to Reproduce
1. 
2.

**Comment by paulvanbrenk** [comment]
were there any errors when installing?

Can you try the repair option in the VS Installer?

Can you collect the logs using vscollect? aka.ms/vscollect

**Comment by paulvanbrenk** [comment]
Closing. I am not able to reproduce, and can't investigate without the log files.
