### ISSUE TITLE
Launch Node.js Profiling... menu option missing

### ISSUE THREAD

**Issue by brianlagerman** [Microsoft/nodejstools#1755]
##### Expected Behavior 

In a node.js project, Launch the Node.js Profiling tool from the Analyze menu as demonstrated [here](https://github.com/Microsoft/nodejstools/wiki/Profiling#2-launch-nodejs-profiling)

##### Actual Behavior 

Menu option doesn't exist

- NTVS Version: 1.4.10918.1
- Visual Studio Version: 15.4.2 (Enterprise 2017)
- Node.js Version: 8.9.0 LTS

##### Steps to Reproduce

Install node.js workload in Visual Studio, create node.js project

**Comment by brianlagerman** [comment]
For what it's worth, I see that others have 2 distinct packages for NTVS, for example:

> Node.js Tools   1.2.40726.00
> Adds support for developing and debugging Node.js apps in Visual Studio
> 
> Node.js Tools - Profiling   1.2.40726.00
> Profiling support for Node.js projects.

I don't have the Profiling extension, only: 

> Node.js Tools   1.4.10918.1
> Adds support for developing and debugging Node.js apps in Visual Studio

Were these merged at some point? I don't see any additional Profiling option in the installer...

**Comment by paulvanbrenk** [comment]
As you noted this has been deprecated for VS 2017 for the time being.
