### ISSUE TITLE
How to install Node.js tools with Build Tools for Visual Studio 2017?

### ISSUE THREAD

**Issue by mbp** [Microsoft/nodejstools#1773]
When using Node.js tools in a build environment, we use the testadapter in `Common7\IDE\Extensions\Microsoft\NodeJsTools\TestAdapter`

For a build server, we have "Build Tools for Visual Studio 2017" installed, but there is no option to install Node.js development workload?

**Comment by paulvanbrenk** [comment]
Unfortunately that's currently not supported, and you're the first to ask for this... I'll investigate and see what I can do.

For now as a workaround, install VS...

**Comment by paulvanbrenk** [comment]
Looks like this will be supported in Visual Studio 2017 Update 6, though we weren't able to get this in preview 2. It should be in the next preview and RTW.

**Comment by mbp** [comment]
@paulvanbrenk sorry for writing in the closed issue, but I just installed the latest 15.6.0 Build Tools
I find that I can install "Node.js build tools" workload, but I don't find the test adapter in the installation.

The file `Microsoft.NodejsTools.TestAdapter.dll` does not exist in any path below `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools`

For the VS installation, is is found here: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\NodeJsTools\TestAdapter
`

**Comment by paulvanbrenk** [comment]
That's correct. We haven't added the test adapter yet, we wanted to make a bunch of changes to make that more applicable to not just Node projects. That work is scheduled for a future update though.

**Comment by jan-zaruba-deltatre** [comment]
If I simply run `dotnet build` on a solution that contains njsproj it fails with this error despite it builds fine in VS2022. SO any progress there?

**Comment by JPSefe** [comment]
Same as @jan-zaruba-deltatre dotnet build gives this message while Visual Studio does not complain

**Comment by joj** [comment]
We don't support dotnet build for this project system. We do support it on the new project system. You can try migrating to that by right clicking on the project and clicking on "Convert to New JavaScript Experience".
