### ISSUE TITLE
[loc][Query][Node.js] Localizability of"0; "StartActionHeader"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/nodejstools#1774]
Hi, we have a question from a translator. Could you help please?

Source:
Start Action

File Name:
localize\ENU\Microsoft.NodejsTools.dll

Resource ID:
0; "StartActionHeader"

Query:
Is Start a verb or part of the noun here? Occurs twice in scope.

**Comment by paulvanbrenk** [comment]
It's a noun. It should represent, the action executed when starting the application.

**Comment by PDostalek** [comment]
Thanks!
