### ISSUE TITLE
Please update nsproj format to include by default like new csproj

### ISSUE THREAD

**Issue by sudsy** [Microsoft/nodejstools#1776]
It would be great if .nsproj files were include by default with explicit exclusions for things like the node_modules folder.  This would bring it into line with the new csproj format [Reference](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#default-compilation-includes-in-net-core-projects)

**Comment by paulvanbrenk** [comment]
thanks, we're tracking this in #1548 

But this is going to take a while, since it's a lot of work just to get to parity... and we prefer to add new features or fix bugs.
