### ISSUE TITLE
Requires Web Developer Tools in VS 2013

### ISSUE THREAD

**Issue by LegalizeAdulthood** [Microsoft/nodejstools#178]
I installed a minimal C++ installation of VS 2013.  When I installed the NodeJS tools, it didn't complain, but the new project wizard from existing code silently failed top open my project.  When I manually attempted to open it, VS informed me that I needed the Web Developer Tools installed.  The NodeJS installer should detect the absence of this optional feature and require it as a prerequisite before installing.  Apparently this is needed even when I'm doing a console NodeJS application and not a web application.

**Comment by mousetraps** [comment]
agreed, it's super frustrating to run into this. we should probably just check for a relevant file in ```C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions``` during setup

**Comment by mjbvz** [comment]
This has been fixed for VS15. When installed through the VS installer, we now automatically pull in all dependencies, including webtools. You try this out [by installing VS15](https://www.visualstudio.com/en-us/news/releasenotes/vs15-relnotes) and selecing the Node.js workload.

Thanks.
