### ISSUE TITLE
High CPU usage from Node.js: Server-Side Javascript process in Visual studio

### ISSUE THREAD

**Issue by IronSean** [Microsoft/nodejstools#1788]
Note: This may be the wrong place for this, please let me know if so.

##### Expected Behavior 
There is no Node.js or TypeScript in my app, so I would expect Node to not even be running. Or if it is running, to be using very few resources.

##### Actual Behavior 
The Node.exe thread arbitrarily switches from low cpu usage to 80-100% usage of a Single Core for 10-15 seconds, spinning up laptop fans and using power.

- NTVS Version: 1.4.10918.1
- Visual Studio Version: 15.4.4
- Node.js Version: 8.9.7

##### Steps to Reproduce
1. Open Visual Studio
2. Run any .Net Application, debug it, stop debugging it, the node exe will be running in all cases.

The node.exe, based on what I've read online, seems to be running the Typscript language features 
as disabling TypeScript support within Visual Studio will eliminate the CPU usage.

**Comment by paulvanbrenk** [comment]
In the Task Manager, in the details view, you can add the column for the Command line. Can you post the command line for the offending node process here?

Also, the TypeScript language service is also used for JavaScript files.

**Comment by IronSean** [comment]
`"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\x86\node.exe" --expose-gc "C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.3\tsserver.js" --cancellationPipeName \\.\pipe\tsserver-cancellation-12800 --useSingleInferredProject --locale en-US --typingSafeListLocation "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TypeScript\typingSafeList.json" --allowLocalPluginLoads --eventPort 64462`

*Note*: There could be some typos, Task manager doesn't allow you to copy and paste so I had to transcribe it...

**Comment by paulvanbrenk** [comment]
Yep, that's the TypeScript/JavaScript language service. I know we are aware of issues there, and are working on making it more performant, but I have a hard time finding a specific issue which tracks it. 

Since this repo is specifically for the Node Tools workload, and your issue doesn't seem to touch that at all, can you open an issue on the [TypeScript GitHub repo](https://github.com/Microsoft/typescript)?
