### ISSUE TITLE
Wildcards not supported in "files" property of tsconfig.json

### ISSUE THREAD

**Issue by john-cullen** [Microsoft/nodejstools#1796]
##### Expected Behavior 
All files in subdirectories with the .ts extension are compiled.

Building in Visual Studio Code correctly compiles every file.

##### Actual Behavior 
Build error `C:/Users/john/Code/bwf/src/**/*.ts' not found.`

- NTVS Version: 1.4.10918.1
- Visual Studio Version: 15.4.5
- Node.js Version: 8.9.1

##### Steps to Reproduce
1. Try to use wildcards in a "files" property of tsconfig.json, `"files": [ "./src/**/*.ts" ]`

**Comment by paulvanbrenk** [comment]
This is by design, you want to use the `include` property. See here: http://www.typescriptlang.org/docs/handbook/tsconfig-json.html

Not sure why this works in VS Code, but that seems like a [TypeScript](https://github.com/microsoft/typescript) issue.
