### ISSUE TITLE
No completions for built-in Buffer class without require

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#182]
We provide proper completions when you ```require('buffer')```, but it is also possible to use Buffer without the ```require('buffer')``` incantation.

**Comment by mousetraps** [comment]
Scratch that, we don't provide proper completions. For instance ```Buffer.isBuffer``` is not present in the completion list.

**Comment by mjbvz** [comment]
Fixed in NTVS 1.2 Alpha with ES6 Intellisense Preview

![image](https://cloud.githubusercontent.com/assets/12821956/14691539/9c7f7cc2-0706-11e6-8f4f-974fef6d3955.png)
