### ISSUE TITLE
Visual Studio 2017 default eslint ignore files in sub directory under project root folder.

### ISSUE THREAD

**Issue by xs2bharat** [Microsoft/nodejstools#1821]
##### Expected Behavior 
Visual studio should analyze all *.js files whether they are under project root or in sub-directories.. For e.g. under <Project root>/lib/*.js files are ignored.

##### Actual Behavior 
Visual studio only analyze *.js files under project root.

- NTVS Version: Node.js Tools 1.4.11025.7
- Visual Studio Version: VS 2017 15.5.2
- Node.js Version: 8.7.0

##### Steps to Reproduce
1. npm install eslint@latest from "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External" directory 
2. Update PATH environment variable to add this path "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External"
3. Open VS 2017 njsproj
4. Add .eslintrc file and .eslintignore file under project root
4. Open any file under project root, you will see eslint errors and warnings but when you open any file under sub directory for e.g. under "lib", no errors or warning are visible even though when you run eslint through cmd, it shows valid warnings and errors.

**Comment by paulvanbrenk** [comment]
Looks like this is an issue with the eslint implementation in Visual Studio, and not limited to the node.js tools. 

Please open an issue using the Visual Studio Feedback tool. or in the [Visual Studio Feedback Community](https://developercommunity.visualstudio.com/)
