### ISSUE TITLE
Exception from require module isn't printed

### ISSUE THREAD

**Issue by wtyp** [Microsoft/nodejstools#1831]
When you get a syntax error from an included module, you get an exception breakpoint in vm.js (createScript function) but the exception is not written to the console.
You can simply reproduce it by creating app.js with the following code:

`const a = require('./test')`
inside test.js just put a syntax error, for example: `)`

The exception should be written to the console, instead you only get a breakpoint in vm.js.

- Visual Studio Version: 2017 15.5.2
- Node.js Version: 8.9.1

**Comment by naphtul** [comment]
Yes, I've noticed the same issue!

**Comment by paulvanbrenk** [comment]
Created a VS Feedback ticket to track this, since the debugger team owns this component. (And they prefer that).

https://developercommunity.visualstudio.com/content/problem/180453/exception-from-require-module-isnt-printed.html
