### ISSUE TITLE
Breakpoint not hit on required modules

### ISSUE THREAD

**Issue by wtyp** [Microsoft/nodejstools#1837]
Breakpoint are not hit when using required modules, see the following example:
1. Put the following code in app.js:
`const test = require('./test')`
2. Put the following code in test.js:
```
let test3 = function () {
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			resolve(true)
		}, 1000)
	})
}

let	test2 = async function () {
	let a = await test3()
}


let test = async function () {
	console.log('start')
	let result = await test2()
	console.log('end')
}
test()
````

3. Put a breakpoint on console.log('start') in test.js
4. Run the app

Breakpoint is not hit.

Visual Studio Version: 2017 15.5.2
Node.js Version: 8.9.1

**Comment by paulvanbrenk** [comment]
Created a [feedback item](https://developercommunity.visualstudio.com/content/problem/190181/breakpoint-not-hit-on-required-modules.html), since the responsible team prefers that.
