### ISSUE TITLE
Live Editing Not Working (Edit and Continue)

### ISSUE THREAD

**Issue by timwillhack** [Microsoft/nodejstools#1838]
##### Expected Behavior 
Live Editing Working (Edit then Continue)
##### Actual Behavior 
If I edit any code and hit save it acts strange, doesn't break in the editor where it says it is in code, I've changed some code that just outputs a string differently and that doesn't output with the changes I've made when it runs that line.

- NTVS Version:
1.4.11025.7
- Visual Studio Version: 
15.5.4
- Node.js Version: 
8.9.4

##### Steps to Reproduce
1. create new node project, import one js file. save, exit reopen (just in case)
2. put a break point at the start of the file on a line with something like var nothing =0;
3. put a line after like console.log('hello')
4.  run debug and wait for it to break
5.  change 'hello' to 'world' 
6.  f10, f10 and look at the output in the window - its still 'hello'

**Comment by paulvanbrenk** [comment]
Edit and Continue is currently not supported. Though I can't comment on any timeline at this time.

**Comment by timwillhack** [comment]
It was working in the past though no?  I've seen a ton of videos talking about it and showing it working.  Thank you

**Comment by paulvanbrenk** [comment]
Yeah, it worked in Node 6

**Comment by MattMinke** [comment]
Is there any desire for this feature to be fixed.
