### ISSUE TITLE
Attach Debugger to Executing Node.js Script, Debugger Hangs

### ISSUE THREAD

**Issue by ezolotko** [Microsoft/nodejstools#1840]
##### Expected Behavior 
Setting a breakpoint in the loop leads to a breakpoint hit
OR "Break All" breaks the execution, pointing to a code line in the loop

##### Actual Behavior 
"Break All" does nothing, breakpoints not hit, all other debugger commands not available (except "Stop Debugging").

- NTVS Version: 1.4.11025.7
- Visual Studio Version: 15.5.5
- Node.js Version: 8.9.4

##### Steps to Reproduce
1. Create file named app.js with the following content:
```
console.log("Hello");

i = 0;
while (true) {
    console.log(i);
    console.log(i);
    console.log(i);

    if (i % 2 == 0)
        console.log("e");
    else
        console.log("odd");

    i++;
}
```

2. Run the command: `node --inspect=4545 app.js`

3. In VS2017, select Debug/Attach To Process, select WebKit websocket connection type, use ws://localhost:4545 as the connection target, click Refresh, select the found node instance, click Attach.

Initially reproduced [here](https://github.com/Microsoft/ClearScript/issues/43).

**Comment by paulvanbrenk** [comment]
Created a [Feedback ticket](https://developercommunity.visualstudio.com/content/problem/190171/attach-debugger-to-executing-nodejs-script-debugge.html) on the VS Developer Community, since the responsible team prefers that.
