### ISSUE TITLE
Feature request: Customizing / adding custom property pages to projects.

### ISSUE THREAD

**Issue by MichalOleszczuk** [Microsoft/nodejstools#1852]
##### Expected Behavior 
Adding custom property tab with properties like
https://www.codeproject.com/Articles/881782/Creating-custom-UI-property-pages-sheets-in-Visual
```
<ItemGroup>
  <PropertyPageSchema Include="boost.xml" >
    <Context>Project</Context>
  </PropertyPageSchema>
</ItemGroup>
```

Its essential for extending nodejs projects if someone want's to create new project wizard based on NTVS.
##### Actual Behavior 
You are unable to extend properties page from xml file?
I was unable to find any documentation on this topic.

- NTVS Version: Node.js Tools 1.4.11025.7
- Visual Studio Version:  Visual Studio Professional 2017
- Node.js Version: 8.9.1

##### Steps to Reproduce
It would be great if you could actually just include xml file and the properties will be implemented like in **codeproject** example from 2015.

**Comment by paulvanbrenk** [comment]
Do you any specific properties in mind, what would it allow you to do what you currently can not?

**Comment by MichalOleszczuk** [comment]
We are creating custom extension with project wizard based on NTVS. We need to specify for example "developer id", "private key path" or OVA server adress. And that's just the beginning.

We will be creating lot of custom variables for crypto-signing and so on.

Currently i can not use project properties to store that data for every project. And the valid way to do it is by project properties.

**Comment by paulvanbrenk** [comment]
You are going to have a hard time doing that with NTVS, since we currently don't have any extensibility points (we just didn't design for that). If we move to a new project system we'll certainly keep that in mind, but I don't expect that happen anytime soon. (Think 2019 rather than 2018)

**Comment by MichalOleszczuk** [comment]
Ok i understand. Thanks for the answer.

**Comment by paulvanbrenk** [comment]
Closing this. This is tracked in the design document for the new project system
