### ISSUE TITLE
NPM package list GUI

### ISSUE THREAD

**Issue by MgSam** [Microsoft/nodejstools#1853]
Is there a way to get the NPM package list for non-NodeJS project types? We have a ASP.NET MVC project that is using Angular 2+ (and thus depends on NPM). I can't find any way to get a list of NPM references in Visual Studio (besides just opening package.json, obviously).

FWIW, I think this feature should, out-of-the-box, work the same as it does for NuGet packages (or Bower packages, though that should really be removed now that Bower is deprecated).

Thanks.

**Comment by paulvanbrenk** [comment]
I agree, but since this seems more an issue with the ASP.NET side, can you file an issue here: https://developercommunity.visualstudio.com/spaces/8/index.html

That gives it more visibility.

**Comment by MgSam** [comment]
@paulvanbrenk 
Are you serious? A post on the VS forums will have more visibility? I'm pretty sure that's where posts go to die. 

This repo is where the NPM tooling was developed, no? You work for Microsoft. Please @mention the correct people or point me to a more appropriate repo and I'll open a separate issue.

**Comment by paulvanbrenk** [comment]
Yes, the developer community is where the ASP.NET team collects their feedback.

**Comment by EnricoReich** [comment]
Could be any progress achieved here?
