### ISSUE TITLE
IntelliSense not removing functions from completion list when require is commented out.

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#186]
**helpers/index.js**
```javascript
String.prototype.trimZeros = function () {
	return this.replace(/\u0000/g, '');
}
```

**app.js**
```javascript
require('./helpers')
"".trimZeros // we expect completions for this function
```

However, when require('./helpers') is commented out, trimZeros incorrectly remains in the completions list even though analysis has completed.

**Comment by mjbvz** [comment]
In ES6 preview Intellisense, this case (extending the prototype) does not seem to be picked up at all.

**Comment by mousetraps** [comment]
Yeah.... I have a feeling that's going to happen a lot....

**Comment by mjbvz** [comment]
Closing since we have now fully moved to ES6 / Typescript backed editor. This specific IntelliSense use case is no longer supported
