### ISSUE TITLE
[loc][Query][Node.js] Localizability of 0; "6001" // Debug launch configuration for Node.js

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/nodejstools#1876]
Hi, 
we have a question from a translator. Could you help please?

Source:
Debug launch configuration for Node.js

File Name:
localize\ENU\Microsoft.NodejsTools.dll

Resource ID:
0; "6001"

Query:
Please confirm that Debug is a verb here

**Comment by paulvanbrenk** [comment]
I changed the description in the file. https://github.com/Microsoft/nodejstools/pull/1879
