### ISSUE TITLE
NTVS Web Code analysis menu missing from Visual Studio 15.6

### ISSUE THREAD

**Issue by fehrm** [Microsoft/nodejstools#1906]
##### Expected Behavior 
Menu is shown:
![image](https://user-images.githubusercontent.com/8399245/37716454-df920846-2d1e-11e8-8635-de7d27f18824.png)

This works in combination with Visual Studio 2017 15.5.7 and NTVS version 1.4.11025.7

##### Actual Behavior 
As of Visual Studio 15.6.X the menu is missing. I reinstalled the Node.js workflow several times.
![image](https://user-images.githubusercontent.com/8399245/37716581-21a9cdae-2d1f-11e8-8a6d-269fa1ba5f6a.png)

- NTVS Version: 1.4.11027.3
- Visual Studio Version: Microsoft Visual Studio Enterprise 2017 Version 15.6.3
- Node.js Version: 8.9.4

##### Steps to Reproduce
1. Upgrade Visual Studio to 15.6.X
2. Install Node.js workflow (in case it is missing)
3. Click Tools Menu at Top
4. Notice that the "Web Code analysis" sub-menu is missing.

##### General notes
I have reproduced this on three different machines, across Visual Studio (2017) Enterprise, Pro and Community. On all machines the submenu Web Code analysis disappears when Visual Studio is updated to the newest version of 15.6

**Comment by paulvanbrenk** [comment]
This is part of ASP.NET and not part of the Node Tools. (If it previously was installed with the Node Tools, that was an unintended side-effect).
