### ISSUE TITLE
incorrect formatting when function defined inside object block

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#191]
```javascript
var foo = {
	bar: function(arg) {<press enter here>
}
```

**result:**
```javascript
var foo = {
bar: function(arg) {
        <cursor>
}
```

**Comment by mousetraps** [comment]
This also occurs for any nested blocks (e.g. for) within the function.

**Comment by hoanhtien** [comment]
Not able to repro this issue.

**Comment by mjbvz** [comment]
I'm not able to repo this issue either. I tried playing around with the formatter settings  a but, but please reopen if you are still hitting this.
