### ISSUE TITLE
Array, Number, and maybe other constructors are not showing full list of completions

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#192]
Instead it is only showing ```Array()``` in the completion list.

**Comment by kant2002** [comment]
According to my research, this code somewhere in the [Nodejs\Product\Analysis\Analysis\GlobalBuilder.cs](https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Analysis/Analysis/GlobalBuilder.cs#L222)
