### ISSUE TITLE
SELECT Node version

### ISSUE THREAD

**Issue by jmaFinistereVar** [Microsoft/nodejstools#1920]
Hello,

I am using Visual 2017 for my typescript developments. I have two versions of Node installed on my PC:

- Node V4 in folder : C:\Program Files\nodejs
- Node V8 in folder : C:\Program Files\nodejs_V8\node-v8.9.3-win-x64

I try to swtich from one to the other through "Option / Tools / Web Package Management" but even when I select folder "C:\Program Files\nodejs_V8\node-v8.9.3-win-x64" at the top of the list it is always Node V4 that is running. I would like to know how I can select Node v8 ?

Note: this question has also been asked on [Microsoft forum](https://social.msdn.microsoft.com/Forums/fr-FR/59dea25a-c338-4e19-a262-9ae1146b1f19/set-node-version?forum=vssetup)

**Comment by jmaFinistereVar** [comment]
Thank you very much for your answer.
I updated the node version but I ran into a new probem : when trying to install `sqlite3` with the options `--build-from-source --scripts-prepend-node-path="C:\\Program Files\\nodejs_V8\\node-v8.9.3-win-x64\\node.exe"` it failed with the message

> npm WARN invalid config scripts-prepend-node-path="C:\\\\Program Files\\\\nodejs_V8\\\\node-v8.9.3-win-x64\\\\node.exe"
> sqlite3@4.0.0 install C:\Users\jerome.marquet\Documents\workSpace\services\isogeo-sdk-ts\NodejsConsoleApp1\node_modules\sqlite3
npm WARN lifecycle npm is using C:\Program Files\nodejs_V8\node-v8.9.3-win-x64\node.exe but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> node-pre-gyp install --fallback-to-build
'node' n'est pas reconnu en tant que commande interne
ou externe, un programme executable ou un fichier de commandes.

So my ew question is do you know how to use the `--scripts-prepend-node-path` option ? Or is it broken on Visual 2017 ?

Best regards 
![image](https://user-images.githubusercontent.com/14360444/38725494-c7bbb7e4-3f07-11e8-9882-57264f4d709e.png)

**Comment by paulvanbrenk** [comment]
@jmaFinistereVar glad you figured it out.
