### ISSUE TITLE
[loc][Query][Node.js] Localizability of 0; "NodeHeader"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/nodejstools#1921]
Hi,
we have a question from a translator. Could you help please?

Source:
Node

File Name:
localize\ENU\Microsoft.NodejsTools.dll

Resource ID:
0; "NodeHeader"

Query:
We assume this is the general concept here, please confirm or advise.

**Comment by paulvanbrenk** [comment]
Yeah, that just says "Node.js" and doesn't need to be translated.

**Comment by PDostalek** [comment]
Thanks for confirmation
