### ISSUE TITLE
Crash on debugging a test

### ISSUE THREAD

**Issue by ashwini-ms** [Microsoft/nodejstools#1941]
##### Expected Behavior 
Able to debug the tests
##### Actual Behavior 
crash
![image](https://user-images.githubusercontent.com/30875507/39152473-59d98604-46fd-11e8-97ce-c04e385542a0.png)

- NTVS Version: 1.3
- Visual Studio Version: 2017
- Node.js Version: 

##### Steps to Reproduce
1. Open njsproj in visual studio
2.  debug any tests

**Comment by paulvanbrenk** [comment]
Is that the correct version of Visual Studio? if it is 2017, can you make sure you're on Upate 6 (or newer).

I am not able to reproduce.
