### ISSUE TITLE
VS2015 go to definition does not work after renaming file

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#195]
This is either unrelated, or may be a simpler repro of #18. Using a Node.js console app...

**1.2.js**
```javascript
var b = 'totally awesome'



console.log(b);
```

F12 on ```b``` yields:

![image](https://cloud.githubusercontent.com/assets/762848/8050674/1c9ac7ca-0e26-11e5-885a-f5d59b14d1a9.png)

Similarly, after shift-F12, clicking on any of the results fails to navigate to the proper location.

**Comment by mousetraps** [comment]
Nevermind... this has nothing to do with #35 or dots in the filename - this is a rename bug...

**Comment by mousetraps** [comment]
We're not updating the analysis cache after rename, which is causing go-to-definition to attempt to navigate to the wrong file.

**Comment by kant2002** [comment]
Also issue appears if you rename and have document window with renamed file opened. When close and reopen window after rename, issue does not appears.

If I understand correctly, JS AST attached to each opened document, and only that part not updated when rename occurs, for the actual analysis I see code which reanalyze new file and remove old one.

**Comment by mjbvz** [comment]
Fixes with NTVS 1.2 on ES6 Preview Intellisense.
