### ISSUE TITLE
Remote debugging on raspberry Pi

### ISSUE THREAD

**Issue by apostrophesoftware** [Microsoft/nodejstools#1952]
Is it possible to get the Node js remote debug feature working on the Raspberry Pi using Visual Studio 2017?  I have looked at the documentation for Node js tools and the documents state they are out of date and that the features are available directly in Visual Studio 2017.  I cannot get it to work and cannot see the tools->Node.js tools\Remote Debug Proxy Menu option.

I am using Visual Studio 2017 version 15.7 with the Node js workflow installed.

**Comment by paulvanbrenk** [comment]
Remote debugging has been broken for a while, and instead of further confusing users we decided to remove that menu option. 

It's on the list of features we need to investigate if there's enough users that want/need this. For now I would suggest using VS Code.
