### ISSUE TITLE
Improve Debugger Attaching to child process experience 

### ISSUE THREAD

**Issue by ValYouW** [Microsoft/nodejstools#197]
Hi,

(This is not a bug, but a feature request).
In my code I have a master process that forks a child process, the master process debug port is 5858, for the child process I set the debug port to 5859.
VS is attaching to port 5858, but then the child process hangs as it is waiting for a debugger to attach to its debug port...

`server.js`:

``` js
var cp = require('child_process'),
    path = require('path');

var WORKER_PATH = path.resolve(__dirname, 'worker.js');
var WORKER_ARGS = [];

console.log('Master starting...');

setTimeout(function () {
    console.log('Forking worker');

    var execArgv = process.execArgv.slice();
    var debugPort = process.debugPort + 1;
    for (var i = 0; i < execArgv.length; i++) {
        var match = execArgv[i].match(/^(--debug|--debug-brk)(=\d+)?$/);
        if (match) {
            execArgv[i] = match[1] + '=' + debugPort;
            break;
        }
    }

    var options = { env: process.env, silent: false, execArgv: execArgv };
    var nodeFork = cp.fork(WORKER_PATH, WORKER_ARGS, options);
    console.log('Forked worker, pid:', nodeFork.pid);
}, 1000);
```

`worker.js`

``` js
console.log('Worker is starting, pid:', process.pid);
setInterval(function () { 
    console.log('Worker still alive, pid:', process.pid);
}, 2000);
```

The output I see:
![image](https://cloud.githubusercontent.com/assets/4539636/8053596/d30ac630-0e9a-11e5-9f55-8bd690411fff.png)

**Comment by zam6ak** [comment]
Any updates on this?
I also noticed if you use cluster the debugger does not attach to workers and the entire experience if borked...

**Comment by mousetraps** [comment]
Thanks for bumping this. Eventually we hope to streamline the process, but here's what you can do in the meantime. 

In VS, you can actually attach to multiple ports at a time. So as soon as you hit...
![image](https://cloud.githubusercontent.com/assets/762848/8258667/99e7007a-166b-11e5-8b6a-9ea153a232a7.png)

You can do ```Debug > Attach to Process...``` (```Ctrl + Alt + P```)
![image](https://cloud.githubusercontent.com/assets/762848/8258686/c313d612-166b-11e5-9522-bd34ed420fd0.png)

Specify the following options in the dialog:
* **Transport:** Node.js Remote Debugging
* **Qualifier:** localhost:5859

Then press **Refresh**, and you'll see the process appear in the list of Available Processes.
![image](https://cloud.githubusercontent.com/assets/762848/8258725/17622822-166c-11e5-9c16-c65ca14cbb55.png)

Then when you select **Attach**, you'll be able to continue and hit breakpoints in the worker. 
![image](https://cloud.githubusercontent.com/assets/762848/8258785/a1594736-166c-11e5-8d83-200c446e8ab9.png)

If you're attaching to multiple processes, the **Process** dropdown will let you know where you are, and help you move between them. 
![image](https://cloud.githubusercontent.com/assets/762848/8258823/fdd3aa74-166c-11e5-8f89-60a30aba6ef0.png)

Let me know if you have any more questions - we've been meaning to document this specific scenario for some time.

**Comment by ValYouW** [comment]
Thx. I have tried the regular "attach to process" method before opening this issue and it didn't work, I'll try to use the correct transport now... 
What about profiling child processes? should it work regularly or a tweak is needed? 
thanks again...

**Comment by mousetraps** [comment]
Yeah, that should work fine. There's nothing too special going on there. Essentially, we run 
```node --prof server.js``` under the covers, grab the v8 log, and sprinkle in some VS reporting tools to make it more useful. You can also drag in an existing log. 
https://github.com/Microsoft/nodejstools/wiki/Profiling

**Comment by mousetraps** [comment]
Also... if you get the chance to play around with it further and have any ideas, then now's the perfect time to bring them up - turns out we have a meeting with some of the VS profiling/diagnostics folks about potential improvements in this area early next week!

**Comment by ValYouW** [comment]
Hi,

The debugging is working great after attaching using the "Node.js remote debugging" transport.
Profiling is not working so well (actually at all) for child processes...

**Comment by mousetraps** [comment]
@ValYouW are samples collected properly if you run ```node --prof myScript.js``` in the command line? If not, then that is an issue with node/v8, and we unfortunately can't do anything about it short of writing our own profiling hooks.

**Comment by deandob** [comment]
Hi, any chance of seeing the streamlining of attaching to multiple child processes automatically while debugging? I have a large node.js app using a plugin pattern that I have just split into separate child_processes because any instability in a plugin will bring down the whole process. All working well (except for using a bit more memory) but its a real pain to debug the child plugins manually. 

Ideally if VS monitors child_process fork/spawn and automatically attaches to the child PID that would be sweet!

**Comment by JohnRucker** [comment]
How is this a closed issue.  I see the exact same thing on 9/2/2016

**Comment by mjbvz** [comment]
@JohnRucker This issue is open and tracking possible improvements that could be made to debugging node child process.

To debug child processes, the current behavior of NTVS is no different from what node normally does ([see this issue and explanation](https://github.com/Microsoft/nodejstools/issues/575#issuecomment-235769337)). We'd like to improve this, and would happily accept any contributions in this area.

**Comment by VooVoo01** [comment]
“Attach to process…” works fine for remote debugging, but it is not convenient to attach each child process every time after running the application.
I use the solution based on [Visual Commander Extension](https://vlasovstudio.com/visual-commander/index.html).  You can create the buttons on the tools bar and attach all child process with one click.

![default](https://cloud.githubusercontent.com/assets/22634158/22261293/0d5fd686-e275-11e6-8760-7ba689a4a0fa.png)

After installing free edition of Visual Commander Extension choose _VCmd –> Commands…_
  and create two small scripts on Visual Basic with code below (use your own addresses and ports):
1. For quick attach to one process.
```
Imports EnvDTE
Imports EnvDTE80
Imports Microsoft.VisualBasic

Public Class C
	Implements VisualCommanderExt.ICommand

	Sub Run(DTE As EnvDTE80.DTE2, package As Microsoft.VisualStudio.Shell.Package) Implements VisualCommanderExt.ICommand.Run
          Dim dbg2 As EnvDTE80.Debugger2 = DTE.Debugger
          Dim trans As EnvDTE80.Transport = dbg2.Transports.Item("Node.js remote debugging")
          Dim processRemote As EnvDTE80.Process2

	   Dim mPort As String = InputBox( "Debug port?", "tcp://192.168.100.10:****")	

	   If mPort <> "" Then
					' your remote address or 127.0.0.1
          	Dim transportQualifier = "tcp://192.168.100.10:" & mPort & "/"
          	Dim processesRemote = dbg2.GetProcesses(trans, transportQualifier)
	   	processesRemote.Item("node.exe").Attach()
	   End If
	End Sub

End Class

```

2. For quick attach to all processes.
```
Imports EnvDTE
Imports EnvDTE80
Imports Microsoft.VisualBasic

Public Class C
	Implements VisualCommanderExt.ICommand
	Sub Run(DTE As EnvDTE80.DTE2, package As Microsoft.VisualStudio.Shell.Package) Implements VisualCommanderExt.ICommand.Run

 	Try
          Dim dbg2 As EnvDTE80.Debugger2 = DTE.Debugger
          Dim trans As EnvDTE80.Transport = dbg2.Transports.Item("Node.js remote debugging")

          Dim processRemote As EnvDTE80.Process2
	   Dim transportQualifier As String

		' your ports of child processes
          For mPort As Integer = 8560 To 8562
		' your remote address or 127.0.0.1
            transportQualifier = "tcp://192.168.100.10:" & CStr(mPort) & "/"
            Dim processesRemote = dbg2.GetProcesses(trans, transportQualifier)
	     processesRemote.Item("node.exe").Attach()
          Next

	Catch ex As System.Exception
	   MsgBox(ex.Message)
    	End Try

	End Sub
End Class
```

Add them into your tools bar using:
_Service -> Customize -> Commands -> Toolbar -> Add command... -> VCmd_

You will see the list of VCmd commands, choose your own.

**Comment by mousetraps** [comment]
@VooVoo01 that's awesome! thanks for sharing!

**Comment by VooVoo01** [comment]
“Attach to process…” does not work for remote debugging in VS2015 with node.js v.8 and higher if we are using the command '--inspect-port=5860' _(for example)_.
Are there any solutions for debugging child processes with VS2015 and node.js v.8?

**Comment by paulvanbrenk** [comment]
@VooVoo01 unfortunately Node 8 debugging will not be support in VS 2015.

[Visual Studio 2017 Update 3](https://www.visualstudio.com/downloads/) works great with Node 8 though.

**Comment by paulvanbrenk** [comment]
Tracking this in an internal tracker, since this is an issue in the node 8 debugger, which doesn't use the GitHub issue tracker.
