### ISSUE TITLE
Debug mocha test with nodejs 8 doesn't work

### ISSUE THREAD

**Issue by Frahmer** [Microsoft/nodejstools#1977]
##### Expected Behavior 
Hit breakpoint in debug modus

##### Actual Behavior 
Debug ends without hit breakpoint

- NTVS Version: 1.4.11027.3
- Visual Studio Version: 2017 15.7.1
- Node.js Version: 8 & 10 tested

##### Steps to Reproduce
1. create new nodejs project
2. add mocha to project: npm install mocha --save
3. add mocha test file (.js or .ts make no different)
4. build project
5. add breakpoint in test file
6. start debugging from test (test with breakpoint) in test explorer

It works with nodejs 7 as expected.

**Comment by paulvanbrenk** [comment]
Can you create a bug on https://developercommunity.visualstudio.com/ the team responsible prefers to check issues there, and if a customer creates a bug it has more leverage than when I do it.

**Comment by Frahmer** [comment]
Ok, i have created a bug message [here](https://developercommunity.visualstudio.com/content/problem/263180/debug-mocha-test-with-nodejs-8-doesnt-work.html)

**Comment by paulvanbrenk** [comment]
Closing since this is tracked in the developer community
