### ISSUE TITLE
Nodejs debugging doesn't work with VS 2017 15.7.1 and nodejs 8

### ISSUE THREAD

**Issue by Frahmer** [Microsoft/nodejstools#1978]
##### Expected Behavior 
debug nodejs project with nodejs 8

##### Actual Behavior 
Message promt with content "Attempting to add script that was already added '...\node_modules\bbcode-parser\bbTag.js'!"

- NTVS Version: 1.4.11027.3
- Visual Studio Version: 2017 15.7.1
- Node.js Version: 8 & 10 tested

##### Steps to Reproduce
1. press debug button in visual studio

Same behavior like [developercommunity.visualstudio.com](https://developercommunity.visualstudio.com/content/problem/250222/node-debugging-gives-attempting-to-add-script-that.html) - I don't know if it the same cause.
My Project has many npm modules (~32), with Visual Studio 15.6.X it works as expected.
With nodejs 6 it works, but my project need nodejs 8 >.<

**Comment by paulvanbrenk** [comment]
Yeah, that the same issue.  It's tracked by the debugging team using the issue you linked.
