### ISSUE TITLE
issue with debugging

### ISSUE THREAD

**Issue by megadrojatel** [Microsoft/nodejstools#199]
From time to time, when i start debug my application, after pressing on F5 or Start Debugging, the debug started and seems that the program running, but it not running (i have some console.log() prints lines in a code, nothing printing in cmd) and not stopping on breakpoints at all. 
After restarting of visual studio, its run and debugging work perfectly 

My machine is: 
win8.1 64bit 
vs2013 premium Update 4 

Best Regard 
Denis

**Comment by mousetraps** [comment]
Did you try the latest Dev build? https://github.com/Microsoft/nodejstools/releases

Fixes a race condition in debugging that caused similar symptoms

**Comment by AcousticGuitar** [comment]
I too have had this issue, it's almost as if Node itself doesn't "kick-in" as it's very early in the debugging loading or scheduling of the run...

**Comment by mousetraps** [comment]
Have you tried the latest Dev build I linked to above?

**Comment by megadrojatel** [comment]
Has not tried yet, I have to finish my project.
I will try in a week and a half. 
Tnx

**Comment by pke** [comment]
Is there a dev build available for VS 2013 too? Not all companies run their development on Beta IDEs

**Comment by mousetraps** [comment]
@pke yes, see the downloads in the link above. We currently have Dev builds available for 2012, 2013, and 2015.

**Comment by mousetraps** [comment]
Closing this issue as a duplicate. Please post at #246 if you're still running into issues with the latest builds.
