### ISSUE TITLE
Remote Debugging Doesn't Work

### ISSUE THREAD

**Issue by NickSchweitzer** [Microsoft/nodejstools#1994]
##### Expected Behavior 
Able to remotely debug a Node.js application running on a Raspberry Pi. I have seen this same error reported multiple times in this space, but I have yet to see anyone with a solution, and every time the issues is closed. Hopefully there is enough detail here for you to provide a solution.

I also noticed that this page (https://github.com/Microsoft/nodejstools/wiki/Remote-Debugging-Node.js-running-on-Linux) has the following note:

🎵Note: This documentation is outdated at this point, especially when using the Node tools in Visual Studio 2017. We're working on update docs, and will redirect you to those when they're ready.

I could not find ANY updated documentation, so if there is a new process, then the documentation really needs to be updated, because this is extremely frustrating.

##### Actual Behavior 

- NTVS Version: 1.4.11027.3
- Visual Studio Version: 15.7.4
- Node.js Version: 8.11.3

##### Steps to Reproduce
1. Deployed my nodejs application to Raspberry Pi
2. SSH to Raspberry Pi and run following command:
node RemoteDebug.js -waitforattach app.js
3. In Visual Studio, open Debug -> Attach to Process
Connection Type: node.js remote debugging
Connection Target: ip address of Raspberry Pi port 5858
Click Refresh, then double click on process in Available Process list box

The following error message box appears in Visual Studio
---------------------------
Microsoft Visual Studio
---------------------------
Unable to attach to the process. Operation not supported. Unknown error: 0x80004005.
---------------------------
OK   
---------------------------

The following appears in the SSH console of the Raspberry Pi:
node RemoteDebug.js -waitforattach app.js
node: /usr/bin/node
scriptToDebug: app.js
passThroughArgs:
localClientPort: localhost:5859
remoteServerPort: undefined:5858
startDebuggeeOnRemoteConnect: true
startDebuggeeBrokenAtEntryPoint: false
remoteServerSocket listening for connection
remoteServerSocket connected
Debuggee started: /usr/bin/node --debug=5859 app.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:5859
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

**Comment by paulvanbrenk** [comment]
Try debugging using the webkit websocket connection type. The node remote debugging only supports node versions before 8.

**Comment by NickSchweitzer** [comment]
Are there instructions on how to do this? Is it just a matter or changing the connection type, but you still start the app the same way using RemoteDebug.js?

**Comment by paulvanbrenk** [comment]
No, simply starting the app with `--inspect` should work.

**Comment by NickSchweitzer** [comment]
Still doesn't work. 

I started the app with the following command:
sudo node --inspect-brk app.js
Debugger listening on ws://127.0.0.1:9229/154f76e5-de02-45f4-9b03-cf56ba7cffb2
For help see https://nodejs.org/en/docs/inspector

Then in VS2017, I chose "Webkit websocket (no authentication)" as the Connection Type, and the IP address of the Raspberry Pi as the Connection Target, and received the following error:

---------------------------
Microsoft Visual Studio
---------------------------
Unable to connect to 'http://192.168.31.219:9222/'.  An operation is not legal in the current state.
---------------------------
OK   
---------------------------

**Comment by paulvanbrenk** [comment]
It says:

Debugger listening on ws://127.0.0.1:**9229**/154f76e5-de02-45f4-9b03-cf56ba7cffb2

And VS is trying to connect to  'http://192.168.31.219:**9222**/' 

If you start with `--inspect-brk=9222` it should work. Can you connect with Chrome?

**Comment by NickSchweitzer** [comment]
I also attempted to create an ssh tunnel from my machine that has Visual Studio on it as described in this article:
https://nodejs.org/en/docs/guides/debugging-getting-started/#enabling-remote-debugging-scenarios

The results did not change

**Comment by digeff** [comment]
@NickSchweitzer  Could you please send us a screenshot of the Attach to Process dialog state just before you click the attach button that shows you the error message? Given that GitHub is public, please blank-out all the private or identifiable information of the screenshot before posting it.

Could you also please try to debug this same scenario with Chrome DevTools ( chrome://inspect/#devices ) and tell us what happens there?

Thanks!
