### ISSUE TITLE
Running Angular 6 app in VS 2017

### ISSUE THREAD

**Issue by vaindil** [Microsoft/nodejstools#1995]
Hello! Is it possible to run an Angular 6 app in VS 2017? I'm running 15.8 Preview 3, which has Node.js Tools `1.4.20606.1 Commit Hash:9d5755c0d5f08ad9c5e0051bedb602a3de834d3e`. Running an app with VS requires setting a startup file, but an Angular 6 app using angular-cli doesn't have a file like that. I can build and use everything else, so I can just manually call `ng serve`, but I figured I'd check if it's possible to do through VS itself.

Thank you!

**Comment by paulvanbrenk** [comment]
You can try this using the Open Folder support in VS, which supports running npm scripts from the context menu on `package.json`.

But for additional support we need to make a lot of changes to the project system, which we're considering but will take some time.
