### ISSUE TITLE
Add README.md file to repository

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#2]

**Comment by KevinRansom** [comment]
Sara,

If you submit a PR I can pull it until we can get the right permissions  sorted out.

Kevin

**Comment by mousetraps** [comment]
They actually added me to the visualfsharp team (surprise!), so we should be good for now. Not sure how to create a team - I can sort that out on Monday - but feel free to transfer ownership to me. Unless you guys want to adopt NTVS, that is. :)
