### ISSUE TITLE
Indenting options use JavaScript settings, not Node.js

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#20]
Problematic line:
``` csharp
            var props = dte.get_Properties("TextEditor", "JavaScript");
```

**Comment by SteveALee** [comment]
This is not the behaviour I am seeing. 

I spent ages wondering why my changes to the Editor Tabs for Javascript did nothing in my server.js file! Then I found the node settings :)

**Comment by mousetraps** [comment]
This is only for the indenting options (block vs smart indent vs. None). So now that you've figured out that whole node vs. JavaScript thing, your indenting options are actually in JavaScript!

**Comment by mousetraps** [comment]
And The tabs vs. Spaces and relevant options are still in Node

**Comment by SteveALee** [comment]
I've got it!
