### ISSUE TITLE
Is it possible to pass command line arguments to node for tests?

### ISSUE THREAD

**Issue by robbie-mac** [Microsoft/nodejstools#2001]
I'm playing around with a test framework making use of es2015 modules. And I want to see the results in the test explorer, in VS 2017 (15.7.5) with NTVS (1.4.11027.3)

As of node 10.6, calling an es2015 module from a cjs script requires the use of import(), which requires the command line argument --experimental-modules.

So how do I go about passing those arguments, or is it even possible?

**Comment by paulvanbrenk** [comment]
That's currently not possible. We'll take this into account for future releases.

**Comment by robbie-mac** [comment]
Thanks for the quick answer. Closing for now. I'm not much of a C# programmer but this might be a good first project for me.

**Comment by paulvanbrenk** [comment]
Yeah, I think it wouldn't be too hard. 

I would add another property to the project file similar to the ones we recently introduced for test framework and test root. The thing to watch out for, are arguments which would cause the node process to never complete, things like `watch` etc...

**Comment by robbie-mac** [comment]
Thanks again. Ill take a look.
