### ISSUE TITLE
LastActiveSolutionConfig stored in project file

### ISSUE THREAD

**Issue by kant2002** [microsoft/nodejstools#2034]
##### Expected Behavior 
LastActiveSolutionConfig values should not be stored in the project file

##### Actual Behavior 

I have following line in the file
```
<LastActiveSolutionConfig>Debug|Any CPU</LastActiveSolutionConfig>
```

##### Steps to Reproduce
1. Open existing project

**Comment by NoelAbrahams** [comment]
This is a significant interference as the project file is frequently modified by some process and keeps cropping up on source control.

**Comment by amcasey** [comment]
@PranavSenthilnathan Can you please check whether other projects store this in the .*proj.user file?

**Comment by rakatyal** [comment]
@kant2002: Do you see this value in the *.proj.user file or the main project file?

**Comment by kant2002** [comment]
@rakatyal it working on new project. Working in a sense that this is same behavior as in C#.

**Comment by rakatyal** [comment]
Thanks for confirming @kant2002.
