### ISSUE TITLE
"Wait for input when process exits" checked but console still closing instantly

### ISSUE THREAD

**Issue by Taraj2** [Microsoft/nodejstools#2048]
##### Expected Behavior 
console  should wait for press any key 

##### Actual Behavior 
console close instantly

- NTVS Version: 1.4.20802.1
- Visual Studio Version: 15.8.0
- Node.js Version: 10.9.0
##### Steps to Reproduce
check this options and run something
![obraz](https://user-images.githubusercontent.com/15572699/44220048-ce5d3900-a17d-11e8-9fff-fe4460a4ff99.png)

**Comment by jenokizm** [comment]
Hi, I have a similar problem. When an error occurs in the application and it falls with the exception, I have to read the error information in the console. Instead, unfortunately the console closes quickly and prevents me from reading the output. I use all the latest tools on Windows 7.

**Comment by amcasey** [comment]
This appears to be the same as #1998.
