### ISSUE TITLE
It's not possible to set a startup file without extension via context menu

### ISSUE THREAD

**Issue by skleeschulte** [Microsoft/nodejstools#205]
For files without file-extension the context menu in the solution explorer is missing the "Set as Node.js Startup File" option. This is needed for example when importing an existing express 4 project, or if the startup script is accidentally changed in an express 4 project created by visual studio. (The default startup file in express 4 is bin\www).

As a workaround it is possible to manually edit the "StartupFile" entry in the .njsproj-file to e.g. point to bin\www, which also is the setting used in newly created express 4 projects.

**Comment by mousetraps** [comment]
Done :smiley:

Fixed in #153 and available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)

**Comment by mousetraps** [comment]
And setting the startup file is overall much easier now - you can set it in the project properties page too now.
