### ISSUE TITLE
TestAdapter: Test discovery fails on test projects that contain a large number of test files

### ISSUE THREAD

**Issue by lukedgr** [Microsoft/nodejstools#2055]
We have Mocha Unit Test projects with 100-150 test files each, and test discovery now fails because the command line to execute node.js test discovery from C# exceeds the windows command line length limit of 8191 characters.

Tests were discovered without issue for the same test projects using Visual Studio Version 15.7.6 and NTVS 1.4.11027.3

##### Expected Behavior 
All Tests are discovered

##### Actual Behavior 
[8/29/2018 7:22:38 AM Error] The command line is too long. And no tests are visible for that project in the test explorer.

- NTVS Version: 1.4.20802.1 Commit Hash:97e1085d8b4b8e3e51c398e910177f87e86d135e
- Visual Studio Version: 15.8.2
- Node.js Version: All

##### Steps to Reproduce
1. Create a unit test project with enough test files so that the command line to execute node.js test discovery is > 8191 characters

##### Potential Fix: 
Write the list of test files to a file and pass that file path to the node.js process instead of passing all of the test files to the node.js process through the command line.

**Comment by armanio123** [comment]
Issue has been resolved. Thanks @lukedgr for fixing it.
