### ISSUE TITLE
Support adding new folder to project while debugging

### ISSUE THREAD

**Issue by skleeschulte** [Microsoft/nodejstools#206]
There is no option to add a new folder to a project in the solution explorer (only existing folders).

**Comment by skleeschulte** [comment]
Update: Sometimes "New Folder..." shows up in the "Add" submenu, but most of the time it's missing.

**Comment by mousetraps** [comment]
Hmm... can you reproduce this issue consistently? Which node in solution explorer are you not properly seeing the option in? (different item nodes might go through a different codepath to display that option in the context menu)

**Comment by skleeschulte** [comment]
Looks like I cannot reproduce the issue consistently. I have an existing project where most of the time when I right-click a folder (which is included in the project) and choose "Add", the add folder option is missing. However, sometimes it is there. And if I create a new project/solution with the wizard, the add folder option is shown in the "Add" context menu.

Is there a way to "reset" my existing project? Maybe that would solve the problem.

**Comment by mousetraps** [comment]
Unloading and loading the project is pretty much the closest you can get to a "reset". So if you right click the same folder multiple times, does it reproduce consistently? If that's the case, it would be helpful if you could send over the .njsproj file so we can check it over.

**Comment by billti** [comment]
We can't repro. This would seem to be a VS issue more than an NTVS issue too if it is occurring. Maybe something to follow up with the VS folks (unless you only see this in NTVS).

**Comment by skleeschulte** [comment]
Now I found out that it depends on if the project is running or not. If the project is running (debug mode), then the "New Folder" option is missing in the "Add" context menu. The options "New Item...", "Existing Item..." and "Existing Folder..." are still there. If the project is not running, "New Folder" appears in the menu.

**Comment by mousetraps** [comment]
Ahh, makes sense... when we implemented edit & continue, we never ended up getting to creating new folders (I don't specifically recall what it was about that scenario that complicated things, though).

Re-opened this issue as a "feature"

**Comment by paulvanbrenk** [comment]
Considering the technology used for the project system is very old, and poorly supported. So this won't be possible until we move to a new implementation.
