### ISSUE TITLE
Deployment options - aka "Publish"

### ISSUE THREAD

**Issue by EdSF** [Microsoft/nodejstools#207]
First, unsure if this is the proper place for such (not technically an "issue" more like "feedback"), so it's ok to take it down if inappropriate.

Being new to all this, and primarily a "VS user", perhaps more guidance on _deployment_ (aka "Publish") _other_ than the Azure option. 

Pretty sure this is a no-brainer for all Node devs...just not so for n00b and/or "VS folk" like me (using `Publish` -> to whatever, even file system for later push to some host)

Thanks!

**Comment by mousetraps** [comment]
Thx for the feedback. Agreed, we should document this more fully (and test more fully too -  I anticipate there are a few gotchas since we do some hacky things to enable publish to azure, and don't test the other scenarios as frequently)

**Comment by paulvanbrenk** [comment]
The best documentation we currently have for publishing to Azure is here: 

https://docs.microsoft.com/en-us/visualstudio/javascript/publish-nodejs-app-azure

We don't support any other publishing scenarios, but we're considering them for a future release of VS.
