### ISSUE TITLE
[Discussion] Copy build to output folder

### ISSUE THREAD

**Issue by seansaleh** [Microsoft/nodejstools#21]
I'm trying to copy the results of a build to an output folder as part of our build scripts
I've tried setting 
```xml
    <BaseIntermediateOutputPath>C:\Out</BaseIntermediateOutputPath>
    <IntermediateOutputPath>C:\Out</IntermediateOutputPath>
    <OutputPath>C:\Out</OutputPath>
```
but have had none of the js code or modules copied
I know earlier versions used to drop to the bin folder but that's no longer the case

How would I tell my njsproj to copy to a specific output folder?

**Comment by mousetraps** [comment]
Closing, as this issue is pretty old. Will reopen if anyone else runs into this.
