### ISSUE TITLE
Setting all *.js to 'Content' under 'public' folder upon import

### ISSUE THREAD

**Issue by zam6ak** [Microsoft/nodejstools#210]

**Comment by zam6ak** [comment]
I created a node project from existing files.
Existing project has a significant number of files and subfolders under /public which are reporting as failed upon build due to their type set to 'Compile' instead of 'Content'....

Is there any way to mark all *.js files under particular folder (in this case 'public') as 'Content automatically?

**Comment by mousetraps** [comment]
We are planning to make it easier, but for a different reason (#142)... what type of build errors are you getting?

**Comment by zam6ak** [comment]
Well the issue is that upon import, all *.js files in /public/javascripts/ folder are flagged as 'Compile' and the build fails with several hundred "Ambiguous catch identifier. Cross-browser behavior difference." errors.  These are comming from 3rd party libraries over which I have no control. They should not be inspected at all and so to eliminate errors I have to flag them as 'Content'..one...at...the....time.....
I should be able to right click on the folder and choose 'Treat as Content' or something....


And then of course there is 
"Files in your project exceed MAX_PATH, please move your project to a location with a shorter path."

which I understand is issue between how NPM lays out module structure and Windows not supporting more than 255 chars in path....But even moving to C:\src does not help nor does 'dedupe' helps....
I should be able to "turn off' this as a build error....

**Comment by mousetraps** [comment]
Gotcha, thx for the info. Can you give me an example of one of the 3rd party libraries that you're using that is having the issue? Are they VS extensions? It's useful to understand what tools people are using that have potential to conflict with the way we do stuff. 

In the meantime... Have you tried excluding the files from the project altogether? (right click, exclude) Like node_modules - it's not always necessary to include files in the project itself in order to work with them.

**Comment by mousetraps** [comment]
Fixed in #243

**Comment by mousetraps** [comment]
There is now a context menu command on folders to enable this, and it's available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)

**Comment by zam6ak** [comment]
Nice. it works....
I am not too fond of the labeling though - putting (node) and (browser) next to folders.....To verbose...
Perhaps folder icons should be indicators if code is node vs browser....
Just my 2c

In any case this issue is resolved.
