### ISSUE TITLE
Support for CodeLens

### ISSUE THREAD

**Issue by zam6ak** [Microsoft/nodejstools#213]
Will there be support for CodeLens in NodeJS projects?

**Comment by mousetraps** [comment]
No concrete plans at the moment, but that doesn't mean it we can't do it ;-). That said... based on a quick search, there doesn't appear to be a public extensibility model for CodeLens yet, so don't count on it any time soon.

**Comment by zam6ak** [comment]
According to few posts [1] [2]  CodeLens is available in VS 2015 RC for JavaScript.
And I can confirm this as well. However, the experience is not the same as with C# for example.
You see author and change log 'per file' but not on snippets above methods (again like in C#)

[1] http://blogs.msdn.com/b/visualstudioalm/archive/2015/04/29/what-s-new-in-codelens-for-visual-studio-2015-rc.aspx
[2] http://blogs.msdn.com/b/visualstudioalm/archive/2015/02/25/codelens-file-activity-and-history-now-available-for-c-javascript-and-sql-files-stored-in-git.aspx

**Comment by mousetraps** [comment]
Our editing experiences diverged when we stopped using the built-in javascript language service (JSLS) available in VS in favor of our own homegrown analysis engine, so unfortunately we don't get this stuff for free. Right now we're chatting with some folks internally to see how we might be able to join forces, but until that happens we would need to rely on a public extensibility point.

**Comment by mousetraps** [comment]
Closing this issue - this feature may make it in eventually into our new consolidated (in progress) javascript language service in VS, but it won't be provided by NTVS.
