### ISSUE TITLE
TestAdapter is causing Visual Studio 2019 to freeze

### ISSUE THREAD

**Issue by misaz** [Microsoft/nodejstools#2131]
Deadlock occur when attemped to save file randomly. One thread background is allways executing `Microsoft.NodejsTools.TestAdapterImpl.dll!Microsoft.NodejsTools.TestAdapter.TestContainerDiscoverer.GetTestProjectFromFile(string filename))` while Visual Studio freeze

https://developercommunity.visualstudio.com/content/problem/415146/visual-studio-freeze-1.html

- NTVS Version: default from Visual Studio Installer
- Visual Studio Version: 2019 Preview 2.2
- Node.js Version: not installerd

### Easy steps to successfully reproduce issue (tested on newly installed Windows Server 2019 virtual machine with 1 CPU and 1 GB RAM):

1.) Install Visual Studio 2019 Enterprise Preview with selected at least:
- .NET desktop development
- **Node.js development**

Example installconfig (cannot be attached here because of unallowed extension):

```
{
  "version": "1.0",
  "components": [
    "Microsoft.Net.ComponentGroup.TargetingPacks.Common",
    "Microsoft.ComponentGroup.Blend",
    "Microsoft.VisualStudio.Component.EntityFramework",
    "Microsoft.VisualStudio.Component.DiagnosticTools",
    "Microsoft.VisualStudio.Component.IntelliTrace.FrontEnd",
    "Microsoft.VisualStudio.Component.Debugger.JustInTime",
    "Microsoft.VisualStudio.Component.LiveUnitTesting",
    "Component.Microsoft.VisualStudio.LiveShare",
    "Microsoft.VisualStudio.Workload.ManagedDesktop",
    "Microsoft.VisualStudio.Component.WebDeploy",
    "Microsoft.VisualStudio.Workload.Node"
  ]
}
```

2.) Create new **C# Unit Test Project** (.NET Framework) project.

3.) Fullfil pregenerated test case (TestMethod1) with code `Assert.AreEqual(10, 5 + 5);`

4.) **Open Test Explorer** window and wait until it load and show loaded TestMethod1.

5.) Press **Ctrl + S or save button 20 times**. Visual Studio will freeze. (Visual Studio freezes randomly at save, so try it until it freeze, on my slow low cost virtual machine it is allways at first try).

**Comment by amcasey** [comment]
@armanio123 Did you already fix this?

**Comment by armanio123** [comment]
Yes, it was fixed by this PR: https://github.com/Microsoft/nodejstools/pull/2124.

The latest Visual Studio release should have the fix ready.
