### ISSUE TITLE
NullReferenceException in AttemptUpdateAsync

### ISSUE THREAD

**Issue by sharwell** [microsoft/nodejstools#2176]
When connecting to a Live Share session, I'm observing a NullReferenceException in PackageJsonTestContainerDiscoverer.AttemptUpdateAsync which causes the Live Share session to fail. At minimum, this exception should not be propagating through the `PackageJsonTestContainerDiscoverer.OnActiveWorkspaceChangedAsync`.

##### Actual Behavior 

- NTVS Version: 1.5.10424.1 c3ce0ae0
- Visual Studio Version: 16.2.0 Preview 1.0
- Node.js Version: Unknown

##### Steps to Reproduce
1. Open a Live Share link from another user

**Comment by amcasey** [comment]
Thanks, @sharwell!  I'm guessing `GetIndexWorkspaceService` returns null for the Live Share workspace.

**Comment by IlyaBiryukov** [comment]
There are Live Share customers hitting this issue. Can you please prioritize it?
https://github.com/MicrosoftDocs/live-share/issues/2970, 
https://devdiv.visualstudio.com/DevDiv/_queries/edit/1049398/?triage=true
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1049869

**Comment by amcasey** [comment]
Thanks, @IlyaBiryukov!  FYI @minestarks

**Comment by minestarks** [comment]
@IlyaBiryukov  thanks - it's on my radar, I'll make sure we're treating it with high priority

**Comment by pedropablo** [comment]
This is fixed but not released yet, right? I had to uninstall node.js development to recover live share functionality :(

**Comment by minestarks** [comment]
This will be in the next 16.5 Preview. Sorry for the frustrating experience!
