### ISSUE TITLE
After an error building the project VS is not longer able to run the app

### ISSUE THREAD

**Issue by mikehc** [Microsoft/nodejstools#22]
After running the app correctly for the first time. I pressed "restart" to run the app again after doing some changes. The build failed with this message:

```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Node.js Tools\Microsoft.NodejsTools.targets(93,37): error MSB4023: Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "..\..\..\Projects\myproject\\node_modules\prova\node_modules\watchify\node_modules\browserify\node_modules\insert-module-globals\node_modules\combine-source-map\node_modules\inline-source-map\node_modules\source-map\lib\source-map\basic-source-map-consumer.js". C:\Users\Miguel\Projects\myproject\node_modules\prova\node_modules\watchify\node_modules\browserify\node_modules\insert-module-globals\node_modules\combine-source-map\node_modules\inline-source-map\node_modules\source-map\lib\source-map\basic-source-map-consumer.js
Done building project "MyProject.njsproj" -- FAILED.

Build FAILED.
```

After that I try to run the project (not restart) and the project build just fine. But it not longer runs node.exe and I'm not able to debug the project.

I have to restart VS to make it work again.

I'm using NTVS 1.0 under Visual Studio 2013 Community Edition.

**Comment by mousetraps** [comment]
It looks like your project exceeds MAX_PATH (you're at 265 chars, thanks to the prova module) :-(

I'm surprised you didn't get a MAX_PATH warning, and that it works fine when you restart VS, though. 

Does it work if you try 'npm dedupe' and/or move your project to a shorter path? Some people have also had good luck with [flatten-packages](https://www.npmjs.com/package/flatten-packages).

**Comment by mousetraps** [comment]
Just checking - did you manage to get past this issue, or are you still blocked?

**Comment by mikehc** [comment]
Yes, I got around it. Thanks!

    _____________________________

**Comment by linquize** [comment]
After dedupe still exceed MAX_PATH. Is it possible to debug the app as-is? Simply skip js files with long file names.
