### ISSUE TITLE
Automatic resolution of internal Typescript modules in separate files?

### ISSUE THREAD

**Issue by gravidThoughts** [Microsoft/nodejstools#220]
I have a ASP.net project that uses TS with internal modules and has a file per class. As long as the module name is the same in the file, all exported members can be seen in all files automatically without needing to use the old `///<reference..../>` convention.

This does not seem work when using a nodejs application template. 

I am trying to confirm that this does not work, and I am not doing something wrong.

**Comment by NoelAbrahams** [comment]
@gravidThoughts, 

With NodeJS one needs to use CommonJS, not internal modules. Does that make sense?

**Comment by gravidThoughts** [comment]
Yes. 

I guess my issue is at this point in time there is poor support for the concept of a single external module split across multiple files.

How do I implement private/internal classes that help a module do its job?

**Comment by NoelAbrahams** [comment]
> I guess my issue is at this point in time there is poor support for the concept of a single external module split across multiple files.

Yes, that's right. See Microsoft/TypeScript#17

> How do I implement private/internal classes that help a module do its job?

The only option for true private classes is to have it in the same file. We don't normally do this, preferring instead to defining "internal" type classes externally and importing them into the main class.

**Comment by gravidThoughts** [comment]
I appreciate your responses Noel.

Do we have to wait for ECMA6 before we have a robust modular pattern for TS, or does ECMA5 have the necessary semantics?

**Comment by NoelAbrahams** [comment]
TS already supports ES6 modules (as of 1.5). It's an improvement on the old module system, but I don't think there's anything in the pipeline for solving multi-file external modules. 

Probably the best bet is to close this issue and raise a question on the TS forum.

**Comment by NoelAbrahams** [comment]
Or better still on typescript gitter: https://gitter.im/Microsoft/TypeScript
