### ISSUE TITLE
VsDoc Intellisense XML not working

### ISSUE THREAD

**Issue by mavericken** [Microsoft/nodejstools#222]
While type inference appears to be working quite well, vsdoc appears to not be working.

Here is my version information:
node.js tools  1.0.30109.03
vs2013 12.0.31101.00 update 4

Simple examples of issue:
![image](https://cloud.githubusercontent.com/assets/7833752/8256241/a949fdda-1673-11e5-9242-c7274b7f6335.png)
-------
![image](https://cloud.githubusercontent.com/assets/7833752/8256246/aeb0bd4a-1673-11e5-8c3e-a6ebc7a9bab3.png)
--------

Here is the same code from the images for copy and paste convenience:

```javascript
// example to show vsdoc _not working_ in node.js tools  1.0.30109.03 vs2013 12.0.31101.00 update 4

function testFunction(theParameter) {
    /// <summary>Function for example in determining if vsdoc is working.</summary>
    /// <param name="theParameter" type='Array'>Letting the program know it is an Array</param>
    /// <returns type="Array">The same as the input.</returns>
    return theParameter;
}

testFunction()
```

 ------

```javascript
// example to show vsdoc _working_ in asp.net project vs2013 12.0.31101.00 update 4

function testFunction(theParameter) {
    /// <summary>Function for example in determining if vsdoc is working.</summary>
    /// <param name="theParameter" type='Array'>Letting the program know it is an Array</param>
    /// <returns type="Array">The same as the input.</returns>
    return theParameter;
}

testFunction()
```

----------

Also, I tried jsdoc with webessentials as a workaround, and  the issues I see there are possibly related:

It appears that type inference is overriding explicit jsdoc:
![image](https://cloud.githubusercontent.com/assets/7833752/8256454/32fad60c-1675-11e5-9f37-623629c693f8.png)

Jsdoc has no effect inside the function body, as I get no intellisense choices or type info:
![image](https://cloud.githubusercontent.com/assets/7833752/8256507/871b0ea0-1675-11e5-8f9c-f720e87c453e.png)

**Comment by mousetraps** [comment]
Actually we don't support vsdoc at all at the moment (that was something we lost when we migrated away from the language service available in the rest of visual studio in favor of a static analysis engine). We do, however, support jsdoc.

**Comment by pdtdev** [comment]
OK - this would explain why node.js tools do not have IntelliSense for jQuery inside a JavaScript say.

I've been searching for a way to support IntelliSense for JavaScript in node.js tools, is this possible using jsDoc?

**Comment by billti** [comment]
Glad you got it working using JsDoc!

In Node Tools, JsDoc and the inference engine currently provide intellisense. There are no plans to add VsDoc support currently unless we see high demand for it. (Usage of Vsdoc format comments in JavaScript is relatively low).

**Comment by larnera** [comment]
Thanks pdtdev. This has fixed it for me too.
