### ISSUE TITLE
Each test case is runs in a separate node.js process

### ISSUE THREAD

**Issue by lukedgr** [Microsoft/nodejstools#223]
Copying issue from https://nodejstools.codeplex.com/workitem/1615

Selecting a subset or all the test cases to be run from the Test Explorer will make each test case to be run on it's own separate node.js process. 

This leads to test hooks for the suite not being honored, as they are run for each test case, instead of for each test suite. For instance, on Mocha:

``` javascript
describe('myTestSuite', function(){
    before(function() {
        veryExpensiveOperation();
    });

    it('testCase1', function() { ... });
    it('testCase2', function() { ... });
});
```

If testCase1 and testCase2 are selected and run from test explorer, we would get the "before()" function called twice, essentially this makes the before() behaving like a beforeEach() (check out Mocha's page about hooks). 

Ideally, the suite should be run on a single node.js process, so before() and after() method could be run only once per suite, allowing expensive code to be factored in a way that optimizes the execution time. 

The issue is on the TestExecute.cs for the test adapter, on the RunTestCases() method. It iterates over all the test cases and calls RunTestCase() for each one of them. RunTestCase() spawns a new nodejs process and asks mocha to execute that specific test case received as argument.

**Comment by mousetraps** [comment]
Yeah, we would make *a lot* of people happy if we fixed this one... 

Thx for copying it over. I'll close the issue in codeplex and redirect to here.

**Comment by NoelAbrahams** [comment]
Is there any chance of adding this to an explicit milestone? The current mechanism of spinning off a separate node process is adding about 200 ms to every single test.

**Comment by SteveALee** [comment]
I've no idea if it's possible with Mocha but it would be great to support the standard [TAP protocol](https://en.wikipedia.org/wiki/Test_Anything_Protocol) in the VS runner for process / runner communication. For example see [node-tap](https://github.com/isaacs/node-tap) and I'm using [tape](https://www.npmjs.com/package/tape) which supports node and browsers.

An advantage of TAP is there are lots of tools that support it. It's also mature (very).

**Comment by mousetraps** [comment]
@SteveALee what do you mean by "support"? What functionality are you looking for? The default mocha reporter in ntvs is tap
https://github.com/Microsoft/nodejstools/commit/b93b59119f6f1a189d54c946f258ac12ebd2e5e4

**Comment by SteveALee** [comment]
I was simply thinking that if the VS runner windows and the processes it talk to both  talk TAP then we have the ability to swap either for alternative. May not hold water on analysis though.

**Comment by paulvanbrenk** [comment]
Closing as we no longer spin up a new instance of Node for each test, but re-use running instance. (This has been the case in v1.3 and every version of Visual Studio 2017).
