### ISSUE TITLE
Debugger: No code has been loaded for this location

### ISSUE THREAD

**Issue by ace234b** [Microsoft/nodejstools#224]
I'm experiencing some odd behaviour with the debugger. I'm not sure if this is as expected. I am new to NodeJS.

Certain breakpoints will not trigger with the error 'The breakpoint will not currently be hit. No code has been loaded for this code location'.

This is occurring with Visual Studio 2015 RC. I've tried using NTVS 1.1 Beta and the Dev Build from 6-15-2015.

The below code reproduces the issue for me;
```javascript
var foo = ['foo','bar']

foo.forEach(function (currentValue) { 
    console.log(currentValue)
})
```
If a breakpoint is set on the line foo.forEach everything works as expected. However if I have a breakpoint on the console.log line it is never hit and the message 'The breakpoint will not currently be hit. No code has been loaded for this code location' appears when you hover over the breakpoint which has turned white.

**Comment by Neil-p-Hughes** [comment]
I did not have this issue with Visual Studio 2015 RC. and NTVS 1.1 Beta
but I updated to VS 2015 from RC and uninstalled the beta tools and installed the RC version 
so current setup is Visual Studio 2015 Enterprise. and NTVS 1.1 RC from I think it was July 16th

I also have the same setup on my other pc except VS 2015 community.
The rest of my team is still setup with VS 2015 RC and the beta version they can all debug fine without issue.

the issue I have is that code is not loaded for breakpoints. code is loaded for break points in the main server file for node but not other required files.

also I should note my project is a typescript project.

I an debug app.ts fine, but no other file. I have noticed if I set a break point in app.ts and then step into another file, I can set break points in that file for the rest of the session.

**Comment by Neil-p-Hughes** [comment]
I have also tried out VS code it Is having the same experience for me with the debugger. I'm not sure if there is a relation between the 2 debuggers.

**Comment by meiry** [comment]
Is there solution to this ? 
i also getting this error while trying to debug existing node,js app 
only the app.js is debuggable , other files aren't

**Comment by mjbvz** [comment]
I'm unable to repo this specific problem with NTVS 1.2 Alpha. If anyone is still running into this behavior, please open a new issue. Thanks.
