### ISSUE TITLE
Node.JS outdated version causing eslint errors

### ISSUE THREAD

**Issue by Zekfad** [microsoft/nodejstools#2249]
##### Expected Behavior 
Node.js tools normal behavior.

##### Actual Behavior 
ESLint fails because of incompatibility of Node.JS executable Node.js Tools using.
This issue in [VS Developer Community](https://developercommunity.visualstudio.com/content/problem/856202/js-eslint-no-warning-comments-terms-causing-invali.html) and in [ESLint repo](https://github.com/eslint/eslint/issues/12620)

- VS Version: 2019
- babel-eslint Version: 10.0.3
- eslint Version: 6.7.2
- NTVS Version: 1.5.11023.1 Commit Hash:579896f0984848d17d080c8a1c3ddff98d5ba96f
- Visual Studio Version: Version 16.4.2
- Node.js Version: installed - 13.3.0; NJSTools using (Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\NodeJs) - v10.16.3

##### Steps to Reproduce
1. Install lasted ESLint
2. Use `no-octal-escape` or this config - [eslintrc.json.txt](https://github.com/microsoft/nodejstools/files/3987968/eslintrc.json.txt)

##### Possible fixes
I manually updated executables in `Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\NodeJs` and `Microsoft Visual Studio\2019\Community\Common7\ServiceHub\Hosts\ServiceHub.Host.Node.x86` to mitigate the problem.
Now it works without problems, so it's possible to simply upgrade distribution of node  if there wouldn't be any backward compatibility issues.

**Comment by rachelgshaffer** [comment]
@Zekfad thanks for opening this issue but the version of Node used for ESLint is actually unrelated to this repo (a bit confusing, I know!). I am still tracking your issue with the feedback ticket [here](https://developercommunity.visualstudio.com/content/problem/856202/js-eslint-no-warning-comments-terms-causing-invali.html) and will post and close that ticket when the updates are shipped in VS.

**Comment by Zekfad** [comment]
@rachelgshaffer, thank you for reply, sorry for misunderstood the situation.
