### ISSUE TITLE
Support "just my code" for debugging

### ISSUE THREAD

**Issue by AcousticGuitar** [Microsoft/nodejstools#225]
Given: Node.js console application (using Visual Studio) which has downloaded several packages via NPM. When NPM does this it downloads the source code of those packages and puts them into the node modules folder.

Problem: The javascript code that I'm writing needs debugging of which I will often single step into to see the code paths. But the problem is it defines "Just My Code" as being anything it used during the "compile" of the project. This includes those node modules so I wind up on long goose chases often.

Is there a way to exclude single stepping into the node modules and in effect only step into "just my code"...?

**Comment by mousetraps** [comment]
Unfortunately we don't support "just my code" yet, but we should definitely consider it for a future release.

**Comment by AcousticGuitar** [comment]
Thanks for response!

**Comment by AcousticGuitar** [comment]
I noticed this is up for grabs.  But maybe a few tips on how to debug this problem using a local copy of node tools, I'm not too familiar with debugging code used in a VS environment... Please advise on how to get started and what modules we will want to look into... Thanks

**Comment by mjbvz** [comment]
I'm really excited about this feature and am glad that you want to look into implementing it. However, we're in early talks to unify our Node debug experience with VSCode's, and that work may drastically change the internals of the NTVS debugger. Implementing "just my code" will involve a lot of different technologies and may end up being fairly complex and, while I certainly don't want to discourage your involvement, I also don't want you to put in time and work improving the current debug engine if we are planning to move off it sometime shortly. @mousetraps Do you agree?

Here are some general documents about [getting started building NTVS ](https://github.com/Microsoft/nodejstools/wiki/Build-Instructions) and [testing NTVS](https://github.com/Microsoft/nodejstools/wiki/Running-Our-Tests) on your local machine. Let me know if you run into any problems getting up and running.

Again, I really want to see this feature added and would love to have you contribute, but let's make sure this still aligns with our plans to improve the NTVS debug experience. Thanks.

**Comment by mousetraps** [comment]
Agreed with @mjbvz - this feature is a non-trivial amount of work, so as much as we'd appreciate the contribution, I can't in good conscience recommend investing time into it just yet. Let's revisit after investigative work around the new debug engine (see #961). Happy to discuss further if you have any Qs or want to dive into anything else :smiley:.

**Comment by AcousticGuitar** [comment]
Thanks MouseTraps...  I appreaciate the feedback

**Comment by paulvanbrenk** [comment]
This is something we should get for free for Node 8, once the debugging integration with VS Code is completed.
