### ISSUE TITLE
Debugging opens two windows side by side (Typescript and Javascript)

### ISSUE THREAD

**Issue by AcousticGuitar** [Microsoft/nodejstools#226]
Writing code in Typescript, making changes, clicking on Start/Debug causes 2nd window to open and focus on Javascript equivalent.  It forces developer to have to switch back to Typescirpt to make changes and continue.  Should be option to turn off or allow developer to choose where that window opens like all other Visual Studio Windows.

**Comment by mousetraps** [comment]
Hmm, maybe I don't understand what the situation you're describing, but I can't reproduce this issue. Could you provide a bit more detail? Are there any other extensions that might be at play here?

**Comment by AcousticGuitar** [comment]
I'll check...

**Comment by mousetraps** [comment]
Closing as this issue is pretty old and haven't heard back.
