### ISSUE TITLE
Debugger step over doesnt

### ISSUE THREAD

**Issue by MarkAurit** [Microsoft/nodejstools#227]
vs2013 win764 Whenever I try to step out or just step over I go into lower level js files (as if I were just stepping into), such as connect.js and layer.js that aren't part of my app.  Doesn't exhibit this behavior with c#. Im not sure of the version of nodetools, I believe it is 1.0 (installed around early May)

**Comment by mjbvz** [comment]
I haven't seen this behavior recently in any testing on NTVS 1.1 and NTVS 1.2 alpha. If you run into this issue again, please open another issue with some repo steps so we can investigate. Thanks.
