### ISSUE TITLE
Analyzer not respecting "None" analysis setting

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#228]
Currently investigating the heap dump @NoelAbrahams sent us

**Comment by NoelAbrahams** [comment]
@mousetraps, are you releasing a version for VS 2015 RTM out on the 20th of July?

**Comment by mousetraps** [comment]
Indeed, we're aiming for a release in line with VS2015 RTM, but it won't be an RTM. Apologies in advance for the slow responses, as we're heads down for the next few weeks trying to get as many fixes in as possible. :smile:

**Comment by NoelAbrahams** [comment]
No worries. I hope this one goes in :smile:

**Comment by mousetraps** [comment]
@NoelAbrahams Do you recall if this was a recent issue (maybe in one in the past few dev builds or so?)

**Comment by NoelAbrahams** [comment]
@mousetraps, 

I wasn't aware of the issue, because it took a memory dump to figure out that the setting was not being respected. So it's possible that this was always the case.

I have been experiencing performance issues for the past 5 months or so.

**Comment by mousetraps** [comment]
Mind checking out the [latest dev build](https://github.com/Microsoft/nodejstools/releases)?

And you mentioned you have a lot of projects, so there's a good chance you're also affected by #354

**Comment by NoelAbrahams** [comment]
Thanks. Will give it a try.
