### ISSUE TITLE
Documentation for remote debugging in azure fails to mention that Windows 8 is required

### ISSUE THREAD

**Issue by zeiphon** [Microsoft/nodejstools#239]
The relevant documentation is here: https://github.com/Microsoft/nodejstools/wiki/Advanced-Debugging#remote-debugging-on-windows-azure

A list of steps detailing the remote debugging of node.js in azure does not mention that Windows 8 is required, so that only on the final step of attaching to the process is the user informed by a dialogue:
`Remote debugging of node.js Microsoft Azure applications is only supported on Windows 8 and above.`

This should be specified near the beginning of the section.

Additionally, why is Windows 8 required?

**Comment by mousetraps** [comment]
Agreed, we should document this better. The reason it only works for 8+ is because we use web sockets for Azure remote debugging, which unfortunately depends on a component only shipped in Windows 8+
https://msdn.microsoft.com/en-us/library/system.net.websockets.clientwebsocket(v=vs.110).aspx

**Comment by mousetraps** [comment]
just updated the docs to reflect this.
