### ISSUE TITLE
how to host node application in iis

### ISSUE THREAD

**Issue by digish777** [Microsoft/nodejstools#240]
how to host node application in iis

**Comment by mousetraps** [comment]
All the info you'll need is here. 
https://github.com/tjanczuk/iisnode

**Comment by digish777** [comment]
that was pretty fast., stay online.

**Comment by digish777** [comment]
how about at the time of hosting.

**Comment by mousetraps** [comment]
You should install iisnode the same way or the hosting provider may already have it available (eg azure web apps). Anyways, these questions aren't VS-related, so I'm closing this issue as external. 

If you use node tools for VS and deploy to azure, we have templates available for you to make things easier, and you should chat with your hosting provider or file an issue on iisnode if you run into any other issues not related to NTVS.

**Comment by digish777** [comment]
you should not have closed that fast mouse trap. Please wait.

**Comment by digish777** [comment]
i installed iisnode . nothing happened.

**Comment by mousetraps** [comment]
Sorry, this repo is not for general node tech support. You'll need ask these questions somewhere else.

**Comment by digish777** [comment]
HTTP Error 403.14 - Forbidden

**Comment by digish777** [comment]
i am getting this when i am hosting node application using express 3 and node created using visual studio. Hope you will respect visual studio. yes, of course : you have the right not to answer.

**Comment by digish777** [comment]
The Web server is configured to not list the contents of this directory.

**Comment by digish777** [comment]
the iis that i am using is iis7.5

**Comment by digish777** [comment]
my operating system is 32 bit, i have installed the 32 bit version.

**Comment by digish777** [comment]
of iisnode

**Comment by digish777** [comment]
i have installed both node and iisnode.

**Comment by digish777** [comment]
issue that iis is showing: A default document is not configured for the requested URL, and directory browsing is not enabled on the server.

**Comment by digish777** [comment]
i can see the site using visual studio. but for me to work, i normally host the application in iis. i cannot do run from visual studio all the time.

**Comment by digish777** [comment]
okay for it. I love Microsoft

**Comment by mousetraps** [comment]
Thx for the additional info. From what you're saying... it's working fine in Visual Studio, but not iisnode. I appreciate that you're using VS, but you should really just file an issue in the iisnode repo I linked to above. They will be able to help you out better there.

**Comment by digish777** [comment]
doing that.
