### ISSUE TITLE
Running/debugging does not work with x64 version of io.js (but does with x86)

### ISSUE THREAD

**Issue by alejandro5042** [Microsoft/nodejstools#245]
I spent a few hours trying to figure out why debugging doesn't work with io.js despite the [wiki documentation](https://github.com/Microsoft/nodejstools/wiki/io.js-and-ES6-support) saying that it should. Turns out you can't use the x64 version. It *might* launch the first time and run. But you'll never hit a breakpoint or anything. The x86 version works just as you would imagine.

Is this a bug? Expected behavior? Should we update the documentation?

Using:
* io.js 2.3.2 (x86 and x64): https://iojs.org/dist/v2.3.2/
* NTVS 1.1 Beta: https://nodejstools.codeplex.com/releases/view/614706
* Visual Studio 2013 Ultimate - Update 4 (non-elevated)

Thank you for this awesome tool!

**Comment by mousetraps** [comment]
Definitely a bug, not expected behavior. We should make a note of it in the docs until it's fixed, though.

**Comment by mousetraps** [comment]
@alejandro5042 just noticed you're using 1.1 Beta - Have you tried one of our latest dev builds? https://github.com/Microsoft/nodejstools/releases

**Comment by alejandro5042** [comment]
Unfortunately, I can still reproduce the issue with the 7-15-2015 dev build. When I hit run, my app immediately launches and is up and running before Visual Studio catches up several seconds later and switches to debug mode (with all the tool windows).

**Comment by mousetraps** [comment]
Hey, we just added a live diagnostics feature to help us get to the bottom of issues like this that are difficult for us to repro - mind trying it out? More details here: https://github.com/Microsoft/nodejstools/issues/246#issuecomment-127715686

**Comment by billti** [comment]
I just verified this with the latest bits from io.js and NTVS. Taking a look...
