### ISSUE TITLE
Don't show project context menu items all the time

### ISSUE THREAD

**Issue by davidwengier** [microsoft/nodejstools#2461]
Looks like https://github.com/microsoft/nodejstools/pull/2460 inadvertantly caused a menu item to be added to the top of every project in Solution Explorer in VS. I expect this was unintentional, especially since I have no javascript projects in this solution :)

<img width="406" alt="image" src="https://user-images.githubusercontent.com/754264/235559984-93cbb215-41d1-4789-b0e2-1deac2dd7e61.png">

Would be great if this could be shown only when necessary, and/or moved so its not at the very top, as my muscle memory expects "Build" to be the first item there, and its a bit jarring.

**Comment by joj** [comment]
@Shenniey to take a look. This should only happen if the project was detected to have been migrated from NTVS. There's something odd going on here :)

**Comment by Shenniey** [comment]
This fix won't be in effect until the insertion into VS is completed. I'll close this issue when that completes.
