### ISSUE TITLE
The 'Show all files' button settings saved in project file

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#250]
When change how Solution Explorer should show files, that setting saved in the `.njsproj` file. Which is goes to source control. Which is clearly not desired behavior.

**Comment by mousetraps** [comment]
Indeed, this belongs in an .njsproj.user file

**Comment by kant2002** [comment]
I found that issue related to [this code](https://github.com/Microsoft/nodejstools/blob/master/Common/Product/SharedProject/CommonProjectNode.cs#L574) and that this setting is persisted in the [templates shipped with NTVS](https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/ProjectTemplates/NodejsConsoleApp/NodejsConsoleApp.njsproj#L21)

By just removing this project setting from template files, issue will disappear. Please confirm and I could submit PR
