### ISSUE TITLE
"Your app has entered a break state, but no code is currently executing that is supported by the selected debug engine"

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#252]
**app.js**
```javascript
var npm = require('npm');
npm.load('--silent', function (err, data) {
    npm.ll('--silent', cb)
});

function cb (err, data) {
    for (var property in data) {
        console.log(property); // <-- SET A BREAKPOINT HERE
    }
}
```

**Produces the following error when the breakpoint is hit:**
![image](https://cloud.githubusercontent.com/assets/762848/8513648/8deed0b2-2328-11e5-8ddc-63c5b8ea909c.png)

**Other info:**
* node v0.12.5
* VS 2015

Haven't tested other configs. The app clearly breaks at the "right" spot (based on console.log statements)

**Comment by tyeth** [comment]
Please, any news... Also with pausing trying to debug sample express project

**Comment by mousetraps** [comment]
I can no longer reproduce this issue, but will reopen if someone can provide repro steps.

**Comment by bharatmangal04** [comment]
I have created a ASP.NET Core project and for me it always say code is in breaking mode. I am no longer to debug my code.. my email is bharat.gupta@microsoft.com. If require we can talk on skype for business and show you the issue

**Comment by MichaelSouleep** [comment]
this happens usually there some mistakes in your ui code
ie  you defined your gird row's height as auto ,but it doesn't fit the inside control

**Comment by pavloshargan** [comment]
@MichaelSouleep  Thank you so much, i have been finding the obctacles for a half a day. I can't believe the problem was hiding in Xaml, Goddamn WPF!
