### ISSUE TITLE
"Install New NPM Packages" Refresh Error

### ISSUE THREAD

**Issue by fatihyucelsen** [Microsoft/nodejstools#253]
New >> Basic Nodejs Express 4 Application project 
Right Click "npm" in Solution Explorer 
Click "Install New npm packages..." 
New window opens and downloads package list which is about 90MB 
Shows "Refresh Failed" error 

Error Details in Output Window: 
Microsoft.NodejsTools.Npm.SemverVersionFormatException: Invalid semantic version: '0.1.4-DEPRECATED-USE-cfenv-INSTEAD'. The version number must consist of three non-negative numeric parts of the form MAJOR.MINOR.PATCH, with optional pre-release and/or build metadata. The optional parts may only contain characters in the set [0-9A-Za-z-]. 

Platform: 
Windows 8.1
Visual Studio 2015 Community Edition 
Nodejs Tools v1.1 Beta

**Comment by mousetraps** [comment]
Unfortunately I can't repro this issue. Can you try again after clearing your npm cache?
![image](https://cloud.githubusercontent.com/assets/762848/8519632/f91840e8-2388-11e5-8a36-d7cbfdf737f2.png)

**Comment by fatihyucelsen** [comment]
I try it. useless.

Detail:
http://txs.io/xm6b

**Comment by mousetraps** [comment]
hmm you shouldn't be seeing the upgrade message at the beginning if the db was deleted. You can double check (and delete it manually) in "%localappdata%\microsoft\node.js tools". Go ahead and delete that entire folder and restart VS. 

If that doesn't work, I can send you a copy of my db sometime tomorrow.

**Comment by fatihyucelsen** [comment]
Unfortunately this did not work either.

http://txs.io/1m6b

**Comment by billti** [comment]
I tried with the latest release and got no issue either. I also extracted the [code that throws that exception](https://github.com/Microsoft/nodejstools/blob/35817ffdaa1797f95628a22f588fc3ed885f884b/Nodejs/Product/Npm/SemverVersion.cs#L47) into a test app and fed it the semver it is complaining about (i.e. '0.1.4-DEPRECATED-USE-cfenv-INSTEAD') and it parses it fine. There must be something else weird going on here, as the RegEx that parses this looks pretty straight forward and hasn't changed in a while.

What language OS/VS are you running?

**Comment by kant2002** [comment]
I also has no such issues on the latest bits.
Could you @fatihyucelsen make screenshot of the Help->About with information about NodeJS version ?

**Comment by kant2002** [comment]
Good, looks like we found issue. It is different regional settings.@emretto found that he was running Turkish version of Windows and change regional settings to English make NTVS works.

**Comment by mousetraps** [comment]
Now available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)
