### ISSUE TITLE
Deploying to Azure Web apps through VSO - Build fails

### ISSUE THREAD

**Issue by arcadiogarcia** [Microsoft/nodejstools#255]
I created a Azure Web app and I set up the continuous deployment using a Visual Studio Online git repository. Then I created a new project using the "Blank Azure Node.js Web Application" template, committed and pushed to test it. The deployment fails, and the build log in Visual Studio Online tells me that MSBuild failed. The MSBuild log is the following:

Build started 7/6/2015 4:11:48 PM.
     1>Project "d:\a\src\TimeRoom\TimeRoom.sln" on node 1 (default targets).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Debug|Any CPU".
       The target "MvcBuildViews" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.Publishing.targets (840,131)" does not exist in the project, and will be ignored.
     1>Project "d:\a\src\TimeRoom\TimeRoom.sln" (1) is building "d:\a\src\TimeRoom\TimeRoom\TimeRoom.njsproj" (2) on node 1 (default targets).
     2>PrepareForBuild:
         Creating directory "obj\Debug\".
       CoreCompile:
         Creating directory "bin".
         Copying file from "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Node.js Tools\Microsoft.NodejsTools.WebRole.dll" to "bin\Microsoft.NodejsTools.WebRole.dll".
       CreateTfsBuildInfoFile:
         The build information will not contain the TFS project collection URI or the symbol path. The resulting experience to go back to code from binaries won't be complete. To enable a complete experience, set /p:IncludeServerNameInBuildInfo=true in the MSBuild arguments. To understand more, see http://go.microsoft.com/fwlink/?LinkID=316979&clcid=0x409.
         Creating directory "d:\a\bin\_PublishedWebsites\TimeRoom".
         Copying file from "d:\a\bin\TimeRoom.BuildInfo.config" to "d:\a\bin\_PublishedWebsites\TimeRoom\BuildInfo.config".
       _CopyWebApplicationLegacy:
         Copying Web Application Project Files for TimeRoom
         Creating directory "d:\a\bin\_PublishedWebsites\TimeRoom\bin".
     2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets(136,5): error MSB3030: Could not copy the file "obj\Debug\TimeRoom.exe" because it was not found. [d:\a\src\TimeRoom\TimeRoom\TimeRoom.njsproj]
     2>Done Building Project "d:\a\src\TimeRoom\TimeRoom\TimeRoom.njsproj" (default targets) -- FAILED.
     1>Done Building Project "d:\a\src\TimeRoom\TimeRoom.sln" (default targets) -- FAILED.

Build FAILED.

       "d:\a\src\TimeRoom\TimeRoom.sln" (default target) (1) ->
       "d:\a\src\TimeRoom\TimeRoom\TimeRoom.njsproj" (default target) (2) ->
       (_CopyWebApplicationLegacy target) -> 
         C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets(136,5): error MSB3030: Could not copy the file "obj\Debug\TimeRoom.exe" because it was not found. [d:\a\src\TimeRoom\TimeRoom\TimeRoom.njsproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:02:52.31

It seems that MSBuild fails because it is looking for an exe file as the result of the build process. That does not seem to make any sense, did I miss any step in the setup? Or it is expected that I write my own deployment script?

**Comment by mousetraps** [comment]
Unfortunately we explicitly do not support VSO build/test at the moment for reasons like this. However there are some workarounds (eg have you tried creating a fake .exe?)

**Comment by arcadiogarcia** [comment]
For some reason, I'm not able to commit the .exe. Right-clicking on the project and selecting publish works perfectly though, so I will use that. Thanks for your help!
