### ISSUE TITLE
Debugging issue with graceful-fs (<4.1.0): "Code not running"

### ISSUE THREAD

**Issue by JanMattner** [Microsoft/nodejstools#257]
While debugging a program, that uses fs-extra, I stumbled upon the following message:

![code-not-running](https://cloud.githubusercontent.com/assets/7443680/8542404/c35ff884-2495-11e5-900b-0ca39b653412.jpg)

Instead of hitting the breakpoint, the above message is shown. After some investigation, it turned out that [node-graceful-fs](https://github.com/isaacs/node-graceful-fs) is the reason, which is used by fs-extra. Specifically, any breakpoint in the callback of the mkdir function of graceful-fs is not hit.
Example code (breakpoints on both console.log commands):

``` javascript
var fs = require("graceful-fs");

console.log('Hello world'); // breakpoint is hit

fs.mkdir("C:/Users/AIT/Desktop/t2", 511, function (err) {
    console.log("hello"); // debugging is paused, but "Code not running" message is shown
});
```

At that time, it used the graceful-fs version 3.0.8. Now they changed the implementation and with version 4.1.0, everything works fine. However, whatever they did there, prevented debugging with the Node Tools, so you might still want to look into that issue.

I suspect that it is related to what they did in fs.js at that time, [see the file of version 3.0.8](https://github.com/isaacs/node-graceful-fs/blob/a26f21044a5f0ded3e33080829a126966fee5343/fs.js)

**Comment by mjbvz** [comment]
Still a problem in NTVS 1.2 Alpha with that version of Graceful FS. Not a problem with 4.x.

Seems like this logic from `fs.js` could be a cause (4.x doesn't use `vm` in this file, but I only took a quick glance at the files):

```js
var mod = require("module")
var pre = '(function (exports, require, module, __filename, __dirname) { '
var post = '});'
var src = pre + process.binding('natives').fs + post
var vm = require('vm')
var fn = vm.runInThisContext(src)
fn(exports, require, module, __filename, __dirname)
```

**Comment by paulvanbrenk** [comment]
Closing, since this is no longer a problem with current versions of Node and Graceful FS
