### ISSUE TITLE
NODEJS Console (Typescript) project compile issues erroneous errors...

### ISSUE THREAD

**Issue by AcousticGuitar** [Microsoft/nodejstools#259]
## Given:

A NODEJS (Typescript) console application project (all Protractor test modules)...  If any of the "other modules= those not actively being edited" have an error, the error messages after the compile indicate the currently edited file has the errors.  Clicking on any of the errors takes you to illogical cursor locations in the opened file and the messages are completely erroneous.
## Solution:

After fixing all errors in entire project, the false errors just magically go away. 
## Recreation:

Create a NODEJS Typescript console application project for Protractor. Protractor Requires  "NPM Protractor" ,  a config.ts and specs.ts file.  
## Config.ts file

![image](https://cloud.githubusercontent.com/assets/10676026/8551495/9d439532-249c-11e5-996f-ed010c0dc129.png)
## Specs.ts file

![image](https://cloud.githubusercontent.com/assets/10676026/8551652/8c6e1ede-249d-11e5-863d-c674078b4423.png)
## Add Another TS file with an error

Now create a third file in TS like this: NOTICE in the prototype def there is a missing comma which makes this file invalid to TS and JS....

![image](https://cloud.githubusercontent.com/assets/10676026/8551458/4e9ec4ec-249c-11e5-97c6-763c91ac4011.png)
## Compile the project..

 and note the error messages, click on any one of them...

![image](https://cloud.githubusercontent.com/assets/10676026/8551625/6bde6e3a-249d-11e5-9a14-e27af5d1fb15.png)

You are brought to the specs.ts page which does not have any errors...  Notice in the image above where the cursor is.. This was placed there by the editor after clicking on the first error for line 8.

**Comment by mousetraps** [comment]
Is this issue specific to NTVS projects, or does it also occur if you create another type of TS project?

**Comment by AcousticGuitar** [comment]
I believe the answer is yes.  I only have this issue when using NODE and NTVS within Visual Studio, no other project type has this behavior.  Thanks.

**Comment by paulvanbrenk** [comment]
I no longer reproduce this in Visual Studio 2017 with TypeScript 2.3
