### ISSUE TITLE
Specifiy browser to launch

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#26]
It would be useful to specify **which** browser is launched when the 'Start web browser on Launch" is set. It currently uses the default browser but my default browser is FIrefox but I need for IE better integrated client debugging (as far as I can tell I need to get IE to invoke a second copy of  VS for client debugging in VS)

**Comment by mousetraps** [comment]
You should actually be able to set this option from the start button dropdown. 
![image](https://cloud.githubusercontent.com/assets/762848/7013186/1c2b3ec8-dc6c-11e4-936c-52f64c3a27ec.png)
If you don't have this option, my guess is that you started from a console app (see [this bug](https://nodejstools.codeplex.com/workitem/1819)). In the meantime, you'll be able to enable this option if you create a new project and use 'From Existing' or... I think you should be able to get away with setting ```<ProjectTypeGuids>```` in your .njsproj file as follows:
``` xml
<ProjectTypeGuids>{3AF33F2E-1136-4D97-BBB7-1795711AC8B8};{349c5851-65df-11da-9384-00065b846f21};{9092AA53-FB77-4645-B42D-1CCCA6BD08BD}</ProjectTypeGuids>
```

```{349C5851-65DF-11DA-9384-00065B846F21}``` is the web application project type guid, so including that will enable the browser dropdown.

**Comment by SteveALee** [comment]
@mousetraps Oh yes!! So it is. Thank you. 

You know I spent some time going through all the menus and options. I guess I'm of an age where I still expect toolbars to be alternatives to menus items, plus I use keyboard more than mouse so tend to ignore toolbars :)
