### ISSUE TITLE
Add more samples, tutorials, or docs to help users onboard

### ISSUE THREAD

**Issue by billti** [Microsoft/nodejstools#260]
The templates are minimal. Additional guidance to help learn the product or create new projects quickly would be very helpful. Maybe have some starter projects that can be cloned from GitHub?

**Comment by mousetraps** [comment]
On a related note, I went ahead and updated some of the wiki pages, and more notably changed the wiki homepage to be more inclusive and easier to navigate.
https://github.com/Microsoft/nodejstools/wiki

This also enables us more easily understand our own doc structure so we can improve it.

**Comment by mousetraps** [comment]
I also added some Windows-specific resources and links to other VS extensions, among other things.

**Comment by mjbvz** [comment]
Closing as too opened ended. We should create more actionable issues to track any work in this area.

The nodejs guidelines may also cover some of this: https://github.com/Microsoft/nodejs-guidelines
