### ISSUE TITLE
Folder based project support

### ISSUE THREAD

**Issue by billti** [Microsoft/nodejstools#262]
Being able to just open a folder and work with the files within it as a Node project would be really useful. This would help sharing amongst different tools (by not requiring a VS specific project file) and be similar to capabilities in other editors.

**Comment by sondreb** [comment]
Now that Visual Studio 2015, this should perhaps be possible to add since ASP.NET 5 project supports a folder-based structure where files are not saved in the project files.

**Comment by mousetraps** [comment]
Still needs a lot of work, but the first stage of this work is done and will light up in Dev15.
