### ISSUE TITLE
Expose ability to run Grunt or Gulp tasks from the IDE

### ISSUE THREAD

**Issue by billti** [Microsoft/nodejstools#263]
Similar to #10, it would be really useful to be able to launch tasks from common runners, such as Grunt or Gulp, from the UI (and view any output).

**Comment by kant2002** [comment]
In the VS2015 this functionality already integrated. It is called `Task Runner Explorer`.
Here the extension with same functionality for VS2013 from MS.
https://visualstudiogallery.msdn.microsoft.com/8e1b4368-4afb-467a-bc13-9650572db708

You could just add installing that extension to the Installer for VS2013, and issue would be solved

**Comment by itanex** [comment]
Additionally, the [Grunt Launcher](https://visualstudiogallery.msdn.microsoft.com/dcbc5325-79ef-4b72-960e-0a51ee33a0ff?SRC=https://github.com/Microsoft/nodejstools/issues/263) extension is available for VS2013 and VS2015.

**Comment by mousetraps** [comment]
Yep, the extension is available, but weve been considering tighter integration. Any ideas on how things could be better or to streamline the current experience?

**Comment by mjbvz** [comment]
Closing in favor of #963 which tracks the integration work
