### ISSUE TITLE
Add optional debugger logging

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#271]
This will help us track down race various debugging oddities that people are running into.

**Comment by kant2002** [comment]
Could you give more information about areas where debugger logging could be added?

**Comment by mousetraps** [comment]
Sure thing! Turns out we already log all the info we need when the debugger is attached (it all passes through AD7Engine.DebugWriteLine)
https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Debugger/DebugEngine/AD7Engine.cs#L1293

So it would be helpful to be able to optionally save this out to a log file rather than it only being available when a debugger is attached. That way when people run into an issue, we can ask them to turn on logging, and when they send it to us, we can just do a diff their machine's output with what what we might expect it to be.
