### ISSUE TITLE
Project Properties Feature Request

### ISSUE THREAD

**Issue by atom0s** [Microsoft/nodejstools#272]
Would it be possible in a future version to extend the project properties page to be specific to the current build type selected? This way multiple people working on the same project can define their own settings while not overwriting others?

For example, by default there is the Debug and Release builds when the project opens. However, altering the settings for either is not specific to that build type. 

It would be very useful to be able to define our own build types, so things can be done on a per-user basis.

**Comment by mousetraps** [comment]
Good idea. We should look into offering multiple build configuration options for a project. This could potentially help streamline some remote debugging scenarios as well.

What do you mean by defining build types on a per-user basis? Is that different from per-project?

**Comment by atom0s** [comment]
Ignore that per-user thing.. I repeated myself with terrible context, heh.

Multiple build configurations is what I was referring to. I was using "per-user" as an example referring to projects that have multiple users working on it at the same time and would rather have their own personal build settings.

For example, of the projects myself and another co-worker work on, I prefer using MySQL for testing and local development, while he prefers SQLite. Having the option to use the build type drop-down to choose things like 'Debug - MySQL' and 'Debug - SQLite' and so on would be a great help. Currently we use environment variables to setup which database we want to use locally but we have a commit war between the projects main settings for which one is loaded by default. 

But yes, the jist of this request was to get multiple build configurations added to this wonderful project. :)

**Comment by paulvanbrenk** [comment]
This is on the list of minimum requirements if we decided to move to a new project system. This is unfortunately too complex to add to the current project system.
