### ISSUE TITLE
Copy Files between projects copies successfully, but does not include the file in the project

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#279]
When copy files between NTVS projects, only copy file operation performed, but the actual file is not added to the project.

**Comment by mjbvz** [comment]
Just gave this a shot on NTVS 1.2 Alpha with VS 2015 Update 2. Here were the steps I tried:
* Create Project1 and new solution using Node console app template.
* Create Project2 in the solution, also using Node console app template.
* Create a Javascript file in project 2 called `test.js`
* Copy `test.js` and paste into Project1

**Result**
I see that a copy of the file is now in project1 directory and also included in the project

I also tried dragging the file from project2 to project1.  And I tried this using non-javascript files too. All cases seemed to work just fine.

@kant2002 If you are still running into this problem, please share your repo steps and we'll take another look. Thanks.
