### ISSUE TITLE
JSHint and JSCS errors off by 1 line

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#28]
Using the Web Essentials I find that the error/warning line numbers are off by one in the JSHint and JSCS error output window. For example the following code (line 1 in the editor)

``` javascript
var http = require('http')
```
gives this error (note line number is 2)

```
Message	1	JsHint (W033): Missing semicolon.	C:\Users\Steve\documents\projects\NodejsWebApp1\NodejsWebApp1\server.js	2	28	
```

Double clicking on the error does got to the correct line in the source so it's just the displayed line number that is off by one

**Comment by mousetraps** [comment]
This occurs for every project type I've tried (not just NTVS), so looks like it's is a WebEssentials issue..
https://github.com/madskristensen/WebEssentials2013
