### ISSUE TITLE
When building project TestAdapter warning appears

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#283]
Text of warning.

`C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.`

So far this is not give me any problem

**Comment by mjbvz** [comment]
I no longer see this issue in the output of a clean `TestAdapter` build with a detailed output. Please reopen if you still see the problem.

Thanks.
