### ISSUE TITLE
breakpoint hit multiple times

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#29]
``` javascript
var http = require('http');
var port = process.env.port || 1337;
http.createServer(function (req, res) {
    res.writeHead(200, { 'Content-Type': 'text/plain' }); <- set breakpoint here
    res.end('Hello World\n');
}).listen(port);
```

For some reason this breakpoint is hit three times for me when I load the page. Does this repro for anyone else?

**Comment by MystK** [comment]
It only hit once for me. I am using CTP6 and Firefox Developer Edition if it makes a difference.

**Comment by mousetraps** [comment]
And interestingly it was hit 2x for @jinglou... I'll attach a debugger when I get the chance since I can repro it consistently

**Comment by mousetraps** [comment]
no longer reproduces
