### ISSUE TITLE
Add Jasmine support to Test Explorer

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#296]
Jasmine is the 2nd most popular test framework, and we should add support for running/debugging tests within NTVS's test explorer. 

For anyone interested in getting started on this... our test framework is quite extensible, and the code we'd need to write is all javascript. 
- https://github.com/Microsoft/nodejstools/wiki/Test-Framework-Extensibility

See mocha.js for an example:
- https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/TestFrameworks/mocha/mocha.js

**Comment by mousetraps** [comment]
Old codeplex issue, lots of upvotes: https://nodejstools.codeplex.com/workitem/671

**Comment by mjbvz** [comment]
See PR #989, which added Tape test framework support, for what this work would entail.
