### ISSUE TITLE
Node.exe path should support relative paths

### ISSUE THREAD

**Issue by alejandro5042** [Microsoft/nodejstools#297]
I upgraded from 1.1 Beta to the 7-15-2015 dev build and reopened my solution and was unable to run it.

I had a relative path in the project settings under "Node.exe path". I use the [electron](https://github.com/atom/electron) [pre-built package](https://www.npmjs.com/package/electron-prebuilt) which installs the executable under `node_modules\electron-prebuilt\dist\electron.exe` relative to the project. It used to work but no longer does.

Specifying a relative path is key in allowing us to submit the .njsproj file into source control and having others be able to debug/run the project without having to modify the project file to specify an absolute path on their machines.

**Comment by mousetraps** [comment]
I'm pretty sure we never supported this because we haven't really changed anything in this codepath, and the current code would always produce an error if File.Exists returned false on the relative path (running without the debugger attached, however, does work.) In any case, working on a fix that explicitly adds this support.

**Comment by mousetraps** [comment]
Also are you sure you weren't relying on the functionality described in the following link?
https://nodejstools.codeplex.com/workitem/1533

And just to be clear... I'm not denying that it used to work before... Just saying that I am very surprised if it did :smiley:

**Comment by alejandro5042** [comment]
Interesting. I checked my the project file history in source control and--surprisingly, I suppose--did not have an absolute path before the upgrade and it surely worked!

```
<NodeExePath>node_modules\electron-prebuilt\dist\electron.exe</NodeExePath>
```

Thank you for officially adding this feature! A small change but a major win :)

**Comment by alejandro5042** [comment]
Thanks @mousetraps! This will be used every day here.

**Comment by mousetraps** [comment]
Np, mind trying the [latest dev build](https://github.com/Microsoft/nodejstools/releases)?
