### ISSUE TITLE
Cannot find function source code under "Function details" view when profiling

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/nodejstools#299]
The problem can be reproed via walking through the profiling tutorial in the [wiki](https://github.com/Microsoft/nodejstools/wiki/Profiling#profiling). The profiling reports "The matching source file could not be found." when clicking on function names in the profiling report. Clicking the "Browse to find source" only shows a .cs file.

The problem happen for VS2015 and VS2013, but not VS2012.

Screenshot:
![1](https://cloud.githubusercontent.com/assets/1171301/8758944/d0f74fee-2c9f-11e5-91d8-090a52c57784.png)

**Comment by mousetraps** [comment]
The fix is now available in our [latest dev build](https://github.com/Microsoft/nodejstools/releases)
