### ISSUE TITLE
Node.js Interactive Window and TypeScript

### ISSUE THREAD

**Issue by MystK** [Microsoft/nodejstools#30]
Hello. Is there an option to allow TypeScript to work with the NIW? 

If not, would this be feature in the near future?

**Comment by mousetraps** [comment]
For now, the best workaround I know is...
* creating a typescript file with the code you want to to test (and make sure you are using the CommonJS module system)
* using require('path-to-underlying-javascript-file') and use it as you would if you were using node.exe in the command line. 

Re: future plans - We'll have a roadmap up soon so this *future* thing becomes a little more concrete. For this... probably not near future unless it's coming from the TypeScript team or some really dedicated TypeScript + Node.js fan. . 

Now let's say you fit in one of these two categories :)

From an engineering point of view...  While we do support TypeScript, we actually throw you into the TypeScript editor when you're working with .ts files. So support in the interactive would require the Node.js IntelliSense engine, syntax highlighter, etc. to support TypeScript (pretty non-ideal from a maintenance perspective). Alternatively if TypeScript exposed the right pieces to us, we could potentially plug into their tooling and get this for free. Additionally, we'd need to do some extra compile step to generate the .js code before running it through node.exe.

**Comment by mousetraps** [comment]
@bowdenk7 @jramsay @paulvanbrenk @danielrosenwasser potentially interesting Salsa / Node.js / TS scenario, and may even help people experiment with and learn typescript! It would involve transpiling and running under the covers, and also presents some interesting challenges when it comes to incremental updates.

**Comment by DanielRosenwasser** [comment]
:+1:, and https://github.com/Microsoft/TypeScript/issues/6508 might also be an issue of interest here.

**Comment by paulvanbrenk** [comment]
Closing this.

This will require wide ranging changes, and the current usage doesn't warrant making those changes.
