### ISSUE TITLE
When loading cached Node.js project display name of the project

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#301]
Would be interested to known which project is loading now, so I could see the progress. I have relatively slow PC sometimes and it is interesting to know how much time left until VS started.

**Comment by billti** [comment]
Doesn't this already display in the status bar?

**Comment by kant2002** [comment]
Actually not. VS just display other statistics, like amount of functions loaded from analysis. But all that displays without indication of project name and after the project loaded. But when working with slow loading projects (which is any project withinn NTVS for me) would be good display project name before it start loading, then when I wait for it to load I will know which one project is slow.

Not sure if this would be realiable due to async nature of VS but would like give it a try. Please reopen

**Comment by billti** [comment]
Gotcha. OK. Thanks.

**Comment by paulvanbrenk** [comment]
This is a feature for Visual Studio, and not limited to Node Tools. Unfortunately they weren't interested in taking this at this time.

You're best bet at this point would be to open an issue on the [Visual Studio developer community](https://developercommunity.visualstudio.com/)
