### ISSUE TITLE
add support for tsconfig in njsproj 

### ISSUE THREAD

**Issue by afaayerhan** [Microsoft/nodejstools#302]
currently working with typescript and it would be good if there is support for tsconfig, so as we can easily switch between VsCode for mac and when developing on windows we can use full futured power of visual studio 2015

**Comment by mjbvz** [comment]
From #605:

Support for `tsconfig.json` files seems to have be introduced into Typescript for VS at some point (perhaps TS 1.8). I've tested with a `tsconfig.json` at the root of my NTVS project and see the configuration options getting picked up properly during compilation.

Let me know if there is some other aspect of `tsconfig.json` support you were looking for, or if you have any ideas on how the experience could be improved.

Thanks.
