### ISSUE TITLE
Debugger Crash: Assertion failed: object-InternalFieldCount() > 0

### ISSUE THREAD

**Issue by itanex** [Microsoft/nodejstools#307]
While debugging and inspecting variables for their contents the debugging session is terminated and this message appears in the console window. 

> Assertion failed: object-InternalFieldCount() > 0, file d:\jenkins\workspace\node-js-msi-julien\d8c2bb\src\util-inl.h, line 117

### REPRO:

1. Set a break point or two
2. Press F5 or click the "start browser" button or select "Start Debugging" from the "Debug" menu
3. Execute the path of code that will result in the break point occurrence
4. Inspect an object.

### NOTES:

I have noticed, not fully tested, that this occurs when inspecting objects with a large graph. However, I have had on a few occasions experienced this with simple objects as well. Most of the time I have been inspecting the *response* object that is returned from the requesting client object of the 'node-rest-client' NPM package.

**Comment by kant2002** [comment]
This looks like Node.js/io.js issue.
Which version do you use?

**Comment by itanex** [comment]
v0.12.7

**Comment by kant2002** [comment]
Did you use `crypto` module?

I see similar error here: https://github.com/joyent/node/issues/9028

**Comment by mauricionr** [comment]
+1

**Comment by mauricionr** [comment]
I'm trying to debug my application but, always crash with this error
```Assertion failed: object->InternalFieldCount() > 0, file d:\jenkins\workspace\no
dejs-msi-julien\d8c2e2bb\src\util-inl.h, line 117```

**Comment by billti** [comment]
This is crash coming from Node itself, not something we can fix in NTVS. Per the issue @kant2002 linked to, looks like they are investigating how to fix this on the Node side.

**Comment by mauricionr** [comment]
I got this error in visual studio code, sorry!

https://code.visualstudio.com/issues/detail/19281
