### ISSUE TITLE
VS2015 F5 is inconsistent

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#31]
Oftentimes it doesn't go any further than "debugger listening on port 5858"

(using basic express app)

**Comment by jinglou-** [comment]
I've got a quite consistent repro with a typescript Starter Azure Express 3 project.

**Comment by mlowijs** [comment]
Same in VS2013. Works again after restarting VS for some reason...

**Comment by mlowijs** [comment]
Running without debugging works fine (Ctrl-F5), by the way.

**Comment by mousetraps** [comment]
@mlowijs - thx for reporting. Can't repro that issue w/ 2013... what version of node are you running? And are you able to reproduce this with the NTVS basic console app template?

**Comment by mousetraps** [comment]
I still can't get a consistent repro on this, but the currently known workaround may be to pause and continue execution (see #83)

**Comment by mikehc** [comment]
I'm having a consistent repro of this on VS 2015 RC. I notice that if I let "Start web browser on launch" unchecked I don't get past the "debugger listening on port 5858" message. But if I check that option the debugger launch normally.

**Comment by mousetraps** [comment]
@mikehc awesome observation! I can now repro with the "Blank Node.js Web Application" template when "start browser on launch" is unchecked on VS2015.

**Comment by mikehc** [comment]
Great job! When should we expect the next beta version?

**Comment by mousetraps** [comment]
Aiming for a dev build on Friday.

**Comment by mousetraps** [comment]
Fix is available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)
