### ISSUE TITLE
When adding existing packages to devDependencies they does not appear in npm node

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#311]
I have collegue remove devDependencies from package.json. When I open project and copy these dependencies back, they still appear in the `npm` node as installed, but not listed in the `package.json`.
After reloading everything appears under `dev` node.

**Comment by paulvanbrenk** [comment]
I don't understand what you mean by: 
> copy these dependencies back

Where do you copy from/to?

Closing for now, since I made a couple of fixes here, which may solve this.
