### ISSUE TITLE
Run devenv /setup only once during upgrade

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#315]
We should not run it while uninstalling NTVS, as this unnecessarily doubles setup time. 

#288 added an option to skip devenv /setup, so we should be able to take advantage of that flag.

**Comment by mjbvz** [comment]
Fixed for VS 15. For that release, we are moving to a different install story based on VSIXs. Visual studio will handle this for us. We've see a lot of odd issues with `/setup` in VS2015 in the past so I'm not sure we want to risk removing any extra steps for the old msi installers.
