### ISSUE TITLE
Improve test coverage for PackageJson parsing

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#321]
TODO: contributors, private, main, bin, directories (hash), repository, config. Also verify that field ordering doesn't make a difference. 

related to #320, as we should have caught this in our unit tests

**Comment by mjbvz** [comment]
Closing as too open ended. 

Any changes the touch parser code should introduce pinning tests around the behavior being changed plus, if the change is a fix, tests to verify that whatever bug has been fixed. This way we build up a library of tests for this code over time, hopefully without accumulating too many unnecessary tests.
