### ISSUE TITLE
Cannot  "import { NameValueUnits } from" 

### ISSUE THREAD

**Issue by kevinpas** [Microsoft/nodejstools#323]
NOTE:  See issue 322 first.

See branch "AddVS15" of https://github.com/kevinpas/Klib6

There are two imports in the startup file "Klib6/Tests/Core/CoreTests.ts".  If you comment out the second one you can successfully run and debug/step through the tests in the startup file.

If you uncomment the second import and uncomment the two lines near the bottom:
//var units           = "mm";
//var nameValueUnits  = new NameValueUnits( name, value, units );

when you try to run it you get the exception (on win7):

Debugger listening on port 5858
module.js:338
    throw err;
          ^
Error: Cannot find module 'NameValue'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\ ... \Git\GitHub\Klib6\Source\Core
\NameValueUnits.js:46:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
Press any key to continue...

**Comment by kevinpas** [comment]
This issue, for me, is only related to the visual studio 15 project in the repo described above.

And I forgot.  In Issue 322 I showed that the vs 15 project is in the Tools folder.

**Comment by NoelAbrahams** [comment]
I think the problem is in [line 45 of Source/Core/NameValueUnits.ts](https://github.com/kevinpas/Klib6/blob/AddVS15/Source/Core/NameValueUnits.ts#L45).

Try
```typescript
import { NameValue } from "./NameValue";
```

Without the path node will try to resolve to its own module library, e.g to `fs`, `util`, `path` etc.

**Comment by kevinpas** [comment]
Voted wrong location
