### ISSUE TITLE
Debugger hangs/fails after first breakpoint

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/nodejstools#324]
Hi,

**Version**: VS 2015 RTM / NTVS 1.1 RC / TS 1.5

To reproduce:
- Right-click on an NTVS project and launch the debugger, this will bring up the browser at the URL and port where node is listening.
- Set a breakpoint in the code.
- Carry out an action in the browser so that the breakpoint is hit.
- At this point the breakpoint does get hit, but no result is returned to the browser.

If I don't set the breakpoint then everything works as normal.

This problem makes it very difficult to debug NTVS apps.

**Comment by mousetraps** [comment]
Not sure I understand... why do you expect a result to be returned to the browser if the debugger is stopped at a breakpoint? Does the page not render when you continue execution?

**Comment by NoelAbrahams** [comment]
The debugger is not stopped at the breakpoint. I hit the breakpoint and then hit F5 to continue, but it seems to hang at that point.

**Comment by mousetraps** [comment]
Gotcha, thanks for the clarification. Does this happen with every project for you or is it a specific scenario? Do you notice anything else out of the ordinary (perhaps in the Node console window?) Does the page render fine when you remove the breakpoint after hitting it?

**Comment by NoelAbrahams** [comment]
> Does this happen with every project for you or is it a specific scenario? 

I just tested it again and it seems to happen mostly when one sets a breakpoint deep within a nested callback (i.e. nested promises). For the simple cases it seems to work fine.

> Do you notice anything else out of the ordinary (perhaps in the Node console window?) 

Nothing in the console.

> Does the page render fine when you remove the breakpoint after hitting it?

Removing the breakpoint after the event does not seem to have any effect. The call does not return.

I also notice that VS is not letting me set breakpoints in certain valid places. The breakpoint keeps slipping. And VS keeps breaking the JavaScript file instead of the TypeScript file, where the breakpoint was set. 

The combination of these problems makes it rather difficult. We can improve the reliability of the debugging experience by:

* Ensuring breakpoints are settable where required in TypeScript file (i.e. solve the slipping problem)
* Ensuring the debugger only every hits breakpoints in TypeScript files, instead of the JavaScript.
* Solve the problem of the occasional hang.

**Comment by paulvanbrenk** [comment]
Closing Considering there is no consistent repro, and there have been no recent reports.
