### ISSUE TITLE
Nuget package manager cannot 'see' Node.JS projects

### ISSUE THREAD

**Issue by vas85** [Microsoft/nodejstools#326]
1) Create a new Node JS project
2) Right click Node JS project and click "Set as StartUp Project"
3) Open NuGet package console

Expected:
NuGet package console finds the default project and I can use NuGet commands

Actual:
NuGet package console cannot find any Node.JS projects and so I can't use NuGet with Node.JS projects

**Comment by mousetraps** [comment]
This would need to be fixed on nuget's side. We have no control over this. That said... here are some pointers to the relevant code for anyone is interested in making a PR to Nuget:
* Add a new project system (probably similar to fsharp) https://github.com/NuGet/NuGet.VisualStudioExtension/blob/401654af9408877cd1ddcbda6cdaa0a205b89291/src/PackageManagement.VisualStudio/ProjectSystems/FSharpProjectSystem.cs
* add to dictionary: https://github.com/NuGet/NuGet.VisualStudioExtension/blob/401654af9408877cd1ddcbda6cdaa0a205b89291/src/PackageManagement.VisualStudio/ProjectSystems/MSBuildNuGetProjectSystemFactory.cs#L19-L25
* Node.js Project Guid: "9092AA53-FB77-4645-B42D-1CCCA6BD08BD"
https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Guids.cs#L33

**Comment by vas85** [comment]
Cool. I'll push up a branch on the NuGet side when I have time.

**Comment by mousetraps** [comment]
Also out of curiousity, what's your scenario? Why do you want to use nuget instead of npm with a node project?

**Comment by vas85** [comment]
It's pretty low in priority. I was using it for new dev environment setup (where I can install node via nuget).

**Comment by Nekromancer** [comment]
I got same issue. I would like to use NuGet next to npm for ex. to download TypeScript definitions for npm library like that: https://www.nuget.org/packages/shortid.TypeScript.DefinitelyTyped

**Comment by mousetraps** [comment]
@Nekromancer the currently recommended way of adding typescript definitions is to use tsd, as specified in our docs. 
https://github.com/Microsoft/nodejstools/wiki/TypeScript#adding-typescript-type-definitions

**Comment by paulvanbrenk** [comment]
Closing. Since the primary reason to use Nuget, i.e. for definitions, is no longer the recommended way.

**Comment by Arturace** [comment]
I don't need to use Nuget for definitions. I want to use 1 internal package manager at my company. Our web applications are in C#, but we often need JavaScript/TypeScript code for front-end purposes. 

Thankfully, using nuget.exe to install the package manually anywhere works well enough, but it would be great to do this directly form the VS package manager.
