### ISSUE TITLE
List Bower packages as dependencies for npm & Bower like as in ASP.NET 5 project

### ISSUE THREAD

**Issue by ggondim** [Microsoft/nodejstools#328]
Like this:

![""](http://goo.gl/EuzbHD)

It's an enhancement.

**Comment by sondreb** [comment]
Displaying versions of packages is a great benefit in the Node Tools, which is not available on the ASP.NET 5 projects.

**Comment by paulvanbrenk** [comment]
We should get this for free, when we move to a shared NPM package manager with ASP.NET
