### ISSUE TITLE
Should not end template headers and subheaders with periods.

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#33]
It's pretty weird and not a good default. 
![image](https://cloud.githubusercontent.com/assets/762848/7034178/89dab3e0-dd34-11e4-95f7-15cd8a4bb49b.png)

**Comment by paladique** [comment]
This looks like a pretty easy fix and a way for me to get acquainted with Node.js tools. Mind if I take this on?

**Comment by mousetraps** [comment]
All yours! :-)

**Comment by paladique** [comment]
Should I be making a test for this? Wasn't sure if a cosmetic/UI change like this must also fall under testing per the [contributor guidelines doc](https://github.com/Microsoft/nodejstools/wiki/Contributing).

**Comment by mousetraps** [comment]
Nope - not necessary for this one, but thanks for reading the guidelines! We should clarify that because if you *had* included one, I would have actually asked you to take it out. :smiley: we have UI tests, but try to avoid them if we can because they:
* Take a while to run
* can be difficult to maintain

So we don't have any UI tests that would test the aesthetics or string values of anything like that because they're not risky enough to warrant the extra 10 seconds on every test run. And every time we would go to make a minor change, the UI tests would break even though things aren't actually broken. The only time we might test strings are if those strings tell us something about the functional state of a program (e.g. we do this in some of the Interactive window tests)

**Comment by paladique** [comment]
:+1: Good to know, thanks!
