### ISSUE TITLE
Update fwlink to point to github issue tracker

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#330]
"https://go.microsoft.com/fwlink/?LinkId=507637"

should point to... https://github.com/Microsoft/nodejstools/issues

**Comment by mousetraps** [comment]
@crwilcox I don't have access to this link, but ptvscore does - mind adding me as an owner and/or updating it?

**Comment by mjbvz** [comment]
Fixed: "https://go.microsoft.com/fwlink/?LinkId=507637" hits github issue tracker now.
