### ISSUE TITLE
Shutting down VS while accessing a property page results in a catastrophic failure

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#331]
![image](https://cloud.githubusercontent.com/assets/762848/8952594/1d8289a0-358d-11e5-9f53-e30d47ec2b5a.png)

We should check if NodejsPackage.Zombied is true before calling GetDialogPage otherwise some of our shutdown activities may be halted prematurely.

**Comment by mousetraps** [comment]
@zooba fyi it's likely ptvs is also affected by this in certain scenarios

**Comment by zooba** [comment]
Maybe, but it looks like you haven't taken the major refactoring to avoid going via the package for stuff like this. We probably fail to get a particular service earlier now.

**Comment by mjbvz** [comment]
I have not been able to repo this in my testing.

Please let me know if the crash still occurs and the repo steps, and we can reopen this.

Thanks.
