### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by noopole** [Microsoft/nodejstools#333]
I'd like to use the Navigation Bar with my Node.js projects to visualize objects and methods in the javascript text editor.

Cf. #136 for Class View, but here it's about Navigation Bar.

EDIT: for me it's a bug since Navigation Bar works with any non-NTVS javascript file.

**Comment by noopole** [comment]
mousetraps said in #344: "You can still find it if you change the build action from "compile" to "content" (close the corresponding editor for that file if it's already open), which will bring you client-side completions."
...and Navigation Bar, too! Thank you for this trick.

**Comment by mousetraps** [comment]
Np - also check out our docs on this
https://github.com/Microsoft/nodejstools/wiki/Working-with-Browser-(Clientside)-JavaScript-in-NTVS

**Comment by noopole** [comment]
Thanks, I completed an (auto-)answer in Stackoverflow about this concern with your link
(at http://stackoverflow.com/questions/31695196).

**Comment by paulvanbrenk** [comment]
This works as expected in 1.3
