### ISSUE TITLE
Cannot use code snippets

### ISSUE THREAD

**Issue by elmojo** [Microsoft/nodejstools#342]
Within VS 2015, I cannot use code snippets.  Normally I can type "if" and hit the TAB key twice and it will template out an "if" statement using a code snippet.  This is no longer working.  Tried "for", "function", "while", etc.  In fact the IntelliSense portion is broken too.  Normally, IntelliSense appears when I begin typing but now it only appears after the "dot" operator.

Microsoft Visual Studio Professional 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00081

Installed Version: Professional

**Comment by mousetraps** [comment]
Thx we're aware of this (#158), and you're in luck because there's a PR out for it now :smiley: #339

**Comment by mousetraps** [comment]
Re: IntelliSense, it should also show up if you press ctrl+space, but it will not show up when you start immediately typing... yet, at least - just added it as a feature request
https://github.com/Microsoft/nodejstools/issues/345
