### ISSUE TITLE
include option to immediately display intellisense while typing without pressing ctrl space

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#345]
For instance, typing 'v' should display all completions matching "v". Currently you would have to type "v<ctrl+space>" 

This is most well known as: "Show completion list after a character is typed"

copied from: https://nodejstools.codeplex.com/workitem/1719

**Comment by noopole** [comment]
I think NTVS already does this.
I never press [CTRL + Space].
Maybe I didn't quite understand this feature.

**Comment by mousetraps** [comment]
We only show completions after pressing dot or Ctrl+space. So if you just started typing "proc", this feature would immediately pop up a completions list with process. If your build action is set to "content", you'll see the list immediately because JSLS is kicking in, but you won't see it when editing node code.
