### ISSUE TITLE
Github Docs for software to build - in order to debug/test/contrib to project

### ISSUE THREAD

**Issue by dfberry** [Microsoft/nodejstools#347]
This [Build Instructions page] (https://github.com/Microsoft/nodejstools/wiki/Build-Instructions) says that the VS SDK is required but the "Tools for Visual Studio 2015" section of this [page] (https://www.visualstudio.com/downloads/download-visual-studio-vs) says it is part of the VS 2015 install as option feature with instructions [here] (https://msdn.microsoft.com/en-us/library/bb166441(v=vs.140).aspx). 

I would edit the Build wiki page here on github but I can't tell if that change is moderated or how doc changes are handled. 

It would be nice to save the next person a few minutes. Mind if I make the change?

**Comment by mousetraps** [comment]
Sure, go right ahead!

We don't actively moderate the wiki (I check in every so often to make sure everything is in good order and there's no need to create process around it), so your changes will go live immediately. That said (barring typos and such), we very much appreciate filing an issue so ppl are aware of the change.

**Comment by dfberry** [comment]
Edited. https://github.com/Microsoft/nodejstools/wiki/Build-Instructions
