### ISSUE TITLE
Add troubleshooting section to documentation

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#355]
This'll make it easier for ppl who file issues to provide us with actionable information

Useful tidbits to add: 
* https://github.com/Microsoft/nodejstools/issues/246#issuecomment-127715686
* #44 
* #69 
* #116

**Comment by mjbvz** [comment]
Created Wiki page here: https://github.com/Microsoft/nodejstools/wiki/Troubleshooting and migrated some of the useful parts of the referenced comments over. Feel free to add anything else.
