### ISSUE TITLE
Keep tabs option for Jade keeps resetting in VS2015

### ISSUE THREAD

**Issue by Agamnentzar** [Microsoft/nodejstools#358]
`Keep tabs` option for Jade resets to `Insert spaces` after every restart of Visual Studio 2015

Works fine in Visual Studio 2013

using version 1.1 RC

**Comment by RodChr** [comment]
I'm seeing this as well, in most file types: JavaScript, TypeScript, etc.

**Comment by neico** [comment]
This is indeed highly annoying to remember each time you start VS2015 that you have to set the Tab setting to "keep tabs" before doing anything else...

I'd like to see this fixed for the 1.1 release, else I'll probably go insane on that one at some point...

PS: I'd personally only care about the Node.JS file type but it looks more like a general issue...

**Comment by mousetraps** [comment]
Looks like VS plans on fixing it in an [update](https://connect.microsoft.com/VisualStudio/feedback/details/1628173/spaces-vs-tabs-when-reformatting-a-document). Maybe try using the [editor config extension](https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328) in the interim?

**Comment by billti** [comment]
Not our issue. Looks like VS is fixing it. Closing.
