### ISSUE TITLE
Project settings window background according to active theme

### ISSUE THREAD

**Issue by syagev** [Microsoft/nodejstools#365]
It'd be nice if the project's settings window could adhere to the active theme (e.g. dark). This always looks kind of buggy to me:

![capture-vs](https://cloud.githubusercontent.com/assets/5247438/9251661/041bfec2-41dd-11e5-9096-59a4bd015624.PNG)

**Comment by mousetraps** [comment]
Unfortunately this is a general Visual Studio issue - all of the WPF controls should be themed, but any of the older WinForms controls (project properties, options pages, etc.) remain unthemed.
