### ISSUE TITLE
labels on folders should only be displayed at the top level

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#368]
This should hopefully make them a little less distracting.

**Comment by kant2002** [comment]
I'm slowly migrate my project from JS to TS. TS files and folders does not have labels in this case. And since we do gradual migration of the existing code, sometimes it is mixed. In that case the labels in the nested folders actually helps me. Just FYI.

**Comment by mousetraps** [comment]
awesome thanks, closing this as by-design both for that reason and because when I investigated it further I remember why I didn't do that in the first place :smiley:

**Comment by mousetraps** [comment]
(the original reason was also that if you set a folder as content type, then you want some immediate response in the UI to indicate that it worked)
