### ISSUE TITLE
IntelliSense Doesn't work for built in modules

### ISSUE THREAD

**Issue by 5an1ty** [Microsoft/nodejstools#372]
var http = require('http');
    http.

This example does not give me any suggestions for methods or properties of the http object.

Using:
node v0.12.7
VS Community 2015
NTVS 1.1

**Comment by billti** [comment]
Is this across all projects, or a one-off? Existing code or new code? Are you analysis settings not set to "none"? Does it work if you create a brand new console app? You mention build-in modules, so does it work for your own modules?

**Comment by 5an1ty** [comment]
This is across all projects, even when I create a brand new console app. It does indeed work on my own modules that I require. I only have issues with for example: fs, http, cluster, ...

**Comment by billti** [comment]
We fixed an issue causing this in our latest RC (see https://github.com/Microsoft/nodejstools/releases/tag/v1.1-RC.2.1). This should resolve the issue. If not, please comment and we'll reopen. Thanks!
