### ISSUE TITLE
Project Dependencies and Edge.js Integration?

### ISSUE THREAD

**Issue by MeirionHughes** [Microsoft/nodejstools#374]
Just to throw this idea out there; would it be possible to have support for integration between node.js, edge.js and dotNet libraries?

Use case would be to have a node.js project that is dependent on a .Net project. In my case, I want the dotNet side for CPU heavy tasks and feeding the results back into the node.js server. Edge.js lets me so this, but more native support for doing this in visual studio (plug debugging) would be great.

**Comment by mousetraps** [comment]
Intriguing suggestion, but I don't think EdgeJS is popular enough that we would consider adding explicit support for it anytime soon.

**Comment by MeirionHughes** [comment]
Fair enough; in the end I actually abandoned node.js in favor of Owin (Nowin implementation) purely because I need direct access to nuget libraries that do heavily lifting.
