### ISSUE TITLE
Enable script debugging in Visual Studio from Chrome

### ISSUE THREAD

**Issue by noopole** [Microsoft/nodejstools#375]
Hi- 

Since Node.js and Chrome share V8 as a JS engine, would it be complicated to make NTVS debug JS code from Chrome, as VS can do for IE with ASP.NET? 

Thank you by advance for your anwser.

**Comment by billti** [comment]
Visual Studio 2015 already supports debugging Chrome, that's how the the Cordova tools work. We are investigating ways to make debugging more seamless across scenarios, but this is general VS features and not NTVS specific. Feel free to upvote features on the User Voice site ( https://visualstudio.uservoice.com/forums/121579-visual-studio )
