### ISSUE TITLE
Mocha won't find your NodeJS unit tests in Visual Studio 2013

### ISSUE THREAD

**Issue by mick8moses** [Microsoft/nodejstools#376]
Scenario: Creating new NodeJS project from existing Node.js Code
Behavior: If you create your VS project file (*.njsproj) outside of the master folder where your previously created node project is located - the unit tests of you node project will not be discovered in Visual Studio.

**Comment by billti** [comment]
Have you followed the steps to set the test framework? See https://github.com/Microsoft/nodejstools/wiki/Test-Explorer#discovering-mocha-tests

**Comment by mick8moses** [comment]
yes it actually has directly to do with where the nsproj file is created. For example I have two nodejs projects being worked on by other developers using a different IDE and using Git for Source Control. I create a folder (let's call it SolutionFolder) and download the two NodeJS projects into it from Git (let's call them NodeJS_ProjA & NodeJS_ProjB). Now what I had planned to do was keep all the Visual Studio artifacts in my SolutionFolder that is not being checked into Git. But if the nsproj files are there - the unit tests are undiscoverable, move it to NodeJS_ProjA folder - no problem unit tests immediately found. Another interesting much more annoying bug - is that the solution file if not in the NodeJS_ProjA folder will not show the source control icons (locks & checks) - I'll put this in another bug report.

**Comment by kaustavdm** [comment]
To add to the issue, in my case, the `pwd` for the tests was in the directory in which the test files were kept, and not in the root of the project. I haven't found any way to run the tests from the root of the project. Not sure if this deserves to be a separate issue. It looks to be related. It would greatly help if a distributable work-around was suggested.

**Comment by billti** [comment]
@kaustavdm I don't understand what you mean by `the pwd for the tests was in the directory in which the test files were kept`. Could you please clarify?

@mick8moses There may well be expectations in the code that the NTVS project file is in the root of the project (i.e. same location as package.json, .gitignore, etc...), and it therefore looks for the tests in the relative `./test' folder - just as Mocha does.

Do the tests get discovered and executed correctly if you go to the properties of the JavaScript file and mark it as a Mocha test file? (see https://github.com/Microsoft/nodejstools/wiki/Test-Explorer#discovering-mocha-tests)

**Comment by kaustavdm** [comment]
@billti I don't intend to divert OP's point, but here is what I meant: Say your project structure is like this:

```
- tests/
   | - repo.test.js
- main.js
- package.json
```

`repo.test.js` contains Mocha tests, and it needs to test to see if `main.js` exists. Now, if I run `npm test` in the root of the project, the working directory is set to the root of the project. In this case, this is what I have to do to check if `main.js` exists:

```js
var exists = fs.existsSync("./main.js");
```

But, when I run the same tests in Visual Studio, the working directory is set to the directory in which the test file exists, in this case, it is set to `"./tests/"`. So, the code above has to change to:

```js
var exists = fs.existsSync("../main.js");
```

I solved compatibility using a [workaround](https://github.com/applait/artysee/blob/master/package.json#L8).

**Comment by paulvanbrenk** [comment]
We should set the working dir to the project root.

**Comment by paulvanbrenk** [comment]
@kaustavdm well that took forever, but it's fixed in Visual Studio Update 8. 

`npm` from the root of the project and the Test Explorer in VS now behave the same.
