### ISSUE TITLE
Source Control icons not showing up in Visual Studio IDE if soln file is not kept in the NodeJS project file

### ISSUE THREAD

**Issue by mick8moses** [Microsoft/nodejstools#378]
For example I have two nodejs projects being worked on by other developers using a different IDE (say Webstorm) and using Git for Source Control. I create a folder (let's call it SolutionFolder) and download the two NodeJS projects into it from Git (let's call them NodeJS_ProjA & NodeJS_ProjB). If the solution file is kept in the SolutionFolder the projects will not show the source control icons (locks & checks). If I create a separate solution file for each project AND keep them in the NodeJS_ProjA & NodeJS_ProjB folders the locks & checks appear. This is an annoying bug because one of the greatest features to me is running multiple projects under one visual studio IDE instance. That way I can run one instance projA and projB within the confines of one IDE and step through them.

**Comment by mjbvz** [comment]
From the description, I believe this is a general Visual Studio issue and not NTVS specific. I was unable to repo it in my testing on the latest release of VS 2015.

Please let me know if you are still running into this and we can try to track down the correct contacts. Thanks.

**Comment by Iviglious** [comment]
Looks like this is an issue with Visual Studio.
I'm experiencing it even now with VS 2017 Pro.
Do you know of a VS thread for this?
Any fix? @mick8moses @mjbvz

**Comment by hempels** [comment]
Same issue with VS 2019. If anyone has created a VS issue, please link it here so we can +1.

I strongly suspect this is related to the node.js tools project system and not a general VS issue since I do not have the same problem with asp.net core projects.

**Comment by ydjopa** [comment]
Source Control Icon not showing up in VS code. Is there any fix yet?
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by tamaspalya** [comment]
For me the problem was that even though I added a new ClassLibrary to my solution, I selected the wrong location. So it only appeared to be within the solution but it was in fact not included in source control. Hope this helps.
