### ISSUE TITLE
100% cpu when hovering over large Node.js Buffer objects

### ISSUE THREAD

**Issue by Pablo76** [Microsoft/nodejstools#387]
Whenever I hover over or touch somehow nodejs Buffer objects I get entire IDE frozen (while node.exe taking 100% cpu). I recall it was working fine with older version of NTVS (I also had node 12.5 back then as I recall).
Now it's completely unusable. Uninstall for me.

**Comment by Pablo76** [comment]
Just an update. I tried to uninstall node 12.7 and installed 12.5, I tried to install latest dev version of NTVS, I tried to install 1.0 version. I tried to do npm -g  update, I tried to deleted all project metadata (*.suo, sdf, .ntvs_analysis.dat etc), in all cases when I simply try to hover over a Buffer variable I get node.exe 100% cpu and unresponsive VS for 10-15 seconds (Usually I had to kill node.js).
Everything uninstall, we'll try in 2016 maybe it will be better than chrome debugging.

**Comment by billti** [comment]
Thanks for reporting. So when you hit this the first time, where you using an older version of NTVS? (I ask as we made a fix here recently - https://github.com/Microsoft/nodejstools/issues/248 - and I'm thinking if this may have regressed something).

**Comment by Pablo76** [comment]
No, i think I haven't seen it before installing latest. But as I wrote I tried to instal old, but it didn't help. The only other thing that's different from when it was ok that I had VS upd4, now it's update 5

**Comment by mousetraps** [comment]
@Pablo76 would you mind taking a screenshot of your task manager details view (sorted by cpu or memory - whichever issue is relevant to you) with the "command line" column included? This'll help us figure out where it's coming from. 

It would also be helpful if you could provide us with some of the information as described in: https://github.com/Microsoft/nodejstools/issues/44#issue-67240928

**Comment by Pablo76** [comment]
I tried a few things and I have specific pattern that always results in this problem.
![1](https://cloud.githubusercontent.com/assets/13692617/9551699/4f52226a-4dbb-11e5-91e5-032500320215.png)

On 1.png you can see that I'm on first break point, at this point if I hover over 'parser' I get all teh members with no issues. However, if I continue and try to do the same from within callback then I get 100% on node.exe (see 2.png).
![2](https://cloud.githubusercontent.com/assets/13692617/9551711/5e7c95c2-4dbb-11e5-82c4-51558ce7298b.png)

as you can see, tall the code in there is simple and all the libs are public code (flvee from npm). I wanted to package a simple zip with everything, but when I tried to put some dummy file instead of 1.flv I got different behavior. Moreover, I noticed that the bigger the file size that I try to read the longer it freezes when I try to hover over parser variable. With empty file I get instant list of parer's members, with a random file (50MB txt file) I get a noticeable delay already. In my original code 1.flv is 1GB ant takes like 15 seconds whenever I hover over most of variables inside my code.

**Comment by billti** [comment]
Seems like this is probably Node trying to evaluate the expression and return the contents to the debugger, which in this case is the contents of a huge file. I see similar lock-ups if I have an array with thousands of items and try to expand the array in the Locals window (I'm only interested in seeing the initial elements, but it appears to be trying to retrieve/display all of them).

Can you confirm that this only occurs when trying to investigate the values of very large objects? We'll have to see if there is anything we can do here. (As we don't know the size of the object until we request it from Node and get it back).

**Comment by mousetraps** [comment]
One idea is essentially chunking the output, so rather than showing all 10000 entries, force people to drill down a bit more (show 100 entries at a time.) This would also make navigation much easier. So if we wanted to display 200 entries, for instance, rather than listing them all outright, we would force people to expand to view the full set of entries.
```js
  [0..99] 
  [100..199]
```

Or maybe even a hybrid approach would be appropriate.
```
  [0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6..99]
  [100..199]
```

**Comment by billti** [comment]
Right, but do we still have to _get_ the entire value from Node in the first place? i.e. We can chunk the data fine on our side once we have it, but that might be too late if the big cost is _getting_ the data from Node. Can we request it in chunks from Node?

**Comment by Pablo76** [comment]
Well, when debugging with node-inspector there is no such problem. E.g.
it's not node that does something wrong, it's the node-vs that asks node
for something that it should not have asked perhaps.
Maybe parser object has internal arrays of read buffers, so when I hover
over parser node-vs tries to populate all possible expansion of member
variables of that parser var?..

**Comment by paulvanbrenk** [comment]
This is fixed when debugging Node 8
