### ISSUE TITLE
NTVS 1.1 folder naming doesn't work with web publish

### ISSUE THREAD

**Issue by tomscharf** [Microsoft/nodejstools#388]
When folders are renamed from "public" to "public (browser)" or "public (node)" this breaks web publishing as it now publishes files to a "public (browser)" folder instead of "public".

**Comment by billti** [comment]
The suffix should only be in the display name, not the actual underlying folder. If we're trying to deploy using the display name, seems like we'll need to fix this. Thanks for reporting!

**Comment by tomscharf** [comment]
Right.  The local folder keeps the correct name, but web publish seems to use the display name when sending it to the server via FTP.  I had to revert back to v1.0 and this resolved it for now.

**Comment by mousetraps** [comment]
Just sent a PR out for this (see #439). Just to make sure we're on the same page here since it took me some time to get a repro... normal publish-project was working fine, but right-clicking and publishing a specific folder was not?

**Comment by tomscharf** [comment]
I was right clicking in solution explorer and using publish for specific folders.  That's the "normal" publish for my work flow.  That's just the way I've always done it.  

On another subject, the thing that just drives me crazy right now is getting intellisense working properly, or at all.  I know you guys are aware of this problem.    I really, really miss this coming from C#.  I know there are technical limitations here related to languages, but getting this working solidly would be a huge step forward.  I can't seem to get anything working for nodejs modules or JavaScript libraries, and I can't seem to figure out what is supposed to actually work and what is a known technology limitation currently, or how to debug the problem.  Lost in the weeds....

**Comment by billti** [comment]
@tomscharf We just pushed a new release with the fix for the publishing, and a couple of fixes for intellisense issues. See https://github.com/Microsoft/nodejstools/releases if you'd like to check it out. Thanks!
