### ISSUE TITLE
Npm node doesn't display extraneous npm v3 dependencies when npm cleanup fails

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#394]
This is an edge case. In some cases, npm will be installing a package, installation fails, and some of the top level dependencies fail to be cleaned up. This results in top level dependencies with a "_requiredBy" property that are nonetheless extraneous because the package that requires them is not installed. NTVS will subsequently fail to display these dependencies in the npm node.

**Comment by paulvanbrenk** [comment]
No clear repro, probably fixed in NPM 5
