### ISSUE TITLE
Feature: Typescript fallback intellisense

### ISSUE THREAD

**Issue by mavericken** [Microsoft/nodejstools#404]
I find myself torn between using Typescript and JavaScript.  The JavaScript tooling has decent tooling that Just Works.  Typescript has really high quality tooling that can be a pain to use.

It seems to me it would be possible to bring the good qualities of both together in nodejstools.  Check out this example:
![image](https://cloud.githubusercontent.com/assets/7833752/9590218/4479af5a-5001-11e5-87e9-1beac2ce67d0.png)
--
![image](https://cloud.githubusercontent.com/assets/7833752/9590267/96bbe634-5001-11e5-9329-8069f2a1aa51.png)

No intellisense of course, because it is any type.  But wait, if I switch to my compiled JavaScript tab I get something different...
![image](https://cloud.githubusercontent.com/assets/7833752/9590320/d1ce1bde-5001-11e5-99dd-d7d52a5af188.png)
--
![image](https://cloud.githubusercontent.com/assets/7833752/9590325/e274163c-5001-11e5-822a-9d859ade07ca.png)

The idea is to try to automatically fallback to the JavaScript Intellisense when TypeScript is coming up blank.  I suspect it could be a very popular feature, especially if it allows zero config usage of Javascript NPM modules, by doing something like (&lt;any&gt;require)("insert-obscure-untyped-javascript-package-here").

**Comment by NoelAbrahams** [comment]
> Typescript has really high quality tooling that can be a pain to use

I'm sure the TypeScript team would be keen to know the pain points of using their tooling.

**Comment by mjbvz** [comment]
Going forward, we plan to move both our JavaScript and Typescript Intellisense to use the Typescript language service. This will result in a much more consistent experience across JS and TS for NTVS, and a more consistent Intellisesnse experience with VS Code and other tools as well. Additionally, the Typescript language service is being actively developed and using it will hopefully allow NTVS to support new features and pick up enhancement much more quickly. 

Check of the NTVS 1.2 Alpha for a preview of the new Typescript language service based Intellisense. Please report any issues you encounter and let us know if you have any suggestions. 

Thanks.
