### ISSUE TITLE
TCP connection logic happens synchronously on the UI thread

### ISSUE THREAD

**Issue by billti** [Microsoft/nodejstools#408]
See comments in the code on pull request https://github.com/Microsoft/nodejstools/pull/406

TCP connection attempts by default retry a couple times with a delay inbetween. This means they can take a couple seconds to complete. As such, we should ensure our TCP connections aren't happening via blocking calls on the UI thread.

**Comment by paulvanbrenk** [comment]
Not investing in the Node 6 debugger.
