### ISSUE TITLE
F10 stops on last line of file

### ISSUE THREAD

**Issue by ASayre** [Microsoft/nodejstools#41]
If there is a line of code on the last line of a file, it will appear as if F10 doesn't do anything when trying to F10 over that line the first time.

If there is whitespace on the last line of a file, when F10'ing the prior non-empty line, we will stop at that last line.

for reference, When we F10 again, it'll goto the end of module.js.

**Comment by paulvanbrenk** [comment]
This doesn't reproduce for me when debugging Node 8+
