### ISSUE TITLE
When open large file VS freezes.

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#416]
I by mistake open file with DevExtreme file, and the whole VS freeze. It probably analyzing the file, but I don't need it. At least not at this price. I would like to be able close this file and stop analysis. 
Take ~5 minutes, and I almost kill it, but during writing report it unfreeze.

After reopening VS and trying to open same file issue was not reproduced. But maybe this is related to #415. 
I'm running 1.1. RC2

**Comment by billti** [comment]
Is DevExtreme a JavaScript file? If not, I doubt NTVS was trying to analyze it. It's probably just a generic problem with VS trying to open massive files.

**Comment by kant2002** [comment]
Yes. This is Javascript library. Maybe you are right  and this is VS problem

**Comment by mjbvz** [comment]
I created a 20MB 500,000 line JS file and could repo this with "Full Intellisense". But with ES6 Intellisense preview in NTVS 1.2 alpha, I no longer see a full hang. There is a 2-3second delay opening the file while VS does some work, but after that the file loads just fine. You can browse and view the file just fine now, but the editing experience is pretty horrible (lots of delays) as most tools are not optimized for large single files like this.
