### ISSUE TITLE
Errors in the TypeScript Mocha unit test template file

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/nodejstools#418]
In both VS 2015 and VS 2013, adding a TypeScript Mocha unit test file will introduce errors to the project. 
Screenshot:
![1](https://cloud.githubusercontent.com/assets/1171301/9691820/ccd130da-52f9-11e5-9fff-bcf203666129.png)

**Comment by AronVanAmmers** [comment]
As a workaround, installing typings for mocha, for example by using `tsd`:
```
tsd install mocha --save
```

Ensure the type definitions are referenced in the main file:

```
/// <reference path="typings/tsd.d.ts" />
```

The behaviour out of the box should not cause errors though.

**Comment by mjbvz** [comment]
Updated workaround using `typings`:

1. Install [typings](https://github.com/typings/typings)
2. In project directory, from the command prompt run `$ typings install dt~mocha --global` to get the mocha typings that tell Typescript about `describe` and `it`
3. In the unit test file, add `/// <reference path="typings/globals/mocha/index.d.ts" />` to the top of the file

**Comment by paulvanbrenk** [comment]
Not sure we can do this through the wizard, but you should just install the typings.
