### ISSUE TITLE
Cannot start the node interactive window in VS 2013

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/nodejstools#419]
When trying to open the node interactive window via ``Ctrl + K, N``, an error message would pop out:
![capture](https://cloud.githubusercontent.com/assets/1171301/9691846/f9fb40a0-52f9-11e5-8eb8-4e0e72d05ac1.PNG)

**Comment by learkk** [comment]
same error with VS Community 2015

**Comment by billti** [comment]
This is a MEF issue that sneaked in. Seems to be inconsistent (based maybe on load order when scanning the DLLs). I pushed a fix to master and will re-release the RC soon ( see https://github.com/Microsoft/nodejstools/commit/ca2f319199d9b98a9a000021a6066a9208314133 ).

**Comment by billti** [comment]
@learkk We just pushed a new release with this fix. See https://github.com/Microsoft/nodejstools/releases if you'd like to check it out. Thanks!
