### ISSUE TITLE
Visual Studio crashes on exception.

### ISSUE THREAD

**Issue by MichaelMcGlothlin** [Microsoft/nodejstools#42]
I'm trying to use generators with harmony enabled. When I try to run the program from Visual Studio it crashes with this error. If I run it directly from node at the command-line it doesn't give me any errors. I don't seem to be able to catch this exception.

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
```

**Comment by mousetraps** [comment]
That's no good. Would you mind providing some simple repro code?

I tried with the following (with --harmony and --use_strict flags), and no dice.
``` javascript
var argumentsIterator = argumentsGenerator('a', 'b', 'c');

// Prints "a b c"
console.log(
    argumentsIterator.next().value,
    argumentsIterator.next().value,
    argumentsIterator.next().value
);

function* argumentsGenerator() {
    for (let i = 0; i < arguments.length; i += 1) {
        yield arguments[i];
    }
}
```

**Comment by mousetraps** [comment]
And just to be clear... you mean the program that Visual Studio is running crashes... not Visual Studio itself, right?

**Comment by mousetraps** [comment]
Any updates on this issue, or are you still blocked?

**Comment by mousetraps** [comment]
closing this as no repro since we haven't heard back, but happy to re-open if you're still running into it.

**Comment by RobertSmart** [comment]
This is now happening to me when I use node-inspector to attach to
