### ISSUE TITLE
Solution explorer unusable (show/hide/delete/.. files)

### ISSUE THREAD

**Issue by arogg** [Microsoft/nodejstools#421]
Steps to reproduce (my exact setup is at bottom of this post):

create new blank node typescript project
install the npm packages i have installed ( see bottom of post). do NOT add node_modules to project
how try doing show/hide all files (button at top of solution explorer) multiple times and see how slow it is. this also seems to effect the performance of deleting files from the solution explorer negatively.

further observations:

- hiding node_modules folder (in windows) with npm 3.x fixes the problem, but ONLY if there are no typescript files in the project, which obviously is never the case. hide node modules and add 3 files with "import bla = require("./somefile")" (to explorer, not the project) and the problem is there again. only removing node_modules on npm 3.x fixes the problem
- using npm 2.x while hiding node_modules in explorer fixes the problem for good. as i said using npm 3.x i have to remove the node_modules folder to fix the problem, but then i can't use node without node_modules..
- node.js intellisense is set to "no intellisense" and "save to disk" is set to "disabled"
- so obviously NTVS is doing something or too much of which it should not do when performing actions in the solution explorer

---
		i'm using:
		- windows 7 x64 pro
		- npm 3.3.2
		- visual studio ultimate 2013 update 5
		- NTVS 1.1 RC2
		- NOT using resharper (disabled)
               - typescript 1.6 (the beta that came out)

my packages:

 "URIjs": "^1.16.0",
    "async": "^0.9.0",
    "asyncawait": "^0.7.4",
    "beepbeep": "^1.2.0",
    "bluebird": "^2.9.33",
    "bower": "^1.4.1",
    "browser-sync": "^2.0.0-rc9",
    "browserify": "^10.2.3",
    "browserify-shim": "^3.8.9",
    "chai": "^3.2.0",
    "chalk": "^1.1.1",
    "del": "^1.1.1",
    "elementtree": "^0.1.6",
    "event-stream": "^3.3.1",
    "exorcist": "^0.4.0",
    "exposify": "^0.4.3",
    "extend": "^3.0.0",
    "fs-extra": "^0.16.3",
    "globby": "^1.2.0",
    "gulp": "gulpjs/gulp#4.0",
    "gulp-batch": "^1.0.5",
    "gulp-cached": "^1.1.0",
    "gulp-concat": "^2.5.2",
    "gulp-count": "^0.1.0",
    "gulp-debug": "^2.0.1",
    "gulp-filter": "^2.0.2",
    "gulp-if": "^1.2.5",
    "gulp-inject": "^1.1.1",
    "gulp-insert": "^0.4.0",
    "gulp-order": "^1.1.1",
    "gulp-plumber": "^1.0.0",
    "gulp-remember": "^0.3.0",
    "gulp-rename": "^1.2.2",
    "gulp-replace": "^0.5.4",
    "gulp-sourcemaps": "^1.5.1",
    "gulp-sync": "^0.1.4",
    "gulp-tap": "^0.1.3",
    "gulp-typescript": "https://github.com/arogg/gulp-typescript/tarball/master",
    "gulp-util": "^3.0.4",
    "lazypipe": "^0.2.3",
    "lodash-node": "^3.5.0",
    "longjohn": "^0.2.7",
    "main-bower-files": "^2.6.2",
    "merge-stream": "^0.1.7",
    "microtime": "^1.4.2",
    "mocha": "^2.2.5",
    "node-windows": "^0.1.7",
    "npm": "^2.13.0",
    "path-posix": "^1.0.0",
    "pretty-data": "^0.40.0",
    "promethify": "^0.1.0",
    "proxyquire": "^1.7.1",
    "ps-node": "0.0.4",
    "source-map-support": "^0.3.2",
    "stream-series": "^0.1.1",
    "stream-to-promise": "^1.0.4",
    "temp": "^0.8.1",
    "through-pipes": "0.0.4",
    "through2": "^0.6.5",
    "tsd": "^0.5.7",
    "tsify": "^0.11.2",
    "typescript": "^1.5.3",
    "typescript-require": "https://github.com/arogg/typescript-require/tarball/master",
    "underscore.string": "^3.1.1",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^3.2.1",
    "winston": "^0.9.0",
    "xtend": "^4.0.0",
    "yargs": "^3.15.0"

**Comment by billti** [comment]
Thanks for the report. If you just open the TypeScript file as a loose file (i.e. outside the context of a Node project) do you see the same behavior also? I'm trying to determine if this is purely a TypeScript issue, or if NTVS is involved.

Another useful test would be to add a 'tsconfig.json' file to the root and exclude the node_modules folder, so that TypeScript doesn't crawl it looking for TypeScript files (see https://github.com/Microsoft/TypeScript/wiki/tsconfig.json ).

If you're able to try the above that would be helpful in narrowing the cause, else I'll try and set up a repro when I get time. Thanks!

**Comment by mjbvz** [comment]
I've tried to repo this using the provided info on NTVS 1.2 alpha but was unable to. @arogg If you are still running into this problem, please reopen this issue with some additional repo steps so we can better investigate. Thanks.
