### ISSUE TITLE
Breakpoints in TypeScript unit tests work only without js-out dir

### ISSUE THREAD

**Issue by arogg** [Microsoft/nodejstools#422]
Steps to reproduce:

my project structure:
- app
  - ..some typescript files
- tests
  - mytestfile.ts

make sure mytestfile.ts contains at least a mocha unit test
make sure a js out dir is not set in project opts
i set breakpoint in mytestfile.ts and run corresponding mocha unit test in debug mode via test explorer
breakpoint is hit normally
then specify a js out dir in project opts
rebuild solution
run the unit test again in debug mode via test explorer
breakpoint is not hit!

further observation: "debugger;" statements are always hit.
    ---
            i'm using:
             - windows 7 x64 pro
        - npm 3.3.2
        - visual studio ultimate 2013 update 5
        - NTVS 1.1 RC2
        - typescript 1.6 beta

**Comment by kant2002** [comment]
Please see #380 or #322

**Comment by paulvanbrenk** [comment]
There is another issue when debugging TypeScript unit tests, but when that is fixed this will work as expected.
