### ISSUE TITLE
Error retrieving websocket debug proxy information from web.config

### ISSUE THREAD

**Issue by wein2011** [Microsoft/nodejstools#423]
I created a new project based on the the Blank Azure Node.js Web Application in Visual Studio Community 2015 with the node tools 1.1 RC2 installed. I am able to publish the project to my Azure account in Debug mode without problems and it runs fine. When I try to the menu command Attach Debugger (Node.js). I get the error:

Could not attach to node.exe process on Azure Website at http://<xxx>.azurewebsite.net/.
Error retrieving websocket debug proxy information from web.config.

I am running on Windows 10 and the application configuration in Azure has Web Socket enabled.

Any suggestions what to look for next?

**Comment by billti** [comment]
Have you read through the information on https://github.com/Microsoft/nodejstools/wiki/Advanced-Debugging ? Specifically, can you ensure that the web.debug.config file is present, and also test if you can attach directly as per the last section titled `Attaching without Server Explorer`.

**Comment by wein2011** [comment]
Yes, I did follow the information in that link including the long list of items of if you don't see the command. BTW, that link is really good. The web.debug.config file is also present. I had not tested Attaching without Server Explorer. So I just tried it and fortunately it works fine. So I tried to attach again through the Server Explorer unfortunately still no luck.
