### ISSUE TITLE
Attaching to Node process launched with --debug-brk causes Node error

### ISSUE THREAD

**Issue by billti** [Microsoft/nodejstools#425]
Launching with `node debug` or `node --debug` and then attaching works, however when launching a process with `node --debug-brk <script>` to cause a break on the first line, and then attaching VS via NodeJS Remote Debugging transport, results in the below error in the Node process:

```
Debugger listening on port 5858
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
```

This is with NodeJS 0.12.7 and NTVS 1.1 RC2.

**Comment by billti** [comment]
Some more data: It errors when it disconnects in NodeRemoteEnumDebugProcesses.cs@92

```c#
    string request = @"{""command"":""disconnect"",""seq"":1,""type"":""request"",""arguments"":null}";
    request = string.Format("Content-Length: {0}\r\n\r\n{1}", request.Length, request);
    buffer = Encoding.UTF8.GetBytes(request);
    stream.WriteAsync(buffer, 0, buffer.Length, new CancellationTokenSource(5000).Token).GetAwaiter().GetResult();
```

This occurs just when entering the 'localhost:5858' and clicking 'Refresh' to see the processes in the `Attach` dialog.

According to the comments just above these lines, sending a `disconnect` is required though. Need to investigate more...

**Comment by samizzo** [comment]
I'm seeing this now that I've started using the `cluster` module. I start my application which forks. Then I try to attach to the newly forked process, where the debugger is listening on port 5859, and as you mentioned, when I click 'Refresh' it dies. Do you have any workaround for it? It seems I *have* to connect the debugger because otherwise the new forked process just sits there waiting for a debugger to connect.

**Comment by samizzo** [comment]
Is there any way to start node with --debug instead of --debug-brk?

**Comment by paulvanbrenk** [comment]
This still happens on Node 6, and NTVS 1.3... it doesn't on Node 8 though.

**Comment by paulvanbrenk** [comment]
Closing as this works as expected in Node 8, and there is a workaround
