### ISSUE TITLE
Installer MSI doesn't download in edge on windows 10

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#426]
Very strange but nothing happens if I click on the download button on codeplex page (version 1.1)

If I copy the URL for the MSI to windows it works fine.

**Comment by mousetraps** [comment]
Hmm, could you clarify which link you're trying to hit? Can't reproduce the issue :-/

**Comment by SteveALee** [comment]
Oops, it seems it is not the codeplex page but the new VS one

Go here:
https://visualstudiogallery.msdn.microsoft.com/92452068-2478-45aa-8a63-19e2b9bc11d1

and click on the purple download button
https://visualstudiogallery.msdn.microsoft.com/92452068-2478-45aa-8a63-19e2b9bc11d1/file/169855/1/NTVS%201.1%20RC%20VS%202015.msi

Just tried again on the very dodgy hotel wifi and all that seems to happen is the page refreshes.

**Comment by mousetraps** [comment]
Hrm, I can't repro this at all... I think @billti was running into something similar earlier?

**Comment by SteveALee** [comment]
Works for me now (windows 10 build 10547)

**Comment by SteveALee** [comment]
Works for me now (windows 10 build 10547)
