### ISSUE TITLE
WAT70 when building Node.js Cloud Service project using msbuild

### ISSUE THREAD

**Issue by maartenjanson** [Microsoft/nodejstools#428]
I receive a _WAT70_ error when building an Azure Cloud Service Node.js project from the commandline using msbuild.

Dev Environment: Visual Studio 2015, MS Azure Tools 2.7 and NTVS 1.1RC VS2015

Steps to reproduce:
- Open VS, and select File- > New -> Project
- Select 'Other Languages' -> JavaScript -> Node.js and Select 'Cloud Service' as project type
- Select a Web Role project to be included and successfully build it in VS.
- Open a 'MSBuild Command Prompt for VS2015' and browse to the directory that contains the Solution file of the project that I just created
  -Run: MSBuild /target:Publish

If I copy a dummy exe into the project then the build / publish step works.. However this is not acceptable in production.

See detailed error output below...

======= MS Build output  =======
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 03/09/2015 15:26:53.
Project "C:\Users\MJ\Desktop\AzureCloudService1\AzureCloudService1.sln" on node 1 (Publish target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
The target "MvcBuildViews" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.Publishing.targets (843,131)" does not exist in the project, and will be ignored.
Project "C:\Users\MJ\Desktop\AzureCloudService1\AzureCloudService1.sln" (1) is building "C:\Users\MJ\Desktop\AzureCloudService1\AzureCloudService1\AzureCloudService1.ccproj" (2) on node 1 (Publish target(s)).
ResolveServiceDefinition:
  Source Service Definition: ServiceDefinition.csdef
  Target Service Definition: bin\Debug\ServiceDefinition.csdef
ResolveServiceConfiguration:
  Target Profile: Cloud
  Service Configurations: ServiceConfiguration.Local.cscfg;ServiceConfiguration.Cloud.cscfg
  Looking for a service configuration file named: ServiceConfiguration.Cloud.cscfg
  Source Service Configuration: ServiceConfiguration.Cloud.cscfg
  Target Service Configuration: bin\Debug\ServiceConfiguration.cscfg
FindServiceDefinition:
  ServiceDefinition in bin\Debug\ServiceDefinition.csdef
FindServiceConfiguration:
  ServiceConfigurationFile is bin\Debug\ServiceConfiguration.cscfg
CopyServiceModel:
  Running CopyServiceModel target
  Copying the service configuration.
  Copying file from "ServiceConfiguration.Cloud.cscfg" to "bin\Debug\ServiceConfiguration.cscfg".
  Copying the service definition.
  Copying file from "ServiceDefinition.csdef" to "bin\Debug\ServiceDefinition.csdef".
ValidateRoleProjects:
  Web Project        is ..\WebRole1\WebRole1.njsproj
  Worker Project     is 
ResetTargetNames:
  Reset the targetDir      to csx\Debug\
  Reset the TargetName     to ServiceDefinition
  Reset the TargetExt      to .rd
  Reset the TargetFileName to ServiceDefinition.rd
  Reset the TargetPath     to csx\Debug\ServiceDefinition.rd
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.7\Microsoft.WindowsAzure.targets(1329,5): error : WAT070 : The referenced assembly C:\Users\MJ\Desktop\AzureCloudService1\WebRole1\WebRole1.exe was not found. Please make sure to build the role project that produces this assembly before building this Microsoft Azure Cloud Service Project. [C:\Users\MJ\Desktop\AzureCloudService1\AzureCloudService1\AzureCloudService1.ccproj]
Done Building Project "C:\Users\MJ\Desktop\AzureCloudService1\AzureCloudService1\AzureCloudService1.ccproj" (Publish target(s)) -- FAILED.
Project "C:\Users\MJ\Desktop\AzureCloudService1\AzureCloudService1.sln" (1) is building "C:\Users\MJ\Desktop\AzureCloudService1\WebRole1\WebRole1.njsproj" (3:3) on node 1 (Publish target(s)).
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4874,5): error MSB3094: "DestinationFiles" refers to 2 item(s), and "SourceFiles" refers to 1 item(s). They must have the same number of items. [C:\Users\MJ\Desktop\AzureCloudService1\WebRole1\WebRole1.njsproj]
Done Building Project "C:\Users\MJ\Desktop\AzureCloudService1\WebRole1\WebRole1.njsproj" (Publish target(s)) -- FAILED.
Done Building Project "C:\Users\MJ\Desktop\AzureCloudService1\AzureCloudService1.sln" (Publish target(s)) -- FAILED.

Build FAILED.

"C:\Users\MJ\Desktop\AzureCloudService1\AzureCloudService1.sln" (Publish target) (1) ->
"C:\Users\MJ\Desktop\AzureCloudService1\AzureCloudService1\AzureCloudService1.ccproj" (Publish target) (2) ->
(VerifyRoleReferences target) -> 
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.7\Microsoft.WindowsAzure.targets(1329,5): error : WAT070 : The referenced assembly C:\Users\MJ\Desktop\AzureCloudService1\WebRole1\WebRole1.exe was not found. Please make sure to build the role project that produces this assembly before building this Microsoft Azure Cloud Service Project. [C:\Users\MJ\Desktop\AzureCloudService1\AzureCloudService1\AzureCloudService1.ccproj]

"C:\Users\MJ\Desktop\AzureCloudService1\AzureCloudService1.sln" (Publish target) (1) ->
"C:\Users\MJ\Desktop\AzureCloudService1\WebRole1\WebRole1.njsproj" (Publish target) (3:3) ->
(_CopyFilesToPublishFolder target) -> 
  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4874,5): error MSB3094: "DestinationFiles" refers to 2 item(s), and "SourceFiles" refers to 1 item(s). They must have the same number of items. [C:\Users\MJ\Desktop\AzureCloudService1\WebRole1\WebRole1.njsproj]

```
0 Warning(s)
2 Error(s)
```

Time Elapsed 00:00:00.58

**Comment by zhengbli** [comment]
May be related to https://github.com/Microsoft/PTVS/issues/128

**Comment by mousetraps** [comment]
Indeed, we run into the same issues that PTVS has with deployment scenarios. Fact is we pretend to be .NET in a lot of places, and apparently we're not convincing enough here. We need to work with partner teams to make any progress on this issue.

**Comment by moncapitaine** [comment]
Same issue here. No one ever deployed with VSTS an nsproj cloud service? Any progress since Sep 2015?

Regards,
Michael

**Comment by satyarapelly** [comment]
Same issue here, I'm not able to automate the build of PTVS (Python Django Cloud Service application) using MSBuild V14.0. 

Build FAILED.

"C:\Test\LexBadgrAzureCloudService\LexBadgrAzureCloudService.sln" (publish targ
et) (1) ->
"C:\Test\LexBadgrAzureCloudService\LexBadgrAzureCloudService\LexBadgrAzureCloud
Service.ccproj" (Publish target) (2) ->
(VerifyRoleReferences target) ->
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Windows Azure Too
ls\2.7\Microsoft.WindowsAzure.targets(1329,5): error : WAT070 : The referenced
assembly C:\Test\AzureCloudService\pythonwebapp\pythonwebapp.exe was not found.
 Please make sure to build the role project that produces this assembly before
building this Microsoft Azure Cloud Service Project. [C:\Test\AzureClou
dService\AzureCloudService\AzureCloudService.ccproj]

**Comment by mjbvz** [comment]
@satyarapelly You'll want to follow up with PTVS instead here: https://github.com/Microsoft/PTVS/issues

NTVS and PTVS share a common codebase (common as in copy and pasted between the projects 😭 😭 😭 ) so they'll have to fix this on their side.

**Comment by mousetraps** [comment]
@mjbvz - to be fair, it's not copy pasted - it's in a git subtree, it's just that we tend not to sync very often, so for one-off fixes, it tends to be easier to copy/paste rather ;-)

**Comment by paulvanbrenk** [comment]
Closing while we figure out what to do with Cloud Services.

**Comment by ross-bohr** [comment]
@paulvanbrenk , Have you figured out what to do with Cloud Services already? 

As a workaround: Could we use the Visual Studio feature "Publish" through devenv somehow , instead of calling MSBuild directly (as it does not yet work for NodeJS ACS projects) ? If this is possible, could you provide some details how to achieve it ?

**Comment by paulvanbrenk** [comment]
@ross-bohr The "publish" feature also seems to invoke the build step, we're currently leaning to writing up some documentation on how to do this using the Azure CLI.
