### ISSUE TITLE
Need guidelines on how to debug fullstack solution

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#43]
While the documentation and tutorials are great for debugging the server-side node code there is almost no info on how to debug a full stack solution - ie how do we easily switch between debugging node and web browser contexts. Ideally this would be seamless. 

You hint at this in a article saying that if client cde is nested in the node directory structure you should change the build action to "content" from compile. That stops client code messing up server debug but how do we debug client side. We could have a separate project but can projects/solutions be nested? Or what is a sensible director structure so that client can be debugged and node can server the code? 

In addition, some pointers to info on general web debugging in VS would be useful. Most resources that I can locate assume IIS or .NET solutions or Win.JS in modern App context on client side. What about the simplest case of when we just use HTML5 in a browser of our choice and perhaps JQuery or a framework? 

I think VS could be a great tool to rival say WebStorms (VS has better licensing) so this will be required to ease onboarding

copied from: https://nodejstools.codeplex.com/workitem/1909

**Comment by mousetraps** [comment]
Documentation is now available here: https://github.com/Microsoft/nodejstools/wiki/Working-with-Browser-(Clientside)-JavaScript-in-NTVS

**Comment by mousetraps** [comment]
@SteveALee just an fyi since you originally filed this. And as always, feedback is much appreciated :)

**Comment by SteveALee** [comment]
Excellent - thanks
