### ISSUE TITLE
Node v4 x64 profiling not displaying function names

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#434]
Starting with a basic express application, launching profiling and loading some of the pages yields:
![image](https://cloud.githubusercontent.com/assets/762848/9769208/a37f43f6-56dd-11e5-9d0d-78a12ee5a46f.png)

We have a similar issue (#299), where the function names were being displayed, but function code view was not visible. In this case, however, the function names aren’t being displayed at all – it just reports [Unknown]

**Comment by mousetraps** [comment]
duplicate of #362

**Comment by billti** [comment]
Are you sure you duped this to the right one? They don't seem related.

**Comment by mousetraps** [comment]
@billti oops, thx for catching that :smiley:

**Comment by mousetraps** [comment]
From the manual test results:

* 0.10.33 x86
  * PASS - Win 8.1, Dev 14
  * PASS - Win 7, Dev 12
  * PASS - Win 10, Dev 12
* 0.10.33 x64
  * PASS - Win 8.1, Dev 11
  * PASS – Win 10, Dev 14 [my box]
* 0.12.7 x86
  * PASS - Win 10, Dev 14
* 0.12.7.x64
  * **FAIL - Win 7, Dev 14**
  * PASS - Win 8.1, Dev 12
* 4.1.0 x86
  * PASS - Win 7, Dev 11
* 4.1.0 x64
  * **FAIL - Win 8.1, Dev 14**

Also worth noting that 0.10.33 x64 still works because it uses the 32-bit address space for profiling logs.
