### ISSUE TITLE
Do we need to accept the Apache 2.0 licence  in the installer

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#436]
Due to the nature of the Apache 2.0 licence (and indeed other OSS licences) I don't think it is usual for an end user to need / want to accept it. It is NOT a EULA after all (hoorah).

@rgardler may shed some light on this?

Perhaps MS have a policy?

**Comment by mousetraps** [comment]
No idea, and we haven't investigated it lately. We do provide some code with the templates that might be open source, so that might be a part of it?

+@aruneshchandra since he may be able to connect with LCA

**Comment by SteveALee** [comment]
@mousetraps I think I was not clear enough. When installing NTVS the licence is shown (fair enough) but we have to accept it by checking a checkbox. Due to the nature of OSS licences, especially Apache 2.0 I'm not convinced it is required for us to accept them at all as you do a EULA.

**Comment by SteveALee** [comment]
Works for me now (windows 10 build 10547)

**Comment by aruneshchandra** [comment]
Let me follow up with our legal team on this and I'll let you know.

**Comment by mousetraps** [comment]
Ahhh yes, we added that checkbox for the privacy statement mainly. We should check on preferred wording and make that clearer.
Sent from my Rotary Phone




On Thu, Sep 24, 2015 at 7:52 AM -0700, "Arunesh Chandra" <notifications@github.com> wrote:
Let me follow up with our legal team on this and I'll let you know.

---

**Comment by mjbvz** [comment]
This is resolved in VS15, where we have a new install experience. Please try installing VS15 Preview 4 and the Node workload to try it out: https://www.visualstudio.com/en-in/news/releasenotes/vs15-relnotes/

Thanks.

**Comment by SteveALee** [comment]
Works for me. In fact I had already done so when I installed VS :)

FYI as I had install VS2015 P4 a while back I followed the usual workflow of Tools->Extensions -> online and found node,js tools 1.2 Alpha 3 for VS 2015 which DOES ask for licence agreement.
