### ISSUE TITLE
IntelliSense  doesn't work for Node v4 (x64)

### ISSUE THREAD

**Issue by mozgurkaymakci** [Microsoft/nodejstools#440]
I am using Node.js Tools 1.1 RC2 and Node v4 (x64) on Visual Studio Enterprise 2015. IntelliSense doesn't work even for built-in modules like OS.

**Comment by billti** [comment]
This may be due to the same issue as https://github.com/Microsoft/nodejstools/issues/417 . We'll be republishing the latest RC shortly.

I'm seeing some flakiness even with this fix however. Could you try the below?

```js
var x = 10;
x.   // <- Do you get intellisense off of x?
```

If `x` is giving you intellisense then it's not the MEF issue, as the language service is working. If even this doesn't work, then it's the fixed MEF issue.

**Comment by mozgurkaymakci** [comment]
No, it doesn't work. When I press "." after "x", no intellisense popup was shown.

**Comment by billti** [comment]
OK. Almost certainly the same issue as #417 then, as looks like the intellisense is totally busted. We pushed a fix and are spinning up a new build which we'll publish shortly. Sorry for the inconvenience.

**Comment by mozgurkaymakci** [comment]
Thank you for your quick response and action.

**Comment by billti** [comment]
@mozgurkaymakci We just pushed a new release with this fix. See https://github.com/Microsoft/nodejstools/releases if you'd like to check it out. Thanks!

**Comment by mozgurkaymakci** [comment]
It works! Thank you very much.

**Comment by iccfish** [comment]
I'm running this issue again, running Node V4(4.2.1) x64 & NTVS 2.1 RC, can't get intellisense work even for global modules and built-in modules.

![ntvs_1](https://cloud.githubusercontent.com/assets/1091653/10493663/ec352ad4-72e4-11e5-91d5-16937fa261f7.png)

![ntvs_2](https://cloud.githubusercontent.com/assets/1091653/10493665/f06d20d4-72e4-11e5-93b5-568c83048c9d.png)

I've tried uninstall NTVS and reinstall, or changed to the latest dev build(10-14), but can't solve this issue.
Please help me to figure the problem.
Thanks.
