### ISSUE TITLE
Interactive Window package should be loaded lazily

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#443]
We are currently loading the package at VS startup, but it should only be loaded on-demand.

**Comment by mjbvz** [comment]
I was looking at deferring the creation of the `JSAnalyzer` yesterday and the REPL window seems like one of the root causes of that issue as well. 

Loading the REPL window causes us to create Javascript analyzer instances and perform a ton of other operations as well that end up using many tens of MBs of memory, for functionality that the user has not even requested.

**Comment by mousetraps** [comment]
Now that we are shipping the Node.js workload, it is more important that we address this issue because it is causing other team's perf tests to regress.
