### ISSUE TITLE
Intellisense for JSON objects

### ISSUE THREAD

**Issue by 00christian00** [Microsoft/nodejstools#447]
JSON objects are a key items for node js, but I don't get autocomplete for them.
Is it unsupported or there is something wrong with my setup?
For example I have this test json object : 
```
var UserData={
    'createaa':true,
    'key': 'user#abc',
    'UUID':1,
      value:{
     
      'gender': 'F',
      'birthday':'26/07/1995',
      
      }
    }
```

If I type UserData I cannot see any of the members of this object.

**Comment by 00christian00** [comment]
Restarted visual studio and now it's working.
In the meantime I also changed node from v4 to 0.12, don't know if that was the cause.

**Comment by mousetraps** [comment]
hmm, doesn't reproduce on my machine and the node version shouldn't have anything to do with it. That said, we have seen some strange behavior at times when there are errors in the code. Closing this for now, but let us know if you run into it again.
