### ISSUE TITLE
JADE

### ISSUE THREAD

**Issue by AeonRush** [Microsoft/nodejstools#453]
I have a question. I'm trying to write a simple JADE template
```
doctype html
html
  head
    title
    link(rel=
  body
```
IDE don't suggest me variants and doesn't highlight syntax.
You are working on support of JADE in NTVS?
Thanks.
Sorry for my English.

**Comment by mousetraps** [comment]
We don't have intellisense, but syntax highlighting should be available. Are you not seeing it? 
![image](https://cloud.githubusercontent.com/assets/762848/9862252/73122a9a-5aec-11e5-8631-cab306b94e48.png)

**Comment by AeonRush** [comment]
Sorry, my fault. On my Dark theme it's not clearly seen.
![screenshot 3](https://cloud.githubusercontent.com/assets/5580112/9862380/277a907c-5b41-11e5-85e6-53d9da798914.png)
Thanks for answer. It's sad that there is no support for Intellisense. Do you plan to support Intellisense?

**Comment by mousetraps** [comment]
Well... we plan to do a lot of things :smiley:... will we get to in anytime soon? Probably not unless we get a significant # of requests for it or an external contribution. That said, maybe there are a few small things we can do to improve the experience.
* do you have an example of syntax highlighting you find more useful?
* would simple tag completions be helpful? 
* any other ideas?

**Comment by mjbvz** [comment]
Closing as out of scope for NTVS.

Although our VS templates use Jade templates, it is by no means the only popular node templating language and proper support should really be handled by a separate, more targeted extension. I do not believe that NTVS plans to invest in improving Jade (pug) support in the ways described.
