### ISSUE TITLE
NTVS links on other properties point to old location

### ISSUE THREAD

**Issue by billti** [Microsoft/nodejstools#461]
The link on the rotating banner on the page at http://azure.microsoft.com/en-us/develop/nodejs/ points to https://nodejstools.codeplex.com/ .

Also the link in the footer at https://www.visualstudio.com/features/node-js-vs also points to https://nodejstools.codeplex.com/

Both of these should be updated to use fwlinks or aka.ms links so we can keep them current.

**Comment by mjbvz** [comment]
These pages have both been updated since this bug was originally opened. They now point to the correct locations as far as I can tell.
