### ISSUE TITLE
Debugger does not reliably start running nodejs console app.

### ISSUE THREAD

**Issue by chr15stevens** [Microsoft/nodejstools#466]
When I launch my nodejs console app for debugging, more often than not it seems like the process just hangs. I only get "Debugger listening on port 5858" and nothing else.

I can fix this sometimes by restarting visual studio.

**Comment by mousetraps** [comment]
Did you try our latest dev build? http://github.com/Microsoft/nodejstools/releases

It has some related fixes

**Comment by chr15stevens** [comment]
I've just given it a quick go and it seems much better thanks! I'll close this issue for now and let you know if it starts misbehaving again.

**Comment by rkavalap** [comment]
@mousetraps: I am hitting this issue on the latest 10-20 dev build
