### ISSUE TITLE
Have Jade use two space as default for tabs instead of four

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#47]
[from codeplex: https://nodejstools.codeplex.com/workitem/1889]

**Comment by kant2002** [comment]
Upon initial investigation, I don't yet clear places where to start.
I found source code from C# package
http://source.roslyn.codeplex.com/#Microsoft.VisualStudio.LanguageServices.CSharp/Options/CSharpLanguageSettingsSerializer.cs

But looks like it contains a lot of internal magic. 

Again, after some time I found that interface IVsTextManager from Microsoft.VisualStudio.TextManager.Interop
 assembly could do the trick.

It have two methods which could be helpful: SetPerLanguagePreferences and SetUserPreferences

Could somebody advice is this correct direction, or I have to dig in the another place.

**Comment by kant2002** [comment]
Looks like the 
https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/NodejsPackage.cs#L211
is the good place to start. should I use SetPerLanguagePreferences here?

**Comment by mousetraps** [comment]
@kant2002 good find! Yeah, IVsTextManager has some good methods, but unfortunately there doesn't seem to be any good way to set it without overriding the user's settings every time the package is loaded (as would happen in the Initialize method)

I briefly dug into some the XML editor codebase (which does something similar), and looks like this fix would be far more complicated than we initially anticipated, and it's certainly worth asking someone internally who has a little more familiarity with the VS intricacies involved. Definitely taking the fun-size label off of this one :smiley:

+@paulvanbrenk who also looked into this at some point

**Comment by kant2002** [comment]
Any news on this issue @mousetraps? Maybe @paulvanbrenk have a chance?

**Comment by paulvanbrenk** [comment]
Looks like this requires the implementation of the [LanguageService class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.package.languageservice?view=visualstudiosdk-2017) so we can return the [LanguagePreferences](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.package.languagepreferences?view=visualstudiosdk-2017) for this class.

This seems like a lot of work for setting the default indentation (which roams, so you should only have to do this once).
