### ISSUE TITLE
How to reference local modules from git repo

### ISSUE THREAD

**Issue by Laro88** [Microsoft/nodejstools#471]
What it the proper way to reference modules in a local git repo?
I prefer to have the solution and project files in a directory structure, however I keep getting git errors as the referenced repository TestNodeDriver contains a directory structure, and therefore does not have a package.json in the root of the repo.
What I need is to keep my local git repo internal and make it reusable for other projects. Is there a way to do make npm use the a subdirectory as root looking for the package.json file, or do I have to create a "clean" module without .sln - and thereby breaking the nice VS integration with git?
I am open to all suggestions / advice.

```
"repository" :
  { "type" : "git"
  , "url" : "http://internalserver/gitserver/TestNodeDriver.git"
  },
```
This is breaking as the git clone used in npm will include the underlying folder structure.

My issue goes along the lines of this [2974]
(https://github.com/npm/npm/issues/2974) - I am just trying to find out how to work with the limitations in npm

**Comment by mousetraps** [comment]
Hmm... how about a symlink?
`mklink package.json mySubdirectory\package.json`

**Comment by Laro88** [comment]
Not a bad idea? How is this maintainable in NTVS - and what could the pitfalls be?
What I really lack is a "best practice" in handling internally reusable components including easy of maintainability :-)
I am testing with everything in the root folder and it works but it is not clean, so when a developer clones the project then they get what they need - but the project file is also in the node_modules when linking to the project in git.

![projectinroot](https://cloud.githubusercontent.com/assets/12495700/10012659/275bb084-610a-11e5-9e96-121bb0da4fc9.png)

**Comment by mousetraps** [comment]
We don't have best practices, per se, but I can let you know some of the initial assumptions we made, and help you lead you down the past of least resistance. 

In general we assume there is a package.json at the root of the project and a node_modules folder at the root of the project.

The project file, however can specify a totally different root of the project by specifying a different ProjectHome property in the .njsproj file (so you can create the project file outside of the root of the project, or inside of some folder if you like).

You can also use `.npmignore` (which is a general npm concept, not NTVS-specific) to keep things outside of your package altogether.

Hope that helps! We're hoping to streamline this process going forward, so any feedback, additional Qs, etc. are very much appreciated :smiley:
