### ISSUE TITLE
Does it matter to import existing code to git hub when already under git

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#472]
I created a new project form code already under git and left the import to git option ticked

Is that safe?

I noticed your new ms-persist.xml file, but other files were updated, in particular FETCH_HEAD.

**Comment by mousetraps** [comment]
It should be plenty safe. Add from Existing Code completely cancels every action VS so we can override the default templating behavior in VS. I just tried it in VS 2013, and didn't notice any new files (other than the project file).

Maybe VS 2015 changed something up, though - my Dev14 setup is sad right now, though so I can't verify :smiley:

**Comment by SteveALee** [comment]
OK, Thanks. My impression is the updates are harmless.

**Comment by mousetraps** [comment]
Awesome - closing this now, but let us know if it ends up giving you any trouble!
