### ISSUE TITLE
Not able to use Interactive window; error: Sequence contains no elements

### ISSUE THREAD

**Issue by cveld** [Microsoft/nodejstools#473]
When I try to launch the Nodejs interactive window it stops showing a modal dialog with the text "Sequence contains no elements". I am not able to use the interactive window.

Visual Studio 2015 RTM
Nodejs tools 1.1

**Comment by mousetraps** [comment]
Have you tried the latest dev build or RC2.1? It includes some related fixes. http://github.com/Microsoft/nodejstools/releases

If that doesn't work, try forcing the MEF extension cache to be rebuilt:

1. Delete the contents of the folder at `%LOCALAPPDATA%\Microsoft\VisualStudio\14.0\ComponentModelCache`
2. Run `DevEnv.exe /setup` (this is under `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE`, but should be on your PATH if you open a Developer Command Prompt).

Next time you launch VS it will take a while to rebuild (which may be part of the delay above), but should resolve any MEF errors.

Hope that helps!

**Comment by cveld** [comment]
Somehow the interactive window suddenly started working again. It could be
nothing, but I spotted the same error message using the NPM Scripts Task
Runner extension. By inspecting package.json I discovered there was missing
a "scripts"-entry. Maybe there is some relationship?

2015-09-22 1:18 GMT+02:00 Sara Itani <notifications@github.com>:

**Comment by mousetraps** [comment]
Hrm, maybe it rebuilt when you reloaded VS later?

Regarding the error message similarities, that's just coincidence. "Sequence contains no elements" occurs when attempting to select the first item of an empty list. 

In the original issue, I believe the issue occurs here (chances are IntelliSense *also* wasn't working when the issue occurred) 
https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Intellisense/IntellisenseControllerProvider.cs#L67-L72

In task runner (and I'd have to verify - this was just based of a quick txt search for "first()"), but it might be this line:
https://github.com/madskristensen/NpmTaskRunner/blob/dd9d74d32c889abc6c3309255e1c788c7de3f2a4/src/TaskRunnerProvider.cs#L32-L33

**Comment by mousetraps** [comment]
In any case, closing this for now, but let us know if you run into it again.
