### ISSUE TITLE
Task runner errors when opening a project

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#474]
When I open a project I get task runner errors but I have not tried to run any tasks

<pre>
Failed to run "C:\Users\Steve\Documents\projects\GPII-windows\Gruntfile.js"...
cmd.exe /c grunt -b "C:\Users\Steve\Documents\projects\GPII-windows" --gruntfile "C:\Users\Steve\Documents\projects\GPII-windows\Gruntfile.js" --tasks "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\TaskRunnerExplorer\Scripts" vs-grunt-task-reader

Failed to run "C:\Users\Steve\Documents\projects\GPII-windows\package.json"...
Sequence contains no elements
Failed to run "C:\Users\Steve\Documents\projects\GPII-windows\Gruntfile.js"...
cmd.exe /c grunt -b "C:\Users\Steve\Documents\projects\GPII-windows" --gruntfile "C:\Users\Steve\Documents\projects\GPII-windows\Gruntfile.js" --tasks "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\TaskRunnerExplorer\Scripts" vs-grunt-task-reader

Failed to run "C:\Users\Steve\Documents\projects\GPII-windows\package.json"...
Sequence contains no elements
</pre>

I have existing gruntfile and package.js as this is imported code
https://github.com/GPII/windows

<pre>
/*!
GPII Windows Personalization Framework Gruntfile

Copyright 2014 RTF-US

Licensed under the New BSD license. You may not use this file except in
compliance with this License.

You may obtain a copy of the License at
https://github.com/gpii/universal/LICENSE.txt
*/

"use strict";

module.exports = function (grunt) {
    grunt.loadNpmTasks("grunt-contrib-jshint");
    grunt.loadNpmTasks("grunt-jsonlint");
    grunt.loadNpmTasks("grunt-shell");
    grunt.loadNpmTasks("grunt-gpii");
        
    grunt.config.getRaw("gpiiGruntGlobal");
    grunt.initConfig({
        jshint: {
            src: ["gpii/**/*.js", "tests/**/*.js", "index.js", "gpii.js"],
            buildScripts: ["Gruntfile.js"],
            options: {
                jshintrc: true
            }
        },
        jsonlint: {
            src: ["gpii/**/*.json", "tests/**/*.json"]
        }
    });

    grunt.registerTask("build", "Build the entire GPII", function () {
        grunt.task.run("gpii-universal");
    });
};
</pre>

<pre>
{
  "name": "gpii-windows",
  "description": "Components of the GPII personalization infrastructure for use on Microsoft's \"Windows\" ™",
  "version": "0.1.0",
  "author": "GPII",
  "bugs": "http://wiki.gpii.net/w/Main_Page",
  "homepage": "http://gpii.net/",
  "dependencies": {
    "ref-array": "1.1.0"
  },
  "devDependencies": {
    "grunt": "~0.4.4",
    "grunt-shell": "0.6.4",
    "grunt-contrib-jshint": "~0.9.0",
    "grunt-jsonlint": "1.0.4",
    "grunt-gpii": "git://github.com/GPII/grunt-gpii.git#ec8412064e107febb120f0b7437d403453b40d2d",
    "shelljs": "0.3.0"
  },
  "licenses": [
     {
       "type": "BSD-3-Clause",
       "url": "http://www.opensource.org/licenses/BSD-3-Clause"
     }
  ],
  "keywords": ["gpii", "accessibility", "settings", "fluid", "IoC", "Inversion of Control", "configuration", "evented"],
  "repository": "git://github.com/GPII/windows.git",
  "main": "./gpii.js",
  "engines": { "node" : ">=0.10.29" }
}
</pre>

**Comment by mousetraps** [comment]
These errors look like they're coming from task runner explorer (not NTVS). Is there a reason to believe otherwise?

**Comment by SteveALee** [comment]
None whatsoever. Sorry.
