### ISSUE TITLE
No Identical Token Matching

### ISSUE THREAD

**Issue by krusk** [Microsoft/nodejstools#479]
Hi all,

I have Node.JS tools installed in Visual Studio 2013, but in my Node project I don't get an identical token matching. In another project, such as a Web site using JavaScript, it matches without issue where a variable, function, etc. is shown as highlighted with its match. Is there is a configuration I am missing?

Thanks!

K.

**Comment by mousetraps** [comment]
JavaScript and Node.js are using different language services, and we haven't entirely reached feature parity yet. See https://github.com/Microsoft/nodejstools/issues/344#issuecomment-126981409 for more details.

You can also try the ES6 IntelliSense preview and see if you like that better, but I'm not sure you'll get token matching there either. 
https://github.com/Microsoft/nodejstools/wiki/ES6-IntelliSense-Preview-in-NTVS-1.1

Alternatively, you can enable the default JavaScript language service by following the following steps
https://github.com/Microsoft/nodejstools/wiki/Working-with-Browser-(Clientside)-JavaScript-in-NTVS#customizing-browser-and-nodejs-intellisense-modes

**Comment by krusk** [comment]
Thanks. I don't see the Set as Content (browser code) or Set as Compile (Node.js code) to toggle between modes in my directories. Is there a way to check my version of NodeTools to see if I need a different one/which one has this functionality?

**Comment by mousetraps** [comment]
It should be there for any folder with js files. We only introduced it in 1.1 RC, so I recommend downloading the latest build from https://github.com/Microsoft/nodejstools/releases

**Comment by krusk** [comment]
Works like a charm! Thank you Sara! And thank you and the team for all your hard work, its appreciated.

Regards,

K.
