### ISSUE TITLE
How does nodejstools interact with the installed node?

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#482]
Can we happily use any node version and expect things to just work?

I believe NTVS uses the installed and active nodejs? Or does it include it's own?

I ask as #427 reoccurred for me after installing [nvm-windows](https://github.com/coreybutler/nvm-windows) with node 4.1.0 and rolling back to 0.12.x. 

That got me wondering if NTVS has any node version dependency and if the version affects intellisense etc.

**Comment by SteveALee** [comment]
PS I've used the title prefix [question] as can't assign labels. I thought you could delete it when adding the label.

**Comment by SteveALee** [comment]
In particular Node 4.x.x includes some ES6 features I plan to use and I see there is a new experimental support - so there must be some dependency here.

**Comment by code-Review-2015** [comment]
My question is about the same: how do you configure a Node.js project with NTVS so that Intellisense recognizes particular version of Node.js. It seems reasonable to expect this extension to behave similarly to PTVS, in that it is capable of allowing the user to explicitly specify parameters of the environment, *including the version* of Node.js, just as PTVS does for the version of CPython. On one machine I did not install node.js at all prior to NTVS, which appears to implicitly(show up on Start menu) install Node.js 0.12.x. 
On a second machine, I installed [4.1.x](https://nodejs.org/dist/latest/) on my machine *before* installing your recent NTVS.Dev.2015...msi for Visual Studio 2015. I did not see any documentation to do so, but I did the install path `C:\Program Files\nodejs` to my User PATH environment variable. Then I installed NTVS.Dev....msi and it's nice to see that on a new, blank  NTVS project, the *interpreter* recognizes the Node 4.1.x version installed, but unfortunately, Intellisense on the app.js file in the *editor* does not.

**Comment by SteveALee** [comment]
@code-Review-2015 exactly - thanks for being more specific than my rambling. We need to know at least

* What versions of node / npm are supported?
   * any limitations - eg like intellisense for 4.x.x
* What configuration is required- eg %PATH%, how does it locate node.js?
  * does it play well with various node versions managers?
  * must node be installed before NTVS?

and an extra bonus Q
* what about node for the Windows 10 ARM IoT stuff :)

**Comment by mousetraps** [comment]
First we look for whether the path is set in the project file, and then we fall back to checking the environment ( you can see the code here: https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Nodejs.cs#L54) 

Regarding supported versions, see #62 for a comprehensive answer. And you can see our [Manual Test Matrix](https://github.com/Microsoft/nodejstools/wiki/Manual-Test-Matrix) for the versions we are actively testing (sometimes we forget to update it, but in general the most recent versions for node are being tested.) We also test a couple older versions that typically mark inflection points - behavior differences, major changes in API, etc.

**Comment by SteveALee** [comment]
Thanks - I can remove my "todo" to review the code for this and npm :)
I guess you will be adding LTS soon to the Matrix.

So what happens when Nodejs **not** installed?

**Comment by SteveALee** [comment]
This should be added to the docs.

**Comment by mousetraps** [comment]
@SteveALee when Node.js isn't installed, we'll let you know when you try to launch anything that requires node / npm (debugging, npm integration, profiling, interactive window, unit tests). But the editor / intellisense and npm integration (for local packages, that is... we need to call into npm to get the location of the global package list) will be fine. 

And agreed about adding it to the documentation. Our wiki is public, so feel free to add it yourself if you have time before we get to it.

**Comment by SteveALee** [comment]
I added [FAQ](https://github.com/Microsoft/nodejstools/wiki/FAQ) to the wiki.

**Comment by waynebloss** [comment]
Thanks, this thread and the resulting FAQ were super useful to me.

**Comment by waynebloss** [comment]
@SteveALee You might want to look at #534 if you're using nvm-windows. I found that VS2015 was using it's own version of node to install NPM packages instead of the one installed by nvm.

**Comment by SteveALee** [comment]
A little extra information having hit the incorrect node version again being used again.

**In summary: by default VS and nodejstools use a specific install of node and NPM (#534) irrespective of which version should be used by a project. While the project properties can be used to specify which node.exe is used, any use of NPM, such as installing packaged or running package.json scripts, is stuck using the incorrect version.**

**This is a significant issue and needs to be resolved ASAP. it leads to confusion. In my case I got a problem in Hapi saying "const cannot be used with "strict" due to old version of node not supporting ES6 features being used for the Hapi module.**

The node.exe path in projects properties is set to C:\Program Files (x86)\nodejs\node after I created a new project from existing code. I did not knowingly install this as I'm using nvm-windows which uses C:\Program Files\nodejs\node so suspect it might be VisualStudio or one of the extensions.

The project properties node.exe path dialog entry is some sort of default as clicking on it makes it disappear - it cannot be edited.

I'll update the FAQ to explain

**Comment by SteveALee** [comment]
Update: After I removed nvm-winodws and all copies of node and re installed everything including repairing VS, things have settled down. The default node.exe path is the expected  `C:\Program Files\nodejs\node` so I guess it is inheriting the path correctly now from the parent process.

However npm invocations are still showing an incorrect version of node, almost certainly it's using `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\node\node.exe`

**Comment by SteveALee** [comment]
@mousetraps Looks like another problem that seems related to VS extensions using the built in node rather than project node - madskristensen/WebAnalyzer#11

**Comment by SteveALee** [comment]
@mousetraps mousetraps should I create a new issue? This seems to be a bug that goes beyond the original question
