### ISSUE TITLE
[information] Supporting style and lint checkers

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#483]
In an off-list discussion I mentioned I planned to use a particular set of style guidelines with [ESLint](https://github.com/eslint/eslint) and wondered if ESLint was supported. WebEssentials supplies JSHint and JSCS and it appears ESLint replaces both. Of course I can just use ESLint, like any other tool.

Anyway the style I decided to use is [airbnb's ES6](https://github.com/airbnb/javascript)  They also have an (ES5 version)[https://github.com/airbnb/javascript/tree/master/es5]. They provide an .eslintrc and .jshintrc.

I also looked at [hapi.js' style](http://hapijs.com/styleguide) as will be using it rather than express. I considered [standard](http://standardjs.com/) too but not quite ready for no semicolons yet, though there is a fork with semis. (Ooh but look it has a badge!).

At the end of the day I just picked a good one that's close to what I've used with C and am happy (hapi?) with.

**Comment by mousetraps** [comment]
Have you tried the new Web Analyzer extension by any chance? https://visualstudiogallery.msdn.microsoft.com/6edc26d4-47d8-4987-82ee-7c820d79be1d

**Comment by SteveALee** [comment]
No I hadn't. Thanks for the tip. The extra CSS checks will be useful :)

**Comment by SteveALee** [comment]
Here's a nice [article about the background and use of ESLint](http://www.smashingmagazine.com/2015/09/eslint-the-next-generation-javascript-linter/?imm_mid=0d992c&cmp=em-web-na-na-newsltr_20150930)
