### ISSUE TITLE
[suggestion] Make it clear that nodejstools works with any toolchain / workflow

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#484]
It's not obvious but nodejstools works well with pretty much any existing commandline based workflow / tool chain. You can just import an existing project and VS and nodejstools just add a couple of config files. These config files could be added to version control too (though I can't remember if there's clear separation of project and user options).

You should shout this loud and clear. Open source projects can't really force proprietary IDEs on devs but VS is a great option for a dev to pick when on a Windows Host (and don't forget remote debugging too).

**Comment by mousetraps** [comment]
Agreed. More visibly integrating into the CLI workflow would be super helpful in videos and docs.

**Comment by mousetraps** [comment]
And in the product too if we can land on the right UX paradigms.

**Comment by mousetraps** [comment]
I've been pulling up the CLI more often in demos, so hopefully this helps :smiley:
