### ISSUE TITLE
package.json not checked out automatically on install of new npm package

### ISSUE THREAD

**Issue by frauss** [Microsoft/nodejstools#485]
I noticed that if I install a new npm module and I have not manually checked out the project.json file I get an error when npm attempts to update it:

> ====Executing command 'npm install async --save '====
> 
> npm WARN package.json rulesService@1.0.0 No repository field.
> npm WARN package.json rulesService@1.0.0 No README data
> async@1.4.2 node_modules\async
> npm ERR! Error: EPERM, open 'E:\Source\eAP\EditorialApplications\Exposure\Node\trunk\Src\node-rules-service\package.json'
> npm ERR!  { [Error: EPERM, open 'E:\Source\eAP\EditorialApplications\Exposure\Node\trunk\Src\node-rules-service\package.json']
> npm ERR!   errno: 50,
> npm ERR!   code: 'EPERM',
> npm ERR!   path: 'E:\Source\eAP\EditorialApplications\Exposure\Node\trunk\Src\node-rules-service\package.json' }
> npm ERR! 
> npm ERR! Please try running this command again as root/Administrator.
> npm ERR! System Windows_NT 6.2.9200
> npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "async" "--save"
> npm ERR! cwd E:\Source\eAP\EditorialApplications\Exposure\Node\trunk\Src\node-rules-service
> npm ERR! node -v v0.10.33
> npm ERR! npm -v 1.4.28
> npm ERR! path E:\Source\eAP\EditorialApplications\Exposure\Node\trunk\Src\node-rules-service\package.json
> npm ERR! code EPERM
> npm ERR! errno 50
> npm ERR! stack Error: EPERM, open 'E:\Source\eAP\EditorialApplications\Exposure\Node\trunk\Src\node-rules-service\package.json'
> npm
> 
> ====npm command completed with exit code 50====

The module shows up in the list of installed modules with the warning (not listed in package.json).

I can then uninstall the module, manually check out package.json and reinstall but it's not what I would call expected behavior.

Thanks,
Fred

**Comment by mousetraps** [comment]
I presume you're using tfs?

**Comment by frauss** [comment]
Yes, sorry for not being specific.

**Comment by paulvanbrenk** [comment]
Closing since this is fixed in VIsual Studio 2017
