### ISSUE TITLE
Does 'use strict' work? Not seeing any effect in interpreter window.

### ISSUE THREAD

**Issue by code-Review-2015** [Microsoft/nodejstools#487]
To reproduce in NTVS interpreter window:

  Install (1) node.js 4.x.x (2) NTVS.Dev.2015-09-17.VS.2015.msi. Run 2015 and open NTVS interpreter window,

     > 'use strict';
    'use strict'
    > let A = [1, 3];
    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by mousetraps** [comment]
Ah, looks like we're not respecting strict mode in the interactive window, but this code should work fine in the editor.
