### ISSUE TITLE
cursor moves to wrong position after formatting

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#49]
`var result = {'count': 0`<cursor>`}`

press enter

``` javascript
var result = {
        'count': 0

   <cursor> }
```

(brace completion turned on, only seems to repro while typing it out

**Comment by mjbvz** [comment]
Confirmed that this still repos in ES6 Preview Intellisense in NTVS 1.2 Alpha

**Comment by paulvanbrenk** [comment]
THis is a problem in the TypeScript language service. 

https://github.com/Microsoft/TypeScript/issues/15113
