### ISSUE TITLE
add test "traits" support for Mocha/test explorer integration using @ tags

### ISSUE THREAD

**Issue by scrom** [Microsoft/nodejstools#494]
Hi all. Here's a Test Explorer enhancement request around Mocha integration.
I'm currently trying to migrate some old tests from nodeUnit to Mocha and I'm really missing the ability to use test "traits" in VS.

Unless there's already a way to handle this that I've not found in the docs yet, from looking at the Mocha wiki, the tagging approach to tests (e.g. @tag) seems like a sensible placeholder/hook to capture and classify test traits. (Mocha wiki article on tagging here: https://github.com/mochajs/mocha/wiki/Tagging )

No idea how viable this is at the moment but wanted to get the request in.

**Comment by mousetraps** [comment]
Yeah, that would be cool. Not sure how extensible that is, though, so we'd need to do some investigation.

**Comment by scrom** [comment]
Cheers Sara.
For the Traits stuff it's worth a look at this guy's work for NodeUnit - I struggled with understanding the detail as I'm new to the VS side of things but it does have trait support.
https://github.com/jgordon615/NodeUnitTestAdapter

**Comment by haugerbr** [comment]
Mocha @ tags or some other type of metadata to group tests in the test explorer. As it stands if I have 100+ tests I don't have good way to group them in test explorer. At best I can filter them through search but traits definitely give the best flexibility.

**Comment by paulvanbrenk** [comment]
We need work done in the testexplorer/runner to make this work.
