### ISSUE TITLE
mocha unit test output is truncated in VS2013 (update5)

### ISSUE THREAD

**Issue by scrom** [Microsoft/nodejstools#498]
Bear with me, I've only started using mocha tests this week but.
On the current RC (and latest dev build). the stdout from Mocha is being truncated at 3 output lines in the test output window.

sample test code (just adding console.log to the default mocha js template): 

    var assert = require('assert');

    describe('Test Suite 1', function() {
      it('Test 1', function () {
          console.log("output line 1");
          console.log("output line 2");
          console.log("output line 3");
          console.log("output line 4");
          console.log("output line 5");
          console.log("output line 6");
          console.log("output line 7");
          console.log("output line 8");
          console.log("output line 9");

        assert.ok(true, "This shouldn't fail");
      })

    })

Result:
![image](https://cloud.githubusercontent.com/assets/409676/10188314/3f32e4be-6756-11e5-85c0-969be7c7b043.png)

I'm sure I saw at some point an option to copy/past into notepad to see the full text but I might've been imagining it.

I was using VS2015 on a different machine last night and the stdout looked fine on there so this appears to be a pre VS2015 issue only.

**Comment by scrom** [comment]
forgot to say - this is using mocha@2.3.3 if that makes any difference

**Comment by mousetraps** [comment]
Interesting... I haven't seen that before. One thing you can try is specifying a different reporter using mocha.json as described in the release notes for 1.1 RC and see if that helps (sorry this hasn't made it to our wiki yet.) https://github.com/Microsoft/nodejstools/releases/tag/v1.1.RC

**Comment by scrom** [comment]
Cheers. I'll take a look at let you know.
Not urgent as I've upgraded my main dev boxes to VS2015 now (and upgraded the old NodeUnit adapter to work) but I'll experiment with the reporters and see how results change on VS2013 (update 5)

**Comment by mjbvz** [comment]
I believe the test UI has been improved in VS2015 so that is now easy to view the entire test output: 

![image](https://cloud.githubusercontent.com/assets/12821956/18071965/bb9f8e98-6e0e-11e6-9077-b77e94cceeca.png)

We are no longer focusing on making this type of change in VS2013. Please try updating the VS2015 and the latest versions of NTVS if you are running into this problem.

Thanks.
