### ISSUE TITLE
Mocha tests - mocha.json options file not found. Using default values...

### ISSUE THREAD

**Issue by scrom** [Microsoft/nodejstools#499]
Low priority I think but...
From what I've researched, mocha usually uses a mocha.opts file, not a .json file.
As we're expecting a json file instead, the format and location of this needs to be documented for users/devs along with what options are/aren't supported.

At a minimum if there's no expectation that an end user will modify the defaults set by this plugin it's possibly worth suppressing this message in TestFrameworks/Mocha/mocha.js

**Comment by mousetraps** [comment]
Agreed, we should make it clearer what that's for.

Fwiw the best documentation is currently available in our [1.1 RC release notes](https://github.com/Microsoft/nodejstools/releases/tag/v1.1.RC) - we haven't moved it over to our wiki just yet, but feel free to jump in and help (our wiki is public) :smiley:

And you can view some of the discussion around why mocha.json at https://github.com/Microsoft/nodejstools/pull/168

**Comment by scrom** [comment]
Cool - thanks. Reading now...
... ok - understand the reasoning behind using a different file from .opts and the location.

And in the release notes too :) - is the test config part new in there?

I'll fathom out a starter on the wiki for this - probably something about "Configuring Test Output"

**Comment by scrom** [comment]
Wiki done - "Configuring Mocha Options" (as it's more than just test output).

Thanks for the help on this.

**Comment by landonpoch** [comment]
Any plans to support more options (like the --require flag)?  Also, it might be good to document which flags don't currently work.  I'm tempted to hack around in the mocha.js file to get things working but I don't want to break my upgrade path.
