### ISSUE TITLE
Node Tools Integration with SharePoint projects

### ISSUE THREAD

**Issue by rroman81** [Microsoft/nodejstools#501]
I am trying to integrate the Node.js with building the front-end artifacts and deploy them to a SharePoint isntance. I am currenlty using the SharePoint full-trust project but i think the approach is similar with any type of SP project types, either full-trust or apps.  
I am unfamiliar with the code base but would love to get some pointers how to start here. 
Currently, i have built the pre-build event and wired the afterBuild in the msbuild to perform node js functionality, but the task manager would be nice in case i just need a gulp specific task run and not msbuild itself.  Suggestions/Thougthts?

**Comment by mousetraps** [comment]
Have you tried using Task Runner Explorer? (built-in to VS2015 or available as an extension for VS 2013 https://visualstudiogallery.msdn.microsoft.com/8e1b4368-4afb-467a-bc13-9650572db708)

Also I'm not really familiar with SharePoint - could you describe more specifically what you're looking for?

**Comment by mousetraps** [comment]
Closing as it's unclear what the scenario is here and we haven't heard back in a while.

**Comment by rroman81** [comment]
Totally forgot about this question, sorry. I'll review more on my end and report back.
