### ISSUE TITLE
Place open brace on new line after function stopped working

### ISSUE THREAD

**Issue by endasil** [Microsoft/nodejstools#502]
In Tools -> Options -> Node.js -> Formatting -> Braces i have "Place open brace on new line after function" and "Place open brace on new line for control blocks " checked.

If i have a function like this:
function SuperDuperFunction()
{

}

Then go to edit format selection / document, it will move the opening bracket to the same line.  

function SuperDuperFunction() {

}

Any idea what causes this or how i can work around it?

**Comment by mousetraps** [comment]
hrm... I can't seem to reproduce... What's the build action of the file set to? If it's set to "Compile", then the Node.js formatting settings will kick in. But if it's set to "Content", the JavaScript formatting settings will kick in and you'll have the select the proper setting there too.

See #67 for more info, but this is one of the unfortunate results of having separate language services for Node.js / JavaScript.

**Comment by endasil** [comment]
The build action is set set to Compile.  I tried setting javascript formatting to "Place open brace on new line after function" too. Tried changing between Compile and content, unchecking and checking braces on new line but nothing seems to change. Do you have any other troubleshooting advice?

**Comment by mjbvz** [comment]
I can't repo this with NTVS 1.2 alpha on either Full Intellisense or Es6 Preview Intellisense.

Please reopen and provide additional details if you are still running into the problem. 

Thanks.

**Comment by Timwi** [comment]
I am having this issue as well, but with no relation to node.js. I have a JavaScript file marked as “Content” (not “Compile”) and the setting is not respected:

https://i.imgur.com/BPYxCDh.png
