### ISSUE TITLE
No outlining for multiline comments

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/nodejstools#503]
Probably related to #67 and others - I added a bunch of JSDoc comments to my project yesterday and I noticed that there is no outlining (collapse/uncollapse) for multi-line comments. I understand that it's probably coming since it already works in non-Node Javascript files, but I couldn't find an issue for it here.

If I didn't do inline documentation, I probably wouldn't care so much about this feature. If there were only some way of doing documentation that made it easy for me to jump from the function I'm working on, directly to the documentation editor - I'd be in heaven because I really don't like looking at the inline documentation when I'm not editing it but it's so convenient to have the docs and the code all in one place.

**Comment by mjbvz** [comment]
Fixed in NTVS 1.2 Alpha with ES6 Preview Intellisense

![image](https://cloud.githubusercontent.com/assets/12821956/14469710/e3c0be92-009a-11e6-9ff8-de7e501179f7.png)

![image](https://cloud.githubusercontent.com/assets/12821956/14469747/0944ab10-009b-11e6-90d5-956ce98cc56b.png)
