### ISSUE TITLE
Wrong line ending added to js file when editing a multiline comment.

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/nodejstools#504]
When I edit `*.js` files that have all `LF` line endings, Visual Studio mostly respects that and does not replace them with `CR+LF` when saving. However, when I turn a single-line JSDoc style comment into a multiple line comment, a `CR+LF` is added to the file.

Example: *If I put the cursor after the last period in the comment below and press ENTER, that comment will contain a `CR` character.*

```js
/** My function for greeting the world. */
function myFn() {
  alert('Hello, world!');
}
```

Probably related to #67 and others...
Originally entered at madskristensen/WebEssentials2015#104 but I don't think that was the correct repo.

**Comment by mjbvz** [comment]
I've been unable to repro this issue with NTVS 1.2 using the Typescript backed editor (some of the functionality around comment completion was also removed #786). Please give it a try and let me know if you are still seeing the problem.

Thanks.
