### ISSUE TITLE
npm window contrast messed up in dark theme

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#507]
![image](https://cloud.githubusercontent.com/assets/762848/10288499/17aacb40-6b4e-11e5-9a0d-c3d4fb34c4df.png)

**Comment by mjbvz** [comment]
Seems to be fixed in NTVS 1.2 Alpha

![image](https://cloud.githubusercontent.com/assets/12821956/14469427/5e7da7aa-0099-11e6-97eb-abe8bd014536.png)
