### ISSUE TITLE
Formatting mangles multiline / doc comments

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#51]
And incorrectly indents things that follow them.

Begin with
```js
/*
 * foo
 * bar
 **/
baz
```
Insert an opening curly brace on a new line before the comment, and a closing one on a new line after the comment. The latter will trigger reformatting, and the result is:
```js
{
    /*
 * foo
 * bar
 **/
baz;
}
```
Note how only the first line of the comment was indented, but not the following lines; and how `baz` was not indented, either.

[from codeplex: https://nodejstools.codeplex.com/workitem/1567]

**Comment by mjbvz** [comment]
Fixed in Es6 Intellisense Preview in NTVS 1.2 Alpha

![image](https://cloud.githubusercontent.com/assets/12821956/14266712/f958edb4-fa7e-11e5-9874-cb23bca332a1.png)
