### ISSUE TITLE
Support meteor apps

### ISSUE THREAD

**Issue by adaptabi** [Microsoft/nodejstools#510]
Would make `Visual Studio` trully amazing.

Currently `Webstorm` is supporting very well `meteor` apps, including debugging from `chrome/v8/firefox/ie` and `server side node` at same time!

That is amazing!!

**Comment by mousetraps** [comment]
Thanks for the feedback. We also saw a lot of demand for this feature when we were on codeplex too (though the upvotes on that issue were skewed because it made the rounds on twitter.) https://nodejstools.codeplex.com/workitem/540

**Comment by dotnetwise** [comment]
Believe it or not, Meteor is the future of javascript apps.
Also I think a lot of Java/ASP.NET apps are already moving towards meteor.

**Comment by mousetraps** [comment]
Sweet - do you have any data on this by any chance? I agree that Meteor is insanely cool and I always point people to it for an example of how awesome things could be... but I haven't (personally) seen much pickup in production apps. Maybe I'm just looking in the wrong place, though :smiley:

**Comment by dotnetwise** [comment]
Yes! Being `10th` most starred project of github, beside jquery, node, bootstrap and other css libraries!!

**Comment by mousetraps** [comment]
@dotnetwise yeah, I've seen the GH repo, and it is indeed popular. However... it's one thing to be excited about a technology, and quite another to actually use it. Do you know any good indicators of active usage?

**Comment by fabiodr** [comment]
+1 Many people in the forum would like to see this feature.

**Comment by billti** [comment]
I see we have issue #618 tracking an issue here regarding debugging/attach, but is there anything more specific for `Support meteor apps` you had in mind?

**Comment by inbaldoron** [comment]
I also commented on #618 with some additional features.
Support meteor would be a great feature :+1:

**Comment by paulvanbrenk** [comment]
This references the following; www.meteor.com/

**Comment by paulvanbrenk** [comment]
We'll consider this when moving to a new project system.
