### ISSUE TITLE
IntelliSense closes after typing some characters like '$'

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#514]
Given the scenario below, the IntelliSense popup unexpectedly closes after typing `$`. It reappears after typing `_`
![image](https://cloud.githubusercontent.com/assets/762848/10318131/e1e3e3dc-6c1c-11e5-83f0-dca7d0ef4484.png)

**Comment by hoanhtien** [comment]
Something to do with the following method:

```C#
private static bool IsIdentifierFirstChar(char ch) {
    return ch == '_' || (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z');
}
```
