### ISSUE TITLE
Forking a child process in debug does not redirect children stdout to its parent

### ISSUE THREAD

**Issue by aguerot** [Microsoft/nodejstools#519]
Using Node.js Tools   1.0.30428.03 with Visual Studio Enterprise 2015 RTM

Here is the main code that forks a new worker (worker.ts)

app.ts
```javascript
import cp = require('child_process');

console.log('Main started');

var execArgv = (<any>process).execArgv.slice(); //create args shallow copy
var debugPort = (<any>process).debugPort + 1;

for (var i = 0; i < execArgv.length; i++) {
    var match = execArgv[i].match(/^(--debug|--debug-brk)(=\d+)?$/);
    if (match) {
        execArgv[i] = match[1] + '=' + debugPort;
        break;
    }
}

//var options = { env: process.env,  silent:false, execArgv: execArgv, cwd: targetProcessCwd };
var options = { env: process.env, silent: false, execArgv: execArgv };

var childProcess = cp.fork('./worker.js', [], options);

childProcess.on('close', (code) => console.log('id:' + childProcess.pid + ' closed with statusCode:' + code));
```
Here is the worker's code:

worker.ts
```javascript
console.log('Process id:' + process.pid);
//process.stdout.write('Process id:' + process.pid);

setInterval(() => {
    console.log('Forked is still alive:' + process.pid);
    //process.stdout.write('Forked is still alive:' + process.pid);
}, 500);
```

Pressing F5 in Visual Studio starts app.js and forks a new debuggable process worker.js.
The issue is that stdout from the child process is not visible to the main node process. console.log from the child process are not visible in app process

If I run node.exe app.js from command line, I can see the child process stdout. Same with node.exe --debug app.js

Pressing F5 in Visual Studio in Release mode has the same effect as in Debug mode

I think that Visual Studio is interfering with the two processes

**Comment by mousetraps** [comment]
Under the covers, we run --debug-brk, not --debug, which means that the child processes are ending up in a paused state. Take a look at https://github.com/Microsoft/nodejstools/issues/197#issuecomment-113581676 for instructions on how to attach to multiple processes so you can continue execution.
