### ISSUE TITLE
brace-bracket-paren doesn't dedent

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#52]
This causes rest of user code to be indented even though we're at the end of statement
``` js
angular.module('flapperNews', []).controller('MainCtrl', [
    '$scope',
    function ($scope) {
        $scope.test = 'Hello world';
    }]);
```
hit enter. notice we are indented

[copied from codeplex https://nodejstools.codeplex.com/workitem/1504]

**Comment by mjbvz** [comment]
Fixed in ES6 Preview Intellisense in NTVS 1.2 Alpha

![image](https://cloud.githubusercontent.com/assets/12821956/14266786/a894e67a-fa7f-11e5-8232-106abf4a64ec.png)
