### ISSUE TITLE
Error in Visual Studio 2015 Update 1 CTP 

### ISSUE THREAD

**Issue by Delie** [Microsoft/nodejstools#530]
Apologies for flagging this if you're not testing in the 2015 Update 1 CTP yet, but I'm getting an error upon opening a Jade file in the editor.  

It seems to be complaining that "contentTypes" is not a key.  Occurs in the constructor for Microsoft.NodejsTools.ClassifierProviderMetadata

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.&#x000D;&#x000A;   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)&#x000D;&#x000A;   at System.Collections.Immutable.ImmutableDictionary`2.System.Collections.Generic.IDictionary&lt;TKey,TValue&gt;.get_Item(TKey key)&#x000D;&#x000A;   at Microsoft.NodejsTools.ClassifierProviderMetadata..ctor(IDictionary`2 values)&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)&#x000D;&#x000A;   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.MetadataViewClassProvider.CreateProxy(IReadOnlyDictionary`2 metadata, IReadOnlyDictionary`2 defaultValues, Type metadataViewType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetStrongTypedMetadata(IReadOnlyDictionary`2 metadata, Type metadataType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.&lt;CreateValue&gt;b__10_0(RuntimeImport import)&#x000D;&#x000A;   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()&#x000D;&#x000A;   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)&#x000D;&#x000A;   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.DelegateServices.&lt;&gt;c__DisplayClass2_0`1.&lt;As&gt;b__0()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeMatchingFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, Object errorSource)

**Comment by mousetraps** [comment]
We'll try to investigate this before our next release

Just so I understand the problem better... does it occur with every jade file? Or only when there is specific text in the editor?

**Comment by Delie** [comment]
Hmm, good question.  Unfortunately, since my original post I tried to uninstall/reinstall the NodeJS tools, but it seems I can no longer install at all.  I'm using Visual Studio Community 2015, version 14.024606.01 Update 1 CTP.  

I've tried installing NTVS 1.1 RC2.1 VS 2015, and NTVS.Dev.2015-10-20.VS.2015, but both of them are coming up with a "Visual Studio 2015 is required" error.

I only upgraded to the Update 1 CTP, because I wasn't able to save my tab settings in the text editor for Jade files, but looks like it made matters worse :)

I think I originally installed the Node JS tools on top of the non Update-1 version of VS Community 2015. I then updated VS Community 2015 to VS Community 2015 Update 1 CTP, and that's when I started getting the Jade error in Node JS tools.  I think it happened with any Jade file, but can't re-test it at the present time given my dev environment is now different to how it was originally.

**Comment by Delie** [comment]
If there's any other tests I can do in VS2015 Update 1 CTP let me know and I'll be happy to help

**Comment by mousetraps** [comment]
@billti fyi looks like this issue is still occurring in the latest vs update bits.

**Comment by billti** [comment]
I just installed the VS2015 Update1 RC and the latest NTVS build, and got this issue also. Deleting the MEF cache and running `devenv /setup` to recalculate didn't resolve it. The MEF error log only contains events unrelated components. 

Not sure what is causing this to happen now... but we'll need to get it resolved before we ship 1.1 :-( Investigating...
