### ISSUE TITLE
All files incorrectly showing pending VC changes with MS git provider

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#531]
I checked out a project from GitHub using latest Git For Windows (64bit) and then added it as existing code to a new nodejstools project.

Now almost all files show pending changes in solution explorer, even though there are none according to command line "git status" or VS diffs (from right click on file).

I wondered if was core.autocrlf which his on by default (install option) but setting it to false in .git\config makes no difference. I can find no docs for the git provider since it moved to VS core.

I am using fully updated VS community 2015, lates dev release of nodejstools, microsoft git provider (not logged into TFS at all), GitHub extensions also installed. Windows 10 64 bit

I raised this [on the VS General forum](https://social.msdn.microsoft.com/Forums/vstudio/en-US/d9bcc6d4-f08c-45f5-a707-a8ccdab6f432/all-files-showing-pending-changes-in-solution-explorer?forum=visualstudiogeneral) as it might not be NTVS related.

**Comment by SteveALee** [comment]
in #534  @mousetraps pointed out the Options->Projects and Solutions->ExternalWebTools and there is a local git setting there.

I'm wonder if this is used by MS git provider rather than system installed git (as there can be several) and it's autoCRLF settings are different, causing the false pending updates?

Will investigate when I have more time.

**Comment by paulvanbrenk** [comment]
Not able to repro this behavior, and sounds like this is not something Node Tools specific.

Closing, if you're still seeing this, please open an issue on the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/).
