### ISSUE TITLE
should not display completions within VariableDeclarationLists or BindingLists with more than one element

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#535]
right now we respect:
```js
var a// no completions
const a// no completions
```

However it does not display properly when there is more than one element in the completions list. 
```js
var a, b// displays completions
var a = 3, b//displays completions
const a, b//displays completions
const a =3, b//displays completions
let a, b//displays completions
let a =3, b//displays completions
```

We initially enabled this in #456, but it looks like that won't work for VariableDeclarationLists or BindingLists. Instead we'll need to dive into the [ReverseExpressionParser](https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Intellisense/ReverseExpressionParser.cs) to fix this issue.

**Comment by mjbvz** [comment]
Tried above cases, all seem fixed in ES6 Intellisense preview in NTVS 1.2 Alpha
