### ISSUE TITLE
Need option to keep node cmd window open when node exits

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#536]
In some cases it is desirable to keep the node command window open after node has exited in order to see the output.

this may be unusual but I am running some code that does not run a server but runs code and exits.

Can this be made an option?

I guess a temp work around would be to make the "node exe path" a cmd file with a pause in it.

**Comment by mousetraps** [comment]
There are in fact two options in **Settings** > **Node.js Tools** > **General**
* Wait for input when process exits abnormally
* Wait for input when process exits normally

**Comment by SteveALee** [comment]
Excellent, I should have looked there as well as project specific options. Thanks
