### ISSUE TITLE
Do not assume Node.js Web Application when creating from existing Node.js code

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/nodejstools#543]
Most of my Node.js projects are not web projects, they're console applications. However, when I create a new project _From Existing Node.js Code_, it always assumes that it's a web application and therefore the nsproj files includes the ASP.NET Project Type GUID `349c5851-65df-11da-9384-00065b846f21` and it's flavor properties. For now, I just edit the nsproj file in Notepad and remove them.

The ASP.NET project stuff is usually what gives me problems like always asking me if I want to compile the project before running it and freezing.

**Comment by paulvanbrenk** [comment]
I suggest using the ["Open Folder"](https://docs.microsoft.com/en-us/visualstudio/ide/develop-code-in-visual-studio-without-projects-or-solutions) option in VS.
