### ISSUE TITLE
should not display completions within function parameter names lists

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#544]
e.g. 
``` js
function myFunctionName(myParameterName1, myParameterName2//don't show completions
```

**Comment by mjbvz** [comment]
Fixed in ES6 Intellisense Preview in NTVS 1.2 Alpha.

![image](https://cloud.githubusercontent.com/assets/12821956/14268005/0c4691b8-fa8b-11e5-90d7-cd1722913ea1.png)
