### ISSUE TITLE
.ntvs_analysis.dat

### ISSUE THREAD

**Issue by mackdesignarts** [Microsoft/nodejstools#556]
Would be nice if you warned us about this ever expanding .dat file and the damage it will do to our repository if we don't gitignore it. 

Or better still please fix this. We lost a day of development cleaning our history from this monster file lodged in project root that kept doubling in size.

**Comment by mousetraps** [comment]
Thanks for the feedback. We'll try to improve our docs / videos to help people avoid it in the future. In the meantime, our wiki is public, so feel free to hop it and add anything you feel might be useful to help others get started.

And what do you mean by "fix this"? In this case, we didn't actually intend for people to share this file... hence the fact that it's a dot file that's hidden by default. Does it get out of hand on your local machine, when it isn't getting checked into source?

**Comment by mjbvz** [comment]
With [NTVS 1.2 Beta ](https://github.com/Microsoft/nodejstools/releases), there's no more `.ntvs_analysis.dat` file 🎆 (at least so long as you stick with ES6 IntelliSense)

Please download the beta and try out our modern IntelliSense powered by Typescript. It should perform much better, and also better supports modern JavaScript. Please report any problems you run into and feel free to share any feedback on the new IntelliSenseexperience. Thanks.
