### ISSUE TITLE
No moduleResolution flag support

### ISSUE THREAD

**Issue by djflex68** [Microsoft/nodejstools#559]
It would be nice to have the moduleResolution compiler flag available from the project properties. We are stuck to Typescript 1.5 today because it's not possible to specify moduleResolution: "node" (and a refactoring of the whole project would be too heavy).

**Comment by mousetraps** [comment]
@billti any ideas?

**Comment by mjbvz** [comment]
I believe the correct solution is now to add a `tsconfig.json` at the top level of your project, like so:

```json
{
  "compilerOptions": {
    "moduleResolution": "node"
  }
}
```

This works in my testing. Give it a try and let me know if you run into any problems.

Thanks.
