### ISSUE TITLE
#466 Debugger does not reliably start running nodejs console app (10-20) dev build

### ISSUE THREAD

**Issue by rkavalap** [Microsoft/nodejstools#561]
Facing issue #466 using the latest dev build. No option to re-open so opening a new one.

**Comment by rkavalap** [comment]
Using VS 2013 Update 5.

**Comment by penguin20000** [comment]
Same here using VS 2015

**Comment by Ampakinetic** [comment]
Likewise, running an express app in VS2015

**Comment by mousetraps** [comment]
Thanks all. This is a recent regression. Try using the previous dev build, and we'll try to get this sorted out soon.

**Comment by Ampakinetic** [comment]
Yes the previous build works well, thank you!  And can I mention you have a lovely smile :)

**Comment by mousetraps** [comment]
New dev build up! https://github.com/Microsoft/nodejstools/releases
