### ISSUE TITLE
No intellisense on Express after npm install with a new project

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#566]
**Repro steps:**
* file > new project > express 4 template
* wait for packages to install and analysis to complete
* hovering over `app` yields `unknown type`

When this issue occurs, of the top-level packages installed (the ones that appear in `package.json` and were installed with ), some appear to have been analyzed and some don't:

> :x: **body-parser:** unknown type
:x: **cookie-parser:** unknown type
:x: **debug:** unknown type
:x: **express:** unknown type: 
:heavy_check_mark: **jade:** completions available
:heavy_check_mark: **morgan:** completions available
:heavy_check_mark: **serve-favicon:** completions available
:heavy_check_mark: **stylus:** completions available

An interesting coincidence about this list is that the packages yielding `unknown type` are those packages sorted towards the beginning of the alphabet. This is consistently the case, and this issue appears to be unrelated to the sort order in package.json.

The express 3 template yields similar results:
> :x: **express:** unknown type
:x: **jade:** unknown type
:heavy_check_mark: **stylus:** completions available

**Workaround:** if you install any other package, say `azure`, completions are suddenly available for all of the packages (including those towards the beginning of the alphabet.)

**Comment by mousetraps** [comment]
This issue also affects all dependencies of a package. For instance...
```js
// completions for all express dependencies not available
var connect = require('./node_modules/express/node_modules/connect');

// completions for all stylus dependencies available
var cssParse = require('./node_modules/stylus/node_modules/css-parse');
```

**Comment by Parralex** [comment]
This problem is currently affecting me, and I tried running:
`npm install azure --save`
In my project's directory but Express still does not show any Intellisense options. Installing another package (jquery) also did not help. Perhaps I am misunderstanding your workaround.
