### ISSUE TITLE
High memory consumtion

### ISSUE THREAD

**Issue by wmmihaa** [Microsoft/nodejstools#567]
Hi,
I'm experiencing a very high memory utilization when using Visual Studio 2015 with node.js projects. I assume it has to do with the number of npm packages (~40). It starts off alright, but slowly builds up to consume between 1.5 - 2.1 GB of RAM.
  
![untitled](https://cloud.githubusercontent.com/assets/3214367/10718382/b00cf5b0-7b71-11e5-9c5c-6dd891f3e83f.png)

**Comment by wmmihaa** [comment]
BTW. Then whole project folder with npm modules included is around 860 MB. My fairly large web project consumes < 200 MB.

**Comment by wmmihaa** [comment]
This might also be useful...
![untitled](https://cloud.githubusercontent.com/assets/3214367/10718446/fbfb5420-7b72-11e5-98df-163f2eb5ba5a.png)

**Comment by wmmihaa** [comment]
Some more input:
Closing the solution will not have any affect, nor does it have any affect if I remove the node_modules folder before opening VS.
HTH

**Comment by mtycholaz** [comment]
I have this exact same problem. My fix has been to covert the project to a C# class library for now.

**Comment by mjbvz** [comment]
I've created a troubleshooting page to document some possible work arounds for high memory usage: https://github.com/Microsoft/nodejstools/wiki/Troubleshooting#high-memory-usage-workarounds 

If you on the  NTVS 1.2 Alpha, try switching to use ES6 Preview Intellisense as a first step (`Tools -> Options -> Text Editor -> Node.js -> IntelliSense`). Our homegrown static analysis engine is usually to blame for high memory usage, and ES6 Preview Intellisense uses a more modern and efficient language service developed by the Typescript team. We will still try to fix leaks and crashes in our static analysis engine of course, but will probably not invest in fixing some of the fundamental memory consumption problems it has.

**Comment by mjbvz** [comment]
If you are seeing unacceptably high memory usage, please try installing NTVS 1.2 Alpha and switching to ES6 Preview Intellisense. NTVS 1.2 Alpha 2 fixes a number of memory leaks and reduces memory usage across the board. There's still room for improvement, so please report any performance problems you encounter with Alpha 2.

Thanks.
