### ISSUE TITLE
No Intellisense 

### ISSUE THREAD

**Issue by ghost** [Microsoft/nodejstools#568]
I have a fresh install of Visual Studio 2015 with the 10/22 build of NTVS. Code completion fails to appear for stylus and jade (stylus files lack even highlighting). JavaScript files are limited to the most basic members. 

Any advice out there to get this plugin working?

**Comment by mousetraps** [comment]
@JuniorHaxe we don't have code completions for jade, and VS doesn't have any built in stylus support. Feel free to vote for the uservoice request here:
* https://webessentials.uservoice.com/forums/140520-general/suggestions/3084755-syntax-and-compile-support-for-stylus

In the meantime, you can try just opening the stylus files using the CSS editor (you can set the default editor by right clicking a file in solution explorer, and selecting "open with", select the CSS editor, and "set as default"), or manage your default file extension settings in Tools > Options > Text Editor > File Extension.

Regarding your other issue, what do you mean JavaScript files are limited to the most basic members? Could you elaborate on what completions you're seeing and what completions you expect to see?

**Comment by mousetraps** [comment]
Hey, mind trying out this private build and letting me know if it fixes the intellisense issue for you? https://github.com/mousetraps/nodejstools/releases/tag/v1.1.PrivateDev-10.11.2015

**Comment by mousetraps** [comment]
Closing this as we have yet to receive more info that would help us diagnose the issue. Please let us know if you're still running into issues with the latest dev build, and we'll reopen. https://github.com/Microsoft/nodejstools/releases
