### ISSUE TITLE
VS2015 Execute MSBuild InlineTask

### ISSUE THREAD

**Issue by AndreSayreMSFT** [Microsoft/nodejstools#57]
Hello, 

I'm trying to run this simple inline task at the end of njsproj file without success:
```xml
<UsingTask TaskName="Hello2" TaskFactory="CodeTaskFactory" AssemblyName="Microsoft.Build.Tasks.v12.0" >
  <ParameterGroup />
  <Task>
    <Code Type="Fragment" Language="cs">
      Log.LogMessage("Hello, world!", MessageImportance.High);
    </Code>
  </Task>
</UsingTask>
<Target Name="TestBuild" BeforeTargets="Build">
  <Hello2 />
  <Message Text="hello message" Importance="high"/>
</Target>
```
I get the error MSB4175, but even if I copy the dll to MSBuild 12.0 folder, the task is unable to run. 

I'm using VS2015, but I think the problem occurs in VS2013 too. 

Thanks in advance for your help.

**Comment by mjbvz** [comment]
Not sure this is NTVS specific. While I'm not too familiar with msbuild and tasks, but was able to get this working by changing the line: `AssemblyName="Microsoft.Build.Tasks.v12.0"` to read `AssemblyName="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v12.0"` 

If anyone is still running into this problem, give that a shot.

Sorry for the delay getting around to this.
