### ISSUE TITLE
Provide a flag to indicate that the debugger is attached

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/nodejstools#572]
Hi,

I'm not sure if this is already available in some form. I just wish to run separate code when the debugger is attached. I wonder whether the debugger has access to `process` or a similar global var in Node in order to set a flag, e.g

```javascript
if(process.env.debugger){
  // only when debugging
}
``

**Comment by billti** [comment]
Sounds like what you want is a Node feature, not an NTVS feature. There is some discussion on this topic at http://stackoverflow.com/questions/6889470/how-to-programmatically-detect-debug-mode-in-nodejs

Alternatively, you could set an environment variable on the project properties for when VS launches the project and detect if that is set.

NTVS can't just go adding extra command-line switches/options to signify this, else that may affect how Node apps parse the command-line.

**Comment by NoelAbrahams** [comment]
Okay, understood. Incidentally, the following (from the link) seems to work:

```javascript
        if (typeof v8debug === 'undefined') {

            throw new Error('Do not execute unless debugging');
        }
```

Thanks.
