### ISSUE TITLE
Error - cannot start npm

### ISSUE THREAD

**Issue by christian4423** [Microsoft/nodejstools#576]
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)   at System.Diagnostics.Process.Start()   at Microsoft.VisualStudioTools.Project.ProcessOutput..ctor(Process process, Redirector redirector)Error - cannot start npm

I am unable to much with this tool. 
No matter what I do I get this error. I am up to date with the tool with Visual Studio 2013 Professional. 
In my project properties I have made sure the path is set to node.exe as well.

**Comment by billti** [comment]
Have you installed Node from http://nodejs.org and can run both Node and NPM from the command-line? (Open a Windows command prompt and try (`node --version` and `npm --version`).

**Comment by christian4423** [comment]
Yes, I am running the latest version of node. I was using cmd and sublime text with the nodeunit module flawlessly. But in vs2013 professional I am getting that error. I am able to right click on my solution and get to command line that way and install node modules. I tested it on my buddies work station who is running the same environment as me and it worked in his visual studio

**Comment by christian4423** [comment]
My npm was out of date. It was 2.14.7 now it is 3.3.10 and I am still getting this error.

**Comment by billti** [comment]
Thanks. One silly question, but worth asking: has VS been restarted since you installed Node/NPM? Sometimes processes don't detect changes to environment vars (i.e. that PATH) until they are restarted.

Also, is Node/NPM installed to the default location (i.e. "C:\Program Files")? Do you have anything non-default about the install (e.g. Windows installed to a drive other than C:, VS in a custom location, your user profile folder redirected, etc.).

**Comment by christian4423** [comment]
Yeah, when I upgraded npm I changed the path from the the npm in program files to the app data path. That way I do not have to worry about npm getting overwritten when node.js installes or upgrades next.

**Comment by mjbvz** [comment]
@christian4423 Sorry for the lack of better follow up here. I'm going to close this for now since it is not clear if this is still an issue. Please reopen if the original problem is still occurring for you.

Thanks
