### ISSUE TITLE
Error: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#577]
During the run via debugger, application does not start when I load module which has native binding it produce errors

```
Error: %1 is not a valid Win32 application.
```

I have installed 
VS2015
NTVS 10-22-2015 Dev Build
NodeJS 4.1.1

**Comment by mousetraps** [comment]
This looks like an error with the native module, not with NTVS. Have you tried running the app via the command line?

**Comment by kant2002** [comment]
Yes, I do try. With command line working fine.

**Comment by kant2002** [comment]
I suspect that this is something with configuration on my PC, not NTVS per se. But this could be good opportunity for docs.

**Comment by mousetraps** [comment]
Native modules are always annoying... Probably some env vars are amiss or something. Maybe try to debug with automatic exception handling turned on?

**Comment by mousetraps** [comment]
(In NTVS, that is, not NTVS src)

**Comment by kant2002** [comment]
Where could I find this setting? in the Tools -> Options -> Node.JS Tools, don't see anything like that.

**Comment by mousetraps** [comment]
Ctrl + alt + E, select all node.js exceptions

**Comment by kant2002** [comment]
Aa, this one :smile: . Let me try.

**Comment by kant2002** [comment]
I swamped with ENOENT errors

Below full stack trace from command line
```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: %1 is not a valid Win32 application.
PROJECTROOT\node_modules\lwip\build\Release\lwip_image.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at PROJECTROOT\node_modules\lwip\lib\Image.js:3:22
    at Object.<anonymous> (PROJECTROOT\node_modules\lwip\lib\Image.js:16:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by kant2002** [comment]
BTW: When I run application from Node.JS interactive Window everything is working.

**Comment by mousetraps** [comment]
Hrm... I've been using lwip this past week and haven't run into any issues in VS. I have a *hunch* about what it might be, though... Could you try printing out `process.version` and `process.arch` in both your running app and in the interactive window and report the results? I have a feeling there's a node version / architecture issue at play here...

**Comment by kant2002** [comment]
From console
```
process.version = 'v4.1.1'
process.arch = 'x64'
```

When running from VS
```
process.version = v0.12.7 
process.arch = ia32
```

**Comment by billti** [comment]
So it looks like the native module runs fine in Node v4 x64, and not Node v0.12 x86 then. I take it you have both installed on the box. If you point to the Node v4 .exe location for the project properties to launch does it run fine?

**Comment by kant2002** [comment]
Brilliant!! @billti, I thought that you are using some internal version of Node. Forget that it could be configured in the project settings. Thanks a lot!!!

**Comment by kant2002** [comment]
Maybe it is so simple, so it is good to put it on the wiki, in the some 'well-known issues' page. I don't see such page, but I think would be good to have something like that. What do you think?

**Comment by kant2002** [comment]
Now I change my mind. I think this is an issue with `NodeExePath` settings. By default the value of the `NodeExePath` should be based on the settings in my PATH env variable, not some predefined value.

**Comment by mousetraps** [comment]
@kant2002 this is the logic we currently use to determine the default node exe path. Perhaps it would make more sense to check the PATH before the reg key. 
https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Nodejs.cs#L54

Hints on how to check things are configured as expected (printing process.arch and process.version) might be useful to add to the NTVS wiki.

And re: general issues w/ node or node+windows, our new guidelines repo is better suited for that content, but adding a pointer from the wiki would be great as well (similar to how we do in the [readme](https://github.com/Microsoft/nodejstools#documentation)) https://github.com/Microsoft/nodejs-guidelines

**Comment by kant2002** [comment]
Hmm, I understand logic why Registry was put in the first place. For large company like MS shipping product potentially require to have external dependencies pinned. But from end-user perspective (and for Node.js user in the first) this logic seems counter-intuitive and should be replaced with PATH-first strategy, or better I could also select which Node.JS version is used in the Node.JS Tools options page. I definitely want have ability to override such option globally, to simplify my life with VS.

I suspect that current installation issues could come from Apache Cordova Tools for VS which install NodeJS if I remember correctly. Since you could not influence how people install that, it is reasonable to provide option for developer to override global settings. Actually this is place where I initially look for NodeJS path override, and then even not look in the Project Properties, since I think they are useless.

**Comment by billti** [comment]
Cordova had an issue where they weren't detecting x64 Node, and so were still installing an x86 version regardless. They have fixed this (I logged this bug against them, so verified the fix also). Thus with the latest Cordova, if you already have Node installed, it should correctly detect it and not install it's own copy.

Checking the registry first makes sense to me. A default Node install will always update the PATH environment variable, so the override registry key would never be used if PATH was checked first.

**Comment by heiliuer** [comment]
for me,follow steps is ok

node uninstall node-sass
set PYTHON="C:\Python27\python.exe"
node install node-sass
