### ISSUE TITLE
NTVS breaks when you have doskey setup

### ISSUE THREAD

**Issue by zagros** [Microsoft/nodejstools#579]
# Background

It's possible in Windows to mimic ~/.bash_profile feature of unix system by the following mean.  NTVS breaks when you setup this behaviour.  As a result I have to disable all my shortcuts.
# About Doskey Command in Windows
- [Doskey Documentation](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/doskey.mspx?mfr=true)
- [Command Processor Autorun](https://technet.microsoft.com/en-us/library/cc779439%28v=ws.10%29.aspx) :  This feature mimics the bash profile feature of linux
# How to replicate
- Create a file `C:\some_folder\my_profile.cmd`
- Edit the registry key `HKEY_CURRENT_USER\Software\Microsoft\Command Processor\Autorun` and set it to the path above (i.e.  `C:\some_folder\my_profile.cmd`)
- Open the `my_profile.cmd` and put some doskey mapping (anything). for example: `doskey desktop=cd %USERPROFILE%\desktop`
- Now open an existing Node project in VS
- VS Crashes
- Go and disable the `Autorun` command by renaming it to `Autorun_bak`.  Now open VS and your node project.  Everything is fine.

**Comment by paulvanbrenk** [comment]
Closing as we'll probably never get to this.
