### ISSUE TITLE
Can't Build Project or Publish to Azure

### ISSUE THREAD

**Issue by krusk** [Microsoft/nodejstools#580]
am using NodejsTools in Visual Studio 2013, but can publish my project to Azure. When I build my file I get the following error:

>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Node.js >Tools\Microsoft.NodejsTools.targets(115,5): error MSB4018: The "AssignTargetPath" task failed >unexpectedly. System.IO.PathTooLongException: The specified path, file name, or both are too long. >The fully qualified file name must be less than 260 characters, and the directory name must be less >than 248 characters.

Any clues on how I can fix this/get my node project to publish up to Azure?

**Comment by krusk** [comment]
When I publish I get this error:

>Error	1	Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path ".\node_modules\azure\node_modules\azure-keyvault\node_modules\azure-common\node_modules\request\node_modules\form-data\node_modules\combined-stream\node_modules\delayed-stream\lib\delayed_stream.js". C:\Users\krusk\documents\visual studio 2013\Projects\CoBox\CoBox\node_modules\azure\node_modules\azure-keyvault\node_modules\azure-common\node_modules\request\node_modules\form-data\node_modules\combined-stream\node_modules\delayed-stream\lib\delayed_stream.js

**Comment by billti** [comment]
Unfortunately you are hitting the infamous MAX_PATH issue. See https://github.com/Microsoft/nodejstools/issues/69 for more details / background / workarounds.

**Comment by mousetraps** [comment]
In addition to using a shorter path, npm v3 (which installs modules maximally flat), or some of the other workarounds suggested, you can use git deploy to Azure, which will do an npm install on deploy (which means you can avoid deploying node_modules altogether.

For more information, check out our new guide that includes tips for getting past common gotchas like MAX_PATH: 
https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#max_path-explanation-and-workarounds

**Comment by krusk** [comment]
Thank you!
