### ISSUE TITLE
VS "Navigate To" feature needs enhancements when using Node projects

### ISSUE THREAD

**Issue by zam6ak** [Microsoft/nodejstools#581]
If you activate "Navigate To" (CTRL + ,) while in Node JS project and try to search for a file name (try "common.js") it lists all the hits from node_modules which "pollutes" the dropdown and makes feature unusable.

"Navigate To" should work better in Node projects. 
Just try to compare it to VS Code (CTRL+SHIFT+F) or Atom (CTRL+T) functionality.

**Comment by mousetraps** [comment]
I wouldn't go so far as to not list items in `node_modules`, but I agree that making the sort order smarter and making node_modules easier to filter out would be helpful. Searching for index.js is a lost cause at the moment...

**Comment by mousetraps** [comment]
Unfortunately I don't know if this is a point of extensibility within VS, so we may not be able to handle this without changes from VS-land.

**Comment by mousetraps** [comment]
Ooh, actually - you *can* filter out node_modules by de-selecting 'show all files' in Solution Explorer. It's not the best solution in the world, but it's something :smiley:

**Comment by mousetraps** [comment]
If anyone wants to investigate this, I believe the correct interface is `INavigateToItemProvider`:
https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.language.navigateto.interfaces.inavigatetoitemprovider.aspx

**Comment by paulvanbrenk** [comment]
Moving to the TS LS fixed this
