### ISSUE TITLE
Unable to debug half of the time

### ISSUE THREAD

**Issue by djflex68** [Microsoft/nodejstools#583]
I have the latest version of node JS tools for Visual Studio 2013 (RC 2.1) and it's still impossible to launch properly the debugging process. The console hangs on "Debugger listening on port xxx" and nothing happens.  I have to relaunch Visual Studio to get it working again.
![image](https://cloud.githubusercontent.com/assets/6740026/10965650/d5231c90-83ae-11e5-9d32-c6de6453b8b1.png)

**Comment by billti** [comment]
When you say "I have to relaunch Visual Studio to get it working again", so it does work then at least once after you start VS? Can you detail for me when it does/doesn't work (i.e. always works first time after launch, 50% success after that, etc.).

Has this been a consistent or recent problem with the tools? Which version of Node are you using?

**Comment by mousetraps** [comment]
Also have you tried the latest dev build? We fixed an issue with the same symptoms some time after RC2.1 https://github.com/Microsoft/nodejstools/releases

**Comment by barrycarr** [comment]
Hi,
I'm having  the same issue. except that debugging doesn't work 100% of the time for me. I can launch the debugger and I see the console window, as aboe, but the debugger never stops on a break point. 

I'm currently running:
* VS2015 Community
* NTVS 1.1
* Node 4.2.2 (x64)
* Windows 10 (just upgraded from Win 7) 

I was using Resharper 10, but un-installing that made no difference.  I also tried debugging using the 32bit version of node 4.2.2, but that didn't make any difference, either. I have no problems debugging with Chrome via the node-inspector package, btw.

If there's anything else you need to know, please let me know. Thanks

**Comment by kritollm** [comment]
Same problems here, didn't stop on breakpoint before a function call, but if I placed the breakpoint inside the function to be called it stopped correctly. I remember I had  problems in Visual Code when I tried to debug a node app there a few months ago, breakpoints didn't work well with async code.

**Comment by billti** [comment]
Sorry you're hitting issues here.
@barrycarr Your setup looks similar to mine in terms of software and versions, and I'm not seeing this behavior. Is it in a specific project or code pattern? Or even if you just create a new simple project with a few "console.log()" statements and try to step through it do you see the issue?

If it's with a specific project or code pattern, would you be able to provide a repro we can use?

Note there is also the debug diagnostics you can enable. The output from this would be helpful also. See https://github.com/Microsoft/nodejstools/issues/246#issuecomment-127715686 for details.

**Comment by dasariramacharan** [comment]
I face the same issue when i create a new "empty console nodejs" using vs2015 professional with update 1.  I was able to resolve the issue by running the visual studio in admin mode.

I am able to debug or see ouput for my code only if i run as admin.

**Comment by isaacllopisaracil** [comment]
A related issue in StackOverflow here: http://stackoverflow.com/questions/31321808/ntvs-projects-do-not-run-at-all-when-i-click-start-or-press-f5

**Comment by cseppy** [comment]
Experiencing the same issue here w/ VS 2013 and version 1.1.30910.02 of the tools. My projects launch into debug about 40% of the time. I usually get around this by starting w/ out debug. If I have to debug in node, a relaunch usually works the 1st time.

I just created a new node express 4 project and it failed to launch debug 2x in a row. I relaunched and it worked.

**Comment by cicorias** [comment]
Also getting a hang just stepping through debugger - I have a hang dump if interested.

**Comment by jtobinisaniceguy** [comment]
Also getting a hang with VS2015/ndoe.js tools 1.1.31117.00 and node 5.2.0
Anecdotally happens after computer goes to sleep, 100% after a hibernate
Recovery is to end task VS2015 and start again

Info report as follows:

Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA758
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA758
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA758
Microsoft Visual C++ 2015

Visual F# 2015   00322-20000-00000-AA758
Microsoft Visual F# 2015

Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA758
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Node.js Tools   1.1.31117.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.1.31117.00
Profiling support for Node.js projects.

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.31105.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.31105.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.31105.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual Studio Tools for Universal Windows Apps   14.0.24720.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Xamarin   3.11.837.0 (f10676f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   5.1.5.3 (f98871a95a479f6d71b3067b7e5834d41fcb2118)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   8.10.4.0 (6db87c53c073f4af2f5247fb738a27ea08c094fd)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS Unified Migration   1.0
Automated migration for Xamarin iOS Classic projects to Unified

Xamarin.TestCloud.Integration   1.0
Early preview of Xamarin Test Cloud integration

**Comment by mjbvz** [comment]
p{ease try downloading and using the [NTVS 1.2 Beta](https://github.com/Microsoft/nodejstools/releases). We've made a number of improvements to debugger reliability and I have not seen this problem recently. 

Please try out 1.2 and let me know if you are still running into this issue. and we can continue the investigation. Thanks.
