### ISSUE TITLE
Intellisense with 'require'd libraries

### ISSUE THREAD

**Issue by josephliccini** [Microsoft/nodejstools#587]
Hello!

First, NTVS is great!  Really like the VS Integration with Node, so thank you for great work!

I'm having a few issues with intellisense, but first, I'll give you the configuration I am using:

NTVS 1.1 RC 3
Visual Studio 2015 Community (haven't installed Update 1)
NodeJS v0.12.7
NPM v3.4.0
VSVim

I am running into completions not showing (with Ctrl-SPACE) on libraries (i.e., lodash).

```js
var _ = require('lodash');

function foo() {
	_.<CTRL-SPACE>
}
```

Now, I thought it was a MAX_PATH issue but I resolved that by installing NPM 3.4, and moving the .sln containing folder to C:\;  however, since fixing MAX_PATH, I'm still not having completions.

On built-in modules, however, I'm able to get completions; i.e. modules ```fs```, ```path```, ```http```, etc.

Is this intended behavior, or am I doing something wrong?

I thought maybe including the node_modules folder in the project would help, but when I went to do that, I got a warning, so I figured it wouldn't help.

Thanks!
Joe

**Comment by mousetraps** [comment]
Hey, I just fixed #566, which may be related. Mind trying out this private build and seeing if it fixes the issue for you? https://github.com/mousetraps/nodejstools/releases/tag/v1.1.PrivateDev-10.11.2015

**Comment by josephliccini** [comment]
Tried it and no luck; 

I also deleted the .ntvs_analysis.

I was able to get completions still on built-in NodeJS modules, and on a 'require'd module I wrote, but not on any of the ones installed by NPM.

**Comment by mousetraps** [comment]
Just to help isolate the issue... Can you try with a brand new project and the build provided above? Then try installing a package like express, wait 30 seconds, and see if intellisense appears?

**Comment by josephliccini** [comment]
OK finally got a chance to try this.

When I did a new Basic Web NodeJS project, npm installed Lodash and Express, waited 30 seconds, and there were no issues (IntelliSense appeared normal and completely).

I'm not sure if it is worth mentioning, but my project with IntelliSense issues is a rather large project with many dependencies, forked from the MEAN stack boilerplate, and I created the .njsproj / .sln from 'Existing NodeJS Code' option.

**Comment by MaciejHanajczyk** [comment]
Hi,
It's working with loaded libs like express or lodash, but theres no intellisense at all for node js core modules. 
This seems like very import feature to have for any people starting with NTVS 

```
var fs = require('fs');

function foo() {
    fs.<CTRL-SPACE>
}
```

**Comment by MaciejHanajczyk** [comment]
The same in this startup clause

```
http.createServer( function (req, res)
{
    res.writeHead(200, { 'Content-Type': 'text/plain' });

    res.<CTRL-SPACE>

}).listen(port)
```

**Comment by MaciejHanajczyk** [comment]
I've reinstalled NTVS and it all works as a charm :)

Great stuff.

**Comment by mousetraps** [comment]
closing this issue, as it's been a while and we've updated quite a bit since. please file a new issue if you're still running into problems with the latest releases. 
https://github.com/Microsoft/nodejstools/releases
