### ISSUE TITLE
Dev14 underscore in a typescript file causes VS to crash

### ISSUE THREAD

**Issue by AndreSayreMSFT** [Microsoft/nodejstools#59]
VS 2015 Preview (build 22310.01) 
NTVS 21117.01 

Repro step
Create a Typescript node console app
In app.ts, type:
import _
This brings up the intellisense window then VS crashes. An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll 

Callstack is attached. 

This seems to only occur on VS 2015. 
![callstack](https://cloud.githubusercontent.com/assets/10080679/7077337/dc387834-dec4-11e4-83d5-0945b785ab5a.png)

copied from https://nodejstools.codeplex.com/workitem/1562`

**Comment by jinglou-** [comment]
This is no longer repro in the latest build of VS 2015 (22803.01) and NTVS 1.0 RTW code base.
