### ISSUE TITLE
Installing NPM packages requires Node to be installed on the machine

### ISSUE THREAD

**Issue by billti** [Microsoft/nodejstools#597]
Feedback below. If this is indeed the case, we should update the error string.

> I don’t have Node installed and configured on my machine but I do have the node.exe in a directory.
> Now I create a new Node.js project and want to add a new Node module.
> When I right click on the Npm node and choose “Install new NPM package” I got the message that Node is not installed and that I should either install Node or configure the path to Node.exe in the project properties.
> I configured the path and it was still not working.
> 
> According to this, this behavior is expected, so I suggest that you change the message string

**Comment by mousetraps** [comment]
Agreed. For additional context, the npm path comes from the node.exe path, so this error will throw if npm is not in the same directory.

**Comment by mjbvz** [comment]
#1097 improved the messaging here to make it more clear what is going wrong. It now states if npm is not found.
