### ISSUE TITLE
Visual Studio Code?

### ISSUE THREAD

**Issue by rickmed** [Microsoft/nodejstools#600]
Is this available with VS Code? thanks.

**Comment by mousetraps** [comment]
Just Visual Studio, but let us know what Node.js Tools features you're most excited about and we'll consider bringing them to VSCode!

**Comment by ricmed205** [comment]
I think having an interactive console where you could do all the cmd stuff and a JS repl would be very useful.

**Comment by jjmartin** [comment]
apologies if this comment is inappropriate for this venue, I recently switched to VS Code for my nodejs work from VS Pro with NodeJs Tools  (+resharper).

i found that VS was super unstable with the njs tools and would crash and restart.   it would do a lot of hanging and not let me get work done.

with vs code i miss some of the project structure and some of the built in testing (although after some setup - i am easily able to debug and the tests run a whole lot faster than they ran in VS)

I'm also easily able to take care of syntax issues with the mocha tests or other stuff that causes the squiggly lines through getting the type files in vs code.   That would be a great feature for the nodeJs tools to have is a quick way of getting those type files so the mocha syntax doesn't cause so many visual warnings.

VS code just comes in being cleaner, faster and more oriented towards node js with the error/warnings... where vs seems super heavy, was crashing and it was difficult to tell some of the interactions i was having between various plugins like resharper vs the nodejs tools.    I wouldn't want to disable resharper while i'm in a project with nodejs in it.

**Comment by rkavalap** [comment]
+1

Just tried VS code on my mac recently. I have liked it so far. It's quite different from how Visual studio works.

Things I wish to see in Visual studio / VS code preferably to have same experience 
When I press F5 to debug, IDE generally does a build (C#). Whereas in NTVS I don't have an option to do just build and debug simultaneously. I am bound to perform an explicit build task using an extension like task runner explorer or from command line and then debug. 
I would wish if there was an inclusion of prebuild / post build like how we have in csproj fils so I can add any specific commands like an msbuild task. For any compilation, less 'ing, lint 'ing etc within the .njsproj. 

Will have to see the behavior in VS code. still haven't gotten that far yet.

**Comment by mjbvz** [comment]
Closing since this doesn't track something that can be resolved. 

If you have any recommendations for NTVS based on your experience with VS Code, please open separate issues to track them.

If you have any suggestions for VS Code, please open an issue against the [main VSCode repo](https://github.com/microsoft/vscode) or the [VSCode node debugger repo](https://github.com/microsoft/vscode-node-debug)
