### ISSUE TITLE
NodeExePath variabel should not be saved in Project file by default

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#602]
I see value in storing `NodeExePath` variable in the project file, but for most folks, this is unnecessary and preferable stored in the `.user` file. That way I could change path to Node and it would not affect other team members, which have differnt PC. For example I work on x64 bit CPU, some other guy on 32-bit, or just have 32-bit node.

**Comment by mll75** [comment]
Yes, this feature would be greatly appreciated!
In our team, node is copied locally in a different path for each user.
Meanwhile, we had to use a template to ensure source control will not commit the project file.

**Comment by paulvanbrenk** [comment]
Technically the default is still the project file, mostly because it's the same for ASP.NET, and I didn't want to update all project templates
