### ISSUE TITLE
support for tsconfig.json

### ISSUE THREAD

**Issue by pankleks** [Microsoft/nodejstools#605]
Can we have support for tsconfig.json files?
For real typescript based projects it's really hard to work without this.

**Comment by pankleks** [comment]
Any news around it?

**Comment by mousetraps** [comment]
We'll be working more closely with the TS team going forward to ensure we have fewer discrepancies like this, so it's on the roadmap, but we don't know when exactly we'll get to it just yet.

**Comment by pankleks** [comment]
any updates on that?

**Comment by mjbvz** [comment]
Support for `tsconfig.json` files seems to have be introduced into Typescript for VS at some point (perhaps TS 1.8). I've tested with a `tsconfig.json` at the root of my NTVS project and see the configuration options getting picked up properly during compilation.

Let me know if there is some other aspect of `tsconfig.json` support you were looking for, or if you have any ideas on how the experience could be improved.

Thanks.
