### ISSUE TITLE
Visual studio layouts

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#606]
@mousetraps' excellent [introductory video from Connect15](https://channel9.msdn.com/Events/Visual-Studio/Connect-event-2015/801) shows a nice minimal VS layout. However the default layout is more cluttered IMHO and those new to VS would benefit from instructions on how to get this simpler layout. Or at least a link to the VS docs on this

PS the video should be made high profile in the docs / website

**Comment by mousetraps** [comment]
Hey @SteveALee, just made a repo with some of the settings I use during development to keep things minimal. 
https://github.com/mousetraps/minimal-vs-settings

Thoughts?

**Comment by SteveALee** [comment]
Great - I added an issue over there

**Comment by mousetraps** [comment]
also added this link to the recommended extensions
