### ISSUE TITLE
Installation of 1.1 is still slow

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#607]
I installed on 2 computers running VS Community.

1) With Windows 10 and SSD - stopped at with progress bar at 75% for >1 min
2) Windows WIndows 10 preview and HD - still waiting with progress at 100% and then 75% after 5 mins

I did **not** un install 1.1 dev release first.

**Comment by mousetraps** [comment]
Can you please check the task details pane while you're installing and see if devenv /setup is running in the background at this time? If so, sounds like a VS issue, and in theory the RTM of update 1 will address some of this concern.

**Comment by SteveALee** [comment]
> Can you please check the task details pane while you're installing and see if devenv /setup is running in the background at this time

Yes it is. I ran the repair option this time which was quicker. I then tried update and it sticks at "updating extension registration with VS". 

Seem pretty clear it is a VS issue
