### ISSUE TITLE
Outdated survey/news

### ISSUE THREAD

**Issue by MarkStega** [Microsoft/nodejstools#608]
After installing 1.1 the menu item Tools->Node.js Tools->Survey/News shows old news & survers about v1.0; Either the destination page needs updating or the menu item needs deprecating.

**Comment by mousetraps** [comment]
Thx for calling us out on that! We've been bad about updating it lately...

**Comment by mousetraps** [comment]
Expect us to start up again soon :-)

**Comment by mjbvz** [comment]
We just updated this again for [NTVS 1.2 Beta!](https://github.com/Microsoft/nodejstools/releases) and plan to keep this more up to date in the future.

![image](https://cloud.githubusercontent.com/assets/12821956/16251590/3c186d38-37dc-11e6-9749-fbd16cafe396.png)
