### ISSUE TITLE
icon in solution explorer for Typescript files in VS2013 is incorrect

### ISSUE THREAD

**Issue by jinglou-** [Microsoft/nodejstools#61]
VS 2015 22803.01
NTVS 30324.01
![typescript_iconissue](https://cloud.githubusercontent.com/assets/10081483/7099403/f1410506-dfa6-11e4-995a-c3cefbd947ee.png)

**Comment by heroboy** [comment]
In my VS2013 solution explorer the .js and .ts files' icons are the same. 
Is it a bug?

**Comment by mousetraps** [comment]
Yeah, it should be different (see this HTML App project)
![image](https://cloud.githubusercontent.com/assets/762848/7245059/db737876-e799-11e4-948f-afdb3c6be261.png)

**Comment by mousetraps** [comment]
Fixed this issue for VS2015 using the new project system improvements, but VS2013 is still broken.

**Comment by billti** [comment]
Fixed for VS2015. Not a major issue for VS2013. Closing.
