### ISSUE TITLE
An extra quotation mark is added when trying to run a folder as the startup file

### ISSUE THREAD

**Issue by coyninja** [Microsoft/nodejstools#610]
I'm working with nw.js (Previously Node-Webkit) using Visual Studio 2013 Premium Update 5 with Node.js Tools 1.1.3, and I set the project properties to the following:

**Node.exe path:** N:\Projects\nw.js\nw.exe
**Script (startup file):** .
**Working Directory:** .

This launches nw.exe, however it does so using the following command:

"N:\Projects\nw.js\nw.exe" "N:\Projects\nwjs_projects\Solution.nw\Project.nw\""

Notice the extra quotation mark. If I copy and paste the string above into a command prompt - I get the same error, obviously. If I remove the extra ", it works fine.

**Comment by paulvanbrenk** [comment]
A solution would be to parse the command line our selves in the `PressAnyKey` main method. Not a fan though.

**Comment by paulvanbrenk** [comment]
Closing, since we no longer depend on the `PressAnyKey` utlity for Node 8+ and we don't want to invest in Node 6.
