### ISSUE TITLE
EditorConfig is not applied to package.json

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#612]
With EditorConfig extension installed and .editorconfig containing
<pre>[*]
indent_style = space
indent_size = 4
</pre>

my .js files are indented to 4 spaces as expected but package.json is using 2 spaces.

**Comment by mousetraps** [comment]
Hrm - any reason to believe this issue belongs here, rather than than w/ EditorConfig?

**Comment by SteveALee** [comment]
er, no. Just that I was completely focussed on NTVS intellisense and parsing.

In fact once I exited VS and restarted all was well.

sorry for the noise.
