### ISSUE TITLE
New ES6 intellisense

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#613]
I'm using node 4.x.x and the built in [ES6 features](https://nodejs.org/en/docs/es6/) like `const` and template strings. Currently this seems to be unsupported in intellisense

1) The maximum intellisense option doesn't recognise `const` and highlights ` as an error
2) The ES6 intellisense support appears to just show 'any' for everything.

The problem with adding Definitely Typed definitions is they are community maintained For Hapi the file is very out of date so not really much use. Plus it's a real pain to manually insert and manage the references in each file.

I think an approach that supports ES6 without manual management of definitely Type refs is required.

**Comment by mousetraps** [comment]
Thx for the feedback! Yeah, unfortunately we're taking a step back here in the interest of taking a couple steps forward... See our current discussion on this topic: #488

Regarding max intellisense... we actually do support const & let, but yes - syntax highlighting for most everything else is missing :frowning:

**Comment by SteveALee** [comment]
Are you suggesting the need for explicitly DT refs will removed in time? That requirement is bit of  deal breaker for me. I seem to recall @code required them in the first release but it may have been removed later?

I fully agree with the desire to collaborate with other efforts in this area. But, I'd like to avoid the extra work of managing explicit DT refs, especially as I tend to have many small source files

Can you point me at good introductory docs for the new TS intellisense? I've been trying it with more substantial code and am seeing more useful intellisense now. However, there's still lots of unknowns and 'any's compared with the full NTVS intellisense.

If it's faster that will be a boost, though latest full NTVS intellisense is pretty good now.

The ability to browse using the top combos is a nice extra.

**Comment by billti** [comment]
Tracking this discussion in #488

**Comment by SteveALee** [comment]
##Weird behaviour with ES6 intellisense enabled. ##
I assume it's intellisense as I have disabled all extensions I could and there is no source of the errors given

1) clean project to empty errors list
2) Save the file or simply close and open error list again

![image](https://cloud.githubusercontent.com/assets/618922/11514342/e238d412-986f-11e5-9529-8fa469ef949a.png)


Line 16 is <pre>internals.webBaseURL = `http://${internals.serverHost}:${internals.serverPort}`;
</pre> and as we can see it's correctly highlight the backtick template string

My guess is it's parsing without ES6 on. I set the project to autoload on startup

If I then double click on the error it get this
![image](https://cloud.githubusercontent.com/assets/618922/11514300/a224a3e2-986f-11e5-9841-c8cd93ed4001.png)

And if 'yes' then the intellisense boxes at the top of the file disappear and the highlighting indicates it doesn't like the backtick character - as per the error.

![image](https://cloud.githubusercontent.com/assets/618922/11514318/c16da60e-986f-11e5-9c96-b4dd09b56e87.png)

If I then double click on the file in solution explorer I get the message box again and the intellisense reverts
