### ISSUE TITLE
During opening solution 'Source array was not long enough.'

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#614]
Full error:
```
error  : Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
```

**Comment by mousetraps** [comment]
Can't reproduce, and there's no way we can do anything about this issue with so little information.

**Comment by kant2002** [comment]
Unfortunately not, maybe this is not NTVS issue by iteself, VS 2015 is pretty buggy on itself. I post it here, just in case I could reproduce consistently.

Give me some time to try to reproduce, if I could not find any additional info, then don't mind. I just accept that current release of VS2015 is unreliable.

**Comment by billti** [comment]
Closing with no further info. Will reopen if we can get more details on any issue here.
