### ISSUE TITLE
Solution loading is stuck

### ISSUE THREAD

**Issue by RaniSharim** [Microsoft/nodejstools#620]
vs 2013 + update 5
Nodejs Tools 1.1

This project is working on my teamates computers, by on my pc it gets stuck 80% of the time.
I'v disabled intelisense, that doesn't seem to help.

Deleting the v12.suo seems to solve it temporarily, but it gets stuck again when I reopen it.

**Comment by mousetraps** [comment]
Interesting... we don't actually do anything with the .suo in NTVS... Mind grabbing a dump of the process next time you run into it?

**Comment by zaifworks** [comment]
I am running into the same issue. Deleting .suo fixes it every time.

Microsoft Visual Studio Professional 2013
Version 12.0.40629.00 Update 5
Node.js Tools   1.1.31117.00
Node.js Tools - Profiling   1.1.31117.00

This project uses aws and azure npm packages. Attached is the procmon capture of the devenv.exe process when opening the project.

Thanks for all the help.

[NJS-Project-Stalls.zip](https://github.com/Microsoft/nodejstools/files/67902/NJS-Project-Stalls.zip)

**Comment by RaniSharim** [comment]
I want able to 'solve' it by moving it to another folder. Specificaly vs2013 default project folder.

The dump is 600 mb, how should I deliver it to you?

**Comment by zaifworks** [comment]
I started out using the vs2013 default folder however I had to move it after installing some npm packages with deep folders.

**Comment by mjbvz** [comment]
This sounds like another manifestation of the MAX_PATH problems (see issue #69). Some work arounds in that case is to move the folder to a shorter path and to run `npm dedupe` on the modules.

 If you are still running into this problem, please let me know and we can continue the investigation. Thanks.

**Comment by RaniSharim** [comment]
I'm still running into this problem. The solution has stoped loading at all unless I delete the v12.sou file beforehand, even at the 'original' folder.

**Comment by RaniSharim** [comment]
I'm still running into this problem. The solution won't load at all at any folder unless I delete the v12.sou file first. 
What you're saying doesn't make sense to me, since it does work on the same folder for me if I delete the file, or for my teammates in the exact same folder - it should be either too long all the time or not too long all the time, the folder doesn't change.

**Comment by mjbvz** [comment]
Ok.

It's hard to know where to start looking on this since I cannot repo the problem. Can you try a few additional things:

* Turn on NTVS output logging to the console: `Tools -> Node.js -> Diagnostic Info` and check "Enable Node.js Tools Live Diagnostics output pane". Is anything interesting printed to the output pane while loading the solution?
* Look in the file:  `%AppData%\Microsoft\VisualStudio\12.0\ActivityLog.XML`. Are any errors reported during solution loading?
* Does this problem happen on a clean VS install? It'd be helpful to know if it's just that your VS is in a bad state or if NTVS is the root cause. Doing a full install may be too much work, so try disabling all extensions except NTVS, restarting VS, and then loading the solution. A list of extensions would also be helpful. This is found under: `Help -> About Visual Studio`

Thanks.

**Comment by RaniSharim** [comment]
1. Not that I can see.
2. No. The file doesn't even seem to be updated during project loading
3. a. The only extension i can disable without uninstalling is GitExtensions, and it doesn't seem to make any differance.

3. b. Attached the list of extensions:

Microsoft Visual Studio Professional 2013
Version 12.0.40629.00 Update 5
Microsoft .NET Framework
Version 4.6.01038

LightSwitch for Visual Studio 2013   06177-004-0446016-02989
Team Explorer for Visual Studio 2013   06177-004-0446016-02989
Visual Basic 2013   06177-004-0446016-02989
Visual C# 2013   06177-004-0446016-02989
Visual C++ 2013   06177-004-0446016-02989
Visual F# 2013   06177-004-0446016-02989
Visual Studio 2013 Code Analysis Spell Checker   06177-004-0446016-02989
Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio
ASP.NET and Web Tools   12.5.60612.0
ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
ASP.NET Web Frameworks and Tools 2013   5.2.30612.0
Common Azure Tools   1.4
Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools
Node.js Tools   1.1.40329.04
Node.js Tools - Profiling   1.1.40329.04
NuGet Package Manager   2.8.60723.765
NuGet Package Manager in Visual Studio. For more information about NuGet, visit Office Developer Tools for Visual Studio 2013 ENU   12.0.30626
Microsoft Office Developer Tools for Visual Studio 2013 ENU
PreEmptive Analytics Visualizer   1.2
SQL Server Data Tools   12.0.41012.0
Windows Phone 8.1 SDK Integration   1.0
Workflow Manager Tools 1.0   1.0
Git Extensions

**Comment by mjbvz** [comment]
Thank you for supplying all the requesting info. Unfortunately, without a way to reproduce this issue on our machines and without any obvious errors, there's just not enough information here to for us to investigate further.

I recommend that you [download and build the NTVS](https://github.com/Microsoft/nodejstools/wiki/Build-Instructions). Make sure to checkout the `1.1.x` branch for your testing. Then repo the issue and see where exactly the hang is occurring in the code. That way we can at least get a callstack that may hint at what is going on.

**Comment by infoGraphMT** [comment]
I have the same behavior with 
- Visual Studio 2012
-- Node.js Tools 1.1.40329.04
-- Node.js Tools - Profiling 1.1.40329.04
(and an earlier version I don't remember)
after upgrading NPM

An older copy of my project directory works fine. 

I also have an error in ActivityLog.XML which makes no sense to me:

```
<entry>
    <record>289</record>
    <time>2016/06/17 16:36:19.439</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Construction of frame content failed.&#x000D;&#x000A;Frame identifier: ST:0:0:{608f1815-db09-4978-b970-f45a5d5f46c7}&#x000D;&#x000A;Frame caption: &#x000D;&#x000A;Exception details:&#x000D;&#x000A;System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---&gt; System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.&#x000D;&#x000A;   bei A.cf0da657d5c366425fd56dbfb47c5dc22..ctor()&#x000D;&#x000A;   bei A.c576c1a6529d636ac03c13f674e97ac2c..ctor()&#x000D;&#x000A;   --- Ende der internen Ausnahmestapel&#x00FC;berwachung ---&#x000D;&#x000A;   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandleInternal&amp; ctor, Boolean&amp; bNeedSecurityCheck)&#x000D;&#x000A;   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   bei System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)&#x000D;&#x000A;   bei System.Activator.CreateInstance(Type type)&#x000D;&#x000A;   bei Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, ProvideToolWindowAttribute tool)&#x000D;&#x000A;   bei Microsoft.VisualStudio.Shell.Package.FindToolWindow(Type toolWindowType, Int32 id, Boolean create, ProvideToolWindowAttribute tool)&#x000D;&#x000A;   bei Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsToolWindowFactory.CreateToolWindow(Guid&amp; toolWindowType, UInt32 id)&#x000D;&#x000A;   bei Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()</description>
</entry>
```

This error does not appear on startup when the .suo-file is deleted.

When I delete the .suo-file, Visual Studio does not respond on startup with newly created .suo-file.
Old project also stops workingafter deleting original .suo-file.

**Comment by nquoctuan** [comment]
guys, seriously I cannot do anything, visual studio 2013 with nodejs tool 1.1 hangs forever at starting

Can anyone fix it ?

Thanks,

**Comment by mjbvz** [comment]
@nquoctuan Even with all the information provided by the other commenters, we've been unable to reproduce this problem locally and find the root cause of the hang. The best way to get this resolved is to debug NTVS on a machine that has this problem. [Try downloading and building NTVS on the `v1.1.x` branch](https://github.com/Microsoft/nodejstools/wiki/Build-Instructions) and reproducing the issue while debugging and let us know the results.

Otherwise, please try upgrading to VS2015 and NTVS 1.2. The new release contains many fixes and we have not see this issue reported for it yet.

Thanks.

**Comment by panlina** [comment]
Same issue for long, and just now it hangs every time at startup even it is not loading any solution. I've no other way but to uninstall NTVS, and VS gets back. Same VS 2013 + update 5, NTVS 1.1.

**Comment by infoGraphMT** [comment]
Just a shot in the dark: One of the significant changes from VS2013 to VS2015 is github-integration. 
I remember reading similiar problem descriptions connected to github-integration.
Maybe there is a relation?

**Comment by tawalke** [comment]
This issue still exists in VS2013 Update 5 with Node.js Tools version 1.1.x. I am a fan of VS as a former MS person, but I am going to have to leverage another tool.  The project hangs and does not come back.  Uninstalling and reinstalling VS2013 Update 5 and/or  Node.js Tools does not fix the issue.  

Not being able to repo, is not a solution or an answer.  I am the 3 person to note this issue in the past 30 days.  Please review this issue with more detail and urgency.
Thanks.

**Comment by infoGraphMT** [comment]
Downloaded, tried to follow build instructions, but does not work with VS2012 @mjbvz

**Comment by infoGraphMT** [comment]
Another observation: Activating interactive Window in VS will also cause a freeze (Tools > Node.js Tools > Interactive Window), even with no project loaded

**Comment by infoGraphMT** [comment]
I narrowed it:
works until 8-4-2015 Dev Build,
freezes on NTVS 1.1 RC2.1 VS 2012 or later

**Comment by beeisabelm** [comment]
+1

**Comment by cpoyraz** [comment]
+1 for VS2015

**Comment by paulvanbrenk** [comment]
Haven't seen this in v1.3 for either Visual Studio 2015 or 2017
