### ISSUE TITLE
[suggestion] Get an article on nodejstools in MSDN magazine

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#622]

**Comment by mousetraps** [comment]
I have no clue how to approach this or what particular content might be useful - any ideas?

**Comment by SteveALee** [comment]
The MSDN flash just landed in my inbox [with this ch9 video in it](https://channel9.msdn.com/blogs/raw-tech/nodejs-and-npm-for-the-windows-developer). I've not watched but perhaps Andrew Moll has ideas or could do a NTVS focused piece?

A general introduction to how NTVS supports node dev would be useful. IT could highlight the same features as your recent video

**Comment by SteveALee** [comment]
Hehe, so now I watch it I see it's "node Therapist" Sarah doing a deep dive. That would also work

**Comment by mousetraps** [comment]
Oh good - apparently I already know how to get featured, then :wink:

Thanks for the suggestion - closing as we sort of take opportunities as they come (and as we can afford to - time is of the essence), but we'll definitely keep it in mind for the future as a potential outlet to promote the product.
