### ISSUE TITLE
Unable to edit .jsx files

### ISSUE THREAD

**Issue by aweber1** [Microsoft/nodejstools#625]
I created a "Blank Node.js Web Application", then added a file with a `.jsx` extension. I'm able to open the file and view its contents in Visual Studio. However, I am unable to make any changes/edits within the file. I am able to edit other files in the project (`.js`, `.json`, etc...).

I have other projects in the solution (of type ASP.NET Web Application and Web Site) and am able to open and edit `.jsx` files as expected in those projects.

**Comment by billti** [comment]
You are correct in that Node Tools does not support the JSX syntax yet. The ASP.NET team did some custom work to enable this syntax in their scenarios. We will hopefully add support for this as we add support for a JavaScript language service based on TypeScript. 

Note: You can writing JSX in TypeScript today, and we support TypeScript in NTVS projects, if you are OK writing your code in TypeScript and compiling to JavaScript. See https://github.com/Microsoft/TypeScript/wiki/JSX

**Comment by mousetraps** [comment]
@aweber1 I can't reproduce this - can you try with the latest versions of [TypeScript](https://www.microsoft.com/en-us/download/details.aspx?id=48593) and [NTVS](https://github.com/Microsoft/nodejstools/releases)?

**Comment by aweber1** [comment]
@mousetraps I already had NTVS 1.1 installed, so I installed TypeScript 1.8.4 for VS 2015 and am now able to edit .jsx files. Cheers!
