### ISSUE TITLE
Old versions listed in online extensions

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#627]
If you open the Extensions and Updates dialog and then search online for node you will see 3 old RCs as well as the 1.1 release.

Can they be removed form the market place?

**Comment by billti** [comment]
Good call. I was just noticing myself when trying to search for the 1.1 release on the gallery it was still showing all the RC releases above the actual final release.

@mousetraps Unless you have any concerns about removing these (as our 'releases' page does still point to them), I'd rather just remove them. I don't see why we'd want anyone installing these now.  If no concerns, I'll delete them.

**Comment by mousetraps** [comment]
Yep, we'll remove them and upload the binaries to the GH pages so that older versions are still accessible.
