### ISSUE TITLE
intellisense disappears after closing VS when there is an incomplete statement in editor

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#63]
1) create new console project 
2) npm install async 
3) type code in editor
``` js
var async = require('async')
async.all
```
4) F12 on 'all', and go to definition. (takes you to right place in async.js) 
5) save, close, and reopen project 
6) F12 on 'all' - doesn't work... instead pops up this dialog:
```
---------------------------
Node.js Tools for Visual Studio
---------------------------
Cannot go to definition "async.all"
---------------------------
OK   
---------------------------
And intellisense is completely borked until you delete the .dat file and reload the project. 
```

This issue doesn't seem to occur if the statement is complete

We fixed it earlier, but looks like it's back :( https://nodejstools.codeplex.com/workitem/1706
more discussion: https://nodejstools.codeplex.com/workitem/1963

**Comment by jinglou-** [comment]
Incomplete code only breaks built-in node module intellisense.  User loaded modules still have the intellisense.  So codeplex #1963 is indeed not fixed.  The current bug was fixed.

**Comment by zhengbli** [comment]
I cannot reproduce this bug using the latest build. Both the intellisense and navigation to definition works fine when I reopen the project. 

Env:
VS 2015 RTM 
NTVS build 20150831

**Comment by mousetraps** [comment]
Did you try reproducing this issue? 
https://nodejstools.codeplex.com/workitem/1963

It turns out they were actually separate.

**Comment by zhengbli** [comment]
@mousetraps I can repro that one. Looking into it.

**Comment by zhengbli** [comment]
I found out that the problem might be the ``Scope.EnumerateTowardsGlobal`` line at https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Analysis/Analysis/Analyzer/ExpressionEvaluator.cs#L68
returns correct type the first time; but returns empty object type after reopening the project. Though the function is a abstract function, and I don't know anything about the analysis engine, so can you share some thoughts on this?
