### ISSUE TITLE
Forbidden message when deploying to azure Web App

### ISSUE THREAD

**Issue by JuanKRuiz** [Microsoft/nodejstools#632]
From VS 2015 when I push changes to azure the site isn't deployed. When browse the site it sends a message "Forbidden".

I have tested it with new azure starter project in 2 different machines. VS 2015 Enterprise.

WebDeploy is working OK.

**Comment by billti** [comment]
I tested Azure deployment shortly before release, and it worked fine for me (though attaching for debugging was broken). 

Are you sure it's not an issue on the Azure end? Are you able to deploy other project types and do other management operations (via the VS Tools or the portal) OK? I see you tried on another machine, but do you have another Azure account you could test with?

Also unlikely based on your description, but it is not uncommon to hit MAX_PATH issues deploying to Azure. You might want to ensure this is not happening also (e.g. see https://github.com/Microsoft/nodejstools/issues/580 ).

**Comment by mousetraps** [comment]
@JuanKRuiz I also suggest checking your .gitignore file and make sure that all of your files are getting deployed as you expect them to be.

**Comment by JuanKRuiz** [comment]
I have tested using this template projects

"Blank Azure NodeJS Web Application"  FAIL
"Basic Azure NodeJS  Express 4 Application"   FAIL

**Chrome**
![image](https://cloud.githubusercontent.com/assets/1454560/11800141/fe4c57a4-a2a7-11e5-9414-b03a8dda1341.png)

**Edge **

![image](https://cloud.githubusercontent.com/assets/1454560/11800152/1190c64c-a2a8-11e5-9f6e-60d3509938b2.png)

**This is my VS 2015**

![image](https://cloud.githubusercontent.com/assets/1454560/11800114/d53d421a-a2a7-11e5-85b2-4fca738ae687.png)

**Comment by JuanKRuiz** [comment]
Hi guys, actually it looks like an azure platform issue, many webApps templates in portal are not working including some popular ones like Ghost . Do you knon where is the right place to report this issue?

**Comment by JuanKRuiz** [comment]
I have tested creating the solution from VS and removing "Create Directory for solution", after that the deployment works OK on azure. I guess the web.config must change some paths if this check is enabled.

![image](https://cloud.githubusercontent.com/assets/1454560/11852909/b3d8301e-a408-11e5-85a3-bd84259edfa9.png)

**Comment by mousetraps** [comment]
Ahhh, yes... *that* checkbox... glad you managed to find a workaround. Did you actually manage to find a web.config attribute that gets around the issue during azure deploy? Because I've just been telling people to clear it. In any case, I'll try to connect with someone internally to see what we can do about this, especially since I suspect the same issue plagues other VS project types. 

Feel free to add a note about this to the docs so that other people don't run into the same issue. 
https://github.com/Microsoft/nodejstools/wiki/Publish-to-Azure-Website-using-Git
