### ISSUE TITLE
How to disable automatic 'npm install' when package.json changes

### ISSUE THREAD

**Issue by frankwallis** [Microsoft/nodejstools#634]
Is it possible to disable this feature in Visual Studio?

**Comment by mousetraps** [comment]
Check out VS Update 1, which disables this behavior for Node.js projects.

**Comment by frankwallis** [comment]
I have update 1 installed, but this is not a Node.js project, it is an MVC project and this is still happening.

**Comment by frankwallis** [comment]
Please can you reopen this issue?

**Comment by mjbvz** [comment]
@mousetraps This is a WebTools issue, and not something NTVS is doing, correct?

I believe you can disable this behavior entirely using the answer here: http://stackoverflow.com/a/32891926/306149

**Comment by frankwallis** [comment]
Yes and that is what I do in fact, but then you cannot use the NPM Task Runner extension :(
If this is not the right place for this issue can you please confirm and I'll raise it somewhere else..
