### ISSUE TITLE
Is it possible to disable error message: "... can only be used in a .ts file" while preserving ES6 intellisense?

### ISSUE THREAD

**Issue by MeoMix** [Microsoft/nodejstools#637]
Hey,

I'm writing code in ES6 and transpiling with Babel not TypeScript. I was excited to have ES6 Intellisense, but I see now that I get massive warnings on every file indicating that I'm not using a TypeScript file.

It'd be nice if I could disable that without losing the rest of the perks.

**Comment by billti** [comment]
Can you expand on `I get massive warnings on every file indicating that I'm not using a TypeScript file`? What are you seeing exactly?

**Comment by MeoMix** [comment]
Here's what I see:

![image](https://cloud.githubusercontent.com/assets/1380995/11921745/ed77ab96-a742-11e5-89ae-2373501173a1.png)

It'd be nice to have ES6 IntelliSense without the assumption of TypeScript.

**Comment by mjbvz** [comment]
Try giving the NTVS 1.2 Alpha a try with ES6 Preview intellisense. I believe this has much better support for ES6 modules for JavaScript.
