### ISSUE TITLE
Unable to drag "site.css" file from a folder into "layout.vash" so that it creates the link tag

### ISSUE THREAD

**Issue by dasariramacharan** [Microsoft/nodejstools#642]
1)Unable to drag "site.css" file from a folder into "layout.vash" so that it creates the link tag for the file which i try to include.

2)missing html formatting for the "index.vash" file but formatting is fine for the "layout.vash" file.

Looks like this feature was working before but it doesn't work now.

Am I missing something?

Environment:
Visual studio 2015 update 1
Node.js web application project

[TheBoard - Copy.zip](https://github.com/Microsoft/nodejstools/files/60160/TheBoard.-.Copy.zip)- removed node_modules files except the bin folder files

**Comment by mousetraps** [comment]
You mentioned it was working before - do you remember when and under what circumstances?

**Comment by dasariramacharan** [comment]
In "node-v0.10.25-x64.msi" + Visual studio ultimate 2013 + Node.js tools (v1.0 Alpha date nov 20,2013)

**Comment by mjbvz** [comment]
@dasariramacharan Closing this for now since we do not have enough information to be able to investigate the issue. Please try using NTVS 1.1 or NTVS 1.2 Alpha (which requires VS 2015 Update 2) and reopen if this is still a problem.

Thanks.
