### ISSUE TITLE
Failed tests in VS2015

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#643]
Please finish fix for tests proposed in #539

**Comment by mousetraps** [comment]
The particular tests proposed in #539 will probably be removed, not fixed (see #645 which is now tracking this issue.)

We are aware that the tests (not just VS 2015) are failing as per the appveyor results, and I've created a [single issue](#646) to track those issues (https://ci.appveyor.com/project/mousetraps/nodejstools/branch/master)
