### ISSUE TITLE
ES6 IntelliSense Preview is very broken

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#648]
I have a node 4 file that uses ES6 backtick templates but I am getting errrors with the ES6 Preview enabled

This image shows the problem
![es6 problem](https://cloud.githubusercontent.com/assets/618922/11824454/892bea82-a371-11e5-91a3-bf7285f2d54d.png)

The ES6 is active as the comboboxes at the head of the file show and tehre are no red squiggles on the backticks. 

However there are many errors for line 16 (with backtick). @madskristensen  [says](https://github.com/madskristensen/WebAnalyzer/issues/15) these are form the language services -though important identifying information is omitted from the errors. Also the Error windo was not opened so it's easy to miss them.

If the errors are clicked on the src file is reopened without the combo boxes and with red squiggles on the backticks

![es6 problem](https://cloud.githubusercontent.com/assets/618922/11823145/567a7e02-a36a-11e5-92dc-a90a794940cb.png)

All in all it's very broken.

**Comment by SteveALee** [comment]
It may not be at all related but when I had full intellisense option enabled (not ES6) webanalyzer crashed when trying to edit my eslintrc or running it on a file. Enabling ESc6 stop the crash

**Comment by mousetraps** [comment]
@billti - any ideas?

**Comment by liamprescott** [comment]
Having what appears to be very similar errors:
With or without ES6 intellisense enabled i am getting lots of errors around ES6 code including:
- template literals
- arrow functions
- import statements

![image](https://cloud.githubusercontent.com/assets/10583849/12323797/1c6eae00-bab6-11e5-8985-b94820364ea0.png)

![image](https://cloud.githubusercontent.com/assets/10583849/12323813/3fc55aac-bab6-11e5-9679-5131ca5931d5.png)


Additionally suffering from Visual Studio crashing very frequently (see https://github.com/Microsoft/nodejstools/issues/656#issuecomment-171604581)

**Comment by mjbvz** [comment]
With the latest preview builds and ES6, arrow and template strings seem to be working.

`import` statements still are broken: `Cannot compile modules unless the '--module' flag is provided with a valid module name type ...`

Please open more targeted issues to track any issues you run into with the new preview builds.
