### ISSUE TITLE
Valid Mocha tests are not being parsed

### ISSUE THREAD

**Issue by syagev** [Microsoft/nodejstools#650]
The following [Mocha](https://gist.github.com/syagev/97b34ea2289fc04b6c94) file works when used from the command prompt but does not pass the processing under NTVS. *NOTE: the file has dependencies that I cannot publicly include but am willing to share in a controlled fashion..*

I get the following error when that file is under 'test' and has the 'Testing Framework' property set to 'Mocha':
```
------ Discover test started ------
Processing: S:\Dropbox (Personal)\Projects\Fringefy\odie\test\odie.js
 Test discovery error: [Error: Configuration property "odie.url" is not defined] in S:\Dropbox (Personal)\Projects\Fringefy\odie\test\odie.js
Processing finished for framework of Mocha
Discovered 0 testcases.
========== Discover test finished: 0 found (0:00:02.8381624) ==========
```

The test makes use of the 'config' npm package to load configurations according to environment. The error displayed hints that the configuration was not properly loaded. One reason could be that the `NODE_ENV` variable was not set in the context of running this script. However, I have this env variable set system wide on my machine so I'm not sure that's the cause here.

In any case, as said, command line invocation works just fine:
```
S:\Dropbox (Personal)\Projects\Fringefy\odie>mocha test


DB: Initializing mongo connection
DB: Mongo Connection Success.
  Odie API
    V OPTIONS / should return 200

  Odie POIs endpoint
    V PUT /odie/pois should add a POI
    V GET /odie/pois should return a list of POIs

  Herman endpoint
    V GET /odie/pi/hits/:id should return a PI Task
    V PUT /odie/pi/hits/:id with bad params should return 406
    V PUT /odie/pi/hits/:id should return confirm code
    V PUT /odie/pi/hits/:id repeatedly should fail
```

**Comment by mousetraps** [comment]
What are the specific configuration settings you have for these tests? 

Wrt NODE_ENV - what happens if you try to print out process.env.NODE_ENV in the context of your test? If that works, I don't see why that might be the issue.

**Comment by syagev** [comment]
The configurations include the URLs of the endpoint I'm testing and also database URIs etc. The same configuration params we have for the project itself.

I am not sure how to print something during Visual Studio's discovery process. The output attached above is from the 'Tests' output window. No matter where I put a `console.log` call I do not see it's output in this window (nor in any other window).

**Comment by bartvanderwal** [comment]
@syagev I had a very similar issue, tests running correctly on command line, but could not be detected.

A colleague fixed it, and I just answered my own question on Stackoverflow, perhaps this could help you?
http://stackoverflow.com/questions/34711219/mocha-unit-tests-are-not-found-in-ntvs/34722654#34722654

At any rate the error displayed in the stack trace had no direct relation to the unit test code, but to some external code (code called through your own code, or perhaps some NTVS wrapper code or something, I'm yet to find out).

**Comment by syagev** [comment]
@bartvanderwal, you helped me resolve the issue although it wasn't exactly identical to yours. So for me, the problem was that VS runs the tests from the directory where the tests reside, instead of the project's root folder (or the working directory in the project properties).

This was causing trouble in finding various config files. Once I understood that, the fix was quite simple.

I'm going to go ahead and close this issue, @bartvanderwal if the issue you described is reproducible and related to the working directory I encourage you to open a separate issue.
