### ISSUE TITLE
Editing HTML pages crashes VS

### ISSUE THREAD

**Issue by pixartist** [Microsoft/nodejstools#651]
Whenever I type anything into an HTML document inside a node.js project, vs2015 will completely crash.

**Comment by mousetraps** [comment]
This doesn't sound like an NTVS issue (we don't modify the behavior for HTML files).
* does the issue occur with other project types?
* could you share the corresponding error event information from the Windows event log when this issue occurs?

**Comment by mousetraps** [comment]
Is anyone else running into this? If we want to fix this, we need to get it into the next VS Update, so we'd very much appreciate any help here.

**Comment by mousetraps** [comment]
Closing as we haven't heard back and can't repro.
