### ISSUE TITLE
VSIX Project Template Package creation for NodeJs category in New Project window

### ISSUE THREAD

**Issue by bogacg** [Microsoft/nodejstools#652]
I'd like to create VSIX Package for my custom Node.Js project template but I don't see any Extensibility node containing VSIX Package template, (like the ones under Visual C# and Visual Basic categories in New Project window.) Any plans for such functionality ?

**Comment by bogacg** [comment]
I've just tried to Export Template functionality in File menu. Although Javascript is available as one of the options in Export Template window, NodeJs projects fail to be exported.

**Comment by mousetraps** [comment]
We don't support it at the moment, nor would we accept a PR for `Export Template` behavior in the near future. We're planning to overhaul our project system to move towards a folder / file-based system, so I'd rather focus on that effort than adding new features to our current model. 

That said, you should still be able to create a Project Template in other - admittedly less streamlined - ways, though:
* https://msdn.microsoft.com/en-us/library/ff527340.aspx
* https://www.youtube.com/watch?v=z33jOo75CH4

Hope that helps!

**Comment by bogacg** [comment]
I've tried both methods in links you've provided (my second message above was after I did try first one). They both've failed.
I'll try making a Yeoman generator.
Thank you.
