### ISSUE TITLE
Show All Files - working only for StartUp Project

### ISSUE THREAD

**Issue by MaciejHanajczyk** [Microsoft/nodejstools#657]
If have 3 node js projects in my solution, one set as StartUp Project with "Show All Files" button toggled on in Solution Explorer.
In this situation I can see all folders/files, including the greyed out ones.
If I toggle it off, then only greyed out folders/files from a StartUp Project are disappearing, and in other two I still see them.
The same if I click it again to show all files.

Button is only affecting StartUp Project.

**Comment by mousetraps** [comment]
'Show all files' is a project-specific property (in fact you'll see it if you open your project file in the editor). So you should be able to click on any of the other projects, and select show all files to set them each individually.
