### ISSUE TITLE
Startup file setting breaks debugger

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#66]
If you specify your startup file under the **Node.exe arguments** setting, the debugger does not start. 

(copied from https://nodejstools.codeplex.com/workitem/1862)

**Comment by mousetraps** [comment]
We should make sure we are prepending --debug-brk to the arguments, and maybe even consider overriding the startup arguments altogether when node.exe arguments are passed.

**Comment by kdelmonte** [comment]
Bump.

**Comment by mousetraps** [comment]
Brain-dumping a bit... I looked into this a little further. The problem with simply re-arranging the arguments is that it breaks process.argv because you might have an additional argument present. The solution I'm planning is:
* rename "Node.exe arguments" -> "Node.exe options" to be consistent with node --help
* rearrange arguments so that they are in order that they are appended to one another:
  * Node.exe
  * Node.exe options
  * [new] script (startup file) - this surfaces up the startup file so that it is visible and you can edit it from project properties, but it doesn't block right clicking the file and setting as startup file. 
  * script arguments
