### ISSUE TITLE
Enable/Disable Brakepoints with Ctrl+Click 

### ISSUE THREAD

**Issue by MaciejHanajczyk** [Microsoft/nodejstools#660]
I would be nice to have this feature in VS.

Brakepoint bar Click -> place enabled breakpoint
Brakepoint bar Ctrl+Click -> place disabled breakpoint

Existing brakepoint Ctrl+Click -> toggle between enabled/disabled state of a brakepoint

**Comment by mousetraps** [comment]
Cool idea! Unfortunately we can't really change this UI from NTVS (and even if we could, we probably wouldn't because it would be inconsistent with other project types), but I've passed your feedback onto the VS debugger folks.
