### ISSUE TITLE
typescript decorators giving error

### ISSUE THREAD

**Issue by pranaydutta89** [Microsoft/nodejstools#662]
I am using typescript as my nodejs project and using decorators but its giving compile time error as '	Experimental support for decorators is a feature that is subject to change in a future release. Specify '--experimentalDecorators' to remove this warning.'
                          
now since there is no tsconfig.json so i could not add the above paramtere which the compiler is asking ,and after searching for the issue on net , i changed the node.js project file and added the same parameter, then also still the issue persist, please help me with the issue.
![untitled](https://cloud.githubusercontent.com/assets/3788500/12286114/4fc1db62-b9e7-11e5-8e45-9bdb5fefd39c.png)

**Comment by kant2002** [comment]
You could manually edit `njsproj` and add following lines in the `<PropertyGroup>` section

```
    <TypeScriptEmitDecoratorMetadata>True</TypeScriptEmitDecoratorMetadata>
    <TypeScriptExperimentalDecorators>True</TypeScriptExperimentalDecorators>
```

**Comment by pranaydutta89** [comment]
@kant2002 done it already not helping me out

**Comment by mousetraps** [comment]
@danielrosenwasser any ideas?

**Comment by DanielRosenwasser** [comment]
@mousetraps I think you can close this as a duplicate of https://github.com/Microsoft/TypeScript/issues/6476.

**Comment by mousetraps** [comment]
excellent, thanks for the link :smiley:
