### ISSUE TITLE
Debug configuration

### ISSUE THREAD

**Issue by rnrneverdies** [Microsoft/nodejstools#665]
I'm trying to build the azure-sdk-for-node with nodejs tools for VS. This project has many sub-projects, when I build the project NPM downloads the sub projects form the registry instead of use those form the project itself. (see https://stackoverflow.com/questions/34909329/nodejs-tools-for-vs2015-with-local-dependencies)

Is there any way to use a different package.json file according to Debug/Release configuration?

thanks!

**Comment by mousetraps** [comment]
Just so we're on the same page here... we have a directory that looks like:
```
package.json
dir1
|- package.json
```
Currently when you run `npm install`, it npm installs based on the top-level `package.json`, but not `myFolder/package.json`. You want the equivalent of the following?
```
npm install
npm --prefix dir1 install dir1
```
If so, I suggest specifying any additional steps in a `postinstall` script in the root level package.json, which will run after `npm install` completes.

**Comment by mousetraps** [comment]
Hope that helped. Closing as I haven't heard back in a while.

**Comment by rnrneverdies** [comment]
@mousetraps Sorry for the delay in my anwert

Finnaly we solved this issue by using `npm link`. You can find more details in the following link http://justjs.com/posts/npm-link-developing-your-own-npm-modules-without-tears 

BTW, We've also added a [Suggest in VS User Vocie](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/12415584-support-for-npm-link-in-node-js-tools-symlink-a-p).
