### ISSUE TITLE
Interactive window .npm command not working for multiple projects

### ISSUE THREAD

**Issue by aplocher** [Microsoft/nodejstools#667]
Trying to do all sorts of variations of ".npm [MyProject.DbApp] list" is not working.  It only works if I don't provide arguments.  Am I doing something wrong?

![2016-01-23_16h44_56](https://cloud.githubusercontent.com/assets/1132447/12533786/02c9789e-c1f1-11e5-8e42-c1e6c80ffe3d.jpg)

**Comment by mousetraps** [comment]
The interactive window does not currently support non-Node.js project types. See #480 for further explanation. As mentioned there, we would be open to accepting a PR to enable this behavior.

**Comment by aplocher** [comment]
Thank you.  I must admit that npm and node.js are quite new to me.  For some reason I was assuming the message's mention of "Node.JS Project" meant a project with a packages.json file in it or something.  It makes so much sense now =)
