### ISSUE TITLE
ES6 Intellisense in NIW

### ISSUE THREAD

**Issue by macfarmw** [Microsoft/nodejstools#668]
Thanks for working on ES6 syntax. This is a big help to adopting it more rapidly.

The ES6 Intellisense works nicely in the code editor but not in the NIW. The NIW highlights this line with several red squiggles.

    var x = `The answer is ${3+2}`;

This statement runs in the NIW without any error but it will be confusing to many developers to get error highlights on valid ES6 code.

**Comment by mousetraps** [comment]
Thanks for the feedback!

@jramsay @paulvanbrenk @bowdenk7 - just a heads up that we should start thinking about what it would take to enable Salsa in the Interactive Window as well and also in the upcoming folder/file based project system stuff. One complexity with the Interactive Window is that it can be opened outside of a project context altogether.

**Comment by gdennie** [comment]
Similar issue with code editor for the following line in App.jsx:

var {Routes, Route} = require('react-router');

'{' and '=' flagged as 'expected indentifier' and 'syntax error' respectively.

**Comment by mjbvz** [comment]
We're working on this now. Closing this issue in favor of #1090
