### ISSUE TITLE
Consolidate Node.js and JavaScript formatting settings

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#67]
This disparity in formatting options has caused confusion amongst some users. Node.js and JavaScript formatting settings have reached parity at this point. Is there any reason we might want to include separate settings for client-side and server-side JavaScript code? 

I'm hesitant to simply remove Node.js formatting options and use JS because we still have different IntelliSense options for Node.js and JavaScript, and we don't want people to extrapolate from the formatting options that modifying JS IntelliSense will modify Node.js IntelliSense...

A few ideas:
* Use same settings, but include formatting tab under Node.js options that directs user to JavaScript formatting settings (simply increasing visibility of formatting options.)
* Include same formatting options under Node.js, but just have them linked to JavaScript settings (and include a note that this modifying Node.js options will modify JS options).
* Use different settings, but include a "mirror JavaScript formatting options" button.

**Comment by waynebloss** [comment]
I like the last option (keep using different settings with an option to mirror them).

**Comment by mousetraps** [comment]
Closing as migrating to the new Salsa IntelliSense experience will be our path towards resolving this issue.
