### ISSUE TITLE
Debugger exits on program error as of Node 4.2.6

### ISSUE THREAD

**Issue by Ampakinetic** [Microsoft/nodejstools#675]
I was running Node 4.2.4 and on first run my project logs a DustJS error that happens while it's still warming up.  After upgrading to Node 4.2.6 the debugger node process exits with "Press any key to continue" after this error and I can never run my project. I down graded back to 4.2.4 and it's working again.  Something may have changed in the debugger interface.  Let me know if I can provide any more useful information.

**Comment by mousetraps** [comment]
Or a timing issue with node - technically LTS releases aren't supposed to affect debugger interfaces...

Does the same issue occur if you run your app in the command line? How about if you run with the --debug flag in the command line?

**Comment by Ampakinetic** [comment]
I tried this and found I can run the same app direct from the command line in both normal and with the --debug flag and node doesn't exit.  Everything seems to work normally from the command line.

**Comment by mousetraps** [comment]
Thanks for the additional info. Closing as this appears to be a Node.js issue, so we recommend sticking with 4.2.4 for now - https://github.com/nodejs/node/issues/4917
