### ISSUE TITLE
Object reference not set to an instance of an object in for of

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#676]
In the JS file type

`for (var 1 of [1..2]) {<PRESS ENTER>`

The popup 'Object reference not set to an instance of an object.' appear

**Comment by kant2002** [comment]
Actually just needed `for (var 1<PRESS ENTER>` for this error to appear

**Comment by mousetraps** [comment]
Thanks - potentially related to #684

**Comment by mjbvz** [comment]
This seems to be fixed in NTVS 1.2 Alpha, probably by #743. I tried both Full Intellisense and ES6 Preview intellisense and could not repo this behavior.
