### ISSUE TITLE
Failed to find Mocha package.  Mocha must be installed in the project locally.  Mocha can be installed locally with the npm manager via solution explorer or with ".npm install mocha" via the Node.js interactive window. Processing finished for framework of Mocha

### ISSUE THREAD

**Issue by XiSmartElf** [Microsoft/nodejstools#685]
After build i see message :Failed to find Mocha package.  Mocha must be installed in the project locally.  Mocha can be installed locally with the npm manager via solution explorer or with ".npm install mocha" via the Node.js interactive window.
Processing finished for framework of Mocha

I have mocha installed locally already but vs cannot discover it.

**Comment by mousetraps** [comment]
Interesting... in which path is mocha installed? NTVS should pick up anything in `<project-folder>/node_modules/mocha`

**Comment by kevinbosman** [comment]
We have this same problem. mocha is installed in the parent of `<project-folder>`
We have a typescript solution structure as follows:
```
<solution-folder>
|-- node_modules
|   |   ...
|   +-- mocha
|-- <project-folder>
|   |-- tsconfig.json
|   +-- <project>.njsproj
|-- package.json
+-- <solution>.sln
```
With this structure it is impossible to install mocha under the `<project-folder>` as well as in the `<solution-folder>`. npm won't allow it, but Node.js Tools can't find mocha.

**Comment by kevinbosman** [comment]
@XiSmartElf was this problem resolved?

**Comment by tasoss** [comment]
Hello.i have this same problem too.the tests used to work but now i get this error.i'm not sure if this happened after installing the 'dev' releases.And also i got this strange error once:

An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\xxx\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml".

Exception details:
System.Exception: Exception of type 'System.Exception' was thrown.
   at Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid& packageGuid, Int32 reason, Guid& context)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetPackage()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()

Any ideas please?

**Comment by tasoss** [comment]
@mousetraps  @mjbvz  any ideas please?
