### ISSUE TITLE
Migrate to TypeScript Source Mapper

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#688]
Migrating the to TS source mapper will greatly reduce some of our source mapping issues. We currently have a PR open #441 - we should fix any remaining issues in this PR, merge it in, and begin testing it.

**Comment by mousetraps** [comment]
@mjbvz if you have the chance, it would be great to wrap up this outstanding PR and merge in. I suggest waiting for #686 to land first, though.

**Comment by paulvanbrenk** [comment]
No longer relevant since we moved to the VS Code debugger
