### ISSUE TITLE
NTVS stops VS2013 Classic ASP Debugging from working

### ISSUE THREAD

**Issue by CodaCodr** [Microsoft/nodejstools#703]
I dev an ASP.NET app with a small but vital classic ASP component still in use (the classic asp actually is written in javascript).

I debug in VS2013, both the ASP.NET code and the classic ASP javascript (Win7 iis 7).

I installed NTVS a few days ago. I played around with it for a while - worked fine.  That is, until I needed to debug the classic ASP stuff.  Suddenly, I had no classic ASP debugging.  Checked all the settings in IIS manager - everything seemed fine. Hmm.

Uninstalled NTVS, classic ASP debugging works again.

My plan, of course, was to refactor classic ASP JS code to Node.  But there will be a period where I still need to maintain both and be able to debug both.

Did I miss a step? Is there some special thing I need to do to re-enable classic ASP debugging (in Win7  IIS 7)?

Or... is this a bug?

**Comment by mousetraps** [comment]
@CodaCodr Thanks for reporting! NTVS should certainly not interfere with other debuggers... Any chance you could provide some simple repro steps? Also do any errors show up in the Activity Log? %appdata%\Microsoft\VisualStudio\14.0\activitylog.xml

**Comment by CodaCodr** [comment]
I'll try again Sara, but I don't have the time/resources to do that right away.

BTW, I don't have that folder on my box.  I have a ...\10.0 and a ...\12.0 but searching from above, I don't have activitylog.xml anywhere on my C drive.  I have VS2013 installed, if that helps.

**Comment by CodaCodr** [comment]
One more thing I should mention, iisnode works fine.  Debugging too.  But NTVS was a no-go showstopper.

**Comment by mjbvz** [comment]
Closing as no repo.

Please let me know if you are still running into this problem and we can investigate further.

Thanks.
