### ISSUE TITLE
Feature request: EJS Rendering Engine

### ISSUE THREAD

**Issue by JDGoldman** [Microsoft/nodejstools#715]
Please create templates using EJS in addition to Jade.  EJS is a lot more intuitive (at least in my opinion) for people coming from Classic ASP and ASP.NET.

**Comment by mjbvz** [comment]
Thanks for the suggestion. We would love to support EJS better, but cannot add projects templates for every possible combination of technologies. So instead, we're looking to support a more Node style of development, integrating with tools like Yo and creating other more generic project templates. Look for upcoming work in this area. 

Closing this in favor of that work.
