### ISSUE TITLE
Is there any way to set NODE_PATH for IntelliSense?

### ISSUE THREAD

**Issue by S-ed** [Microsoft/nodejstools#74]
Greetings.
Node for VS looks promising but seems there are no way to make IntelliSense show external dependencies linked by "set NODE_PATH".
All the environment variables in project seems be set on the launch.

**Comment by mjbvz** [comment]
We are moving towards a modern Intellisense experience based on Typescript/Salsa: https://github.com/Microsoft/TypeScript/issues/4789 You can try this out currently with NTVS 1.2 Alpha using the "ES6 Intellisense Preview" intellisense level.

I don't believe that this new experience will be able to pick up IntelliSense information from outside of a local project using `NODE_PATH` either. I recommend either installing the required NPM modules locally or globally as those the use cases we are targeting.

Please give ES6 Preview Intellisense and NTVS 1.2 a try and report any issues you run into. Thanks.
