### ISSUE TITLE
Node.js v6 support

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#745]
Node.js v6 is set to go "stable" in April. We should verify that we haven't had any breaking changes to debugging, profiling, etc. with upcoming latest release and fix any issues if they do exist.

We need to test both x86 and x64. x64 will have a known issue with profiling.

**Comment by mjbvz** [comment]
[v6.0.0 nightly builds to try out](https://nodejs.org/download/nightly/) (this issues itself is one of the top Google results for "Node.js v6")

**Comment by mjbvz** [comment]
Here's some initial thoughts on testing:

**Debugging**
- Starting
  - [ ] Launch
  - [ ] Attach
  - [ ] Attach remote
- Breakpoints
  - [ ] Basic breakpoints
  - [ ] Conditional breakpoints
  - [ ] Break on exception
- Stepping
  - [ ] Step over
  - [ ] Step into
  - [ ] Step out
- Inspection
  - [ ] Callstack
  - [ ] Evaluate expression
  - [ ] Hover tips
  - [ ] Inspect properties
  - [ ] Edit and continue

**Profiling** 
- [ ] Collect profile
- [ ] Hotest path
- [ ] Functions/call tree view
- [ ] Load existing v8 log

**Repl**
- [ ] Basic command evaluation

**Comment by mousetraps** [comment]
nice!! thanks for investigating. Looks thorough enough for now, but of course we'll continue to keep an eye on it as new versions are released.
