### ISSUE TITLE
"Remote / Open Containing folder" throws a null reference assertion if no registry key exists 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#746]
**Repo**
Durring local development, navigate to: "Tools / Node.js Tools / Remote / Open Containing folder" 
Select "Open Containing folder"

**Expected**
Can browse to select containing folder.

**Actual**
Assertion gets thrown about path1 being null.

In `NodeJsPackage.RemoteDebugProxyFolder`, we try to look up two reg key values. If neither exists, we return null. This is then passed to `Path.combine`, causing the assertion to be thrown. We should handle this case better.

**Comment by mousetraps** [comment]
Just to be clear... this issue only occurs in the experimental hive, correct? If so, please mark as "code-happiness" instead of "bug" ("bug" is for user-facing issues).

**Comment by mjbvz** [comment]
Yes, this only gets set by the installer so it should only effect development, unless the registry is changed.
