### ISSUE TITLE
Heap corruption when trying to set a new breakpoint in runtime

### ISSUE THREAD

**Issue by ohzeekay** [Microsoft/nodejstools#754]
I have several projects I work on in parallel using the NTVS with VS2015.
With one of the projects, every time I try to set a breakpoint during runtime, VS stops execution with an error code that translates to a heap corruption. This takes the sting out of using the NVTS with VS2015 to debug my code. 
Would appreciate any help to resolve that.

![image](https://cloud.githubusercontent.com/assets/8249128/13853173/8e20bbfc-ec33-11e5-8f12-dacdd77a4d9e.png)

Note: I just installed the latest development version (from Mar-1 2016) to see if anything is resolved there but the same behavior persists.

THANKS!

**Comment by mjbvz** [comment]
Sorry you are running into problems. To help with the investigation, could you please also let us know:

* What version of Node are you running? `$ node --version`
* Does this happen 100% of the time in this project?
* Do you see any messages in the Node.js error window: `Tools -> Node.js Tools -> Errors`. 
* What does this project do differently than the others? It's odd that only this one project is causing problems, so understanding the difference may help with the investigation. If you can provide the `package.json`, that may also be helpful.

Thanks.

**Comment by ohzeekay** [comment]
Thanks for the help @mjbvz !!

Here's what I got:

`What version of Node are you running? $ node --version`
node version v4.2.3
VS2015 version 12.0.24720.00 Update 1
Node Tools version 1.1.30401.01

`Does this happen 100% of the time in this project?`
Yes. It happens either when I'm trying to set a breakpoint and apparently also just sporadically during runtime (just happened). It is easy to recreate - just have to set a breakpoint in runtime and it crashed pretty fast.

`Do you see any messages in the Node.js error window: Tools -> Node.js Tools -> Errors.`
The output from the last run is here - https://anotepad.com/notes/ib34ee
You will see that the 1st breakpoint I tried to set was successful and after the 2nd one the DebuggerConnection was closed and after that execution stopped.

`What does this project do differently than the others? It's odd that only this one project is causing problems, so understanding the difference may help with the investigation. If you can provide the package.json, that may also be helpful.`
There's nothing unique in this specific project. I tried to erase all the VS intermediate files to find out if anything like that is causing the corruption, restarted my PC etc etc, but couldn't figure this out :/ . Here's a screenshot of my package.json file:
![image](https://cloud.githubusercontent.com/assets/8249128/13856904/7920c302-ec45-11e5-809b-e8fe2386dd08.png)

**Comment by ohzeekay** [comment]
I wanted to also capture a case where it fails just like that in the middle of execution (not touching VS at all while it is running). The output of the Node Errors can be found here: https://anotepad.com/notes/m2twfd

Notice the few lines at the end of the log:
```
[19:28:28.8063069] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[19:36:49.2759321] DebuggerConnection: Connection was closed.
[19:36:49.2889329] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ThreadDestroyEvent (2C3B7532-A36F-4A6E-9072-49BE649B8541)
[19:36:49.2889329] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ProgramDestroyEvent (E147E9E3-6440-4073-A7B7-A65592C714B5)
[19:36:49.2899329] AD7Engine Called ContinueFromSynchronousEvent
[19:36:49.5479477] AD7Engine Finalized (35531361)
```
It looks like somehow the DebuggerConnection connection has been closed. It happens just like that in the middle of execution (notice the time stamps - about 8min after starting).


This issue is a big problem for me as I can't use the NTVS due to that :(

Thanks!

**Comment by mjbvz** [comment]
Ok, I'm looking into this and trying to get a repo.

From the original error message it looks like `node.exe` is what is actually what is having the heap corruption. When you run the same Node program outside of Visual Studio, `node MAIN.js`, do you also see the crash? How about if you run with the app with `node --debug MAIN.js`?

It could be that we are sending a bad debugging message the Node, but I want to make sure that Visual Studio is the root cause here.

**Comment by ohzeekay** [comment]
It looks like indeed the node process just stops in the middle of execution and therefore it's not a NTVS issue. I tried installing node-inspector and it has a similar problem since the connection to the node debugger is lost in the middle.... Bottom line - closing this issue in this forum for now.
Thanks Matt!
