### ISSUE TITLE
support UNC paths when running processes

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#755]
From VS Feedback:

I have my Documents folder set to use a UNC path via VMWare Fusion's sharing feature to share my Mac OS X Documents folder with Windows. When using NTVS 1.1 and trying to install missing npm packages using the option in Visual Studio the output pane reports that CMD.exe cannot use UNC paths and thus the NPM command fails because CMD didn't open with the correct folder and so NPM then tries to install packages into C:\Windows instead of the project folder.

![image](https://cloud.githubusercontent.com/assets/762848/13856646/644bcad8-ec33-11e5-8778-35fc49efcc6e.png)

**Comment by mjbvz** [comment]
The root cause appears to be `ProcessOutput.Run`, specifically that `ProcessStartInfo.WorkingDirectory` does not support unc paths. 

One potential fix may to wrap the executing command in `pushd` + `popd`, but I'm not too familiar with UNC on windows.
