### ISSUE TITLE
Unchecking "Break when an exception is thrown" during debugging session does not properly clear debugging settings

### ISSUE THREAD

**Issue by edvinv** [Microsoft/nodejstools#76]
Hi,
if I checked Break when an exception is thrown during debug session, debugger stops correctly on thrown statement. But if I clear the same options, debugger still stops as previously. I have to stop/start new debug session for this option to take effect.

Is this bug or some V8 limitation?

best regards

**Comment by mousetraps** [comment]
We'll look into it. That's a particularly annoying behavior given the potential amount of noise, and I don't believe it's a V8 limitation.

**Comment by mousetraps** [comment]
Fix is available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)
