### ISSUE TITLE
Tests aren't discovered when the Node.exe path is set to electron.exe

### ISSUE THREAD

**Issue by charlesguse** [Microsoft/nodejstools#764]
I am currently creating an electron.io app. I found that if I change the node.exe path in the njsproj to 'node_modules\electron-prebuilt\dist\electron.exe' then I can get Visual Studio 2015 to debug and run my Electron app.

However, with my Node.exe path set to electron.exe, my tests aren't discovered. I reverted the Node.exe path to the default Node.exe setup and it discovers the test fine.

I currently have found a workaround where I can set up another njsproj that uses the default node.exe path and only include the tests. That allows my tests to be discovered. Is there possibly a better solution to this that I am missing?

Thanks

**Comment by charlesguse** [comment]
Since posting this, I also found that I include the module electron-edge in a test. I get this error:

> ------ Discover test started ------
> Processing: C:\sandbox\...\test\UnitTest2.js
> Processing: C:\sandbox\...\test\UnitTest2.js
> Processing finished for framework of ExportRunner
> Discovered 0 testcases.
>  [Error: The specified module could not be found.
> Processing finished for framework of ExportRunner
> Discovered 0 testcases.
> ========== Discover test finished: 0 found (0:00:00.8711237) ==========

It only seems to be an issue when it is run the code as a test. The code works fine in my app. Anyone have an idea of how I can use Visual Studio 2015 to create and test code for my Electron app?

Thanks again

**Comment by paulvanbrenk** [comment]
We'll consider this when we implement a new project system.
