### ISSUE TITLE
Support multiple configurations

### ISSUE THREAD

**Issue by Earl-Brown** [Microsoft/nodejstools#767]
I have a project that has multiple "main" files, depending on the situation.

I would love to be able to use the project configuration to specify which main script is run.

For example, I _could_ have a "debug wrapper" main script that require()s my real "app.js" to distinguish between debug and release mode, where the "release" configuration would just run "app.js".

Right now, project configurations are ignored.

**Comment by paulvanbrenk** [comment]
The easy workaround here is to create multiple projects, integrating this in the project is a lot of work for relative little gain.
