### ISSUE TITLE
Support Typings in addition to TSD

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#768]
I think it would be sensible to have multiple strategies here. Since not only TSD right now the package manager for typigns, and there also Typings project which has main and browser folder. If both folders would be included in the project, they break the build. right now Typings is use `exclude` property in the `tsconfig.json` file.

**Comment by mjbvz** [comment]
Thanks for the suggestion. Since TSD is deprecated, we probably will be looking to moving to typings using the `--ambient` flag sometime in the future.
