### ISSUE TITLE
Great performance, but multi-line comments broken

### ISSUE THREAD

**Issue by matsaleh13** [Microsoft/nodejstools#786]
I enabled ES6 preview as a random attempt to reduce CPU usage of IntelliSense with my Node.js code. (I'm using a different node executable to run my code from the one used by MSVS, so I thought maybe...) Turns out it really helped perf a lot! Yay!

But soon afterwards I found that my multiline comment auto-completion was broken. No more support for typing "/*_" and getting the comment block to complete, and no adding of the leading '_' for newlines in the block comment.

To verify, I switched back to "Quick IntelliSense" for Node.js, and restarted VS. Sure enough, the block commenting was working again... and perf started sucking horribly again. :)

Hope this helps.

**Comment by mousetraps** [comment]
Thanks for the feedback! Unfortunately, switching to a new language service means we need to re-implement features, and we haven't gotten to all of them just yet.

**Comment by matsaleh13** [comment]
Understood. Just making sure it's known. Thanks for the reply.

Oh, and whatever you're doing with the performance, keep it up! :)

**Comment by mjbvz** [comment]
I just tested this in the latest VS2017 builds ("VS15") and confirmed that the TypeScript team has partially added this behavior.

The editor will now automatically complete multiline documentation comments if they precede an documentable element (variable declaration, function, class, ...).

Starting with this code:

![image](https://cloud.githubusercontent.com/assets/12821956/19580478/52d427ac-96db-11e6-881a-335e4b0c4990.png)

When I press `*` again, the following is completed:

![image](https://cloud.githubusercontent.com/assets/12821956/19580489/6aa314ba-96db-11e6-9951-7a92aaca6ce9.png)

However, this completion is not triggered if the element is not documentable:

![image](https://cloud.githubusercontent.com/assets/12821956/19580526/a3ae7ff6-96db-11e6-8dbc-d3be091b0e74.png)



Also, there are no completions for regular (non-documentation) multiline-comments.

**Comment by paulvanbrenk** [comment]
Closing as this is a TypeScript issue.
