### ISSUE TITLE
VS 2015 RC: Unit test debugging broken

### ISSUE THREAD

**Issue by jinglou-** [Microsoft/nodejstools#79]
- VS 2015 22822.01
- Node.js 0.12.2
- NTVS 30324.01

1. Create an NTVS app
2. Add JavaScript Unit test
3. Set a breakpoint in the test
4. In Test Explorer, select to debug the test
5. Breakpoint not hit

PTVS also has the same issue: https://github.com/Microsoft/PTVS/issues/23
This is a very recent regression.

**Comment by toddpi314** [comment]
+1 Seeing this issue on VS 2015 RC and x64 Windows 10 RC

**Comment by ant-fx** [comment]
+1 - Same with VS2015 RC Win8.1

**Comment by mousetraps** [comment]
Hey all, fix is available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)
