### ISSUE TITLE
Indenter does not respect IndentSize option

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#80]
TabSize works fine, and luckily people tend to set IndentSize and TabSize to the same value in general, but this should still be fixed.
https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/SmartIndent.cs#L84-L214

**Comment by mjbvz** [comment]
This is fixed in NTVS 1.2 now that the editor is backed by Typescript.
