### ISSUE TITLE
What version of node.js do you recommend for NTVS 1.2 Alpha??

### ISSUE THREAD

**Issue by michaelderemer** [Microsoft/nodejstools#802]
The previous installers had node chakra installed with it. I see you have preliminary support for node v6.x. I don't really care what version but can you provide a link in your https://github.com/ms-iot/ntvsiot page so as i install prereqs i can make sure i install a tested version of node at the correct time.

**Comment by michaelderemer** [comment]
Previous releases resulted in a folder structure:
C:\Program Files\<something about nodejsUwp>\<node install>
C:\Program Files(x86)\NodejsUwp\<node.dll's for arm, x86, x64>

In alpha 1.2 i only get the Program Files(x86) nodejsuwp folder. I assume this is just because node chakra wasn't included? How exactly do i get that node version. Is there an installer somewhere?

**Comment by michaelderemer** [comment]
Now installed chakra from https://github.com/ms-iot/ntvsiot/releases/tag/node-chakra-5.7.1-0

Was able to install the uwp npm package.
Now when i run the program i get error node.exe: bad option --nolazy

Seems like i'm close. I'm wondering if the order i ran things in screwed something up. The setup of all this could certainly use some  polishing.

**Comment by mjbvz** [comment]
It looks like this is an issue with ntvsiot, not NTVS (which I don't think installs Node at all). If you are still running into problems, try opening an issue against ntvsiot instead.

Thanks.
