### ISSUE TITLE
Automatic typing acquisition adds duplicate declaration files to the project

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/nodejstools#805]
**Version**: NTVS 1.2 Alpha

**Bug 1**

When a project contains a folder called `typings`, every time the project is rebuilt, the `.d.ts` files in that folder are automatically included in the project file. 

This appears to be the expected behaviour, however, the files are included in ***duplicate***.

To reproduce

* Open up the project in the attached zip file.
* Right-click on the project and ***rebuild***.
* Unload and edit the project and observer the multiple copies of `myTypes.d.ts`.

Some observations

* This only affects `.d.ts` files. The file `bar.ts` is not duplicated.
* Only files in the `typings` folder are affected. The file `foo.d.ts` in folder `typings2` is not duplicated.
* A new copy is added after every rebuild.

[NodejsConsoleApp1.zip](https://github.com/Microsoft/nodejstools/files/197627/NodejsConsoleApp1.zip)

**Bug 2**

The automatic acquisition should only occur when the following is true:

* You are using the NTVS 1.2 Alpha.
* You are on VS 2015 (not VS “15”)
* You have a Javascript project (not Typescript)
* Intellisense level is set to “ES6 Preview”.

However, the above problem occurs under the following:

* A typescript NTVS project in VS 2015
* JavaScript intellisense has been switched off.

**Comment by mjbvz** [comment]
Thanks. It seems like part of the work we did to auto include `*.d.ts` files in Javascript VS projects hasn't been properly gated (`NodeJsFileNode.cs`) to only happen when automatic type acquisition is enabled. Automatic type acquisition should never be enabled for Typescript projects.

Testing out this theory and will send out a PR shortly.
