### ISSUE TITLE
ES6 IntelliSense Preview does not understand "require"

### ISSUE THREAD

**Issue by yisk** [Microsoft/nodejstools#817]
I am new in VS and NTVS. Look at the picture please. I have a Node.js console project with two files in it.
Windows 10 (x64), Visual Studio Community '15, lastest NTVS (probably).

![vsnode](https://cloud.githubusercontent.com/assets/7341769/14228385/d61dcd88-f91b-11e5-97b8-f5abac4a15bf.png)

**Comment by kant2002** [comment]
What exact version NTVS you are using, If you look at #587 very likely it is already fixed. Di you try [Node.js Tools 1.2 Alpha](https://github.com/Microsoft/nodejstools/releases) ?

**Comment by mjbvz** [comment]
Also, if you are on 1.2 Alpha, make sure you are on VS 2015 Update 2. You will get very similar behavior to what you describe if you are on a pre update 2 release.

**Comment by yisk** [comment]
I am on Visual Studio Community 2015 Update 2.
Before kant2002's post i had NTVS 1.1, but after installing NTVS 1.2 nothing is changed.
How to check what version of NTVS currently installed?

**Comment by mjbvz** [comment]
In Visual Studio, go to `Help -> About Visual Studio` and then click on `Copy Info`. That will give us all the information about installed plugins and will also list the NTVS version you have installed.

**Comment by yisk** [comment]
Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA971
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA971
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA971
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   5.2.60328.3
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Node.js Tools   1.2.40329.01
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.2.40329.01
Profiling support for Node.js projects.

NuGet Package Manager   3.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

TypeScript   1.8.29.0
TypeScript tools for Visual Studio

**Comment by mousetraps** [comment]
Indeed, this appears to be a bug in the new ES6 Preview. Repro code below so we don't have to re-type it:
```js
/* creatures.js */
var Animals = {
    Mammals: {
        CAT: 1,
        RAT: 2
    },
    Birds: {
        CROW: 3
    }

}

module.exports = Animals;
```

```js
/* app.js */
class ES6_Checker { }
var a = require('./creatures');
a.// "Animals" not in completions list
```

Confirmed that this issue occurs in both VS 2015 Update 2 and VS "15" Preview. This issue does *not* occur in latest versions of VS Code, so it appears to be an issue with the VS integration, not Salsa itself. 

+Salsa team: @jramsay @paulvanbrenk @bowdenk7 @billti

**Comment by jcansdale** [comment]
As a workaround, try renaming app.js to app.ts and changing:
var a = require('./creatures');
to
import a = require('./creatures');

That's what I've been doing.

**Comment by paulvanbrenk** [comment]
@yisk I've gotten this to work by adding a `tsconfig.json` to the root of the project with the following options enabled.
```json
{
  "compilerOptions": {
    "allowJs": true,
    "moduleResolution": "node"
  },
  "exclude": ["node_modules"]
}
```

**Comment by jcansdale** [comment]
Do you know which line fixes it?

I don't completely understand the 'allowJs' option. The documentation seems to say this will allow the TypeScript compiler to compile .js file as well. Will this make the compiler act as a Bable alternative for .js files? I'm getting warnings saying the .js file will be overwritten. Maybe it needs an output directory?

I'm guessing it's maybe the "moduleResolution": "node" line that makes the difference?

**Comment by paulvanbrenk** [comment]
The `allowJs` line allows the Language Service to consider `.js` files, without it only `.ts` files are considered, but you're correct that the `moduleResolution` is the real fix. For the warning you're seeing you would have to add `noEmit:true`.

**Comment by paulvanbrenk** [comment]
I have a fix in codereview, which should ship in VS 2015 Update 3
