### ISSUE TITLE
MSI mising for Node.Js tools 1.1.1

### ISSUE THREAD

**Issue by rkavalap** [Microsoft/nodejstools#824]
@mousetraps I don't see the release version msi's for v1.1.1. I am assuming they are still being built.

Just to see if github staffer responds to github mentions.
@github
User mousetraps created a tag for the project nodejstools 7 hours ago 4/5/2016. I see this on my homepage feed. On the releases page for the same project I see the entry 7 days ago. Shouldn't both strings be in sync. ?
 
![githuberror](https://cloud.githubusercontent.com/assets/80310/14290199/ef846a04-fb12-11e5-9952-0edbe0f7f21f.JPG)

**Comment by mousetraps** [comment]
@rkavalap - the release was actually available, but I updated the notes so that the link to them is more visible.

Regarding the timestamps, "6 days ago" is the last updated timestamp of the branch itself, even though I created the tag only 7 hours ago.
