### ISSUE TITLE
Execution doesn't starts on launch

### ISSUE THREAD

**Issue by mayankdedhia** [Microsoft/nodejstools#83]
At times when I run the project, it just shows a message "Debugger listening on port xxxx" and doesn't proceeds further. I've to manually pause which then shows the execution paused at first line of the start-up file and then click continue to make it work.

**Comment by mousetraps** [comment]
Thx for reporting this. A few questions to help us get to the bottom of it...
* Does this reproduce consistently for you?
* Does it repro for every project (try a simple console app template)? 
* What version of node and VS?

**Comment by mayankdedhia** [comment]
Replies - 
* I could say it reproduces 4 out of 5 times.
* I'm working on just a single project and it is a simple console app.
* Node - **v0.12.0** and VS **2013 Express**

**Comment by objelke** [comment]
Second this - node v.0.12.2, Visual Studio Ultimate 2012 - also seen on VS2013.
Seems to be stuck on the beginning of the first command in the .js file (when trying to break).
Can confirm that break/continue indeed then launches the app properly.

Shows in various projects based on restify or express - seems to be dependent on the "heaviness " of the project (# of modules referenced) - simple cmd line app: haven't reproduced. 

For complex project: good and bad days - sometime 10% success rate, sometimes 10% failure rate.

Other developers on the same projects are not seeing this, perhaps something machine (or timing) specific.

**Comment by mousetraps** [comment]
Just checking since this was brought up in #31... does everything work okay if you check the "start web browser on launch" option in project properties?

**Comment by mousetraps** [comment]
And by okay, I mean better, since this is looking like a race condition to me...

**Comment by objelke** [comment]
Very hard to say since randomness is so high - but I'd say it doesn't make a difference for me.
It appears that browser is invoked past the point of stalling (after a break/continue) - never see it showing up when the debugger is hanging.

**Comment by mousetraps** [comment]
Fix is available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)

**Comment by mayankdedhia** [comment]
Thanks for the update :)
