### ISSUE TITLE
[Node.js Tools 1.2 Alpha] Currently not honoring typescript compile on save setting

### ISSUE THREAD

**Issue by rkavalap** [Microsoft/nodejstools#832]
Repro steps:
Edit a typescript file. 

Expected behavior: 
If Tools -> Text Editor -> Typescript -> Project -> General 
If Compile on Save option unchecked
equivalent js file should not be generated at the current location. 

Current behavior:
Generating a js file. 

Earler versions of ntvs had this in the project file for the behavior
```
<EnableTypeScript>true</EnableTypeScript>
<TypeScriptSourceMap>true</TypeScriptSourceMap>
<TypeScriptModuleKind>CommonJS</TypeScriptModuleKind>
<ToolsVersionPromptShown>1.7</ToolsVersionPromptShown>
```

Which was automatically generating the js file. 

When I open a nodejs solution, I currently see it's automatically edited. But I don't see above setting changes getting added in the edit. 
I am currently not sure where it is getting controlled from.

**Comment by mjbvz** [comment]
I confirmed this behavior, but I'm not sure NTVS is the root cause. It seems like a Typescript issue. @mousetraps, what do you think?

@rkavalap Could you also please go to `Help -> About Visual Studio` and paste the result of `Copy Info` here to let us know what versions of VS, NTVS, and Typescript that you have installed. Thanks.

**Comment by rkavalap** [comment]
Microsoft Visual Studio Enterprise 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

Architecture and Modeling Tools   00322-90000-92003-AA742
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

LightSwitch for Visual Studio 2015   00322-90000-92003-AA742
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-90000-92003-AA742
Microsoft Visual Basic 2015

Visual C# 2015   00322-90000-92003-AA742
Microsoft Visual C# 2015

Visual C++ 2015   00322-90000-92003-AA742
Microsoft Visual C++ 2015

Visual F# 2015   00322-90000-92003-AA742
Microsoft Visual F# 2015

Windows Phone SDK 8.0 - ENU   00322-90000-92003-AA742
Windows Phone SDK 8.0 - ENU

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.7.1   14.0.11112.0
Azure App Service Tools v2.7.1

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

HideMenu   1.0
Hides the Visual Studio main menu, similar to Windows Explorer and Internet Explorer

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2015.2   Build 103.0.20150818.200216
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Team Foundation Server 2015 Power Tools   14.0
Power Tools that extend the Team Foundation Server integration with Visual Studio.

Microsoft Visual Studio Process Editor   1.0
Process Editor for Microsoft Visual Studio Team Foundation Server

Node.js Tools   1.2.40329.01
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.2.40329.01
Profiling support for Node.js projects.

NPM Scripts Task Runner   1.2.55
Adds support for package.json's NPM scripts in the Task Runner Explorer

NuGet Package Manager   3.4.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.40315.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40315.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40315.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

TypeScript   1.8.29.0
TypeScript tools for Visual Studio

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Apache Cordova   Update 8
Visual Studio Tools for Apache Cordova

Visual Studio Tools for Universal Windows Apps   14.0.25123.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Essentials 2015.1   1.0.210
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

Windows Installer XML Toolset   3.10.2.2516
Windows Installer XML Toolset version 3.10.2.2516
Copyright (c) Outercurve Foundation. All rights reserved.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   4.0.0.1717 (1390b70)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.0.0.35 (d300845)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.3.99.33 (ea30b32)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by mousetraps** [comment]
Thanks for reporting! Yep, Matt is correct - sounds like a typescript issue. Please file an issue on https://github.com/Microsoft/TypeScript - they should be able to help you out there.
