### ISSUE TITLE
[Node.js Tools 1.2 Alpha] Automatic Typing from TSD

### ISSUE THREAD

**Issue by rkavalap** [Microsoft/nodejstools#833]
Is there a setting where i can turn off auto install typings ?

When I opened the solution, I found tsd installing typescript definitions for all my packages based on package.json file. It's a good feature. But I am trying to understand the user experience aspect of this.
Most of my team members are mac users, and do not use visual studio. Should the newly added typings files  be included to version control,  So that everyone can leverage type definitions ?

On a side note, I observed, tsd installed several type definitions based on the package.json, only the first typedefinition, and it's respective folder was included to my nodejs project file.

**Comment by mjbvz** [comment]
Thanks for the feedback. Checkout this wiki page for some more background on the typings aquisition: https://github.com/Microsoft/nodejstools/wiki/Automatic-Typings-Acquisition

There is no way to disable this feature on its own, but switching off of 'ES6 Intellisense' to will stop automatic typing acquisition (although there's a bug in the current alpha where that is not actually the case).

For working cross platform, I suggest treading the typings files like the `node_modules` directory and updating your `.gitignore` to ignore both `typings` and `tsd.json`. These file will be recreated automatically for any users on NTVS, so I do not think including them in source control is necessary.
