### ISSUE TITLE
"Install New npm Packages.." window takes a very long time stuck in "Loading published package list.."

### ISSUE THREAD

**Issue by diryboy** [Microsoft/nodejstools#836]
It's trying to download a very big list, and I cannot do anything during this. Is this huge list really necessary to be downloaded?

![image](https://cloud.githubusercontent.com/assets/159110/14343950/fba35528-fcd6-11e5-8e2a-0fec0755b3d8.png)

**Comment by mousetraps** [comment]
You can close the dialog while its downloading and it'll complete in the background, but unfortunately npm doesn't offer any search APIs so it's necessary to download this list. Compare to "npm search" in the command line - should take about the same time initially. Future updates are incremental.

Alternatively if you know the package you're looking for already, you can use .npm in the repl or the command line. 

More info here.
https://github.com/Microsoft/nodejstools/wiki/npm-Integration

**Comment by diryboy** [comment]
Thanks for the info @mousetraps. I'm curious though, what powers the completion list helping you to write the `dependencies` section of `package.json`? That result does not take too long to appear.

**Comment by mousetraps** [comment]
That completion list is searching through names (not description/keywords), so there's much less to download.

Sent from my Rotary Phone

    _____________________________

**Comment by diryboy** [comment]
I see. Wouldn't it be nice to have this available before the big list download is finished?

**Comment by mousetraps** [comment]
Yeah, a more gracefully degraded experience would be nice. Certainly not high on our radar, but I'll reopen in case you or anyone else wants to consider a hybrid approach.

**Comment by mousetraps** [comment]
i think ultimately, though, we need to move towards an actual search api. I know npm is planning to tackle this at some point, but i don't have any sense of timeline.

**Comment by diryboy** [comment]
Sounds good. Thank you. If ultimately going for the search API, then I think in the meantime updating the UI informing people that "The task will continue in the background after closing the window" would be better choice.

**Comment by paulvanbrenk** [comment]
Fixed in VIsual Studio Update 3
