### ISSUE TITLE
How to run gulp task when making build of C# project via MSBUILD

### ISSUE THREAD

**Issue by kanoshin** [Microsoft/nodejstools#837]
In my project i'm running post-build gulp tasks via Task Runner Explorer. Is it possible to modify csproj so that the same tasks were running when i'm building it via msbuild? 
If I import `<Import Project="$(VSToolsPath)\Node.js Tools\Microsoft.NodejsTools.targets" />`to my csproj  - build will fail.

**Comment by mjbvz** [comment]
We now have a wiki page that describes [how to run grunt as a pre or post build action]( https://github.com/Microsoft/nodejstools/wiki/Pre-and-Post-Build-Actions). The process should be very similar for gulp.

Try taking a look at that documentation and let me know if you run into any problems or have any questions. Thanks.
