### ISSUE TITLE
Open > New > Javascript/Node.JS missing

### ISSUE THREAD

**Issue by Humphaz** [Microsoft/nodejstools#843]
Hi,

I have installed the full community, I've installed all the node.js components and NTVS 1.2 Alpha.

I am unable to see the project templates for Javascript or Node.JS as per any of the how-to's.

I do however seem to have the tools, everything else seems to be in place but not access to any of the templates in New?

Any ideas?

Best Regards,

Glyn

**Comment by mjbvz** [comment]
The templates may be installed in one of two different locations depending on system configuration: either under "Installed Templates" or "Installed Templates / Other Languages". Then look in the "Javascript" directory

Please make sure they are not just in one of the temple groups. If they really are missing and are not in any of the groups,  we can look more into the issue.

Thanks.

**Comment by Humphaz** [comment]
No this seems to be a problem seen else where. They exist in the ProjectTemplates but aren't being pulled into the ProjectTemplateCache.

I've tried all sorts, many references to it being an issue with TypeScript versions, I know a lot of stuff got changed at BUILD.

Just seems to be going around and around, I can only think of installing the whole lot and trying to install it again.

Really frustrating this one, lots of potential fixes out there but none seem to work, won't bring them in into the cache.

I've managed to get the Cordorva in from the internet templates, but nothing to allow Javascript and Node.JS in, but as stated it is in the ProjectTemplates directrory.

`11/04/2016  18:47    <DIR>          .
11/04/2016  18:47    <DIR>          ..
11/04/2016  15:58    <DIR>          CSharp
11/04/2016  13:30    <DIR>          Extensibility
11/04/2016  15:58    <DIR>          FSharp
11/04/2016  18:17    <DIR>          JavaScript
11/04/2016  18:17    <DIR>          TypeScript
11/04/2016  13:31    <DIR>          VC
11/04/2016  15:58    <DIR>          VisualBasic
24/03/2016  18:12            16,691 VS_Nodejs.project.vstman
07/04/2016  21:07    <DIR>          Web`

but the ProjectTemplatesCache looks like:

`07/04/2016  21:26    <DIR>          CSharp
07/04/2016  21:26    <DIR>          TypeScript
07/04/2016  21:26    <DIR>          VisualBasic
07/04/2016  21:26    <DIR>          Web`

**Comment by mjbvz** [comment]
Quick question, are you on VS 2015 Update 2?

Unfortunately, if NTVS seems to be loading and working except for the templates, this problem may be hard to diagnose. You can try enabling `Tools -> Node.js Tools -> Diagnostic Info` and turning on `Enable Node.js Tools Live Diagnostics output pane` to see if any errors are printed. Also, check `%APPDATA%\Microsoft\VisualStudio\Version\ActivityLog.xml` to see if there any relevant errors.

You may want to try running 
[`devenv /InstallVSTemplates`](https://msdn.microsoft.com/en-us/library/ms241279.aspx) or [`devenv /Setup`](https://msdn.microsoft.com/en-us/library/ex6a2fad.aspx) from an administrator Visual Studio command prompt to see if that fixes the templates.

**Comment by mjbvz** [comment]
Closing this issue, but please let me know if you are still seeing this.

Please try the steps suggested above as well. Those usually resolve missing template problems like this. Thanks
