### ISSUE TITLE
breakpoints sometime  will not currently hit

### ISSUE THREAD

**Issue by yantrab** [Microsoft/nodejstools#849]
![image](https://cloud.githubusercontent.com/assets/12247800/14464504/b35168be-00d7-11e6-90f6-f206f5683987.png)

**Comment by mjbvz** [comment]
Can you please provide:
* What version of VS and NTVS you are using
* What version of node you are using.
* Repo steps
* Example file or code

thanks

**Comment by mjbvz** [comment]
Closing because there is not enough info for an investigation. @yantrab, please reopen with the requested information if this problem is still occurring. Thanks.
