### ISSUE TITLE
Node_modules inclusion in the project asked 3 times

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#860]
After installing NTVS 1.2 Alpha and opening existing solution with 1 NTVS project + 1 SQL Server project, the NTVS ask to include node_modules 3 times. I always select 'Don't include node_modules (recommended)'

**UPDATE**
Here the image of the dialog which appears
![image](https://cloud.githubusercontent.com/assets/4257079/14582492/3e5ba66a-0428-11e6-9d4e-611c2b01ed8d.png)

**Comment by mjbvz** [comment]
Can you please provide a screenshot of the dialog box you are seeing. We do have code that will show a dialog box about including `node_modules`, but the text it uses (`IncludeNodeModulesCancelTitle`) is different than what you describe. I want to make sure that the dialog is actually coming from our code.

Also, is `node_modules` being correctly not included from the project after you select no? That is, is the bug just the repeated prompting?

Thanks.

**Comment by kant2002** [comment]
@mjbvz Update initial description to include image of dialog

**Comment by mjbvz** [comment]
That's our dialog box all right. 

A few more questions: Was this a one time problem or does it happen whenever you open the project? Does it effect other projects or just this one? Do you have any more specific repo steps?

Thanks.

**Comment by kant2002** [comment]
@mjbvz It happens when I open the project. But it ask me 3 times. I suspect that this could be due to fact that NTVS try to add typings folder from following 3 modules: `typings`, `tslint`, `gulp-tsc`. These modules included in the project, but `node_modules` folder itselft, does not part of the project. That's strange.

**Comment by mjbvz** [comment]
Thanks, those three packages and the observation about `typings` were key to getting a repo of the issue. I believe that the typings acquisition is the root cause.

Will have a fix out for PR shortly.
