### ISSUE TITLE
Duplicate lexical declaration; cannot redefine let or const variables in NTVS 1.1

### ISSUE THREAD

**Issue by gibbok** [Microsoft/nodejstools#862]
- Use Visual Stuio 2015 Community Edition and NTVS V1.1 on Windows 8.1.
- Create a new project choosing from "Blanks Node.JS Console Application".
- In app.js file (or in another file) add the following code:

```
const fs = require('fs');
const del = require('del');
```

In VS palette "Error List" an error is being shown:

> Duplicate lexical declaration; cannot redefine let or const variables

Despite this notice of error the application runs with no exception.

The expected behavior should be: No error in "Error List" palette as code is valid lexical declaration.

Notes:
Right now in order to avoid this issue the following code must be used:

```
var fs = require('fs');
var del = require('del');
```

Notes:
- Issue does not happen on Node.js Tools 1.2 Alpha.
- [SO related question](http://stackoverflow.com/questions/36639911/duplicate-lexical-declaration-cannot-redefine-let-or-const-variables).

**Comment by mjbvz** [comment]
Thanks for the report.

One quick question: what Intellisense level are you on? This setting is found under `tools -> options` then `Text Editor -> Node.js -> Intellisense`

**Comment by mjbvz** [comment]
I'm unable to repo the issue in my testing on VS Community 2015 Update 2, although I tested on Win10 instead of Win8.1.

Besides the Intellisense level, the following information may also help us investigate this further:

* In  `Help -> About Visual Studio what is the specific version of VS listed?
* In the same pane, look for `Typescript` in the installed products. What is it's version?
* It may help to let us know all the plugins that are installed using  `Copy Info`.

As for work arounds, it sounds like NTVS 1.2 Alpha fixes the problem and at least you can get away with using `var` instead of `const`. You can also try changing the Intellisense level in `Text Editor -> Node.js -> Intellisense` to see if that makes any difference (make sure to close and reopen any Js files after changing Intellisense levels.)

**Comment by gibbok** [comment]
Hi, details for my environment:

IntelliSense Level: ED 6 IntelliSense preview

Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA065
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA065
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA065
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.11120.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Bundler & Minifier   1.8.148
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

Color Theme Designer   1.0
Designer for creating new color themes

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

FormatDocumentOnSave   1.0
Enables auto formatting of the code when you save a file. Visual Studio supports auto formatting of the code with the CTRL+E,D or CTRL+E,F key shortcuts but with this extension the command 'Format Document' is executed on Save.

You can find the source here: https://github.com/Elders/VSE-FormatDocumentOnSave

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.2900.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2900.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.31121.1

Node.js Tools   1.2.40329.01
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.2.40329.01
Profiling support for Node.js projects.

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.0.168
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

Strip'em   1.0
Visual Studio 2013 package. Save files with Unix or Windows line endings.

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio

Web Compiler   1.10.306
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015.1   1.0.211
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

**Comment by mjbvz** [comment]
Thanks. 

For NTVS 1.2 Alpha, you need to be on [VS2015 Update 2](https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx). I suspect that this could be causing problems.

We've gated that #806 for future 1.2 preview releases, but this was not handled for the first alpha release.

Try upgrading to Update 2 and see if that fixes the problem.

**Comment by gibbok** [comment]
Thanks for your comment.
I will just summarize what I had tried in hope it can help you to debug better this issue:

- My original issue was on VS2015 Update 1 and NTVS V1.1 on Windows 8.1.
- After an update to NTVS V1.2 Alpha (maintaining  VS2015 Update 1) - issue was solved.
- After your suggestion, I updated to  VS2015 Update 2 and NTVS V1.2 Alpha on Windows 8.1 - IDE works fine, no issue.

**Comment by paulvanbrenk** [comment]
Fixed with the switch to the new Language Service in v1.3 and Visual Studio 2017
