### ISSUE TITLE
Text formatting (braces, spaces) doesn't work any more 

### ISSUE THREAD

**Issue by noopole** [Microsoft/nodejstools#865]
With NTVS 1.1.1 and VS 2015 Update 2, _text formatting_ doesn't work as expected on JS files in node.js projects.

Also, NTVS is displayed as of version 1.1 (not 1.1.1) in the `Tools / Extensions` window.

Also, the `node.js code` and `browser code` labels are not displayed near JS folder names.

**Comment by mjbvz** [comment]
Can you please open separate issues for the second and third problems,and keep this issue tracking just the text formatting issue.

For the text formatting, please also provide:
* List of repo steps
* Expected behavior
* Actual behavior

Thanks.

**Comment by noopole** [comment]
How much is it paid? By now I'm working for a 60 k€/year but I'm sure MS could give more! :smile:

**Comment by mitchjmiller** [comment]
Seeing same issue with formatting.
It seems the formatting for TypeScript is being applied despite me working in Javascript, with the Javascript and Node.js format settings being ignored.

On top of this, the spacing option "Insert space after opening and before closing non-empty parenthesis" does not seem to correctly insert spaces before closing parenthesis when preceded by a curly brace (function code block or object for example).

E.g. it will format as follows (issue being the closing parenthesis not having spaces between):
`myFunctionCall( {  key: "value" });`

**Comment by mjbvz** [comment]
@mitchjmiller Are you also on NTVS 1.1 with VS 2015 Update 2? Also, what is your Intellisense level? I don't think that should effect formatting in 1.1, but just want to check.

**Comment by paulvanbrenk** [comment]
This should work better when using Update 3.
