### ISSUE TITLE
Will nodejstools be integrated into the new Visual Studio Code?

### ISSUE THREAD

**Issue by distracteddev** [Microsoft/nodejstools#87]
https://code.visualstudio.com/

**Comment by mousetraps** [comment]
NTVS and VSCode are totally separate codebases at the moment built on totally different technologies, so any sort of straightforward merge is highly unlikely from a purely technical standpoint.

That said... you can reasonably expect influence back and forth, and expect us to share any code we can feasibly share (no one likes code duplication). 

Make sense?
