### ISSUE TITLE
Reload Project leaking `NodejsProjectNode`

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#870]
**Repo**
- Create simple new Express 4 app.
- Take memory snapshot.
- Unload the project.
- Reload the project.
- Take another snapshot

**Expected**
Only a single `NodejsProjectNodes` should be loaded since this is a fairly heavy object (not directly, but in what it owns).

**Actual**
Two copies of the `NodejsProjectNode` now exist. Repeat to create more instance.

**Comment by mjbvz** [comment]
One potential cycle:

`NodeProjectNode -> NpmController -> FileSystemWatcher -> NpmController -> NodeProjectNode` where `FileSystemWatcher` is never released.

**Comment by paulvanbrenk** [comment]
This doesn't seem to be a problem anymore
