### ISSUE TITLE
Automatic TSD acquistion rules applied for TypeScript project

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#872]
According to section [When Are Typings Automatically Acquired?](https://github.com/Microsoft/nodejstools/wiki/Automatic-Typings-Acquisition#when-are-typings-automatically-acquired) of docs typings should not be aqcuired, but in my TS project following hapens: Files in `typings` folder automatically added to the project.

I think would be reasonable if typings not acquired, then and typings folder should not be added to the project.
BTW: I use Typings and this inclusion not welcome for me. Also it does not respect my `tsconfig.json` settings too.

**Comment by mjbvz** [comment]
Thanks for the report. You are correct that the typing's acquisition change should not effect TS projects. 

This specific include problem was known issue with the 1.2 Alpha and has since been fixed: https://github.com/Microsoft/nodejstools/commit/4fb060f075ca47d014353360d55251992ee919a2
