### ISSUE TITLE
Not documented requirement for MSBuild VS2015

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#892]
In the Wiki section [Build-Instructions](https://github.com/Microsoft/nodejstools/wiki/Build-Instructions) there not clear mentioning that MSBuild from VS2015 is required to build code from source.

I have VS2013 installed, and when run
```
msbuild NodejsTools.sln /p:VsTarget=14.0 /p:VisualStudioVersion=14.0
```
that version was picked up first (Not done anything about make it that way).

Short line which will mention that command like `$env:Path="C:\Program Files (x86)\MSBuild\14.0\bin;"+$env:Path` or `SET PATH=C:\Program Files (x86)\MSBuild\14.0\Bin\;%PATH%` should be run before building.

**Comment by kant2002** [comment]
Forget, I already update the Wiki

**Comment by mjbvz** [comment]
Thanks for updating the wiki. This sounds like a rather sneaky problem so it's good to have this documented.

You can also try running the build commands from the Visual Studio Command Prompt for your chosen version of VS, which I think should always have the correct path set. I'll add that note to the wiki as well.
