### ISSUE TITLE
Visual Studio Community Edition 2015 Update 2 System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by jgkavanaugh** [Microsoft/nodejstools#894]
When opening a project in VS 2015 Update 2 with nodejstools 1.1 the error dialog appears:

An exception has been encountered. This may be caused by an extension.
You can get more information by examining the file...

Opening the ActivityLog the following Errors are present:

` <entry>
    <record>485</record>
    <time>2016/04/26 13:58:42.668</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.&#x000D;&#x000A;   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)&#x000D;&#x000A;   at System.Collections.Immutable.ImmutableDictionary`2.System.Collections.Generic.IDictionary&lt;TKey,TValue&gt;.get_Item(TKey key)&#x000D;&#x000A;   at Microsoft.NodejsTools.ClassifierProviderMetadata..ctor(IDictionary`2 values)&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)&#x000D;&#x000A;   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.MetadataViewClassProvider.CreateProxy(IReadOnlyDictionary`2 metadata, IReadOnlyDictionary`2 defaultValues, Type metadataViewType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetStrongTypedMetadata(IReadOnlyDictionary`2 metadata, Type metadataType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.&lt;CreateValue&gt;b__10_0(RuntimeImport import)&#x000D;&#x000A;   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()&#x000D;&#x000A;   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)&#x000D;&#x000A;   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.DelegateServices.&lt;&gt;c__DisplayClass2_0`1.&lt;As&gt;b__0()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource)</description>
  </entry>`

**Comment by mjbvz** [comment]
Thanks for the report.

Looking at the exception, the only direct mention of our code seems to be:  `Microsoft.NodejsTools.ClassifierProviderMetadata..ctor(IDictionary2 values)`. My best guess is that this gets hit during some of the reflection and component model logic.

A few questions to help with the investigation:
* Does the error happen consistently?
* Does the error happen for every project or just this one?
* Does the error happen for a new, blank console node application? My working theory is that this error would be hit for projects with Jade because that is the only code that mentions `ClassifierProviderMetadata`.
* Can you ignore the error? What happens if you do so?

You can also always try updating to the NTVS 1.2 Alpha to see if that fixes the problem.

**Comment by jgkavanaugh** [comment]
Sorry for the delay I'll take the questions one at a time:

> Does the error happen consistently?

Yes anytime a project containing .jade files is opened

> Does the error happen for every project or just this one?

Every project we have

> Does
> the error happen for a new, blank console node application? My working theory is that this error would be hit for projects with Jade because that is the only code that mentions ClassifierProviderMetadata.

No, only when .jade files are in the project.

> Can you ignore the error? What happens if you do so?

If the error is ignored syntax highlighting and tooltips.

>You can also always try updating to the NTVS 1.2 Alpha to see if that fixes the problem.

I just checked the dev box this was occurring on. An update to 1.2 seems to have corrected the error.
