### ISSUE TITLE
When cloning receive No submodule mapping found in .gitmodules for path 'nodejstools'

### ISSUE THREAD

**Issue by johnmcbride** [Microsoft/nodejstools#9]
When i try to clone the repo using source tree I get the following error

'No submodule mapping found in .gitmodules for path 'nodejstools''

**Comment by mousetraps** [comment]
Oops, looks like we accidentally added a submodule when syncing our repo and then didn't push the change to .gitmodules. I'll fix it, but should be safe to ignore.
