### ISSUE TITLE
remote nodejs typescript debugging

### ISSUE THREAD

**Issue by FredericLatour** [Microsoft/nodejstools#90]
I'm trying to debug a typescript based nodejs site in a vagrant linux machine...
For some reasons, I'm not able to breakpoint in typescript file ... Before I dig any further, does anybody knows if that is supposed to work ?
How is the debugger supposed to know how to map into typescript file in this kind of remote scenario?
Any information appreciated...
thanks

**Comment by mousetraps** [comment]
Maybe you're running into [this issue](https://nodejstools.codeplex.com/workitem/1693)?

**Comment by FredericLatour** [comment]
In fact I was messing with port forwarding... I could make it work in the end...
Thanks for helping
