### ISSUE TITLE
Failing Tests while walking through the Test Explorer documentation

### ISSUE THREAD

**Issue by anubmat** [Microsoft/nodejstools#904]
Add a new JavaScript UnitTest file/JavaScript Mocha UnitTest file in the project, run all the Test cases.

Expected:
Tests that pass are shown with a green tick. The amount of time taken to run the test is also displayed.
 
Actually:
Run test case failed.
Log info:
![image](https://cloud.githubusercontent.com/assets/17298501/14905582/ed30e6ae-0d66-11e6-83f4-2c86775848dd.png)

**Comment by mjbvz** [comment]
I've been unable to repo this. Without a consistent repo, my best advice is to try running `devenv /setup` or reinstalling NTVS to see if perhaps the installation just got into a bad state.

Let me know if you are still seeing this problem. Thanks.
