### ISSUE TITLE
Able to include files in the project while debugging

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#915]
I was able to add files to the project while debugging.

From my experience in C# this is disallowed since it modify the "program" as VS think about it.
Not sure that this is needed to be in NTVS that way, but it surprise me.

**Comment by mjbvz** [comment]
Thanks for the report.

I believe this is by design. Are you noticing any odd or unexpected behavior after including these files?

**Comment by mjbvz** [comment]
Closing this issue since this is by design, but please open new issues if you notice this feature causing odd behavior. Thanks.
