### ISSUE TITLE
NodeJS Tools and Web Essentials

### ISSUE THREAD

**Issue by lilasquared** [Microsoft/nodejstools#92]
I am struggling to get some of the basic functionality out of the Web Essentials Extension on a NodeJS project.  Bundling, minifying, etc are not working on javascript files at all.  Has anyone else tried using these features in tandem with the NodeJS Tools?  Thanks in advance!

**Comment by KamranMackey** [comment]
@lilasquared Uh, have you even asked the developer of Web Essentials if it even supports this one? Because the only possible reason for that functionality to be broken would be that Web Essentials is incompatible with the extension. However, what version & edition of Visual Studio are you using?

**Comment by lilasquared** [comment]
I haven't asked a dev over there yet, I thought it might be something wrong with the NodeJS plugin because it works correctly for other projects within visual studio.
