### ISSUE TITLE
Debug local IISNode app

### ISSUE THREAD

**Issue by ashleyryan** [Microsoft/nodejstools#922]
I have a small node app running locally in IIS on port 1313. I know that IISNode has an integrated debugger in the browser, but I would rather debug it in Visual Studio (my app isn't used in the browser). 

I've read the instructions here:

https://github.com/Microsoft/nodejstools/wiki/Advanced-Debugging#remote-debugging-windows-linux-macos

I know I can't connect directly to port 1313, I need the debug port. But how do I find what port that is for IISNode?

**Comment by mjbvz** [comment]
I'm not familiar with how IISNode works, but based on [this article](https://tomasz.janczuk.org/2011/11/debug-nodejs-applications-on-windows.html), it sounds like IIS node exposes the debugger using a "debug" path segment. When attaching, try passing in the full path with the debugger path segment:  `http://localhost:1313/node/helloworld/app.js/debug`

I also think you can control which ports the debugger is available on using the settings, so make sure debuggerPortRange includes the target port:

```
 <system.webServer>  
    <iisnode        
      debuggerPortRange="1313"  
      debuggerPathSegment="debug"  
      maxNamedPipeConnectionRetry="3"  
      namedPipeConnectionRetryDelay="2000"        
     />  
  </system.webServer
```

Hope that helps.
