### ISSUE TITLE
Problem reading JSON files

### ISSUE THREAD

**Issue by KyleJune** [Microsoft/nodejstools#93]
When I read from a JSON file created by right clicking a folder and selecting add new item, the file cannot be parsed after it's contents are read. 

The only JSON files I can parse are the ones that I created before starting to use Visual Studio. In the below picture, root is able to be parsed, but multipart throws the error. I know it's not the code because I replaced root by copying it's contents, deleting it, then readding root using add new item, then pasting the exact same code that worked before in it, and then it started throwing the same error as multipart.

![error](https://cloud.githubusercontent.com/assets/3241653/7446080/010cd79e-f19a-11e4-9af9-4290bfb0b1f8.png)

When I do:
```javascript
JSON.parse(content);
```
where content is the result of reading from the json file. It throws the following syntax error:
```
SyntaxError: Unexpected token ï»¿
```

I tried just printing out the content using console.log before parsing the JSON and it looks like what's happening is that a "?" is being appended in front of the files contents for some reason.

**Comment by mousetraps** [comment]
The token being referenced is actually the UTF-8 BOM, and Node has decided that fs.readFile is [not going to strip the BOM markers](https://github.com/joyent/node/issues/1918), hence the error you are seeing. There are a couple workarounds described in this [StackOverflow answer](http://stackoverflow.com/questions/24356713/node-js-readfile-error-with-utf8-encoded-file-on-windows), and in VS you can change the encoding of the file by File > Advanced Save Options, and selecting **Unicode (UTF-8 without signature)** as the encoding.
![image](https://cloud.githubusercontent.com/assets/762848/7446344/4b29b4ec-f18a-11e4-88ff-caded0aa7bb8.png)

That said, I wouldn't take issue with changing the default of the json files in the "new item" dialog to avoid additional confusion.

**Comment by KyleJune** [comment]
In VS, I didn't see Advanced Save Options in my File menu. I decided to just change
```javascript
JSON.parse(content);
```
to
```javascript
JSON.parse(content.replace(/^\uFEFF/, ''));
```
Since I wont have control over how future users choose to save their JSON files.

**Comment by mousetraps** [comment]
Okay, closing this issue as external for now, and we can revisit if more people complain. I'm on the fence about changing the default as I'd prefer a potential issue like this to be visible rather than hidden.
