### ISSUE TITLE
ECMAScript target version 'es6' not supported.  Using default 'ES3' code generation.

### ISSUE THREAD

**Issue by alexezh** [Microsoft/nodejstools#932]
Hi,

I get TS5002 warning (es6 not supported) even when I use 
- VS2015, latest updates
- TypeScript 1.8
- Node 4.4.3
- Nodejstools 1.1

Any ideas?

**Comment by mjbvz** [comment]
How did you install Typescript? Under `Help -> About Visual Studio` is the Typescript version listed as 1.8? In my understanding, TS5002 should only happen for old versions of TS.

**Comment by alexezh** [comment]
About shows TypeScript 1.8.31.0. I set ECMAScript6 in project settings.

**Comment by mjbvz** [comment]
I can't repo this in my testing. A few more questions may help with the investigation:

* Does this happen for all your projects or just one?
* Does it happen if you create a new Typescript console application?
* Do you have a custom `tsconfig.json` file or any other custom build logic?

You can also try checking the file: `C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets`

around line 140 where it defines:

```
<TypeScriptToolsVersion Condition="'$(TypeScriptToolsVersion)'==''">1.8</TypeScriptToolsVersion>` 
```

to make sure it is picking up the correct `tsc.exe`.  It should point to the `tsc.exe` in `C:\Program Files (x86)\Microsoft SDKs\TypeScript`

**Comment by alexezh** [comment]
Same happens with new node.js/typescript console app. I found multiple older copies of typescript; deleted them all but this did not help. Microsoft.TypeScript.targets file has 1.8

**Comment by alexezh** [comment]
Update. Adding a reference to es6-promise solved "async undefined" issue. But I still get "cannot find name "await"" when compiling the module

**Comment by alexezh** [comment]
Update. It seems that compiler generates "cannot find name "await"" when await is used outside async function.

**Comment by alexezh** [comment]
Update #3. I am now seeing very strange behavior with sample console app. If I reference "<reference path="./defs/es6-promise.d.ts" I get duplicate symbol "Promise" error. If I remove the reference, I get cannot find symbol "Promise" error.

Also there seems to be difference between Build and Rebuild All. I can get things running (sometime) if I just remove the reference. Running Rebuild All generates errors.

**Comment by mjbvz** [comment]
Looks like the original problem is resolved then?

For update 3, try the solution proposed in this SO answer: http://stackoverflow.com/questions/32408306/how-to-use-es6-promises-with-typescript

Instead of using `<reference />`, it adds `"./typings/es6-promise/es6-promise.d.ts"` to the `files` section of `tsconfig.json` file, along with including `import {Promise} from 'es6-promise';` in the ts file.
`
