### ISSUE TITLE
if user deletes typings folder, we should give them pointer to intellisense options

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#933]
this way we can educate and prevent user confusion w/ the new ES6 preview

**Comment by mjbvz** [comment]
@mousetraps After the improved typings UX work , do you still believe this is necessary? I'm always a bit weary with trying to correctly detect this kind of behavior, given all the edge cases and interesting interactions we have to consider.

**Comment by mjbvz** [comment]
Closing this in favor of the UI improvements made in NTVS 1.2 beta. These alter the user when typings are acquired. [See the wiki for the complete documentation and design of this feature](https://github.com/Microsoft/nodejstools/wiki/Automatic-Typings-Acquisition).
