### ISSUE TITLE
Typings files included in external node_modules cannot be properly excluded from the project file

### ISSUE THREAD

**Issue by charliedavison** [Microsoft/nodejstools#945]
My team and I are having an issue (though I could very much just be missing something!) where packages in my node_modules folder keep having their typings folders added to the project despite the node_modules folder being excluded.

This only seems to occur in packages that have an actual folder called 'Typings' somewhere inside of them.

This wouldn't be so much of an issue, we could live with those files staying in the project, however rather than just including them once and then forgetting about it, they seem to be added multiple times and just cause the project file to grow and grow.

I don't know at what point VS looks for these files, but it's causing a problem where every time we go to switch branches or do a pull, we get a message saying the njsproj file has unsaved changes and have to go and manually exclude the files before we can continue.

Two packages we are seeing this with in our solution - Protractor and Nodemailer.

**Comment by mjbvz** [comment]
Are you on NTVS 1.2 Alpha 1? There was a bug in the first alpha where typings files were been included too eagerly. Here's an explanation of why including typings is required in the first place: https://github.com/Microsoft/nodejstools/wiki/Automatic-Typings-Acquisition

Try updating to NTVS 1.2 Alpha 2 and let me know if you still see the issue. Thanks.
