### ISSUE TITLE
Option to turn off Node Intellisense when using TypeScript

### ISSUE THREAD

**Issue by sameera** [Microsoft/nodejstools#949]
We have a complex Node.js app with multiple npm module dependencies, written in TS.  Almost everytime we open this project it shoots up to 1.5-2GB in memory use. 

I'm assuming that njsprojects try to parse the included node modules to generate IntelliSense and that's causing this memory spike. However, since we already include the .d.ts files for these modules, we probably can live with just the .d.ts based intellisense and disable parsing of node modules.
I could be wrong about intellisense causing the memory spike; but, to me, that seems the most logical explanation.

So, is there a way to disable only this parsing (without turning off Intellisense altogether). If now can we have an option to do so?

PS: 
Rather than using njsproj type, I started with an empty MVC project and manually did npm installs and typings installs (how it was recommended before NTVS). This project behaves well and I get all the intellisense I require. However, I was unable to get VS to attach as the debugger (I maybe doing something wrong with config there). So, I'd still prefer to use NTVS which gives me the debugging option.

**Comment by mousetraps** [comment]
Have you tried modifying the setting in `Tools -> Options -> Text Editor -> Node.js -> IntelliSense` to be either `None` or `ES6 Preview` (available in NTVS 1.2 Alpha 2 - http://aka.ms/ntvslatest)

**Comment by sameera** [comment]
Thank you! This is keeps the memory down to around 250MB on the same project.
