### ISSUE TITLE
FWLink in default Web.config isn't helpful

### ISSUE THREAD

**Issue by AndreSayreMSFT** [Microsoft/nodejstools#95]
However, this FWLink points to the CodePlex main page, and not to a specific page about configuring the Node.js application.

**Comment by jinglou-** [comment]
Pointing to here directly would be more helpful i think. 
http://nodejstools.codeplex.com/wikipage?title=AzureDeployment.

**Comment by mousetraps** [comment]
Updated link to point to github docs:
http://go.microsoft.com/fwlink/?LinkId=290972
