### ISSUE TITLE
Remote debugger fails with unhandled error when attaching 

### ISSUE THREAD

**Issue by jonedw** [Microsoft/nodejstools#950]
- Microsoft Visual Studio Community 2015 - Version 14.0.25123.00 Update 2
- Node.js Tools   1.1.40329.04
- Node V0.12.13

I get the following console output when attaching to a remote debug scrip with the -waitforattach option;

_$ node RemoteDebug.js -waitforattach gateway.js
node: node
scriptToDebug: gateway.js
passThroughArgs:
localClientPort: localhost:5859
remoteServerPort: undefined:5858
startDebuggeeOnRemoteConnect: true
startDebuggeeBrokenAtEntryPoint: false
remoteServerSocket listening for connection
remoteServerSocket connected
Debuggee started: node --debug=5859 gateway.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)_

The corresponding VS error on the PC is:
_Unable to attach to the process.  Operation not supported. Unknown error: 0x80004005._

**Comment by mjbvz** [comment]
See this issue: https://github.com/nodejs/node-v0.x-archive/issues/9216

Make sure that the port are not already in use and everything is configured properly. You can also switch the target port with `-machineport`. Try out a different port and see if that makes any difference.

**Comment by mjbvz** [comment]
Closing this since we need more info to investigate. @jonedw Please let me know if you are still running into this problem.
