### ISSUE TITLE
Verify Salsa is on by default for folder-based projects

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#952]
This is necessary in order for us to provide IntelliSense for Node.js projects.

**Comment by mjbvz** [comment]
Confirmed that the TypeScript team has enabled this for folder based projects in VS15:

![image](https://cloud.githubusercontent.com/assets/12821956/19332468/26137514-90a1-11e6-8f01-8498cf97c6e1.png)

After opening a node project as a folder, I see both local IntelliSense and IntelliSense for installed packages.
