### ISSUE TITLE
Customize Salsa support for folder-based Node.js folder-based projects

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#953]
If a package.json file or node_modules folder is detected, we should detect the Node.js project context and light up Node.js-specific completions

**Comment by mjbvz** [comment]
Confirmed that TypeScript lights up node specific completions (such as `process`) when a node-like project is loaded using open folder: 

![image](https://cloud.githubusercontent.com/assets/12821956/19332564/2b3f11f0-90a2-11e6-833e-8daf1204b748.png)

In this case, the`@types/node` package is downloaded if it is not already cached, and this file is what actually provides these completions
