### ISSUE TITLE
Please print the stack trace when an error is encountered when parsing tests

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/nodejstools#96]
Hi,

When there is an error in a test file NTVS current prints out the following on the "Tests" output window:

```
------ Discover test started ------
Processing: D:\foo\bar\bar.test.js;<plus some 100 file names>;D:\foo\bar\baz.test.js
TypeError: Cannot read property 'foo' of undefined
Processing finished for framework of ExportRunner
Discovered 0 testcases.
========== Discover test finished: 0 found (0:00:02.0461167) ==========
```

From the above, it's impossible to tell which file has the actual error.

Please make this more user-friendly.

* The long list of files is not very useful.
* Print a stack trace with the error.

Thanks.

**Comment by mousetraps** [comment]
Is there any reason you want the full stack trace rather than just the file in question?

**Comment by mousetraps** [comment]
Right, so there's no need to print a stack trace? If it printed just the problematic file name you'd be happy?

**Comment by NoelAbrahams** [comment]
Yes, that would do. If you are able to repro the issue then it should be clear. I would try throwing an exception at the top level (global scope) of a module (file) then importing that module into another for testing. When there are over a hundred files it is not clear where the error occurred.

**Comment by NoelAbrahams** [comment]
@mousetraps, do you happen to have a patch for this that I can try out? I've spent half the morning trying to figure out an error in a test file.

**Comment by NoelAbrahams** [comment]
Couple with the fact that it's not possible to debug tests (#79) this is turning into a bit of a nightmare.

**Comment by NoelAbrahams** [comment]
@mousetraps,

I'm not sure the code

![image](https://cloud.githubusercontent.com/assets/1106823/8075902/b4ed6b6e-0f3d-11e5-9bf5-10d82dcd4442.png)

is going to fix the problem for this issue, because there is no mention of "NTVS_Error:" in the output I posted above.

**Comment by mousetraps** [comment]
Can you try out the [latest dev build](https://github.com/Microsoft/nodejstools/releases)? Otherwise I'll need more info to reproduce the exact issue you ran into.

**Comment by NoelAbrahams** [comment]
@mousetraps, the debugger is working on the latest dev build - so thanks for that.

This issue has not been fixed. To reproduces try out some code like the following:

```javascript

throw 'foo'; // Error in the top level

function mytest() {
}
```

**Comment by mousetraps** [comment]
Gracias! I can repro this one now :smiley:

**Comment by mousetraps** [comment]
Hey, check out #214 - if you want, you should be able to simply copy and paste into your file.

NTVS_ERROR actually gets stripped, which is why you are not seeing it (it does appear when you're using the debug bits, though because we print a little more logging info)

There is also another issue that may be a race condition in Test Explorer / TestAdapter that prevents errors from appearing altogether, so if you're not seeing *any* errors, try "touching" the file a few times until the Test Discovery proceeds more smoothly.

**Comment by mousetraps** [comment]
Available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)

**Comment by NoelAbrahams** [comment]
This looks to be fixed. Thanks.
