### ISSUE TITLE
Duplicate node.d.ts entries added to project file each time the project is loaded

### ISSUE THREAD

**Issue by lukedgr** [Microsoft/nodejstools#969]
##### Expected Behavior

If node.d.ts file entry is already present in the project file do not add another one.
##### Actual Behavior

Each time the project is loaded by visual studio a new `<TypeScriptCompile Include="Scripts\typings\node\node.d.ts" />` entry is added.  See attached screenshot for example outcome.

- NTVS Version: 1.2 Alpha
- Visual Studio Version: VS 2015 Update 2
- Node.js Version: v0.10.36
##### Steps to Reproduce
1. Load a node.js project file that already has a node.d.ts entry in visual studio
2. Open the project file in a text editor notice there are duplicate entries.

Screenshot of result:
![image](https://cloud.githubusercontent.com/assets/3270455/15545763/5dd26ba8-2252-11e6-9dec-ad5bdd5161f6.png)

**Comment by paulvanbrenk** [comment]
This is fixed in VS 2017, not sure in which specific Update... possibly 2.
