### ISSUE TITLE
Warning in task runner but not in command line

### ISSUE THREAD

**Issue by floyd-may** [Microsoft/nodejstools#972]
I have some grunt tasks that do not complete successfully when run from the task runner window. Everything works fine from the command line.

##### Expected Behavior 
Task completes successfully.

##### Actual Behavior 
Task fails to complete with error `Warning: Object #<Object> has no method 'debuglog'`.

- NTVS Version: 1.1.40329.04
- Visual Studio Version: 14.0.25123.00
- Node.js Version: ?

##### Steps to Reproduce
Not entirely sure how to reproduce. I'm compiling typescript with browserify using the tsify plugin via grunt. Relevant config:
```
// snip
browserify: {
            options: {
                debug: true,
                plugin: [
                    ['tsify', [{
                        noEmitOnError: true,
                        failOnTypeErrors: true
                    }]]
                ]
            },
            src: {
                files: {
                    '<%= paths.compiledSource %>': paths.source
                }
            },
// snip
```
I have a `clean` task that works fine.

**Comment by mjbvz** [comment]
Thanks for the report but I don't think that NTVS is to blame here.

I think the root cause may be the version of node that the task runner is using. `util. debuglog` does not exist prior to Node v0.11 if I recall correctly. See this SO answer for updating the path to Node for the task runner: http://stackoverflow.com/questions/31301582/task-runner-explorer-cant-load-tasks

Hope that helps. Thanks

**Comment by floyd-may** [comment]
That fixes it for me, thanks. My google fu wasn't strong enough to find that solution, apparently =)

However, whose issue is this? Is this a visual studio bug? It seems really strange that the VS version dated 2015 would ship Node.js 0.10.31, dated August of 2014 (https://nodejs.org/en/download/releases/).

**Comment by mjbvz** [comment]
@floyd-may I don't blame you, the problem is pretty hard to diagnose and the only reason I knew anything about this was because of #812.

The VS Web Tools is the correct contact here. We prodded them after #812, but will make sure they are still looking into improving this experience.
