### ISSUE TITLE
Double clicking on a Mocha test opens JavaScript source file in external application

### ISSUE THREAD

**Issue by jcansdale** [Microsoft/nodejstools#974]
##### Expected Behavior 

Double clicking on test in Test Explorer should open source file in Visual Studio.

##### Actual Behavior 

Double clicking on Mocha test opens JavaScript source file in external application (Notepad2 in my case).

- NTVS Version: 1.2 Alpha
- Visual Studio Version: 2015
- Node.js Version: v6.1.0

##### Steps to Reproduce
1. Create new Mocha test
2. Double click on test in Test Explorer
![test_explorer](https://cloud.githubusercontent.com/assets/11719160/15723581/fba72164-283a-11e6-97fa-b42779d3ebe2.png)

**Comment by mjbvz** [comment]
Merged in #979 and #982 that should resolve this. Let me know if that is not the case.

Thanks.
