### ISSUE TITLE
debugger gets confused by async/await

### ISSUE THREAD

**Issue by alexezh** [Microsoft/nodejstools#980]
Hi,

I am using TypeScript 1.8 / node 6.2.1 / nodetools 1.1. What is the state of async/await support? Is it fully supported or is it a "preview"? It seems that debugger gets very confused by functions with await.

**Comment by mjbvz** [comment]
Thanks for the report. We haven't been focusing on async/await debugging support yet, but definitely want to support this. I don't believe debuggers should require any special logic for async functions (but that could be totally wrong) so perhaps it's the NTVS source mapper or some other lower level component that is getting confused.

A few point to help with the investigation:

* What exactly are you seeing? Are breakpoints not resolving, not being hit, or getting hit on the wrong lines? 
* Is this behavior consistent?
* Does the same behavior happen with normal ES6 generation functions? I believe TS implements async and await with generators.

Could you also provide a short code sample to make sure we are all on the same page for the investigation. Thanks.

**Comment by paulvanbrenk** [comment]
This is supported in Node 8 and later.
