### ISSUE TITLE
AppVeyor build doesn't expose build artifacts

### ISSUE THREAD

**Issue by jcansdale** [Microsoft/nodejstools#983]
##### Expected Behavior 

I was hoping that Appveyor would expose the build artifacts (installer in particular) here:
https://ci.appveyor.com/project/mousetraps/nodejstools/build/1.0.479/job/4qbjyyp9neub5ter/artifacts

##### Actual Behavior 

Message saying:
"The build job does not contain any artifacts."

##### Steps to Reproduce

1. Navigate to:
https://ci.appveyor.com/project/mousetraps/nodejstools/build/1.0.479/job/4qbjyyp9neub5ter/artifacts

2. "The build job does not contain any artifacts."

**Comment by mjbvz** [comment]
Great idea!

We should also look into publishing ship built MSIs to github: https://www.appveyor.com/docs/deployment/github

The current dev build release process is too manual and I'd love to have something akin to daily builds available for those who are interested. Code signing may be an issue.
