### ISSUE TITLE
NTVS 1.2 Beta verification

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#985]
Install
* Latest VS 2015 build (Update 3 RC+)
* Latest TypeScript build (may want to uninstall previous version of TS)
* Latest NTVS build (40607.01)

**Comment by mjbvz** [comment]
WIP comment for tracking what has been tested and any issues

Testing on VS 2015 Community Update 3


## Project
- New JS project
   - [X] - Create new JS console project
   - [X] - Create new JS express project
- [X] Open existing JS project


----
# Issues
(will open separate bugs to track later)

##### 

![image](https://cloud.githubusercontent.com/assets/12821956/15878044/c0296a66-2ccc-11e6-83b5-15f0946c3f78.png)

**Comment by mousetraps** [comment]
TODO for RC
[ ] Options syncing (#995 and verify)
[ ] #998 options page alignment
[ ] #991 wiki / docs

**Comment by mousetraps** [comment]
Verification looks good. Closing, as I've opened up a separate issue to track remaining work for 1.2 Beta.
