### ISSUE TITLE
Gate 1.2 Final Release installer to VS 2015 update 3 final or later

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#994]
#990 and #993 handle the gating of NTVS 1.2 Beta to VS 2015 Update 3 RC.

For the final NTVS 1.2 release, we should gate the NTVS 1.2 installer to VS 2015 Update 3 final instead, once it becomes publicly available.

**Comment by mousetraps** [comment]
@mjbvz can you update the installer to gate on Update 3 after #1099 goes in?

**Comment by mjbvz** [comment]
Do you know the version number of VS2015 Update 3 RTM?
